GRANT SELECT ON DB_INFRAESTRUCTURA.INFO_EMPRESA_ELEMENTO_UBICA TO DB_COMUNICACION;
GRANT SELECT ON DB_INFRAESTRUCTURA.INFO_UBICACION TO DB_COMUNICACION;
GRANT SELECT ON DB_GENERAL.ADMI_PARROQUIA TO DB_COMUNICACION;
GRANT SELECT ON DB_GENERAL.ADMI_CANTON TO DB_COMUNICACION;