/**
 * @author Javier Hidalgo <jihidalgo@telconet.ec>
 * @version 1.0
 * @since 12/09/2022    
 * SE CREA ROLLBACK DE CREACION DE TABLA TEMPORAL QUE CONTIENE IDENTIFICACIONES DE CLIENTES A SER EXCLUIDAS
 * EN PROCESO DE CORTE MASIVO.
 */
DROP TABLE DB_COMERCIAL.TMP_IDENTIFICACIONES_EXCLUIDAS;
COMMIT;