/**
 * Creacion de nueva tabla ADMI_GRUPO_TAG 
 * @author Roberth Cobeña <rcobena@telconet.ec>
 * @version 1.0
 * @since 16/06/2021
 */
---
CREATE TABLE "DB_INFRAESTRUCTURA"."ADMI_GRUPO_TAG" 
   (	"ID_GRUPO_TAG" NUMBER NOT NULL ENABLE, 
        "SCOPE" VARCHAR2(500), 
        "TAG_ID" NUMBER NOT NULL ENABLE,
        "ESTADO" VARCHAR2(50 BYTE) NOT NULL ENABLE, 
        "FE_CREACION" TIMESTAMP (6) DEFAULT SYSDATE NOT NULL ENABLE, 
        "USR_CREACION" VARCHAR2(30 BYTE) NOT NULL ENABLE, 
        "FE_ULT_MOD" TIMESTAMP (6),        
        "USR_ULT_MOD" VARCHAR2(30 BYTE),         
        "EMPRESA_COD" NUMBER NOT NULL ENABLE, 
         CONSTRAINT "ADMI_GRUPO_TAG" PRIMARY KEY ("ID_GRUPO_TAG")
   );

   COMMENT ON COLUMN "DB_INFRAESTRUCTURA"."ADMI_GRUPO_TAG"."ID_GRUPO_TAG" IS 'ID INCREMENTAL DE LA TABLA';
   COMMENT ON COLUMN "DB_INFRAESTRUCTURA"."ADMI_GRUPO_TAG"."SCOPE" IS 'ID DEL DETALLE DEL SCOPE';
   COMMENT ON COLUMN "DB_INFRAESTRUCTURA"."ADMI_GRUPO_TAG"."TAG_ID" IS 'ID DEL TAG RELACIONADO';
   COMMENT ON COLUMN "DB_INFRAESTRUCTURA"."ADMI_GRUPO_TAG"."ESTADO" IS 'INDICA EL ESTADO DEL TAG AGRUPADO';
   COMMENT ON COLUMN "DB_INFRAESTRUCTURA"."ADMI_GRUPO_TAG"."USR_CREACION" IS 'Indica el usuario que creó el registro.';
   COMMENT ON COLUMN "DB_INFRAESTRUCTURA"."ADMI_GRUPO_TAG"."FE_CREACION" IS 'Indica la fecha de creacón del registro.';   
   COMMENT ON COLUMN "DB_INFRAESTRUCTURA"."ADMI_GRUPO_TAG"."USR_ULT_MOD" IS ' Indica el usuario que realizó modificacion del registro';
   COMMENT ON COLUMN "DB_INFRAESTRUCTURA"."ADMI_GRUPO_TAG"."FE_ULT_MOD" IS 'Indica la fecha de la ultima modificacion del registro.';    
   COMMENT ON COLUMN "DB_INFRAESTRUCTURA"."ADMI_GRUPO_TAG"."EMPRESA_COD" IS ' Indica la ID de la empresa para quien se realiza el registro';
--Secuenciador   
   CREATE SEQUENCE DB_INFRAESTRUCTURA.SEQ_ADMI_GRUPO_TAG INCREMENT BY 1 MAXVALUE 9999999999999999999999999999 MINVALUE 1 NOCACHE;

--Foreign Key
   ALTER TABLE DB_INFRAESTRUCTURA.ADMI_GRUPO_TAG ADD CONSTRAINT FK_ADMI_TAG FOREIGN KEY (TAG_ID)
      REFERENCES DB_INFRAESTRUCTURA.ADMI_TAG(ID_TAG);
COMMIT;
/