GRANT SELECT ON DB_COMERCIAL.INFO_SERVICIO_PROD_CARACT TO DB_SOPORTE;
GRANT SELECT ON DB_COMERCIAL.ADMI_PRODUCTO_CARACTERISTICA TO DB_SOPORTE;
GRANT SELECT ON DB_COMERCIAL.ADMI_CARACTERISTICA TO DB_SOPORTE;