--GRANT PARA NUEVA TABLA CREADA ADMI_PROGRESOS_TAREA
GRANT SELECT ON DB_SOPORTE.ADMI_PROGRESOS_TAREA TO DB_GENERAL;
--GRANT PARA TABLA ADMI_TIPO_PROGRESO
GRANT SELECT ON DB_SOPORTE.ADMI_TIPO_PROGRESO TO DB_GENERAL;
