--PERMISOS PARA CONSULTAR INFORMACION DEL LOS MATERIALES EN EL NAF

GRANT ALL PRIVILEGES ON  NAF47_TNET.ARIN_CARACTERISTICA TO DB_SOPORTE;
GRANT ALL PRIVILEGES ON  NAF47_TNET.ARIN_CARACTERISTICA_ARTICULO TO DB_SOPORTE;
GRANT ALL PRIVILEGES ON  NAF47_TNET.ARINDA TO DB_SOPORTE;
GRANT ALL PRIVILEGES ON  NAF47_TNET.ARAF_CONTROL_CUSTODIO TO DB_SOPORTE; 