--REVOCAR PRIVILEGIOS EN CASO SE QUE SE REQUIERA MANTENER EN PRIVADO LAS SIGUIENTES TABLAS.

REVOKE SELECT ON DB_COMERCIAL.INFO_PUNTO_SALDO FROM DB_SOPORTE;
REVOKE SELECT ON DB_SOPORTE.INFO_INCIDENCIA_REQUEST FROM DB_COMERCIAL;
REVOKE SELECT ON DB_SOPORTE.INFO_INCIDENCIA_CAB FROM DB_COMERCIAL;
REVOKE SELECT ON DB_SOPORTE.INFO_HISTORIAL_INGRESO_APP FROM DB_COMERCIAL;
REVOKE SELECT ON DB_COMERCIAL.ADMI_TIPO_NEGOCIO FROM DB_SOPORTE;
/
