-- DEFINIR EL DIRECTORIO PARA GENERACION DEL REPORTE AUTOMATICO
-- DIR_REPORTES_NC_INDISP  que hace referencia a /app/telcos/reportes/MD/soporte/casos/nc/

CREATE OR REPLACE DIRECTORY DIR_REPORTES_NC_INDISP AS '/app/telcos/reportes/MD/soporte/casos/nc/';

GRANT ALL ON DIRECTORY DIR_REPORTES_NC_INDISP TO DB_SOPORTE;
GRANT ALL ON DIRECTORY DIR_REPORTES_NC_INDISP TO DB_GENERAL;

COMMIT;
/
