--PERMISOS PARA CONSULTAR LAS TABLAS INFO_PUNTO,INFO_PUNTO_SALDO, INFO_INCIDENCIA_REQUEST, INFO_INCIDENCIA_CAB, INFO_HISTORIAL_INGRESO_APP

GRANT SELECT ON DB_COMERCIAL.INFO_PUNTO_SALDO TO DB_SOPORTE;
GRANT SELECT ON DB_SOPORTE.INFO_INCIDENCIA_REQUEST TO DB_COMERCIAL;
GRANT SELECT ON DB_SOPORTE.INFO_INCIDENCIA_CAB TO DB_COMERCIAL;
GRANT SELECT ON DB_SOPORTE.INFO_HISTORIAL_INGRESO_APP TO DB_COMERCIAL;
GRANT SELECT ON DB_COMERCIAL.ADMI_TIPO_NEGOCIO TO DB_SOPORTE;
/