admitipocaso:
    pattern:  /
    defaults: { _controller: "administracionBundle:AdmiTipoCaso:index" }

admitipocaso_show:
    pattern:  /{id}/show
    defaults: { _controller: "administracionBundle:AdmiTipoCaso:show" }

admitipocaso_new:
    pattern:  /new
    defaults: { _controller: "administracionBundle:AdmiTipoCaso:new" }

admitipocaso_create:
    pattern: /create
    defaults: { _controller: "administracionBundle:AdmiTipoCaso:create" }
    requirements: { _method: POST }
    
admitipocaso_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "administracionBundle:AdmiTipoCaso:edit" }

admitipocaso_update:
    pattern:  /{id}/update
    defaults: { _controller: "administracionBundle:AdmiTipoCaso:update" }
    requirements: { _method: POST }
    
admitipocaso_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "administracionBundle:AdmiTipoCaso:delete" }
    
admitipocaso_deleteAjax:
    pattern:  /deleteAjax
    defaults: { _controller: "administracionBundle:AdmiTipoCaso:deleteAjax" }
    requirements: { _method: post }

admitipocaso_grid:
    pattern:  /grid
    defaults: { _controller: "administracionBundle:AdmiTipoCaso:grid"}