grupotag:
    pattern:  /
    defaults: { _controller: "administracionBundle:AdmiGrupoTag:index" }

grupoTag_getGrupoPorScope:
    pattern:  /getGrupoPorScope
    defaults: { _controller: administracionBundle:AdmiGrupoTag:getGrupoPorScope }

grupoTag_show:
    pattern:  /{intTipoScope}/show
    defaults: { _controller: "administracionBundle:AdmiGrupoTag:show" }

grupotag_new:
    pattern:  /new
    defaults: { _controller: "administracionBundle:AdmiGrupoTag:new" }

grupotag_guardar:
    pattern: /guardarGrupoTag
    defaults: { _controller: "administracionBundle:AdmiGrupoTag:guardarGrupoTag" }
    requirements: { _method: POST }

grupotag_create:
    pattern: /create
    defaults: { _controller: "administracionBundle:AdmiGrupoTag:create" }
    requirements: { _method: POST }
    
admitag_edit:
    pattern:  /{intTipoScope}/edit
    defaults: { _controller: "administracionBundle:AdmiGrupoTag:edit" }

admitag_update:
    pattern:  /{id}/update
    defaults: { _controller: "administracionBundle:AdmiGrupoTag:update" }
    requirements: { _method: POST }
    
grupotag_deleteAjax:
    pattern:  /deleteAjax
    defaults: { _controller: "administracionBundle:AdmiGrupoTag:deleteAjax" }
    requirements: { _method: post }

admitag_ajaxGetElementoServidor:
    pattern:  /getElementoServidor
    defaults: { _controller: "administracionBundle:AdmiGrupoTag:getElementoServidor" }

grupotag_crearGrupoTagAjax:
    pattern:  /crearGrupoTagAjax
    defaults: { _controller: "administracionBundle:AdmiGrupoTag:crearGrupoTagAjax" }

grupotag_editarGrupoTagAjax:
    pattern:  /editarGrupoTagAjax
    defaults: { _controller: administracionBundle:AdmiGrupoTag:editarGrupoTagAjax }

grupotag_getEncontrados:
    pattern:  /getEncontrados
    defaults: { _controller: "administracionBundle:AdmiGrupoTag:getScopesRegistrados" }
    
grupotag_getGrupoTagAjax:
    pattern:  /getGrupoTagAjax
    defaults: { _controller: "administracionBundle:AdmiGrupoTag:getGrupoTagAjax" }
