GRANT ALL ON "DB_GENERAL"."GNCK_STRING" TO "NAF47_TNET";
GRANT ALL ON "DB_GENERAL"."GNKG_ADMI_DEPARTAMENTO_C" TO "NAF47_TNET";
GRANT ALL ON "DB_GENERAL"."GNKG_ADMI_ROL_C" TO "NAF47_TNET";
GRANT ALL ON "DB_GENERAL"."GNKG_ADMI_ROL_T" TO "NAF47_TNET";
GRANT ALL ON "DB_GENERAL"."GNKG_ADMI_TIPO_ROL_C" TO "NAF47_TNET";
GRANT ALL ON "DB_GENERAL"."GNKG_ADMI_TIPO_ROL_T" TO "NAF47_TNET";
GRANT ALL ON "DB_COMUNICACION"."CUKG_ALIAS_PLANITLLA_C" TO "NAF47_TNET";
/
