--ELIMINACIÓN DE LAS COLUMNAS ESTADO_WS Y FE_CREACION_WS
ALTER TABLE DB_COMERCIAL.INFO_PERSONA_FORMA_CONTACTO DROP (ESTADO_WS,FE_CREACION_WS);
ALTER TABLE DB_COMERCIAL.INFO_PUNTO_FORMA_CONTACTO   DROP (ESTADO_WS,FE_CREACION_WS);

/