
ALTER TABLE DB_GENERAL.ADMI_PARAMETRO_DET 
ADD (OBSERVACION VARCHAR2(2000) );

COMMENT ON COLUMN DB_GENERAL.ADMI_PARAMETRO_DET.OBSERVACION IS 'Registra informacion de los valores a guardarse en los campos VALOR1, VALOR2, VALOR3, VALOR4, VALOR5';

