ALTER TABLE DB_COMERCIAL.ADMI_CARACTERISTICA 
ADD (DETALLE_CARACTERISTICA CLOB );

COMMENT ON COLUMN ADMI_CARACTERISTICA.DETALLE_CARACTERISTICA IS 'PERMITE DETALLAR LA FUNCIONALIDAD DE LA CARACTERÍSTICA';
/
