/**
 *  
 * Se realiza el script para ingresar los parametros que agrupan a los elementos con clases
 * @author Geovanny Cudco <acudco@telconet.ec>
 * @version 1.0 09-03-2023
 */

SET SERVEROUTPUT ON; 
DECLARE
    INT_ID_PARAMETRO NUMBER;
BEGIN 
    INSERT INTO DB_GENERAL.ADMI_PARAMETRO_CAB
    VALUES(DB_GENERAL.SEQ_ADMI_PARAMETRO_CAB.NEXTVAL,
           'ELEMENTOS CON CLASE',
           'ELEMENTOS CON CLASE A INSTALARSE EN UN NODO',
           'TECNICO',
           'NODO',
           'Activo',
           'acudco',
           sysdate,
           '127.0.0.1',
           NULL,
           NULL,
           NULL);    
    SYS.DBMS_OUTPUT.PUT_LINE('INSERCIÓN EXITOSA DEL PARÁMETRO QUE IDENTIFICA A LOS ELEMENTOS CON CLASE');    
    
    SELECT ID_PARAMETRO
    INTO INT_ID_PARAMETRO
    FROM DB_GENERAL.ADMI_PARAMETRO_CAB 
    WHERE NOMBRE_PARAMETRO = 'ELEMENTOS CON CLASE';        
    
    INSERT INTO DB_GENERAL.ADMI_PARAMETRO_DET (id_parametro_det,PARAMETRO_ID,DESCRIPCION,VALOR1,ESTADO,USR_CREACION,FE_CREACION,IP_CREACION)
    VALUES(DB_GENERAL.SEQ_ADMI_PARAMETRO_DET.NEXTVAL,INT_ID_PARAMETRO,'IDENTIFICA AL TIPO UPS','UPS','Activo','acudco',SYSDATE,'127.0.0.1');
    SYS.DBMS_OUTPUT.PUT_LINE('INSERCIÓN EXITOSA DEL PARÁMETRO UPS');
    
    INSERT INTO DB_GENERAL.ADMI_PARAMETRO_DET (id_parametro_det,PARAMETRO_ID,DESCRIPCION,VALOR1,ESTADO,USR_CREACION,FE_CREACION,IP_CREACION)
    VALUES(DB_GENERAL.SEQ_ADMI_PARAMETRO_DET.NEXTVAL,INT_ID_PARAMETRO,'IDENTIFICA AL TIPO BATERIA','BATERIA','Activo','acudco',SYSDATE,'127.0.0.1');
    SYS.DBMS_OUTPUT.PUT_LINE('INSERCIÓN EXITOSA DEL PARÁMETRO BATERIA');
    
    INSERT INTO DB_GENERAL.ADMI_PARAMETRO_DET (id_parametro_det,PARAMETRO_ID,DESCRIPCION,VALOR1,ESTADO,USR_CREACION,FE_CREACION,IP_CREACION)
    VALUES(DB_GENERAL.SEQ_ADMI_PARAMETRO_DET.NEXTVAL,INT_ID_PARAMETRO,'IDENTIFICA AL TIPO TABLEROS DE TRANSFERENCIA','TABLEROS DE TRANSFERENCIA','Activo','acudco',SYSDATE,'127.0.0.1');
    SYS.DBMS_OUTPUT.PUT_LINE('INSERCIÓN EXITOSA DEL PARÁMETRO TABLEROS DE TRANSFERENCIA');
    
    INSERT INTO DB_GENERAL.ADMI_PARAMETRO_DET (id_parametro_det,PARAMETRO_ID,DESCRIPCION,VALOR1,ESTADO,USR_CREACION,FE_CREACION,IP_CREACION)
    VALUES(DB_GENERAL.SEQ_ADMI_PARAMETRO_DET.NEXTVAL,INT_ID_PARAMETRO,'IDENTIFICA AL TIPO AIRE ACONDICIONADO','AIRE ACONDICIONADO','Activo','acudco',SYSDATE,'127.0.0.1');
    SYS.DBMS_OUTPUT.PUT_LINE('INSERCIÓN EXITOSA DEL PARÁMETRO AIRE ACONDICIONADO');  
        
    INSERT INTO DB_GENERAL.ADMI_PARAMETRO_DET (id_parametro_det,PARAMETRO_ID,DESCRIPCION,VALOR1,ESTADO,USR_CREACION,FE_CREACION,IP_CREACION)
    VALUES(DB_GENERAL.SEQ_ADMI_PARAMETRO_DET.NEXTVAL,INT_ID_PARAMETRO,'IDENTIFICA AL TIPO GENERADOR','GENERADOR','Activo','acudco',SYSDATE,'127.0.0.1');
    SYS.DBMS_OUTPUT.PUT_LINE('INSERCIÓN EXITOSA DEL PARÁMETRO GENERADOR'); 
    
    INSERT INTO DB_GENERAL.ADMI_PARAMETRO_DET (id_parametro_det,PARAMETRO_ID,DESCRIPCION,VALOR1,ESTADO,USR_CREACION,FE_CREACION,IP_CREACION)
    VALUES(DB_GENERAL.SEQ_ADMI_PARAMETRO_DET.NEXTVAL,INT_ID_PARAMETRO,'IDENTIFICA AL TIPO RECTIFICADOR','RECTIFICADOR','Activo','acudco',SYSDATE,'127.0.0.1');
    SYS.DBMS_OUTPUT.PUT_LINE('INSERCIÓN EXITOSA DEL PARÁMETRO RECTIFICADOR'); 
    
    COMMIT;
        
    EXCEPTION
    WHEN OTHERS THEN
      SYS.DBMS_OUTPUT.PUT_LINE('Error: '|| SQLCODE || ' - ERROR_STACK: ' || DBMS_UTILITY.FORMAT_ERROR_STACK 
                               || ' - ERROR_BACKTRACE: ' || DBMS_UTILITY.FORMAT_ERROR_BACKTRACE);  
      ROLLBACK;
END;
/