-- DDL que reversa la ejecución exitosa del DML_24062019_RMORANC_2.pks

Delete from DB_GENERAL.ADMI_PARAMETRO_DET
where  PARAMETRO_ID = (SELECT ID_PARAMETRO FROM DB_GENERAL.ADMI_PARAMETRO_CAB WHERE NOMBRE_PARAMETRO='EQUIPOS_ULTIMA_MILLA');

Delete from DB_GENERAL.ADMI_PARAMETRO_CAB
where  NOMBRE_PARAMETRO='EQUIPOS_ULTIMA_MILLA';

commit;
/
