--Parámetros para la creación del caso y la tarea de ECUCERT
INSERT INTO DB_SOPORTE.ADMI_SINTOMA (ID_SINTOMA,NOMBRE_SINTOMA,DESCRIPCION_SINTOMA,ESTADO,USR_CREACION,FE_CREACION,USR_ULT_MOD,FE_ULT_MOD,EMPRESA_COD,TIPO_CASO_ID)
VALUES (DB_SOPORTE.SEQ_ADMI_SINTOMA.NEXTVAL,'Ip reportada por ECUCERT','Ip reportada por ECUCERT','Activo','nnaulal',SYSDATE,'nnaulal',SYSDATE,'10',1);

INSERT INTO DB_SOPORTE.ADMI_HIPOTESIS (ID_HIPOTESIS,NOMBRE_HIPOTESIS,DESCRIPCION_HIPOTESIS,ESTADO,USR_CREACION,FE_CREACION,USR_ULT_MOD,FE_ULT_MOD,EMPRESA_COD,TIPO_CASO_ID)
VALUES (DB_SOPORTE.SEQ_ADMI_HIPOTESIS.NEXTVAL,'Ip causante de problemas en la red','Ip causante de problemas en la red','Activo','nnaulal',SYSDATE,'nnaulal',SYSDATE,'10',1);

Insert into DB_SOPORTE.ADMI_TAREA (ID_TAREA,PROCESO_ID,ROL_AUTORIZA_ID,TAREA_ANTERIOR_ID,TAREA_SIGUIENTE_ID,PESO,ES_APROBADA,NOMBRE_TAREA,DESCRIPCION_TAREA,TIEMPO_MAX,UNIDAD_MEDIDA_TIEMPO,COSTO,PRECIO_PROMEDIO,ESTADO,USR_CREACION,FE_CREACION,USR_ULT_MOD,FE_ULT_MOD,AUTOMATICA_WS,CATEGORIA_TAREA_ID,PRIORIDAD,REQUIERE_FIBRA,VISUALIZAR_MOVIL) 
values (DB_SOPORTE.SEQ_ADMI_TAREA.NEXTVAL,'1089',null,null,null,'1','0','Revision IPs','Revision IPs','3','HORAS','0','0','Activo','nnaulal',sysdate,'nnaulal',
sysdate,null,null,null,'S','N');

Insert into DB_SOPORTE.ADMI_TAREA (ID_TAREA,PROCESO_ID,ROL_AUTORIZA_ID,TAREA_ANTERIOR_ID,TAREA_SIGUIENTE_ID,PESO,ES_APROBADA,NOMBRE_TAREA,DESCRIPCION_TAREA,TIEMPO_MAX,UNIDAD_MEDIDA_TIEMPO,COSTO,PRECIO_PROMEDIO,ESTADO,USR_CREACION,FE_CREACION,USR_ULT_MOD,FE_ULT_MOD,AUTOMATICA_WS,CATEGORIA_TAREA_ID,PRIORIDAD,REQUIERE_FIBRA,VISUALIZAR_MOVIL) 
values (DB_SOPORTE.SEQ_ADMI_TAREA.NEXTVAL,'1089',null,null,null,'1','0','Revision de casos de CPEs','Revision de casos de CPEs','3','HORAS','0','0','Activo','nnaulal',sysdate,'nnaulal',
sysdate,null,null,null,'S','N');

Insert into DB_SOPORTE.ADMI_TAREA (ID_TAREA,PROCESO_ID,ROL_AUTORIZA_ID,TAREA_ANTERIOR_ID,TAREA_SIGUIENTE_ID,PESO,ES_APROBADA,NOMBRE_TAREA,DESCRIPCION_TAREA,TIEMPO_MAX,UNIDAD_MEDIDA_TIEMPO,COSTO,PRECIO_PROMEDIO,ESTADO,USR_CREACION,FE_CREACION,USR_ULT_MOD,FE_ULT_MOD,AUTOMATICA_WS,CATEGORIA_TAREA_ID,PRIORIDAD,REQUIERE_FIBRA,VISUALIZAR_MOVIL) 
values (DB_SOPORTE.SEQ_ADMI_TAREA.NEXTVAL,'1089',null,null,null,'1','0','Revision de clientes CSOC','Revision de clientes CSOC','3','HORAS','0','0','Activo','nnaulal',sysdate,'nnaulal',
sysdate,null,null,null,'S','N');

Insert into DB_SOPORTE.ADMI_TAREA (ID_TAREA,PROCESO_ID,ROL_AUTORIZA_ID,TAREA_ANTERIOR_ID,TAREA_SIGUIENTE_ID,PESO,ES_APROBADA,NOMBRE_TAREA,DESCRIPCION_TAREA,TIEMPO_MAX,UNIDAD_MEDIDA_TIEMPO,COSTO,PRECIO_PROMEDIO,ESTADO,USR_CREACION,FE_CREACION,USR_ULT_MOD,FE_ULT_MOD,AUTOMATICA_WS,CATEGORIA_TAREA_ID,PRIORIDAD,REQUIERE_FIBRA,VISUALIZAR_MOVIL) 
values (DB_SOPORTE.SEQ_ADMI_TAREA.NEXTVAL,'1089',null,null,null,'1','0','Revision de clientes SG','Revision de clientes SG','3','HORAS','0','0','Activo','nnaulal',sysdate,'nnaulal',
sysdate,null,null,null,'S','N');

Insert into DB_SOPORTE.ADMI_TAREA (ID_TAREA,PROCESO_ID,ROL_AUTORIZA_ID,TAREA_ANTERIOR_ID,TAREA_SIGUIENTE_ID,PESO,ES_APROBADA,NOMBRE_TAREA,DESCRIPCION_TAREA,TIEMPO_MAX,UNIDAD_MEDIDA_TIEMPO,COSTO,PRECIO_PROMEDIO,ESTADO,USR_CREACION,FE_CREACION,USR_ULT_MOD,FE_ULT_MOD,AUTOMATICA_WS,CATEGORIA_TAREA_ID,PRIORIDAD,REQUIERE_FIBRA,VISUALIZAR_MOVIL) 
values (DB_SOPORTE.SEQ_ADMI_TAREA.NEXTVAL,'1089',null,null,null,'1','0','Regularizacion de Ips que no estan en VRF Telconet ni Gepon','Regularizacion de Ips que no estan en VRF Telconet ni Gepon','3','HORAS','0','0','Activo','nnaulal',sysdate,'nnaulal',
sysdate,null,null,null,'S','N');

Insert into DB_SOPORTE.ADMI_TAREA (ID_TAREA,PROCESO_ID,ROL_AUTORIZA_ID,TAREA_ANTERIOR_ID,TAREA_SIGUIENTE_ID,PESO,ES_APROBADA,NOMBRE_TAREA,DESCRIPCION_TAREA,TIEMPO_MAX,UNIDAD_MEDIDA_TIEMPO,COSTO,PRECIO_PROMEDIO,ESTADO,USR_CREACION,FE_CREACION,USR_ULT_MOD,FE_ULT_MOD,AUTOMATICA_WS,CATEGORIA_TAREA_ID,PRIORIDAD,REQUIERE_FIBRA,VISUALIZAR_MOVIL) 
values (DB_SOPORTE.SEQ_ADMI_TAREA.NEXTVAL,'1089',null,null,null,'1','0','Regularizacion de Ips que estan en la VRF Telconet - Jurisdicion UIO','Regularizacion de Ips que estan en la VRF Telconet - Jurisdicion UIO','3','HORAS','0','0','Activo','nnaulal',sysdate,'nnaulal',
sysdate,null,null,null,'S','N');

Insert into DB_SOPORTE.ADMI_TAREA (ID_TAREA,PROCESO_ID,ROL_AUTORIZA_ID,TAREA_ANTERIOR_ID,TAREA_SIGUIENTE_ID,PESO,ES_APROBADA,NOMBRE_TAREA,DESCRIPCION_TAREA,TIEMPO_MAX,UNIDAD_MEDIDA_TIEMPO,COSTO,PRECIO_PROMEDIO,ESTADO,USR_CREACION,FE_CREACION,USR_ULT_MOD,FE_ULT_MOD,AUTOMATICA_WS,CATEGORIA_TAREA_ID,PRIORIDAD,REQUIERE_FIBRA,VISUALIZAR_MOVIL) 
values (DB_SOPORTE.SEQ_ADMI_TAREA.NEXTVAL,'1089',null,null,null,'1','0','Regularizacion de Ips que estan en la VRF Telconet - Jurisdicion GYE','Regularizacion de Ips que estan en la VRF Telconet - Jurisdicion GYE','3','HORAS','0','0','Activo','nnaulal',sysdate,'nnaulal',
sysdate,null,null,null,'S','N');

Insert into DB_SOPORTE.ADMI_TAREA (ID_TAREA,PROCESO_ID,ROL_AUTORIZA_ID,TAREA_ANTERIOR_ID,TAREA_SIGUIENTE_ID,PESO,ES_APROBADA,NOMBRE_TAREA,DESCRIPCION_TAREA,TIEMPO_MAX,UNIDAD_MEDIDA_TIEMPO,COSTO,PRECIO_PROMEDIO,ESTADO,USR_CREACION,FE_CREACION,USR_ULT_MOD,FE_ULT_MOD,AUTOMATICA_WS,CATEGORIA_TAREA_ID,PRIORIDAD,REQUIERE_FIBRA,VISUALIZAR_MOVIL) 
values (DB_SOPORTE.SEQ_ADMI_TAREA.NEXTVAL,'1089',null,null,null,'1','0','Regularizacion de Ips que estan en la VRF GEPON','Regularizacion de Ips que estan en la VRF GEPON','3','HORAS','0','0','Activo','nnaulal',sysdate,'nnaulal',
sysdate,null,null,null,'S','N');

-- Parámetros para la creación del menú casos ECUCERT en la sección de soporte -> reportería
INSERT INTO DB_SEGURIDAD.SIST_ITEM_MENU (ID_ITEM_MENU,ITEM_MENU_ID,NOMBRE_ITEM_MENU,URL_IMAGEN,POSICION,HTML,ESTADO,CODIGO,USR_CREACION,FE_CREACION,USR_ULT_MOD,FE_ULT_MOD,DESCRIPCION_ITEM_MENU,TITLE_HTML,DESCRIPCION_HTML) 
VALUES (DB_SEGURIDAD.SEQ_SIST_ITEM_MENU.NEXTVAL,2127,'Casos ECUCERT','tag_blue.png',null,null,'Activo',null,'nnaulal',SYSDATE, null,null,'Menu tercer nivel - Casos ECUCERT','Casos ECUCERT',null);

INSERT INTO DB_SEGURIDAD.SIST_PERFIL (ID_PERFIL,NOMBRE_PERFIL,ESTADO,USR_CREACION,FE_CREACION,USR_ULT_MOD,FE_ULT_MOD)
VALUES (DB_SEGURIDAD.SEQ_SIST_PERFIL.NEXTVAL,'Casos ECUCERT','Activo','nnaulal',SYSDATE,null,null);

INSERT INTO DB_SEGURIDAD.SIST_MODULO(ID_MODULO,NOMBRE_MODULO,ESTADO,CODIGO,USR_CREACION,FE_CREACION,USR_ULT_MOD,FE_ULT_MOD)
VALUES (DB_SEGURIDAD.SEQ_SIST_MODULO.NEXTVAL,'consulta_casos_ecucert','Activo',null,'nnaulal',SYSDATE,null,null);

INSERT INTO DB_SEGURIDAD.SEGU_RELACION_SISTEMA (ID_RELACION_SISTEMA, MODULO_ID, ACCION_ID, ITEM_MENU_ID, RELACION_SISTEMA_ID, USR_CREACION, FE_CREACION, IP_CREACION, TAREA_INTERFACE_MODELO_TRA_ID)
VALUES (DB_SEGURIDAD.SEQ_SEGU_RELACION_SISTEMA.NEXTVAL, DB_SEGURIDAD.SEQ_SIST_MODULO.CURRVAL, 1, DB_SEGURIDAD.SEQ_SIST_ITEM_MENU.CURRVAL,null,'nnaulal',SYSDATE,'127.0.0.1',null);

INSERT INTO DB_SEGURIDAD.SEGU_ASIGNACION (PERFIL_ID, RELACION_SISTEMA_ID, USR_CREACION, FE_CREACION, IP_CREACION)
VALUES (DB_SEGURIDAD.SEQ_SIST_PERFIL.CURRVAL,DB_SEGURIDAD.SEQ_SEGU_RELACION_SISTEMA.CURRVAL,'nnaulal',SYSDATE,'127.0.0.1');

--Insert a la ADMI_PARAMETRO_CAB para declarar las variables perteneciente a ECUCERT
INSERT INTO DB_GENERAL.ADMI_PARAMETRO_CAB (ID_PARAMETRO,
NOMBRE_PARAMETRO,
DESCRIPCION,
MODULO,
PROCESO,
ESTADO,
USR_CREACION,
FE_CREACION,
IP_CREACION,
USR_ULT_MOD,
FE_ULT_MOD,
IP_ULT_MOD) 
VALUES (
DB_GENERAL.SEQ_ADMI_PARAMETRO_CAB.NEXTVAL,
'PARAMETROS_ECUCERT',
'PARAMETROS QUE SE USAN EN EL PROCESO DE INCIDENCIAS ECUCERT',
'SOPORTE',
NULL,
'Activo',
'nnaulal',
SYSDATE,
'127.0.0.1',
NULL,
NULL,
NULL);

-- Insert a la ADMI_PARAMETRO_DET que son los parámetros para la creación de registros de ECUCERT
INSERT INTO DB_GENERAL.ADMI_PARAMETRO_DET(
ID_PARAMETRO_DET,
PARAMETRO_ID,
DESCRIPCION,
VALOR1,
VALOR2,
VALOR3,
VALOR4,
ESTADO,
USR_CREACION,
FE_CREACION,
IP_CREACION,
USR_ULT_MOD,
FE_ULT_MOD,
IP_ULT_MOD,
VALOR5,
EMPRESA_COD) 
VALUES (
DB_GENERAL.SEQ_ADMI_PARAMETRO_DET.NEXTVAL,
DB_GENERAL.SEQ_ADMI_PARAMETRO_CAB.CURRVAL,
'PARAMETROS_REPORTE_BASE',
'notificaciones_telcos@telconet.ec',
'rsaenz@telconet.ec',
'gz',
'ECUCER_DIR',
'Activo',
'nnaulal',
SYSDATE,
'127.0.0.1',
'nnaulal',
SYSDATE,
'127.0.0.1',
'172.24.4.230',
NULL
);

INSERT INTO DB_GENERAL.ADMI_PARAMETRO_DET(
ID_PARAMETRO_DET,
PARAMETRO_ID,
DESCRIPCION,
VALOR1,
VALOR2,
VALOR3,
VALOR4,
ESTADO,
USR_CREACION,
FE_CREACION,
IP_CREACION,
USR_ULT_MOD,
FE_ULT_MOD,
IP_ULT_MOD,
VALOR5,
EMPRESA_COD) 
VALUES (
DB_GENERAL.SEQ_ADMI_PARAMETRO_DET.NEXTVAL,
DB_GENERAL.SEQ_ADMI_PARAMETRO_CAB.CURRVAL,
'PARAMETROS PARA CREAR TAREA',
'Ip reportada por ECUCERT',
'Ip causante de problemas en la red',
'Revision IPs',
'TAREAS DE AUTOMATIZACION',
'Activo',
'nnaulal',
SYSDATE,
'127.0.0.1',
'nnaulal',
SYSDATE,
'127.0.0.1',
NULL,
NULL
);

INSERT INTO DB_GENERAL.ADMI_PARAMETRO_DET(
ID_PARAMETRO_DET,
PARAMETRO_ID,
DESCRIPCION,
VALOR1,
VALOR2,
VALOR3,
VALOR4,
ESTADO,
USR_CREACION,
FE_CREACION,
IP_CREACION,
USR_ULT_MOD,
FE_ULT_MOD,
IP_ULT_MOD,
VALOR5,
EMPRESA_COD) 
VALUES (
DB_GENERAL.SEQ_ADMI_PARAMETRO_DET.NEXTVAL,
DB_GENERAL.SEQ_ADMI_PARAMETRO_CAB.CURRVAL,
'PARAMETROS PARA ENVIAR CORREO',
'Correo Electronico',
'Contacto Tecnico',
'MAIL',
'NOTIFICACION DE INCIDENCIA - DETECCION DE PROBLEMAS CON LA IP',
'Activo',
'nnaulal',
SYSDATE,
'127.0.0.1',
'nnaulal',
SYSDATE,
'127.0.0.1',
NULL,
NULL
);

INSERT INTO DB_GENERAL.ADMI_PARAMETRO_DET(
ID_PARAMETRO_DET,
PARAMETRO_ID,
DESCRIPCION,
VALOR1,
VALOR2,
VALOR3,
VALOR4,
ESTADO,
USR_CREACION,
FE_CREACION,
IP_CREACION,
USR_ULT_MOD,
FE_ULT_MOD,
IP_ULT_MOD,
VALOR5,
EMPRESA_COD) 
VALUES (
DB_GENERAL.SEQ_ADMI_PARAMETRO_DET.NEXTVAL,
DB_GENERAL.SEQ_ADMI_PARAMETRO_CAB.CURRVAL,
'PARAMETROS PARA ESTADO INCIDENCIA',
'Creado',
'Pendiente',
'Analisis',
'Notificado',
'Activo',
'nnaulal',
SYSDATE,
'127.0.0.1',
'nnaulal',
SYSDATE,
'127.0.0.1',
'Atendido',
NULL
);

INSERT INTO DB_GENERAL.ADMI_PARAMETRO_DET(
ID_PARAMETRO_DET,
PARAMETRO_ID,
DESCRIPCION,
VALOR1,
VALOR2,
VALOR3,
VALOR4,
ESTADO,
USR_CREACION,
FE_CREACION,
IP_CREACION,
USR_ULT_MOD,
FE_ULT_MOD,
IP_ULT_MOD,
VALOR5,
EMPRESA_COD) 
VALUES (
DB_GENERAL.SEQ_ADMI_PARAMETRO_DET.NEXTVAL,
DB_GENERAL.SEQ_ADMI_PARAMETRO_CAB.CURRVAL,
'PARAMETROS PARA ASIG TAREA',
'Jefe Departamental',
'empleado',
'Tecnico',
'PROBLEMASIP',
'Activo',
'nnaulal',
SYSDATE,
'127.0.0.1',
'nnaulal',
SYSDATE,
'127.0.0.1',
NULL,
NULL
);

INSERT INTO DB_GENERAL.ADMI_PARAMETRO_DET(
ID_PARAMETRO_DET,
PARAMETRO_ID,
DESCRIPCION,
VALOR1,
VALOR2,
VALOR3,
VALOR4,
ESTADO,
USR_CREACION,
FE_CREACION,
IP_CREACION,
USR_ULT_MOD,
FE_ULT_MOD,
IP_ULT_MOD,
VALOR5,
VALOR6,
VALOR7,
OBSERVACION,
EMPRESA_COD) 
VALUES (
DB_GENERAL.SEQ_ADMI_PARAMETRO_DET.NEXTVAL,
DB_GENERAL.SEQ_ADMI_PARAMETRO_CAB.CURRVAL,
'URL ECUCERT',
'http://telcos.telconet.ec/rs/tecnico/ws/rest/procesar',
'http://telcos.telconet.ec/rs/soporte/ws/rest/procesar',
'https://soc.i.telconet.net/ws/ecucert_validate',
'http://middleware.netlife.net.ec/ws/process',
'Activo',
'nnaulal',
SYSDATE,
'127.0.0.1',
'nnaulal',
SYSDATE,
'127.0.0.1',
'http://apps.telconet.ec/ws/token-security/rest/token/generate',
'http://soc.i.telconet.net/ws/ecucert_search_ipwan',
'http://soc.i.telconet.net/ws/ecucert_search_cliente_csoc',
'http://soc.i.telconet.net/ws/ecucert_search_cliente_sg',
NULL
);

INSERT INTO DB_GENERAL.ADMI_PARAMETRO_DET(
ID_PARAMETRO_DET,
PARAMETRO_ID,
DESCRIPCION,
VALOR1,
VALOR2,
VALOR3,
VALOR4,
ESTADO,
USR_CREACION,
FE_CREACION,
IP_CREACION,
USR_ULT_MOD,
FE_ULT_MOD,
IP_ULT_MOD,
VALOR5,
EMPRESA_COD) 
VALUES (
DB_GENERAL.SEQ_ADMI_PARAMETRO_DET.NEXTVAL,
DB_GENERAL.SEQ_ADMI_PARAMETRO_CAB.CURRVAL,
'PARAMETROS PARA TIEMPO REPORTE',
'24',
'48',
'96',
'192',
'Activo',
'nnaulal',
SYSDATE,
'127.0.0.1',
'nnaulal',
SYSDATE,
'127.0.0.1',
NULL,
NULL
);

INSERT INTO DB_GENERAL.ADMI_PARAMETRO_DET(
ID_PARAMETRO_DET,
PARAMETRO_ID,
DESCRIPCION,
VALOR1,
VALOR2,
VALOR3,
VALOR4,
ESTADO,
USR_CREACION,
FE_CREACION,
IP_CREACION,
USR_ULT_MOD,
FE_ULT_MOD,
IP_ULT_MOD,
VALOR5,
EMPRESA_COD) 
VALUES (
DB_GENERAL.SEQ_ADMI_PARAMETRO_DET.NEXTVAL,
DB_GENERAL.SEQ_ADMI_PARAMETRO_CAB.CURRVAL,
'PARAMETROS QUE NO VERIFICAN VULNERABILIDAD',
'BOTNETS',
NULL,
NULL,
NULL,
'Activo',
'nnaulal',
SYSDATE,
'127.0.0.1',
'nnaulal',
SYSDATE,
'127.0.0.1',
NULL,
NULL
);

INSERT INTO DB_GENERAL.ADMI_PARAMETRO_DET(
ID_PARAMETRO_DET,
PARAMETRO_ID,
DESCRIPCION,
VALOR1,
VALOR2,
VALOR3,
VALOR4,
ESTADO,
USR_CREACION,
FE_CREACION,
IP_CREACION,
USR_ULT_MOD,
FE_ULT_MOD,
IP_ULT_MOD,
VALOR5,
EMPRESA_COD) 
VALUES (
DB_GENERAL.SEQ_ADMI_PARAMETRO_DET.NEXTVAL,
DB_GENERAL.SEQ_ADMI_PARAMETRO_CAB.CURRVAL,
'ACTIVAR WEBSERVICES GUARDAR INCIDENCIA',
'SI',
NULL,
NULL,
NULL,
'Activo',
'nnaulal',
SYSDATE,
'127.0.0.1',
'nnaulal',
SYSDATE,
'127.0.0.1',
NULL,
NULL
);

-- Se guarda el registro en la ADMI_INCIDENCIA para obtener el tiempo que se debe enviar el reporte a ECUCERT por prioridad
INSERT INTO DB_SOPORTE.ADMI_INCIDENCIA_PRIORIDAD(
ID_INCIDENCIA_PRIORIDAD,
TIPO_EVENTO,
PRIORIDAD,
TIEMPO_HORA,
USR_CREACION,
FE_CREACION,
IP_CREACION,
USR_ULT_MOD,
FE_ULT_MOD,
IP_ULT_MOD) 
VALUES (
DB_SOPORTE.SEQ_ADMI_INCIDENCIA_PRIORIDAD.NEXTVAL,
'Incidente',
'Critica',
'24',
'nnaulal',
SYSDATE,
'127.0.0.1',
'nnaulal',
SYSDATE,
'127.0.0.1');


INSERT INTO DB_SOPORTE.ADMI_INCIDENCIA_PRIORIDAD(
ID_INCIDENCIA_PRIORIDAD,
TIPO_EVENTO,
PRIORIDAD,
TIEMPO_HORA,
USR_CREACION,
FE_CREACION,
IP_CREACION,
USR_ULT_MOD,
FE_ULT_MOD,
IP_ULT_MOD) 
VALUES (
DB_SOPORTE.SEQ_ADMI_INCIDENCIA_PRIORIDAD.NEXTVAL,
'Incidente',
'Alta',
'48',
'nnaulal',
SYSDATE,
'127.0.0.1',
'nnaulal',
SYSDATE,
'127.0.0.1');


INSERT INTO DB_SOPORTE.ADMI_INCIDENCIA_PRIORIDAD(
ID_INCIDENCIA_PRIORIDAD,
TIPO_EVENTO,
PRIORIDAD,
TIEMPO_HORA,
USR_CREACION,
FE_CREACION,
IP_CREACION,
USR_ULT_MOD,
FE_ULT_MOD,
IP_ULT_MOD) 
VALUES (
DB_SOPORTE.SEQ_ADMI_INCIDENCIA_PRIORIDAD.NEXTVAL,
'Incidente',
'Media',
'96',
'nnaulal',
SYSDATE,
'127.0.0.1',
'nnaulal',
SYSDATE,
'127.0.0.1');


INSERT INTO DB_SOPORTE.ADMI_INCIDENCIA_PRIORIDAD(
ID_INCIDENCIA_PRIORIDAD,
TIPO_EVENTO,
PRIORIDAD,
TIEMPO_HORA,
USR_CREACION,
FE_CREACION,
IP_CREACION,
USR_ULT_MOD,
FE_ULT_MOD,
IP_ULT_MOD) 
VALUES (
DB_SOPORTE.SEQ_ADMI_INCIDENCIA_PRIORIDAD.NEXTVAL,
'Vulnerabilidad',
'Critica',
'96',
'nnaulal',
SYSDATE,
'127.0.0.1',
'nnaulal',
SYSDATE,
'127.0.0.1');

INSERT INTO DB_SOPORTE.ADMI_INCIDENCIA_PRIORIDAD(
ID_INCIDENCIA_PRIORIDAD,
TIPO_EVENTO,
PRIORIDAD,
TIEMPO_HORA,
USR_CREACION,
FE_CREACION,
IP_CREACION,
USR_ULT_MOD,
FE_ULT_MOD,
IP_ULT_MOD) 
VALUES (
DB_SOPORTE.SEQ_ADMI_INCIDENCIA_PRIORIDAD.NEXTVAL,
'Vulnerabilidad',
'Alta',
'192',
'nnaulal',
SYSDATE,
'127.0.0.1',
'nnaulal',
SYSDATE,
'127.0.0.1');

-- Se ingresa en la NFO_INCIDENCIA_NOTIF el estado no notificado para el filtro de estado de notificación
INSERT INTO DB_SOPORTE.INFO_INCIDENCIA_NOTIF (
ID_INCIDENCIA_NOTIFICACION,DETALLE_INCIDENCIA_ID,CORREO,TIPO_CONTACTO,ESTADO,USR_CREACION,FE_CREACION,IP_CREACION)
VALUES(DB_SOPORTE.SEQ_INFO_INCIDENCIA_NOTIF.NEXTVAL,0,NULL,NULL,'No Notificado','nnaulal',sysdate,'127.0.0.1');

COMMIT;

 /