SET SERVEROUTPUT ON
--Creación de caracteristica para productos isb zte TN	
DECLARE
  LV_CANTIDADASOCIACION NUMBER := 0;
BEGIN
  FOR PRODUCTO IN
  (SELECT ID_PRODUCTO,
    DESCRIPCION_PRODUCTO
  FROM DB_COMERCIAL.ADMI_PRODUCTO
  WHERE DB_COMERCIAL.ADMI_PRODUCTO.NOMBRE_TECNICO IN ( 'INTERNET SMALL BUSINESS', 'TELCOHOME')
  )
  LOOP
    FOR CARACTERISTICA IN
    (SELECT DB_COMERCIAL.ADMI_CARACTERISTICA.ID_CARACTERISTICA,
      DB_COMERCIAL.ADMI_CARACTERISTICA.DESCRIPCION_CARACTERISTICA
    FROM DB_COMERCIAL.ADMI_CARACTERISTICA
    WHERE DB_COMERCIAL.ADMI_CARACTERISTICA.DESCRIPCION_CARACTERISTICA IN (
    'TRAFFIC-TABLE', 'GEM-PORT', 'LINE-PROFILE-NAME', 'SERVICE-PROFILE',
    'VLAN', 'SCOPE', 'INDICE CLIENTE', 'SPID', 'SSID', 'PASSWORD SSID', 'NUMERO PC', 'MODO OPERACION',
    'MAC ONT', 'POTENCIA', 'TRASLADO', 'MAC', 'CLIENT CLASS', 'PACKAGE ID', 'CAPACIDAD1', 'CAPACIDAD2')
    )
    LOOP
      LV_CANTIDADASOCIACION := 0;
      SELECT COUNT(*)
      INTO LV_CANTIDADASOCIACION
      FROM DB_COMERCIAL.ADMI_PRODUCTO_CARACTERISTICA
      WHERE DB_COMERCIAL.ADMI_PRODUCTO_CARACTERISTICA.PRODUCTO_ID     = PRODUCTO.ID_PRODUCTO
      AND DB_COMERCIAL.ADMI_PRODUCTO_CARACTERISTICA.CARACTERISTICA_ID = CARACTERISTICA.ID_CARACTERISTICA
      AND DB_COMERCIAL.ADMI_PRODUCTO_CARACTERISTICA.ESTADO            = 'Activo';
      IF LV_CANTIDADASOCIACION                                           = 0 THEN
        INSERT
        INTO DB_COMERCIAL.ADMI_PRODUCTO_CARACTERISTICA VALUES
          (
            DB_COMERCIAL.SEQ_ADMI_PRODUCTO_CARAC.NEXTVAL,
            PRODUCTO.ID_PRODUCTO,
            CARACTERISTICA.ID_CARACTERISTICA,
            SYSDATE,
            NULL,
            'ReguIsbZte',
            NULL,
            'Activo',
            'NO'
          );
        COMMIT;
      END IF;
    END LOOP;
  END LOOP;
END;
/