
-- REVERSO DEL DETALLE DE PARAMETROS PARA LA NOTIFICACION PASSWORD CAMARA
DELETE DB_GENERAL.ADMI_PARAMETRO_DET
    WHERE PARAMETRO_ID = ( SELECT ID_PARAMETRO FROM DB_GENERAL.ADMI_PARAMETRO_CAB
          WHERE NOMBRE_PARAMETRO = 'PARAMETROS PROYECTO GPON SAFECITY' AND ESTADO = 'Activo')
    AND DESCRIPCION = 'NOTIFICACION_PASSWORD_CAMARA';

COMMIT;
/
