  INSERT
  INTO DB_GENERAL.ADMI_PARAMETRO_DET
  ( 
    ID_PARAMETRO_DET,
    PARAMETRO_ID,
    DESCRIPCION,
    VALOR1,
    VALOR2,
    VALOR3,
    VALOR4,
    VALOR5,
    ESTADO,
    USR_CREACION,
    FE_CREACION,
    IP_CREACION,
    EMPRESA_COD
  )
  VALUES
  (
    DB_GENERAL.SEQ_ADMI_PARAMETRO_DET.NEXTVAL,
    1253,
    'Listado de estados considerados para dar de baja de la INFO_PROCESO_MASIVO_DET',
    'CORTE_MASIVO',
    'FILTROS_REGISTROS_DAR_DE_BAJA',
    'ESTADOS_VALIDADOS_INFO_PROCESO_MASIVO_DET',
    'In-Corte',
    NULL,
    'Activo',
    'mlcruz',
    sysdate,
    '127.0.0.1',
    '18'
  );

UPDATE DB_COMERCIAL.INFO_DETALLE_SOL_CARACT
SET ESTADO = 'SinEjecutar',
USR_ULT_MOD = 'mlcruz',
FE_ULT_MOD = SYSDATE
WHERE CARACTERISTICA_ID IN (1749, 1750, 1751)
AND ESTADO = 'PorEjecutar';

UPDATE DB_COMERCIAL.INFO_DETALLE_SOL_CARACT
SET ESTADO = 'Finalizada',
USR_ULT_MOD = 'mlcruz',
FE_ULT_MOD = SYSDATE
WHERE CARACTERISTICA_ID IN (1749, 1750, 1751)
AND ESTADO = 'Ejecutada';

UPDATE DB_COMERCIAL.INFO_DETALLE_SOL_CARACT
SET ESTADO = 'ExcedioTiempo',
USR_ULT_MOD = 'mlcruz',
FE_ULT_MOD = SYSDATE
WHERE CARACTERISTICA_ID IN (1749, 1750, 1751)
AND ESTADO = 'EnEjecucion';

UPDATE DB_COMERCIAL.INFO_DETALLE_SOLICITUD
SET ESTADO = 'SinEjecutar',
OBSERVACION = OBSERVACION || ' - Pasa de estado PorEjecutar a SinEjecutar por regularización '
WHERE TIPO_SOLICITUD_ID = 179
AND ESTADO = 'PorEjecutar';

UPDATE DB_COMERCIAL.INFO_DETALLE_SOLICITUD
SET ESTADO = 'ExcedioTiempo',
OBSERVACION = OBSERVACION || ' - Registro pasa de estado EnEjecucion a ExcedioTiempo por regularización '
WHERE TIPO_SOLICITUD_ID = 179
AND ESTADO = 'EnEjecucion';

UPDATE DB_INFRAESTRUCTURA.INFO_PROCESO_MASIVO_DET
SET ESTADO = 'FalloReintento',
USR_ULT_MOD = 'mlcruz',
FE_ULT_MOD = SYSDATE,
OBSERVACION = OBSERVACION || ' - Registro pasa de estado Fallo a FalloReintento por regularización '
WHERE PROCESO_MASIVO_CAB_ID IN 
( SELECT ID_PROCESO_MASIVO_CAB
  FROM DB_INFRAESTRUCTURA.INFO_PROCESO_MASIVO_CAB
  WHERE TIPO_PROCESO = 'CortarCliente'
  AND EMPRESA_ID = '18'
  AND SOLICITUD_ID IS NOT NULL)
AND ESTADO = 'Fallo';

UPDATE DB_INFRAESTRUCTURA.INFO_PROCESO_MASIVO_DET
SET ESTADO = 'SinEjecutar',
USR_ULT_MOD = 'mlcruz',
FE_ULT_MOD = SYSDATE,
OBSERVACION = OBSERVACION || ' - Registro pasa de estado PorEjecutar a SinEjecutar por regularización '
WHERE PROCESO_MASIVO_CAB_ID IN 
( SELECT ID_PROCESO_MASIVO_CAB
  FROM DB_INFRAESTRUCTURA.INFO_PROCESO_MASIVO_CAB
  WHERE TIPO_PROCESO = 'CortarCliente'
  AND EMPRESA_ID = '18'
  AND SOLICITUD_ID IS NOT NULL)
AND ESTADO = 'PorEjecutar';

UPDATE DB_INFRAESTRUCTURA.INFO_PROCESO_MASIVO_CAB
SET ESTADO = 'SinEjecutar',
USR_ULT_MOD = 'mlcruz',
FE_ULT_MOD = SYSDATE
WHERE TIPO_PROCESO = 'CortarCliente'
AND EMPRESA_ID = '18'
AND SOLICITUD_ID IS NOT NULL
AND ESTADO = 'PorEjecutar';

COMMIT;
/