--Bloque anónimo para crear un nuevo tipo de elemento para servicio Netfiber
SET SERVEROUTPUT ON
DECLARE
  Ln_IdTipoElemento  NUMBER(5,0);
  Ln_IdMarcaElemento NUMBER(5,0);
BEGIN
  INSERT
  INTO DB_INFRAESTRUCTURA.ADMI_TIPO_ELEMENTO
    (
      ID_TIPO_ELEMENTO,
      NOMBRE_TIPO_ELEMENTO,
      DESCRIPCION_TIPO_ELEMENTO,
      CLASE_TIPO_ELEMENTO,
      ESTADO,
      USR_CREACION,
      FE_CREACION
    )
    VALUES
    (
      DB_INFRAESTRUCTURA.SEQ_ADMI_TIPO_ELEMENTO.NEXTVAL,
      'FIBRA',
      'FIBRA',
      'ACTIVO',
      'Activo',
      'mlcruz',
      SYSDATE
    );
  SELECT ID_TIPO_ELEMENTO
  INTO Ln_IdTipoElemento
  FROM DB_INFRAESTRUCTURA.ADMI_TIPO_ELEMENTO
  WHERE NOMBRE_TIPO_ELEMENTO='FIBRA'
  AND ESTADO                = 'Activo';
  SELECT ID_MARCA_ELEMENTO
  INTO Ln_IdMarcaElemento
  FROM DB_INFRAESTRUCTURA.ADMI_MARCA_ELEMENTO
  WHERE NOMBRE_MARCA_ELEMENTO='GENERICO'
  AND ESTADO                 = 'Activo';
  INSERT
  INTO DB_INFRAESTRUCTURA.ADMI_MODELO_ELEMENTO
    (
      ID_MODELO_ELEMENTO,
      MARCA_ELEMENTO_ID,
      TIPO_ELEMENTO_ID,
      NOMBRE_MODELO_ELEMENTO,
      DESCRIPCION_MODELO_ELEMENTO,
      ESTADO,
      USR_CREACION,
      FE_CREACION,
      USR_ULT_MOD,
      FE_ULT_MOD
    )
    VALUES
    (
      DB_INFRAESTRUCTURA.SEQ_ADMI_MODELO_ELEMENTO.NEXTVAL,
      Ln_IdMarcaElemento,
      Ln_IdTipoElemento,
      'FIBRA INVISIBLE',
      'FIBRA INVISIBLE',
      'Activo',
      'mlcruz',
      SYSDATE,
      'mlcruz',
      SYSDATE
    );
    
    INSERT
    INTO DB_INFRAESTRUCTURA.ADMI_INTERFACE_MODELO
  (
    ID_INTERFACE_MODELO,
    MODELO_ELEMENTO_ID,
    TIPO_INTERFACE_ID,
    CANTIDAD_INTERFACE,
    CLASE_INTERFACE,
    ESTADO,
    USR_CREACION,
    FE_CREACION,
    USR_ULT_MOD,
    FE_ULT_MOD,
    FORMATO_INTERFACE
  )
  VALUES
  (
    DB_INFRAESTRUCTURA.SEQ_ADMI_INTERFACE_MODELO.NEXTVAL,
    (SELECT ID_MODELO_ELEMENTO
    FROM DB_INFRAESTRUCTURA.ADMI_MODELO_ELEMENTO
    WHERE DESCRIPCION_MODELO_ELEMENTO='FIBRA INVISIBLE'
    ),
    3,1,
    'Standar',
    'Activo',
    'jbozada',
    SYSDATE,
    NULL,
    NULL,
    '?'
  );

  SYS.DBMS_OUTPUT.PUT_LINE('Registros ingresados correctamente');
  COMMIT;
EXCEPTION
WHEN OTHERS THEN
  SYS.DBMS_OUTPUT.PUT_LINE('Error: '|| SQLCODE || ' - ERROR_STACK: ' || DBMS_UTILITY.FORMAT_ERROR_STACK 
                           || ' - ERROR_BACKTRACE: ' || DBMS_UTILITY.FORMAT_ERROR_BACKTRACE);
  ROLLBACK;
END;
