/**
 * DEBE EJECUTARSE EN DB_COMERCIAL
 * Rollback para caracteristica InAudit
 * @author Javier Hidalgo Fernández <jihidalgo@telconet.ec>
 * @version 1.0 25-11-2021 - Versión Inicial.
 */
UPDATE DB_COMERCIAL.ADMI_CARACTERISTICA SET ESTADO = 'Inactivo' where DESCRIPCION_CARACTERISTICA = 'InAudit';

/**
 * DEBE EJECUTARSE EN DB_GENERAL.
 * Rollback para los parametros utilizados para proceso de Corte Posible Abusador y Reconexion del mismo
 * @author Javier Hidalgo Fernández <jihidalgo@telconet.ec>
 * @version 1.0 25-11-2021 - Versión Inicial.
 */
DELETE FROM DB_GENERAL.ADMI_PARAMETRO_DET B WHERE B.PARAMETRO_ID IN (SELECT A.ID_PARAMETRO FROM DB_GENERAL.ADMI_PARAMETRO_CAB A WHERE A.NOMBRE_PARAMETRO = 'MOTIVOS_INAUDITAR_CLIENTE');
DELETE FROM DB_GENERAL.ADMI_PARAMETRO_DET B WHERE B.PARAMETRO_ID IN (SELECT A.ID_PARAMETRO FROM DB_GENERAL.ADMI_PARAMETRO_CAB A WHERE A.NOMBRE_PARAMETRO = 'PERFILES_CONECTAR_POSIBLES_ABUSADORES');
DELETE FROM DB_GENERAL.ADMI_PARAMETRO_CAB A WHERE A.NOMBRE_PARAMETRO = 'MOTIVOS_INAUDITAR_CLIENTE';
DELETE FROM DB_GENERAL.ADMI_PARAMETRO_CAB A WHERE A.NOMBRE_PARAMETRO = 'PERFILES_CONECTAR_POSIBLES_ABUSADORES';

COMMIT;

/