/*
 * Creación de tablas y parámetros de ACCESO A NODOS
 *
 * @author Julio Realpe <jrealpe@telconet.ec>
 * @version 1.0 08-04-2022 - Versión Inicial.
 */

SET SERVEROUTPUT ON
CREATE TABLE DB_INFRAESTRUCTURA.INFO_BITACORA_ACCESO_NODO
(
  	ID_BITACORA_ACCESO_NODO	NUMBER PRIMARY KEY,
  	EMPRESA_COD				VARCHAR2(3),
  	DEPARTAMENTO			VARCHAR2(100),
	LOGIN_AUX				VARCHAR2(100),
  	TECNICO_ASIGNADO		VARCHAR2(100),
	TELEFONO				VARCHAR2(20),
  	TAREA_ID				NUMBER,
  	CANTON 					VARCHAR2(200),
  	NODO_ID					NUMBER,
	NOMBRE_NODO   			VARCHAR2(100),
	ELEMENTO_ID				NUMBER,
  	CODIGOS					VARCHAR2(4000),
  	MOTIVO					VARCHAR2(500),
  	ESTADO_NODO_INICIAL		CLOB,
  	ESTADO_NODO_FINAL		CLOB,
  	OBSERVACION				VARCHAR2(4000),
  	ESTADO					VARCHAR2(20) NOT NULL,
  	FE_CREACION 			TIMESTAMP,
  	USR_CREACION			VARCHAR2(100) NOT NULL,
  	FE_ULT_MOD 				TIMESTAMP,
  	USR_ULT_MOD				VARCHAR2(100)
);
CREATE SEQUENCE DB_INFRAESTRUCTURA.SEQ_INFO_BITACORA_ACCESO_NODO
    INCREMENT BY 1
    START WITH 1
    MINVALUE 1
    MAXVALUE 9999999999999999999999999999;

--INSERT ADMI_PARAMETRO_CAB y ADMI_PARAMETRO_DET
  INSERT INTO DB_GENERAL.ADMI_PARAMETRO_CAB
  (
	ID_PARAMETRO,
	NOMBRE_PARAMETRO,
	DESCRIPCION,
	MODULO,
	PROCESO,
	ESTADO,
	USR_CREACION,
	FE_CREACION,
	IP_CREACION,
	USR_ULT_MOD,
	FE_ULT_MOD,
	IP_ULT_MOD
  )
  VALUES 
  (
	DB_GENERAL.SEQ_ADMI_PARAMETRO_CAB.NEXTVAL,
	'PARAMETROS_ACCESO_NODOS',
	'PARAMETRO QUE CONTIENE LOS VALORES Y CONFIGURACIONES NECESARIOS PARA LA CREACION DE BITACORAS',
	'TECNICO',
	'PARAMETROS QUE SE UTILIZA PARA CREAR BITACORAS',
	'Activo',
	'jacarriel',
	SYSDATE,
	'127.0.0.1', 
	NULL,
	NULL,
	NULL
  );


  INSERT INTO DB_GENERAL.ADMI_PARAMETRO_DET
  (
	ID_PARAMETRO_DET,
	PARAMETRO_ID,
	DESCRIPCION,
	VALOR1,
	VALOR2,
	VALOR3,
	VALOR4,
	ESTADO,
	USR_CREACION,
	FE_CREACION,
	IP_CREACION,
	USR_ULT_MOD,
	FE_ULT_MOD,
	IP_ULT_MOD,
	VALOR5,
	EMPRESA_COD,
	VALOR6,
	VALOR7,
	OBSERVACION
  )
  VALUES 
  (
	DB_GENERAL.SEQ_ADMI_PARAMETRO_DET.NEXTVAL,
	( SELECT ID_PARAMETRO FROM DB_GENERAL.ADMI_PARAMETRO_CAB
	WHERE NOMBRE_PARAMETRO = 'PARAMETROS_ACCESO_NODOS' ),
	'PARAMETRO QUE EL TIEMPO DE CADUCIDAD DE UNA TAREA',
	'TAREA_CADUCA',
	'360',
	NULL,
	NULL,
	'Activo',
	'jacarriel',
	SYSDATE,
	'127.0.0.1', 
	NULL,
	NULL,
	NULL,
	NULL,
	NULL,
	NULL,
	NULL,
	NULL
  );

COMMIT;
/
