DELETE DB_GENERAL.ADMI_PARAMETRO_DET
WHERE PARAMETRO_ID =
  (SELECT ID_PARAMETRO
  FROM DB_GENERAL.ADMI_PARAMETRO_CAB
  WHERE NOMBRE_PARAMETRO = 'PARAMETROS_ASOCIADOS_A_SERVICIOS_MD'
  )
AND VALOR1 = 'MODELOS_EQUIPOS'
AND VALOR5 = 'EG8M8145V5G06'
AND ESTADO = 'Activo';
COMMIT;
/