/**
 * DEBE EJECUTARSE EN DB_INFRAESTRUCTURA
 * @author Pedro Velez <psvelez@telconet.ec>
 * @version 1.0
 * @since 29-03-2021
 * Script para agregar campo caso_id en tabla DB_INFRAESTRUCTURA.INFO_PROCESO_MASIVO_CAB
 */

ALTER TABLE DB_INFRAESTRUCTURA.INFO_PROCESO_MASIVO_CAB ADD CASO_ID NUMBER;
COMMENT ON COLUMN DB_INFRAESTRUCTURA.INFO_PROCESO_MASIVO_CAB.CASO_ID IS 'Codigo del caso';

/
