-- Add/modify columns 
ALTER TABLE DB_MONITOREO.GPS_MONITOREO 
DROP COLUMN PUBLISH_ID;

ALTER TABLE DB_MONITOREO.GPS_MONITOREO 
DROP COLUMN ID_CUADRILLA ;

ALTER TABLE DB_MONITOREO.GPS_ULTIMO_PUNTO 
DROP COLUMN PUBLISH_ID;

ALTER TABLE DB_MONITOREO.GPS_ULTIMO_PUNTO 
DROP COLUMN ID_CUADRILLA ;


COMMIT
/