--GRANT PARA SPKG_INFO_TAREA DESDE DB_COMERCIAL
GRANT EXECUTE ON DB_SOPORTE.SPKG_INFO_TAREA TO DB_COMERCIAL;

--INDICE INFO_EVENTO_INDEX7 PARA DETALLE_ID
CREATE INDEX DB_SOPORTE.INFO_EVENTO_INDEX7 ON DB_SOPORTE.INFO_EVENTO (DETALLE_ID ASC);

--GRANT PARA DB_SOPORTE.INFO_EVENTO DESDE DB_COMERCIAL
GRANT UPDATE ON DB_SOPORTE.INFO_EVENTO TO DB_COMERCIAL;



