CREATE INDEX DB_COMERCIAL.INFO_PERSONA_EMPRESA_ROL_CARA ON DB_COMERCIAL.INFO_PERSONA_EMPRESA_ROL_CARAC
  (
    CARACTERISTICA_ID ASC,
    ESTADO ASC
  );

CREATE INDEX DB_SOPORTE.INFO_CASO_ORIGEN ON DB_SOPORTE.INFO_CASO
  (
    ORIGEN ASC
  );