CREATE INDEX INFOCUADRILLAPLANFDET_IDX_001 ON DB_SOPORTE.INFO_CUADRILLA_PLANIF_DET (CUADRILLA_PLANIF_CAB_ID, FE_INICIO, FE_FIN);
CREATE INDEX ADMIINTERVALO_IDX_001 ON DB_SOPORTE.INFO_CUADRILLA_PLANIF_CAB (INTERVALO_ID, ZONA_ID,  FE_TRABAJO, CUADRILLA_ID );

ALTER TABLE "DB_SOPORTE"."INFO_CUADRILLA_PLANIF_CAB" ADD "ACTIVIDAD" VARCHAR2(5);

COMMENT ON COLUMN DB_SOPORTE.INFO_CUADRILLA_PLANIF_CAB.ACTIVIDAD  IS 'CAMPO QUE DEFINE LA ACTIVIDAD DE LA CUADRILLA SI ES DE SOPORTE (S), INSTALACION (I), AMBAS (SI), OPERATIVA (O), RETIRO EQUIPO (RE) E INTER URBANAS (IU) - ADMINISTRACION DE DATA ESTA EN DB_GENERAL.ADMI_PARAMETRO_DET PARAMETRO "PREFERENCIAS_CUADRILLAS_HAL"';
/
