--SE AUMENTA TAMAÑO DE CAMPO VALOR A 1000
--

DROP INDEX DB_COMERCIAL.INFPEREMROLCARAC_IDX_01;
DROP INDEX DB_COMERCIAL.INFO_PERS_EMPR_ROL_CARAC_IDX1;

ALTER TABLE DB_COMERCIAL.INFO_PERSONA_EMPRESA_ROL_CARAC 
MODIFY VALOR VARCHAR2( 1000 );

CREATE INDEX INFPEREMROLCARAC_IDX_01 ON DB_COMERCIAL.INFO_PERSONA_EMPRESA_ROL_CARAC (CARACTERISTICA_ID, VALOR);


CREATE INDEX "DB_COMERCIAL"."INFO_PERS_EMPR_ROL_CARAC_IDX1" ON "DB_COMERCIAL"."INFO_PERSONA_EMPRESA_ROL_CARAC" ("CARACTERISTICA_ID", COALESCE(TO_NUMBER( REGEXP_SUBSTR ("VALOR",'^\d+')),0), "PERSONA_EMPRESA_ROL_ID"); 

--
COMMIT;
/
