--SE ELIMINA COLUMNA ASIGNACION_PADRE_ID DE LA TABLA INFO_ASIGNACION_SOLICITUD
--DEL AMBIENTE DE SOPORTE
---------------------------------------------
ALTER TABLE DB_SOPORTE.INFO_ASIGNACION_SOLICITUD DROP COLUMN ASIGNACION_PADRE_ID;
/