--DDL PARA ELIMINAR LA COLUMNA VALOR_PROGRESO EN CASO DE ERROR.
ALTER TABLE DB_SOPORTE.INFO_PROGRESO_TAREA DROP COLUMN VALOR_PROGRESO;

--DDL PARA ELIMINAR LA COLUMNA ORIGEN EN CASO DE ERROR.
ALTER TABLE DB_SOPORTE.INFO_PROGRESO_TAREA DROP COLUMN ORIGEN;
/
