/*
	Creación de las tablas INFO_RESUMEN_SLA_CAB y INFO_RESUMEN_SLA_DET para ingresar los registros del cálculo SLA para todos los clientes de TN/MD en donde
	la cabecera tendrá la información básica de cada clientes incluido el promedio de disponibilidad calculado de los puntos de cada cliente en caso que tuviesen
	mas de uno y estarán registrados en la tabla de detalle que es donde se tendrá los porcentajes reales por cada punto analizado

	@author Allan Suárez C <arsuarez@telconet.ec>
	@version 1.0
	@since 15-11-2018

*/


CREATE TABLE DB_SOPORTE.INFO_RESUMEN_SLA_CAB 
(
  ID_RESUMEN_SLA_CAB NUMBER NOT NULL 
, RAZON_SOCIAL VARCHAR2(200) NOT NULL 
, IDENTIFICADOR_CLIENTE VARCHAR2(20) NOT NULL 
, EMPRESA VARCHAR2(20) NOT NULL 
, OFICINA VARCHAR2(50) NOT NULL 
, CANTON VARCHAR2(25) NOT NULL 
, PORCENTAJE_DISP_PROMEDIO FLOAT NOT NULL 
, MINUTOS_INCIDENCIA_PROMEDIO FLOAT NOT NULL 
, FECHA_INICIO DATE NOT NULL
, FECHA_FIN DATE NOT NULL
, EMPRESA_COD VARCHAR2(5) NOT NULL 
, PERSONA_ROL_ID NUMBER NOT NULL 
, USR_CREACION VARCHAR2(10) NOT NULL 
, FE_CREACION TIMESTAMP NOT NULL 
, ESTADO VARCHAR2(10) NOT NULL
, CONSTRAINT INFO_RESUMEN_SLA_CAB_PK PRIMARY KEY 
  (
    ID_RESUMEN_SLA_CAB 
  )
  ENABLE 
);

--INDICES

CREATE INDEX DB_SOPORTE.INFO_RESUMEN_SLA_CAB_INDEX1 ON DB_SOPORTE.INFO_RESUMEN_SLA_CAB (PERSONA_ROL_ID ASC);

CREATE INDEX DB_SOPORTE.INFO_RESUMEN_SLA_CAB_INDEX2 ON DB_SOPORTE.INFO_RESUMEN_SLA_CAB (IDENTIFICADOR_CLIENTE ASC);

CREATE INDEX DB_SOPORTE.INFO_RESUMEN_SLA_CAB_INDEX3 ON DB_SOPORTE.INFO_RESUMEN_SLA_CAB (EMPRESA_COD ASC);

--COMENTARIOS

COMMENT ON COLUMN DB_SOPORTE.INFO_RESUMEN_SLA_CAB.ID_RESUMEN_SLA_CAB IS 'Identificador principal de la tabla de resumen del consumo';

COMMENT ON COLUMN DB_SOPORTE.INFO_RESUMEN_SLA_CAB.RAZON_SOCIAL IS 'Razón Social del Cliente (TN/MD)';

COMMENT ON COLUMN DB_SOPORTE.INFO_RESUMEN_SLA_CAB.IDENTIFICADOR_CLIENTE IS 'Identificador del Cliente, esta puede ser Cédula, Ruc o Pasaporte';

COMMENT ON COLUMN DB_SOPORTE.INFO_RESUMEN_SLA_CAB.EMPRESA IS 'Empresa con la que el cliente tiene servicio ( TN/MD )';

COMMENT ON COLUMN DB_SOPORTE.INFO_RESUMEN_SLA_CAB.OFICINA IS 'Oficina referenciada al cliente en su configuración';

COMMENT ON COLUMN DB_SOPORTE.INFO_RESUMEN_SLA_CAB.CANTON IS 'Cantón de procedencia del Cliente';

COMMENT ON COLUMN DB_SOPORTE.INFO_RESUMEN_SLA_CAB.PORCENTAJE_DISP_PROMEDIO IS 'Porcentaje de disponibilidad promedio en un período de tiempo establecido, determinada por todos los logines en caso de TN y para MD el único login existente';

COMMENT ON COLUMN DB_SOPORTE.INFO_RESUMEN_SLA_CAB.MINUTOS_INCIDENCIA_PROMEDIO IS 'Total minutos de incidencia calculado en cada punto de un cliente que tuviese algún caso en un perído de tiempo';

COMMENT ON COLUMN DB_SOPORTE.INFO_RESUMEN_SLA_CAB.EMPRESA_COD IS 'Código empresa del cliente';

COMMENT ON COLUMN DB_SOPORTE.INFO_RESUMEN_SLA_CAB.PERSONA_ROL_ID IS 'Persona empresa rol id del cliente';

COMMENT ON COLUMN DB_SOPORTE.INFO_RESUMEN_SLA_CAB.FECHA_INICIO IS 'Fecha inicio el cálculo';

COMMENT ON COLUMN DB_SOPORTE.INFO_RESUMEN_SLA_CAB.FECHA_FIN IS 'Fecha Fin del cálculo';

COMMENT ON COLUMN DB_SOPORTE.INFO_RESUMEN_SLA_CAB.USR_CREACION IS 'Usuario default de creación del registro';

COMMENT ON COLUMN DB_SOPORTE.INFO_RESUMEN_SLA_CAB.FE_CREACION IS 'Fecha de creación del registro';

COMMENT ON COLUMN DB_SOPORTE.INFO_RESUMEN_SLA_CAB.ESTADO IS 'Estado del registro';

--

CREATE TABLE DB_SOPORTE.INFO_RESUMEN_SLA_DET 
(
  ID_RESUMEN_SLA_DET NUMBER NOT NULL 
, RESUMEN_SLA_CAB_ID NUMBER NOT NULL 
, LOGIN VARCHAR2(100) NOT NULL 
, PORCENTAJE_DISPONIBILIDAD FLOAT NOT NULL 
, TIEMPO_INCIDENCIA NUMBER NOT NULL 
, PUNTO_ID NUMBER NOT NULL 
, CASOS VARCHAR2(1000)
, USR_CREACION VARCHAR2(10) NOT NULL 
, FE_CREACION TIMESTAMP NOT NULL 
, ESTADO VARCHAR2(10) NOT NULL
, CONSTRAINT INFO_RESUMEN_SLA_DET_PK PRIMARY KEY 
  (
    ID_RESUMEN_SLA_DET 
  )
  ENABLE 
);

--INDICES

CREATE INDEX DB_SOPORTE.INFO_RESUMEN_SLA_DET_INDEX1 ON DB_SOPORTE.INFO_RESUMEN_SLA_DET (RESUMEN_SLA_CAB_ID ASC);

CREATE INDEX DB_SOPORTE.INFO_RESUMEN_SLA_DET_INDEX2 ON DB_SOPORTE.INFO_RESUMEN_SLA_DET (PUNTO_ID ASC);

CREATE INDEX DB_SOPORTE.INFO_RESUMEN_SLA_DET_INDEX3 ON DB_SOPORTE.INFO_RESUMEN_SLA_DET (LOGIN ASC);

ALTER TABLE DB_SOPORTE.INFO_RESUMEN_SLA_DET
ADD CONSTRAINT INFO_RESUMEN_SLA_DET_FK1 FOREIGN KEY
(
  RESUMEN_SLA_CAB_ID 
)
REFERENCES DB_SOPORTE.INFO_RESUMEN_SLA_CAB
(
  ID_RESUMEN_SLA_CAB 
)
ENABLE;

--COMENTARIOS

COMMENT ON COLUMN DB_SOPORTE.INFO_RESUMEN_SLA_DET.ID_RESUMEN_SLA_DET IS 'Identificador principal de la tabla';

COMMENT ON COLUMN DB_SOPORTE.INFO_RESUMEN_SLA_DET.RESUMEN_SLA_CAB_ID IS 'Clave foránea de la tabla cabecera de resumen de sla de clientes';

COMMENT ON COLUMN DB_SOPORTE.INFO_RESUMEN_SLA_DET.LOGIN IS 'Login del punto de un determinado cliente';

COMMENT ON COLUMN DB_SOPORTE.INFO_RESUMEN_SLA_DET.PORCENTAJE_DISPONIBILIDAD IS 'Porcentaje de disponibilidad de un cliente que tenga cerrado casos por caída en un período de tiempo';

COMMENT ON COLUMN DB_SOPORTE.INFO_RESUMEN_SLA_DET.TIEMPO_INCIDENCIA IS 'tiempo total de incidencia registrado en los casos reportados';

COMMENT ON COLUMN DB_SOPORTE.INFO_RESUMEN_SLA_DET.PUNTO_ID IS 'Id del punto del cliente';

COMMENT ON COLUMN DB_SOPORTE.INFO_RESUMEN_SLA_DET.USR_CREACION IS 'Usuario default de creación del registro';

COMMENT ON COLUMN DB_SOPORTE.INFO_RESUMEN_SLA_DET.FE_CREACION IS 'Fecha de creación del registro';

COMMENT ON COLUMN DB_SOPORTE.INFO_RESUMEN_SLA_DET.ESTADO IS 'Estado del registro';

COMMENT ON COLUMN DB_SOPORTE.INFO_RESUMEN_SLA_DET.CASOS IS 'Registro de los casos que generan la indisponibilidad';


-- SECUENCIAS

CREATE SEQUENCE DB_SOPORTE.SEQ_INFO_RESUMEN_SLA_CAB INCREMENT BY 1 MAXVALUE 9999999999999999999999999999 MINVALUE 1 NOCACHE;
CREATE SEQUENCE DB_SOPORTE.SEQ_INFO_RESUMEN_SLA_DET INCREMENT BY 1 MAXVALUE 9999999999999999999999999999 MINVALUE 1 NOCACHE;


