CREATE INDEX idx_asig_sol_001 ON DB_SOPORTE.INFO_ASIGNACION_SOLICITUD (ESTADO,OFICINA_ID,DEPARTAMENTO_ID,FE_CREACION,EMPRESA_COD); 
--
ALTER TABLE "DB_SOPORTE"."INFO_SEGUIMIENTO_ASIGNACION" ADD "COMUNICACION_ID" NUMBER;

COMMENT ON COLUMN DB_SOPORTE.INFO_SEGUIMIENTO_ASIGNACION.COMUNICACION_ID  IS 'CAMPO QUE DEFINE EL ID DE LA TAREA PARA LOS REGISTROS QUE TENGAN TIPO DE ATENCION CASO EN LA TABLA INFO_ASIGNACION_SOLICITUD';