GRANT SELECT ON DB_FINANCIERO.ADMI_TIPO_DOCUMENTO_FINANCIERO TO DB_INFRAESTRUCTURA;
GRANT SELECT ON DB_FINANCIERO.INFO_DOCUMENTO_FINANCIERO_CAB TO DB_INFRAESTRUCTURA;
GRANT SELECT ON DB_FINANCIERO.INFO_DOCUMENTO_FINANCIERO_DET TO DB_INFRAESTRUCTURA;
GRANT SELECT ON DB_FINANCIERO.INFO_DOCUMENTO_CARACTERISTICA TO DB_INFRAESTRUCTURA;
GRANT EXECUTE ON DB_FINANCIERO.FNCK_CONSULTS TO DB_INFRAESTRUCTURA;
GRANT EXECUTE ON DB_FINANCIERO.FNCK_TRANSACTION TO DB_INFRAESTRUCTURA;
GRANT SELECT ON DB_FINANCIERO.INFO_DOCUMENTO_HISTORIAL TO DB_INFRAESTRUCTURA;
         
