-- Create/Recreate indexes 
create index DB_FINANCIERO.INF_IDX_PAGCAB_007 on DB_FINANCIERO.INFO_PAGO_CAB (RECAUDACION_DET_ID);

-- Create/Recreate indexes 
create index DB_FINANCIERO.INF_IDX_PAGDET_001 on DB_FINANCIERO.INFO_RECAUDACION_DET (RECAUDACION_ID);
