/**
 * @author José Candelario <jcandelario@telconet.ec>
 * @version 1.0
 * @since 20-04-2020
 * Se crean las sentencias DML para reversar configuraciones de la estructura 
 * DB_GENERAL.ADMI_PARAMETRO_DET.
 */

DELETE FROM DB_GENERAL.ADMI_PARAMETRO_DET
WHERE PARAMETRO_ID IN ( SELECT ID_PARAMETRO
                        FROM DB_GENERAL.ADMI_PARAMETRO_CAB
                        WHERE NOMBRE_PARAMETRO = 'PROCESO_EMER_SANITARIA'
                        AND ESTADO             = 'Activo');
                        
DELETE FROM DB_GENERAL.ADMI_PARAMETRO_CAB
WHERE NOMBRE_PARAMETRO = 'PROCESO_EMER_SANITARIA'
  AND ESTADO           = 'Activo';

DELETE FROM DB_COMUNICACION.INFO_ALIAS_PLANTILLA 
WHERE
PLANTILLA_ID IN (
    SELECT ID_PLANTILLA
    FROM DB_COMUNICACION.ADMI_PLANTILLA
    WHERE CODIGO = 'RPT_EMER_SANIT'
    AND ESTADO   = 'Activo'
);

--SE ELIMINA PLANTILLA DE CORREO 
DELETE FROM DB_COMUNICACION.ADMI_PLANTILLA 
WHERE CODIGO     = 'RPT_EMER_SANIT' 
AND MODULO       = 'FINANCIERO'
AND ESTADO       = 'Activo';

DELETE FROM DB_COMUNICACION.INFO_ALIAS_PLANTILLA 
WHERE
PLANTILLA_ID IN (
    SELECT ID_PLANTILLA
    FROM DB_COMUNICACION.ADMI_PLANTILLA
    WHERE CODIGO = 'RPT_PREV_SOL_ES'
    AND ESTADO   = 'Activo'
);

--SE ELIMINA PLANTILLA DE CORREO 
DELETE FROM DB_COMUNICACION.ADMI_PLANTILLA 
WHERE CODIGO     = 'RPT_PREV_SOL_ES' 
AND MODULO       = 'FINANCIERO'
AND ESTADO       = 'Activo'; 

DELETE FROM DB_COMUNICACION.INFO_ALIAS_PLANTILLA 
WHERE
PLANTILLA_ID IN (
    SELECT ID_PLANTILLA
    FROM DB_COMUNICACION.ADMI_PLANTILLA
    WHERE CODIGO = 'RPT_FIN_SOL_ES'
    AND ESTADO   = 'Activo'
);

--SE ELIMINA PLANTILLA DE CORREO 
DELETE FROM DB_COMUNICACION.ADMI_PLANTILLA 
WHERE CODIGO     = 'RPT_FIN_SOL_ES' 
AND MODULO       = 'FINANCIERO'
AND ESTADO       = 'Activo'; 

DELETE FROM DB_COMERCIAL.ADMI_CARACTERISTICA WHERE DESCRIPCION_CARACTERISTICA ='ES_SOL_FACTURA';

DELETE FROM DB_COMERCIAL.ADMI_CARACTERISTICA WHERE DESCRIPCION_CARACTERISTICA ='ES_MESES_DIFERIDO';

DELETE FROM DB_COMERCIAL.ADMI_CARACTERISTICA WHERE DESCRIPCION_CARACTERISTICA ='ES_PROCESO_MASIVO';

DELETE FROM DB_COMERCIAL.ADMI_CARACTERISTICA WHERE DESCRIPCION_CARACTERISTICA ='ES_ID_SOLICITUD';

DELETE FROM DB_COMERCIAL.ADMI_TIPO_SOLICITUD
WHERE DESCRIPCION_SOLICITUD = 'SOLICITUD DIFERIDO DE FACTURA POR EMERGENCIA SANITARIA';

COMMIT;
/