/** 
 * @author Alex Arreaga <atarreaga@telconet.ec>
 * @version 1.0 
 * @since 05-09-2022
 * Se crea DML de reverso de configuraciones de mejora de generación de débitos.
 */

DELETE FROM DB_COMERCIAL.ADMI_CARACTERISTICA WHERE DESCRIPCION_CARACTERISTICA IN 
('RUTA_NFS_GENERACION_DEBITO','ESTADO_SERVICIO_GENERACION_DEBITO','FE_ACTIVACION_DESDE_GENERACION_DEBITO',
'FE_ACTIVACION_HASTA_GENERACION_DEBITO','MOTIVOS_RECHAZO_GENERACION_DEBITO')
AND ESTADO = 'Activo';

COMMIT;
/
