-- correccion de codigo de diario a 5 caracteres soportados por NAF
UPDATE DB_FINANCIERO.ADMI_PLANTILLA_CONTABLE_CAB
SET COD_DIARIO = REPLACE(COD_DIARIO,'_','')
WHERE COD_DIARIO IN ('M_DEPM','M_MADG','M_DPGM','M_ADGM','M_AGMA','M_ADPM','M_ADMA')
AND EMPRESA_COD = '18';

-- Actualización de glosa de Asientos contables PAGOS EN LINEA
UPDATE DB_FINANCIERO.ADMI_PLANTILLA_CONTABLE_CAB 
SET FORMATO_GLOSA = 'TELCOS | |comentario_pago| |fecha_deposito| |longitud_240' 
WHERE ID_PLANTILLA_CONTABLE_CAB IN (363,362,367);

UPDATE DB_FINANCIERO.ADMI_PLANTILLA_CONTABLE_CAB 
SET FORMATO_GLOSA = 'TELCOS | |comentario_pago| |fecha_deposito| |longitud_250' 
WHERE ID_PLANTILLA_CONTABLE_CAB IN (361,366,364,365);

-- Actualización de glosa de Detalles Asientos contables PAGOS EN LINEA
UPDATE DB_FINANCIERO.ADMI_PLANTILLA_CONTABLE_DET 
SET FORMATO_GLOSA = 'REFERENCIA: |numero_referencia| fDep: |fecha_deposito| |comentario_pago|longitud_100'
WHERE PLANTILLA_CONTABLE_CAB_ID IN (363,362,361,367,366,364,365);


-- Actualización de glosa de Asientos contables RETENCIONES
UPDATE DB_FINANCIERO.ADMI_PLANTILLA_CONTABLE_CAB 
SET FORMATO_GLOSA = 'TELCOS| |nombre_oficina| |pag_fe_creacion| |codigo_tipo_documento| : |nombre_forma_pago| # |numero_referencia| |nombre_cliente|longitud_240' 
WHERE ID_PLANTILLA_CONTABLE_CAB IN (323,324,325,326,327,328,329,330,331,332,
                                    333,334,335,336,337,338,339,340,341,342,
                                    343,344,345,346,347,348,349,350,351,352);

-- Actualización de glosa de Detalles Asientos contables RETENCIONES
UPDATE DB_FINANCIERO.ADMI_PLANTILLA_CONTABLE_DET 
SET FORMATO_GLOSA = 'TELCOS| |nombre_oficina| |pag_fe_creacion| |codigo_tipo_documento| : |nombre_forma_pago| # |numero_referencia| |nombre_cliente|longitud_100' 
WHERE PLANTILLA_CONTABLE_CAB_ID IN (323,324,325,326,327,328,329,330,331,332,
                                    333,334,335,336,337,338,339,340,341,342,
                                    343,344,345,346,347,348,349,350,351,352);

-- Actualización de glosa de Asientos contables TARJETAS CREDITOS
UPDATE DB_FINANCIERO.ADMI_PLANTILLA_CONTABLE_CAB 
SET FORMATO_GLOSA = 'TELCOS| |comentario_det| |nombre_cliente| |nombre_oficina|longitud_240' 
WHERE ID_PLANTILLA_CONTABLE_CAB IN (289,290,291,291,293);--IN (9,21);

-- Actualización de glosa de Detalles Asientos contables TARJETAS CREDITOS
UPDATE DB_FINANCIERO.ADMI_PLANTILLA_CONTABLE_DET 
SET FORMATO_GLOSA = 'nombre_cliente| |comentario_det| |nombre_oficina|longitud_100' 
WHERE PLANTILLA_CONTABLE_CAB_ID IN (289,290,291,291,293);

-- Actualización de glosa de Asientos contables RECAUDACIONES
UPDATE DB_FINANCIERO.ADMI_PLANTILLA_CONTABLE_CAB 
SET FORMATO_GLOSA = 'TELCOS | |comentario_pago| |fecha_deposito| |longitud_250' 
WHERE ID_PLANTILLA_CONTABLE_CAB IN (353,354,355);

UPDATE DB_FINANCIERO.ADMI_PLANTILLA_CONTABLE_CAB 
SET FORMATO_GLOSA = 'TELCOS | |comentario_pago| |fecha_deposito| |longitud_240' 
WHERE ID_PLANTILLA_CONTABLE_CAB IN (356,357,358);

-- Actualización de glosa de Detalles Asientos contables RECAUDACIONES
UPDATE DB_FINANCIERO.ADMI_PLANTILLA_CONTABLE_DET 
SET FORMATO_GLOSA = 'REFERENCIA: |numero_referencia| fDep: |fecha_deposito| |comentario_pago|longitud_100' 
WHERE PLANTILLA_CONTABLE_CAB_ID IN (353,354,355,356,357,358);


-- Eliminación de lo migrado 
DELETE MIGRA_DOCUMENTO_ASOCIADO MDA
WHERE MDA.NO_CIA = '18'
AND MDA.TIPO_MIGRACION = 'CK'
AND EXISTS (SELECT NULL
            FROM MIGRA_ARCKMM MM
            WHERE MM.ID_MIGRACION = MDA.MIGRACION_ID
            AND MM.NO_CIA = MDA.NO_CIA
            AND MM.ANO = 2018
            AND MM.MES = 9
            AND MM.COD_DIARIO = 'CONAP');
            
DELETE MIGRA_DOCUMENTO_ASOCIADO MDA
WHERE MDA.NO_CIA = '18'
AND MDA.TIPO_MIGRACION = 'CK'
AND EXISTS (SELECT NULL
            FROM MIGRA_ARCKMM MM
            WHERE MM.ID_MIGRACION = MDA.MIGRACION_ID
            AND MM.NO_CIA = MDA.NO_CIA
            AND MM.ANO = 2018
            AND MM.MES = 9
            AND MM.ID_FORMA_PAGO IN (10,11,17));
            
DELETE MIGRA_DOCUMENTO_ASOCIADO MDA
WHERE MDA.NO_CIA = '18'
AND MDA.TIPO_MIGRACION = 'CG'
AND EXISTS (SELECT NULL
            FROM MIGRA_ARCGAE AE
            WHERE AE.ID_MIGRACION = MDA.MIGRACION_ID
            AND AE.NO_CIA = MDA.NO_CIA
            AND AE.COD_DIARIO = 'CONAP'
            AND AE.ANO = 2018
            AND AE.MES = 9);

DELETE MIGRA_DOCUMENTO_ASOCIADO MDA
WHERE MDA.NO_CIA = '18'
AND MDA.TIPO_MIGRACION = 'CG'
AND EXISTS (SELECT NULL
            FROM MIGRA_ARCGAE AE
            WHERE AE.ID_MIGRACION = MDA.MIGRACION_ID
            AND AE.NO_CIA = MDA.NO_CIA
            AND AE.ANO = 2018
            AND AE.MES = 9
            AND AE.ID_FORMA_PAGO IN (10,11,17));

DELETE NAF47_TNET.MIGRA_ARCKML ML
WHERE ML.ANO = 2018
AND ML.MES = 9
AND ML.COD_DIARIO = 'CONAP'
AND ML.NO_CIA = '18';

DELETE NAF47_TNET.MIGRA_ARCKMM MM
WHERE MM.ANO = 2018
AND MM.MES = 9
AND MM.COD_DIARIO = 'CONAP'
AND MM.NO_CIA = '18';

DELETE NAF47_TNET.MIGRA_ARCGAL AL
WHERE AL.ANO = 2018
AND AL.MES = 9
AND AL.COD_DIARIO = 'CONAP'
AND AL.NO_CIA = '18';

DELETE NAF47_TNET.MIGRA_ARCGAE AE
WHERE AE.ANO = 2018
AND AE.MES = 9
AND AE.NO_CIA = '18'
AND AE.COD_DIARIO = 'CONAP';
--
--
DELETE NAF47_TNET.MIGRA_ARCKML ML
WHERE ML.ANO = 2018
AND ML.MES = 9
AND ML.COD_DIARIO = 'CONAP'
AND ML.NO_CIA = '18'
AND EXISTS (SELECT NULL
            FROM MIGRA_ARCKMM MM
            WHERE MM.ID_MIGRACION = ML.MIGRACION_ID
            AND MM.NO_CIA = ML.NO_CIA
            AND MM.ANO = 2018
            AND MM.MES = 9
            AND MM.ID_FORMA_PAGO IN (10,11,17));

DELETE NAF47_TNET.MIGRA_ARCKMM MM
WHERE MM.ANO = 2018
AND MM.MES = 9
AND MM.ID_FORMA_PAGO IN (10,11,17)
AND MM.NO_CIA = '18';

DELETE NAF47_TNET.MIGRA_ARCGAL AL
WHERE AL.ANO = 2018
AND AL.MES = 9
AND AL.NO_CIA = '18'
AND EXISTS (SELECT NULL
            FROM MIGRA_ARCGAE AE
            WHERE AE.ID_MIGRACION = AL.MIGRACION_ID
            AND AE.NO_CIA = AL.NO_CIA
            AND AE.ANO = 2018
            AND AE.MES = 9
            AND AE.ID_FORMA_PAGO IN (10,11,17));
            
DELETE NAF47_TNET.MIGRA_ARCGAE AE
WHERE AE.ANO = 2018
AND AE.MES = 9
AND AE.NO_CIA = '18'
AND AE.ID_FORMA_PAGO IN (10,11,17);

--
COMMIT;
--
