/**
 * @author Alex Arreaga <atarreaga@telconet.ec>
 * @version 1.0
 * @since 21-08-2019    
 * Se crea DML para configuraciones al Banco Guayaquil.
 */

--ACTUALIZA A INACTIVO EL ADMI_FORMATO_DEBITO_RESPUESTA EXCEL AL BANCO GUAYAQUIL.
UPDATE DB_FINANCIERO.ADMI_FORMATO_DEBITO_RESPUESTA 
SET ESTADO                 = 'Inactivo',
FE_ULT_MOD                 = SYSDATE,
USR_ULT_MOD                = 'atarreaga'
WHERE BANCO_TIPO_CUENTA_ID = 
  (
  SELECT ABTC.ID_BANCO_TIPO_CUENTA
  FROM DB_FINANCIERO.ADMI_BANCO_TIPO_CUENTA ABTC,
    DB_FINANCIERO.ADMI_BANCO AB,
    DB_FINANCIERO.ADMI_TIPO_CUENTA ATC
  WHERE ABTC.BANCO_ID        = AB.ID_BANCO
  AND ABTC.TIPO_CUENTA_ID    = ATC.ID_TIPO_CUENTA
  AND ATC.DESCRIPCION_CUENTA = 'AHORRO'
  AND ATC.ESTADO             = 'Activo'
  AND AB.DESCRIPCION_BANCO   = 'BANCO GUAYAQUIL'
  AND AB.ESTADO              = 'Activo'
  )  
AND EMPRESA_COD = 18 
AND BUSCA_POR   = 'IDENTIFICACION|CUENTA|VALOR' 
AND ESTADO      = 'Activo';

--ACTUALIZA A ESTADO 'INACTIVO' LOS FORMATOS DE DEBITO DE ENVIO AL BANCO GUAYAQUIL.
UPDATE DB_FINANCIERO.ADMI_FORMATO_DEBITO 
SET ESTADO  = 'Inactivo',
USR_ULT_MOD = 'atarreaga',
FE_ULT_MOD  = SYSDATE
WHERE ID_FORMATO_DEBITO IN (
(
SELECT ID_FORMATO_DEBITO FROM DB_FINANCIERO.ADMI_FORMATO_DEBITO 
WHERE DESCRIPCION        = 'Codigo Orientacion' 
AND BANCO_TIPO_CUENTA_ID = 
  (
  SELECT ABTC.ID_BANCO_TIPO_CUENTA
  FROM DB_FINANCIERO.ADMI_BANCO_TIPO_CUENTA ABTC,
    DB_FINANCIERO.ADMI_BANCO AB,
    DB_FINANCIERO.ADMI_TIPO_CUENTA ATC
  WHERE ABTC.BANCO_ID        = AB.ID_BANCO
  AND ABTC.TIPO_CUENTA_ID    = ATC.ID_TIPO_CUENTA
  AND ATC.DESCRIPCION_CUENTA = 'AHORRO'
  AND ATC.ESTADO             = 'Activo'
  AND AB.DESCRIPCION_BANCO   = 'BANCO GUAYAQUIL'
  AND AB.ESTADO              = 'Activo'
  ) 
AND POSICION 	   = 1 
AND TIPO_FORMATO = 'DETALLE' 
AND EMPRESA_COD  = 18 
AND ESTADO 		   = 'Activo'
),

(
SELECT ID_FORMATO_DEBITO FROM DB_FINANCIERO.ADMI_FORMATO_DEBITO 
WHERE DESCRIPCION        = 'Cuenta Empresa' 
AND BANCO_TIPO_CUENTA_ID = 
  (
  SELECT ABTC.ID_BANCO_TIPO_CUENTA
  FROM DB_FINANCIERO.ADMI_BANCO_TIPO_CUENTA ABTC,
    DB_FINANCIERO.ADMI_BANCO AB,
    DB_FINANCIERO.ADMI_TIPO_CUENTA ATC
  WHERE ABTC.BANCO_ID        = AB.ID_BANCO
  AND ABTC.TIPO_CUENTA_ID    = ATC.ID_TIPO_CUENTA
  AND ATC.DESCRIPCION_CUENTA = 'AHORRO'
  AND ATC.ESTADO             = 'Activo'
  AND AB.DESCRIPCION_BANCO   = 'BANCO GUAYAQUIL'
  AND AB.ESTADO              = 'Activo'
  ) 
AND POSICION     = 2 
AND TIPO_FORMATO = 'DETALLE' 
AND EMPRESA_COD  = 18 
AND ESTADO       = 'Activo'
),

(
SELECT ID_FORMATO_DEBITO FROM DB_FINANCIERO.ADMI_FORMATO_DEBITO 
WHERE DESCRIPCION 	     = 'Secuencial' 
AND BANCO_TIPO_CUENTA_ID = 
  (
  SELECT ABTC.ID_BANCO_TIPO_CUENTA
  FROM DB_FINANCIERO.ADMI_BANCO_TIPO_CUENTA ABTC,
    DB_FINANCIERO.ADMI_BANCO AB,
    DB_FINANCIERO.ADMI_TIPO_CUENTA ATC
  WHERE ABTC.BANCO_ID        = AB.ID_BANCO
  AND ABTC.TIPO_CUENTA_ID    = ATC.ID_TIPO_CUENTA
  AND ATC.DESCRIPCION_CUENTA = 'AHORRO'
  AND ATC.ESTADO             = 'Activo'
  AND AB.DESCRIPCION_BANCO   = 'BANCO GUAYAQUIL'
  AND AB.ESTADO              = 'Activo'
  )  
AND POSICION 	   = 3 
AND TIPO_FORMATO = 'DETALLE' 
AND EMPRESA_COD  = 18 
AND ESTADO       = 'Activo'
),

(
SELECT ID_FORMATO_DEBITO FROM DB_FINANCIERO.ADMI_FORMATO_DEBITO 
WHERE DESCRIPCION        = 'Comprobante de Cobro' 
AND BANCO_TIPO_CUENTA_ID = 
  (
  SELECT ABTC.ID_BANCO_TIPO_CUENTA
  FROM DB_FINANCIERO.ADMI_BANCO_TIPO_CUENTA ABTC,
    DB_FINANCIERO.ADMI_BANCO AB,
    DB_FINANCIERO.ADMI_TIPO_CUENTA ATC
  WHERE ABTC.BANCO_ID        = AB.ID_BANCO
  AND ABTC.TIPO_CUENTA_ID    = ATC.ID_TIPO_CUENTA
  AND ATC.DESCRIPCION_CUENTA = 'AHORRO'
  AND ATC.ESTADO             = 'Activo'
  AND AB.DESCRIPCION_BANCO   = 'BANCO GUAYAQUIL'
  AND AB.ESTADO              = 'Activo'
  )  
AND POSICION     = 4 
AND TIPO_FORMATO = 'DETALLE' 
AND EMPRESA_COD  = 18 
AND ESTADO       = 'Activo'
),

(
SELECT ID_FORMATO_DEBITO FROM DB_FINANCIERO.ADMI_FORMATO_DEBITO 
WHERE DESCRIPCION        = 'Contrapartida' 
AND BANCO_TIPO_CUENTA_ID = 
  (
  SELECT ABTC.ID_BANCO_TIPO_CUENTA
  FROM DB_FINANCIERO.ADMI_BANCO_TIPO_CUENTA ABTC,
    DB_FINANCIERO.ADMI_BANCO AB,
    DB_FINANCIERO.ADMI_TIPO_CUENTA ATC
  WHERE ABTC.BANCO_ID        = AB.ID_BANCO
  AND ABTC.TIPO_CUENTA_ID    = ATC.ID_TIPO_CUENTA
  AND ATC.DESCRIPCION_CUENTA = 'AHORRO'
  AND ATC.ESTADO             = 'Activo'
  AND AB.DESCRIPCION_BANCO   = 'BANCO GUAYAQUIL'
  AND AB.ESTADO              = 'Activo'
  )  
AND POSICION     = 5 
AND TIPO_FORMATO = 'DETALLE' 
AND EMPRESA_COD  = 18 
AND ESTADO       = 'Activo'
),

(
SELECT ID_FORMATO_DEBITO FROM DB_FINANCIERO.ADMI_FORMATO_DEBITO 
WHERE DESCRIPCION        = 'Moneda' 
AND BANCO_TIPO_CUENTA_ID = 
  (
  SELECT ABTC.ID_BANCO_TIPO_CUENTA
  FROM DB_FINANCIERO.ADMI_BANCO_TIPO_CUENTA ABTC,
    DB_FINANCIERO.ADMI_BANCO AB,
    DB_FINANCIERO.ADMI_TIPO_CUENTA ATC
  WHERE ABTC.BANCO_ID        = AB.ID_BANCO
  AND ABTC.TIPO_CUENTA_ID    = ATC.ID_TIPO_CUENTA
  AND ATC.DESCRIPCION_CUENTA = 'AHORRO'
  AND ATC.ESTADO             = 'Activo'
  AND AB.DESCRIPCION_BANCO   = 'BANCO GUAYAQUIL'
  AND AB.ESTADO              = 'Activo'
  )  
AND POSICION     = 6 
AND TIPO_FORMATO = 'DETALLE' 
AND EMPRESA_COD  = 18 
AND ESTADO       = 'Activo'
),

(
SELECT ID_FORMATO_DEBITO FROM DB_FINANCIERO.ADMI_FORMATO_DEBITO 
WHERE DESCRIPCION        = 'Valor' 
AND BANCO_TIPO_CUENTA_ID = 
  (
  SELECT ABTC.ID_BANCO_TIPO_CUENTA
  FROM DB_FINANCIERO.ADMI_BANCO_TIPO_CUENTA ABTC,
    DB_FINANCIERO.ADMI_BANCO AB,
    DB_FINANCIERO.ADMI_TIPO_CUENTA ATC
  WHERE ABTC.BANCO_ID        = AB.ID_BANCO
  AND ABTC.TIPO_CUENTA_ID    = ATC.ID_TIPO_CUENTA
  AND ATC.DESCRIPCION_CUENTA = 'AHORRO'
  AND ATC.ESTADO             = 'Activo'
  AND AB.DESCRIPCION_BANCO   = 'BANCO GUAYAQUIL'
  AND AB.ESTADO              = 'Activo'
  )  
AND POSICION     = 7 
AND TIPO_FORMATO = 'DETALLE' 
AND EMPRESA_COD  = 18 
AND ESTADO       = 'Activo'
),

(
SELECT ID_FORMATO_DEBITO FROM DB_FINANCIERO.ADMI_FORMATO_DEBITO 
WHERE DESCRIPCION        = 'Forma de Cobro' 
AND BANCO_TIPO_CUENTA_ID = 
  (
  SELECT ABTC.ID_BANCO_TIPO_CUENTA
  FROM DB_FINANCIERO.ADMI_BANCO_TIPO_CUENTA ABTC,
    DB_FINANCIERO.ADMI_BANCO AB,
    DB_FINANCIERO.ADMI_TIPO_CUENTA ATC
  WHERE ABTC.BANCO_ID        = AB.ID_BANCO
  AND ABTC.TIPO_CUENTA_ID    = ATC.ID_TIPO_CUENTA
  AND ATC.DESCRIPCION_CUENTA = 'AHORRO'
  AND ATC.ESTADO             = 'Activo'
  AND AB.DESCRIPCION_BANCO   = 'BANCO GUAYAQUIL'
  AND AB.ESTADO              = 'Activo'
  )  
AND POSICION     = 8 
AND TIPO_FORMATO = 'DETALLE' 
AND EMPRESA_COD  = 18 
AND ESTADO       = 'Activo'
),

(
SELECT ID_FORMATO_DEBITO FROM DB_FINANCIERO.ADMI_FORMATO_DEBITO 
WHERE DESCRIPCION        = 'Codigo de Banco' 
AND BANCO_TIPO_CUENTA_ID = 
  (
  SELECT ABTC.ID_BANCO_TIPO_CUENTA
  FROM DB_FINANCIERO.ADMI_BANCO_TIPO_CUENTA ABTC,
    DB_FINANCIERO.ADMI_BANCO AB,
    DB_FINANCIERO.ADMI_TIPO_CUENTA ATC
  WHERE ABTC.BANCO_ID        = AB.ID_BANCO
  AND ABTC.TIPO_CUENTA_ID    = ATC.ID_TIPO_CUENTA
  AND ATC.DESCRIPCION_CUENTA = 'AHORRO'
  AND ATC.ESTADO             = 'Activo'
  AND AB.DESCRIPCION_BANCO   = 'BANCO GUAYAQUIL'
  AND AB.ESTADO              = 'Activo'
  )  
AND POSICION     = 9 
AND TIPO_FORMATO = 'DETALLE' 
AND EMPRESA_COD  = 18 
AND ESTADO       = 'Activo'
),

(
SELECT ID_FORMATO_DEBITO FROM DB_FINANCIERO.ADMI_FORMATO_DEBITO 
WHERE DESCRIPCION        = 'Tipo de Cuenta' 
AND BANCO_TIPO_CUENTA_ID = 
  (
  SELECT ABTC.ID_BANCO_TIPO_CUENTA
  FROM DB_FINANCIERO.ADMI_BANCO_TIPO_CUENTA ABTC,
    DB_FINANCIERO.ADMI_BANCO AB,
    DB_FINANCIERO.ADMI_TIPO_CUENTA ATC
  WHERE ABTC.BANCO_ID        = AB.ID_BANCO
  AND ABTC.TIPO_CUENTA_ID    = ATC.ID_TIPO_CUENTA
  AND ATC.DESCRIPCION_CUENTA = 'AHORRO'
  AND ATC.ESTADO             = 'Activo'
  AND AB.DESCRIPCION_BANCO   = 'BANCO GUAYAQUIL'
  AND AB.ESTADO              = 'Activo'
  )  
AND POSICION     = 10 
AND TIPO_FORMATO = 'DETALLE' 
AND EMPRESA_COD  = 18 
AND ESTADO       = 'Activo'
),

(
SELECT ID_FORMATO_DEBITO FROM DB_FINANCIERO.ADMI_FORMATO_DEBITO 
WHERE DESCRIPCION        = 'Numero de Cuenta' 
AND BANCO_TIPO_CUENTA_ID = 
  (
  SELECT ABTC.ID_BANCO_TIPO_CUENTA
  FROM DB_FINANCIERO.ADMI_BANCO_TIPO_CUENTA ABTC,
    DB_FINANCIERO.ADMI_BANCO AB,
    DB_FINANCIERO.ADMI_TIPO_CUENTA ATC
  WHERE ABTC.BANCO_ID        = AB.ID_BANCO
  AND ABTC.TIPO_CUENTA_ID    = ATC.ID_TIPO_CUENTA
  AND ATC.DESCRIPCION_CUENTA = 'AHORRO'
  AND ATC.ESTADO             = 'Activo'
  AND AB.DESCRIPCION_BANCO   = 'BANCO GUAYAQUIL'
  AND AB.ESTADO              = 'Activo'
  )  
AND POSICION     = 11 
AND TIPO_FORMATO = 'DETALLE' 
AND EMPRESA_COD  = 18 
AND ESTADO       = 'Activo'
),

(
SELECT ID_FORMATO_DEBITO FROM DB_FINANCIERO.ADMI_FORMATO_DEBITO 
WHERE DESCRIPCION        = 'Tipo ID Cliente Beneficiario o Deudor' 
AND BANCO_TIPO_CUENTA_ID = 
  (
  SELECT ABTC.ID_BANCO_TIPO_CUENTA
  FROM DB_FINANCIERO.ADMI_BANCO_TIPO_CUENTA ABTC,
    DB_FINANCIERO.ADMI_BANCO AB,
    DB_FINANCIERO.ADMI_TIPO_CUENTA ATC
  WHERE ABTC.BANCO_ID        = AB.ID_BANCO
  AND ABTC.TIPO_CUENTA_ID    = ATC.ID_TIPO_CUENTA
  AND ATC.DESCRIPCION_CUENTA = 'AHORRO'
  AND ATC.ESTADO             = 'Activo'
  AND AB.DESCRIPCION_BANCO   = 'BANCO GUAYAQUIL'
  AND AB.ESTADO              = 'Activo'
  )  
AND POSICION     = 12 
AND TIPO_FORMATO = 'DETALLE' 
AND EMPRESA_COD  = 18 
AND ESTADO       = 'Activo'
),

(
SELECT ID_FORMATO_DEBITO FROM DB_FINANCIERO.ADMI_FORMATO_DEBITO 
WHERE DESCRIPCION        = 'Numero ID Cliente Beneficiario / Deudor' 
AND BANCO_TIPO_CUENTA_ID = 
  (
  SELECT ABTC.ID_BANCO_TIPO_CUENTA
  FROM DB_FINANCIERO.ADMI_BANCO_TIPO_CUENTA ABTC,
    DB_FINANCIERO.ADMI_BANCO AB,
    DB_FINANCIERO.ADMI_TIPO_CUENTA ATC
  WHERE ABTC.BANCO_ID        = AB.ID_BANCO
  AND ABTC.TIPO_CUENTA_ID    = ATC.ID_TIPO_CUENTA
  AND ATC.DESCRIPCION_CUENTA = 'AHORRO'
  AND ATC.ESTADO             = 'Activo'
  AND AB.DESCRIPCION_BANCO   = 'BANCO GUAYAQUIL'
  AND AB.ESTADO              = 'Activo'
  )  
AND POSICION     = 13 
AND TIPO_FORMATO = 'DETALLE' 
AND EMPRESA_COD  = 18 
AND ESTADO       = 'Activo'
),

(
SELECT ID_FORMATO_DEBITO FROM DB_FINANCIERO.ADMI_FORMATO_DEBITO 
WHERE DESCRIPCION        = 'Nombre del Cliente Beneficiario / Deudor' 
AND BANCO_TIPO_CUENTA_ID = 
  (
  SELECT ABTC.ID_BANCO_TIPO_CUENTA
  FROM DB_FINANCIERO.ADMI_BANCO_TIPO_CUENTA ABTC,
    DB_FINANCIERO.ADMI_BANCO AB,
    DB_FINANCIERO.ADMI_TIPO_CUENTA ATC
  WHERE ABTC.BANCO_ID        = AB.ID_BANCO
  AND ABTC.TIPO_CUENTA_ID    = ATC.ID_TIPO_CUENTA
  AND ATC.DESCRIPCION_CUENTA = 'AHORRO'
  AND ATC.ESTADO             = 'Activo'
  AND AB.DESCRIPCION_BANCO   = 'BANCO GUAYAQUIL'
  AND AB.ESTADO              = 'Activo'
  )  
AND POSICION     = 14 
AND TIPO_FORMATO = 'DETALLE' 
AND EMPRESA_COD  = 18 
AND ESTADO       = 'Activo'
),

(
SELECT ID_FORMATO_DEBITO FROM DB_FINANCIERO.ADMI_FORMATO_DEBITO 
WHERE DESCRIPCION        = 'Dirección Beneficiario / Deudor' 
AND BANCO_TIPO_CUENTA_ID = 
  (
  SELECT ABTC.ID_BANCO_TIPO_CUENTA
  FROM DB_FINANCIERO.ADMI_BANCO_TIPO_CUENTA ABTC,
    DB_FINANCIERO.ADMI_BANCO AB,
    DB_FINANCIERO.ADMI_TIPO_CUENTA ATC
  WHERE ABTC.BANCO_ID        = AB.ID_BANCO
  AND ABTC.TIPO_CUENTA_ID    = ATC.ID_TIPO_CUENTA
  AND ATC.DESCRIPCION_CUENTA = 'AHORRO'
  AND ATC.ESTADO             = 'Activo'
  AND AB.DESCRIPCION_BANCO   = 'BANCO GUAYAQUIL'
  AND AB.ESTADO              = 'Activo'
  ) 
AND POSICION     = 15 
AND TIPO_FORMATO = 'DETALLE' 
AND EMPRESA_COD  = 18 
AND ESTADO       = 'Activo'
),

(
SELECT ID_FORMATO_DEBITO FROM DB_FINANCIERO.ADMI_FORMATO_DEBITO 
WHERE DESCRIPCION        = 'Ciudad Beneficiario / Deudor' 
AND BANCO_TIPO_CUENTA_ID = 
  (
  SELECT ABTC.ID_BANCO_TIPO_CUENTA
  FROM DB_FINANCIERO.ADMI_BANCO_TIPO_CUENTA ABTC,
    DB_FINANCIERO.ADMI_BANCO AB,
    DB_FINANCIERO.ADMI_TIPO_CUENTA ATC
  WHERE ABTC.BANCO_ID        = AB.ID_BANCO
  AND ABTC.TIPO_CUENTA_ID    = ATC.ID_TIPO_CUENTA
  AND ATC.DESCRIPCION_CUENTA = 'AHORRO'
  AND ATC.ESTADO             = 'Activo'
  AND AB.DESCRIPCION_BANCO   = 'BANCO GUAYAQUIL'
  AND AB.ESTADO              = 'Activo'
  ) 
AND POSICION     = 16 
AND TIPO_FORMATO = 'DETALLE' 
AND EMPRESA_COD  = 18 
AND ESTADO       = 'Activo'
),

(
SELECT ID_FORMATO_DEBITO FROM DB_FINANCIERO.ADMI_FORMATO_DEBITO 
WHERE DESCRIPCION        = 'Teléfono Beneficiario / Deudor' 
AND BANCO_TIPO_CUENTA_ID = 
  (
  SELECT ABTC.ID_BANCO_TIPO_CUENTA
  FROM DB_FINANCIERO.ADMI_BANCO_TIPO_CUENTA ABTC,
    DB_FINANCIERO.ADMI_BANCO AB,
    DB_FINANCIERO.ADMI_TIPO_CUENTA ATC
  WHERE ABTC.BANCO_ID        = AB.ID_BANCO
  AND ABTC.TIPO_CUENTA_ID    = ATC.ID_TIPO_CUENTA
  AND ATC.DESCRIPCION_CUENTA = 'AHORRO'
  AND ATC.ESTADO             = 'Activo'
  AND AB.DESCRIPCION_BANCO   = 'BANCO GUAYAQUIL'
  AND AB.ESTADO              = 'Activo'
  ) 
AND POSICION     = 17 
AND TIPO_FORMATO = 'DETALLE' 
AND EMPRESA_COD  = 18 
AND ESTADO       = 'Activo'
),

(
SELECT ID_FORMATO_DEBITO FROM DB_FINANCIERO.ADMI_FORMATO_DEBITO 
WHERE DESCRIPCION        = 'Localidad de pago / cobro' 
AND BANCO_TIPO_CUENTA_ID = 
  (
  SELECT ABTC.ID_BANCO_TIPO_CUENTA
  FROM DB_FINANCIERO.ADMI_BANCO_TIPO_CUENTA ABTC,
    DB_FINANCIERO.ADMI_BANCO AB,
    DB_FINANCIERO.ADMI_TIPO_CUENTA ATC
  WHERE ABTC.BANCO_ID        = AB.ID_BANCO
  AND ABTC.TIPO_CUENTA_ID    = ATC.ID_TIPO_CUENTA
  AND ATC.DESCRIPCION_CUENTA = 'AHORRO'
  AND ATC.ESTADO             = 'Activo'
  AND AB.DESCRIPCION_BANCO   = 'BANCO GUAYAQUIL'
  AND AB.ESTADO              = 'Activo'
  )  
AND POSICION     = 18 
AND TIPO_FORMATO = 'DETALLE' 
AND EMPRESA_COD  = 18 
AND ESTADO       = 'Activo'
),

(
SELECT ID_FORMATO_DEBITO FROM DB_FINANCIERO.ADMI_FORMATO_DEBITO 
WHERE DESCRIPCION        = 'Referencia' 
AND BANCO_TIPO_CUENTA_ID = 
  (
  SELECT ABTC.ID_BANCO_TIPO_CUENTA
  FROM DB_FINANCIERO.ADMI_BANCO_TIPO_CUENTA ABTC,
    DB_FINANCIERO.ADMI_BANCO AB,
    DB_FINANCIERO.ADMI_TIPO_CUENTA ATC
  WHERE ABTC.BANCO_ID        = AB.ID_BANCO
  AND ABTC.TIPO_CUENTA_ID    = ATC.ID_TIPO_CUENTA
  AND ATC.DESCRIPCION_CUENTA = 'AHORRO'
  AND ATC.ESTADO             = 'Activo'
  AND AB.DESCRIPCION_BANCO   = 'BANCO GUAYAQUIL'
  AND AB.ESTADO              = 'Activo'
  )  
AND POSICION     = 19 
AND TIPO_FORMATO = 'DETALLE' 
AND EMPRESA_COD  = 18 
AND ESTADO       = 'Activo'
),

(
SELECT ID_FORMATO_DEBITO FROM DB_FINANCIERO.ADMI_FORMATO_DEBITO 
WHERE DESCRIPCION        = 'Referencia Adicional | Email | fecha de vencimiento' 
AND BANCO_TIPO_CUENTA_ID = 
  (
  SELECT ABTC.ID_BANCO_TIPO_CUENTA
  FROM DB_FINANCIERO.ADMI_BANCO_TIPO_CUENTA ABTC,
    DB_FINANCIERO.ADMI_BANCO AB,
    DB_FINANCIERO.ADMI_TIPO_CUENTA ATC
  WHERE ABTC.BANCO_ID        = AB.ID_BANCO
  AND ABTC.TIPO_CUENTA_ID    = ATC.ID_TIPO_CUENTA
  AND ATC.DESCRIPCION_CUENTA = 'AHORRO'
  AND ATC.ESTADO             = 'Activo'
  AND AB.DESCRIPCION_BANCO   = 'BANCO GUAYAQUIL'
  AND AB.ESTADO              = 'Activo'
  )  
AND POSICION     = 20 
AND TIPO_FORMATO = 'DETALLE' 
AND EMPRESA_COD  = 18 
AND ESTADO       = 'Activo'
),

(
SELECT ID_FORMATO_DEBITO FROM DB_FINANCIERO.ADMI_FORMATO_DEBITO 
WHERE DESCRIPCION        = 'Número Factura' 
AND BANCO_TIPO_CUENTA_ID = 
  (
  SELECT ABTC.ID_BANCO_TIPO_CUENTA
  FROM DB_FINANCIERO.ADMI_BANCO_TIPO_CUENTA ABTC,
    DB_FINANCIERO.ADMI_BANCO AB,
    DB_FINANCIERO.ADMI_TIPO_CUENTA ATC
  WHERE ABTC.BANCO_ID        = AB.ID_BANCO
  AND ABTC.TIPO_CUENTA_ID    = ATC.ID_TIPO_CUENTA
  AND ATC.DESCRIPCION_CUENTA = 'AHORRO'
  AND ATC.ESTADO             = 'Activo'
  AND AB.DESCRIPCION_BANCO   = 'BANCO GUAYAQUIL'
  AND AB.ESTADO              = 'Activo'
  ) 
AND POSICION     = 21 
AND TIPO_FORMATO = 'DETALLE' 
AND EMPRESA_COD  = 18 
AND ESTADO       = 'Activo'
),

(
SELECT ID_FORMATO_DEBITO FROM DB_FINANCIERO.ADMI_FORMATO_DEBITO 
WHERE DESCRIPCION        = 'TipoProceso' 
AND BANCO_TIPO_CUENTA_ID = 
  (
  SELECT ABTC.ID_BANCO_TIPO_CUENTA
  FROM DB_FINANCIERO.ADMI_BANCO_TIPO_CUENTA ABTC,
    DB_FINANCIERO.ADMI_BANCO AB,
    DB_FINANCIERO.ADMI_TIPO_CUENTA ATC
  WHERE ABTC.BANCO_ID        = AB.ID_BANCO
  AND ABTC.TIPO_CUENTA_ID    = ATC.ID_TIPO_CUENTA
  AND ATC.DESCRIPCION_CUENTA = 'AHORRO'
  AND ATC.ESTADO             = 'Activo'
  AND AB.DESCRIPCION_BANCO   = 'BANCO GUAYAQUIL'
  AND AB.ESTADO              = 'Activo'
  ) 
AND POSICION     = 1 
AND TIPO_FORMATO = 'DESGLOSE_IVA_BIEN' 
AND EMPRESA_COD  = 18 
AND ESTADO       = 'Activo'
),

(
SELECT ID_FORMATO_DEBITO FROM DB_FINANCIERO.ADMI_FORMATO_DEBITO 
WHERE DESCRIPCION        = 'Secuencial' 
AND BANCO_TIPO_CUENTA_ID = 
  (
  SELECT ABTC.ID_BANCO_TIPO_CUENTA
  FROM DB_FINANCIERO.ADMI_BANCO_TIPO_CUENTA ABTC,
    DB_FINANCIERO.ADMI_BANCO AB,
    DB_FINANCIERO.ADMI_TIPO_CUENTA ATC
  WHERE ABTC.BANCO_ID        = AB.ID_BANCO
  AND ABTC.TIPO_CUENTA_ID    = ATC.ID_TIPO_CUENTA
  AND ATC.DESCRIPCION_CUENTA = 'AHORRO'
  AND ATC.ESTADO             = 'Activo'
  AND AB.DESCRIPCION_BANCO   = 'BANCO GUAYAQUIL'
  AND AB.ESTADO              = 'Activo'
  ) 
AND POSICION     = 2 
AND TIPO_FORMATO = 'DESGLOSE_IVA_BIEN' 
AND EMPRESA_COD  = 18 
AND ESTADO       = 'Activo'
),

(
SELECT ID_FORMATO_DEBITO FROM DB_FINANCIERO.ADMI_FORMATO_DEBITO 
WHERE DESCRIPCION        = 'Tiporubro' 
AND BANCO_TIPO_CUENTA_ID = 
  (
  SELECT ABTC.ID_BANCO_TIPO_CUENTA
  FROM DB_FINANCIERO.ADMI_BANCO_TIPO_CUENTA ABTC,
    DB_FINANCIERO.ADMI_BANCO AB,
    DB_FINANCIERO.ADMI_TIPO_CUENTA ATC
  WHERE ABTC.BANCO_ID        = AB.ID_BANCO
  AND ABTC.TIPO_CUENTA_ID    = ATC.ID_TIPO_CUENTA
  AND ATC.DESCRIPCION_CUENTA = 'AHORRO'
  AND ATC.ESTADO             = 'Activo'
  AND AB.DESCRIPCION_BANCO   = 'BANCO GUAYAQUIL'
  AND AB.ESTADO              = 'Activo'
  )  
AND POSICION     = 3 
AND TIPO_FORMATO = 'DESGLOSE_IVA_BIEN' 
AND EMPRESA_COD  = 18 
AND ESTADO       = 'Activo'
),

(
SELECT ID_FORMATO_DEBITO FROM DB_FINANCIERO.ADMI_FORMATO_DEBITO 
WHERE DESCRIPCION        = 'Concepto' 
AND BANCO_TIPO_CUENTA_ID = 
  (
  SELECT ABTC.ID_BANCO_TIPO_CUENTA
  FROM DB_FINANCIERO.ADMI_BANCO_TIPO_CUENTA ABTC,
    DB_FINANCIERO.ADMI_BANCO AB,
    DB_FINANCIERO.ADMI_TIPO_CUENTA ATC
  WHERE ABTC.BANCO_ID        = AB.ID_BANCO
  AND ABTC.TIPO_CUENTA_ID    = ATC.ID_TIPO_CUENTA
  AND ATC.DESCRIPCION_CUENTA = 'AHORRO'
  AND ATC.ESTADO             = 'Activo'
  AND AB.DESCRIPCION_BANCO   = 'BANCO GUAYAQUIL'
  AND AB.ESTADO              = 'Activo'
  ) 
AND POSICION     = 4 
AND TIPO_FORMATO = 'DESGLOSE_IVA_BIEN' 
AND EMPRESA_COD  = 18 
AND ESTADO       = 'Activo'
),

(
SELECT ID_FORMATO_DEBITO FROM DB_FINANCIERO.ADMI_FORMATO_DEBITO 
WHERE DESCRIPCION        = 'Valorbase' 
AND BANCO_TIPO_CUENTA_ID = 
  (
  SELECT ABTC.ID_BANCO_TIPO_CUENTA
  FROM DB_FINANCIERO.ADMI_BANCO_TIPO_CUENTA ABTC,
    DB_FINANCIERO.ADMI_BANCO AB,
    DB_FINANCIERO.ADMI_TIPO_CUENTA ATC
  WHERE ABTC.BANCO_ID        = AB.ID_BANCO
  AND ABTC.TIPO_CUENTA_ID    = ATC.ID_TIPO_CUENTA
  AND ATC.DESCRIPCION_CUENTA = 'AHORRO'
  AND ATC.ESTADO             = 'Activo'
  AND AB.DESCRIPCION_BANCO   = 'BANCO GUAYAQUIL'
  AND AB.ESTADO              = 'Activo'
  )  
AND POSICION     = 5 
AND TIPO_FORMATO = 'DESGLOSE_IVA_BIEN' 
AND EMPRESA_COD  = 18 
AND ESTADO       = 'Activo'
),

(
SELECT ID_FORMATO_DEBITO FROM DB_FINANCIERO.ADMI_FORMATO_DEBITO 
WHERE DESCRIPCION        = 'Porcentaje' 
AND BANCO_TIPO_CUENTA_ID = 
  (
  SELECT ABTC.ID_BANCO_TIPO_CUENTA
  FROM DB_FINANCIERO.ADMI_BANCO_TIPO_CUENTA ABTC,
    DB_FINANCIERO.ADMI_BANCO AB,
    DB_FINANCIERO.ADMI_TIPO_CUENTA ATC
  WHERE ABTC.BANCO_ID        = AB.ID_BANCO
  AND ABTC.TIPO_CUENTA_ID    = ATC.ID_TIPO_CUENTA
  AND ATC.DESCRIPCION_CUENTA = 'AHORRO'
  AND ATC.ESTADO             = 'Activo'
  AND AB.DESCRIPCION_BANCO   = 'BANCO GUAYAQUIL'
  AND AB.ESTADO              = 'Activo'
  )  
AND POSICION     = 6 
AND TIPO_FORMATO = 'DESGLOSE_IVA_BIEN' 
AND EMPRESA_COD  = 18 
AND ESTADO       = 'Activo'
),

(
SELECT ID_FORMATO_DEBITO FROM DB_FINANCIERO.ADMI_FORMATO_DEBITO 
WHERE DESCRIPCION        = 'Valorneto' 
AND BANCO_TIPO_CUENTA_ID = 
  (
  SELECT ABTC.ID_BANCO_TIPO_CUENTA
  FROM DB_FINANCIERO.ADMI_BANCO_TIPO_CUENTA ABTC,
    DB_FINANCIERO.ADMI_BANCO AB,
    DB_FINANCIERO.ADMI_TIPO_CUENTA ATC
  WHERE ABTC.BANCO_ID        = AB.ID_BANCO
  AND ABTC.TIPO_CUENTA_ID    = ATC.ID_TIPO_CUENTA
  AND ATC.DESCRIPCION_CUENTA = 'AHORRO'
  AND ATC.ESTADO             = 'Activo'
  AND AB.DESCRIPCION_BANCO   = 'BANCO GUAYAQUIL'
  AND AB.ESTADO              = 'Activo'
  )  
AND POSICION     = 7 
AND TIPO_FORMATO = 'DESGLOSE_IVA_BIEN' 
AND EMPRESA_COD  = 18 
AND ESTADO       = 'Activo'
),

(
SELECT ID_FORMATO_DEBITO FROM DB_FINANCIERO.ADMI_FORMATO_DEBITO 
WHERE DESCRIPCION        = 'TipoProceso' 
AND BANCO_TIPO_CUENTA_ID = 
  (
  SELECT ABTC.ID_BANCO_TIPO_CUENTA
  FROM DB_FINANCIERO.ADMI_BANCO_TIPO_CUENTA ABTC,
    DB_FINANCIERO.ADMI_BANCO AB,
    DB_FINANCIERO.ADMI_TIPO_CUENTA ATC
  WHERE ABTC.BANCO_ID        = AB.ID_BANCO
  AND ABTC.TIPO_CUENTA_ID    = ATC.ID_TIPO_CUENTA
  AND ATC.DESCRIPCION_CUENTA = 'AHORRO'
  AND ATC.ESTADO             = 'Activo'
  AND AB.DESCRIPCION_BANCO   = 'BANCO GUAYAQUIL'
  AND AB.ESTADO              = 'Activo'
  )  
AND POSICION     = 1 
AND TIPO_FORMATO = 'DESGLOSE_RENTA_B' 
AND EMPRESA_COD  = 18 
AND ESTADO       = 'Activo'
),

(
SELECT ID_FORMATO_DEBITO FROM DB_FINANCIERO.ADMI_FORMATO_DEBITO 
WHERE DESCRIPCION        = 'Secuencial' 
AND BANCO_TIPO_CUENTA_ID = 
  (
  SELECT ABTC.ID_BANCO_TIPO_CUENTA
  FROM DB_FINANCIERO.ADMI_BANCO_TIPO_CUENTA ABTC,
    DB_FINANCIERO.ADMI_BANCO AB,
    DB_FINANCIERO.ADMI_TIPO_CUENTA ATC
  WHERE ABTC.BANCO_ID        = AB.ID_BANCO
  AND ABTC.TIPO_CUENTA_ID    = ATC.ID_TIPO_CUENTA
  AND ATC.DESCRIPCION_CUENTA = 'AHORRO'
  AND ATC.ESTADO             = 'Activo'
  AND AB.DESCRIPCION_BANCO   = 'BANCO GUAYAQUIL'
  AND AB.ESTADO              = 'Activo'
  ) 
AND POSICION     = 2 
AND TIPO_FORMATO = 'DESGLOSE_RENTA_B' 
AND EMPRESA_COD  = 18 
AND ESTADO       = 'Activo'
),

(
SELECT ID_FORMATO_DEBITO FROM DB_FINANCIERO.ADMI_FORMATO_DEBITO 
WHERE DESCRIPCION        = 'Tiporubro' 
AND BANCO_TIPO_CUENTA_ID = 
  (
  SELECT ABTC.ID_BANCO_TIPO_CUENTA
  FROM DB_FINANCIERO.ADMI_BANCO_TIPO_CUENTA ABTC,
    DB_FINANCIERO.ADMI_BANCO AB,
    DB_FINANCIERO.ADMI_TIPO_CUENTA ATC
  WHERE ABTC.BANCO_ID        = AB.ID_BANCO
  AND ABTC.TIPO_CUENTA_ID    = ATC.ID_TIPO_CUENTA
  AND ATC.DESCRIPCION_CUENTA = 'AHORRO'
  AND ATC.ESTADO             = 'Activo'
  AND AB.DESCRIPCION_BANCO   = 'BANCO GUAYAQUIL'
  AND AB.ESTADO              = 'Activo'
  )  
AND POSICION     = 3 
AND TIPO_FORMATO = 'DESGLOSE_RENTA_B' 
AND EMPRESA_COD  = 18 
AND ESTADO       = 'Activo'
),

(
SELECT ID_FORMATO_DEBITO FROM DB_FINANCIERO.ADMI_FORMATO_DEBITO 
WHERE DESCRIPCION        = 'Concepto' 
AND BANCO_TIPO_CUENTA_ID = 
  (
  SELECT ABTC.ID_BANCO_TIPO_CUENTA
  FROM DB_FINANCIERO.ADMI_BANCO_TIPO_CUENTA ABTC,
    DB_FINANCIERO.ADMI_BANCO AB,
    DB_FINANCIERO.ADMI_TIPO_CUENTA ATC
  WHERE ABTC.BANCO_ID        = AB.ID_BANCO
  AND ABTC.TIPO_CUENTA_ID    = ATC.ID_TIPO_CUENTA
  AND ATC.DESCRIPCION_CUENTA = 'AHORRO'
  AND ATC.ESTADO             = 'Activo'
  AND AB.DESCRIPCION_BANCO   = 'BANCO GUAYAQUIL'
  AND AB.ESTADO              = 'Activo'
  )  
AND POSICION     = 4 
AND TIPO_FORMATO = 'DESGLOSE_RENTA_B' 
AND EMPRESA_COD  = 18 
AND ESTADO       = 'Activo'
),

(
SELECT ID_FORMATO_DEBITO FROM DB_FINANCIERO.ADMI_FORMATO_DEBITO 
WHERE DESCRIPCION        = 'Valorbase' 
AND BANCO_TIPO_CUENTA_ID = 
  (
  SELECT ABTC.ID_BANCO_TIPO_CUENTA
  FROM DB_FINANCIERO.ADMI_BANCO_TIPO_CUENTA ABTC,
    DB_FINANCIERO.ADMI_BANCO AB,
    DB_FINANCIERO.ADMI_TIPO_CUENTA ATC
  WHERE ABTC.BANCO_ID        = AB.ID_BANCO
  AND ABTC.TIPO_CUENTA_ID    = ATC.ID_TIPO_CUENTA
  AND ATC.DESCRIPCION_CUENTA = 'AHORRO'
  AND ATC.ESTADO             = 'Activo'
  AND AB.DESCRIPCION_BANCO   = 'BANCO GUAYAQUIL'
  AND AB.ESTADO              = 'Activo'
  ) 
AND POSICION     = 5 
AND TIPO_FORMATO = 'DESGLOSE_RENTA_B' 
AND EMPRESA_COD  = 18 
AND ESTADO       = 'Activo'
),

(
SELECT ID_FORMATO_DEBITO FROM DB_FINANCIERO.ADMI_FORMATO_DEBITO 
WHERE DESCRIPCION        = 'Porcentaje' 
AND BANCO_TIPO_CUENTA_ID = 
  (
  SELECT ABTC.ID_BANCO_TIPO_CUENTA
  FROM DB_FINANCIERO.ADMI_BANCO_TIPO_CUENTA ABTC,
    DB_FINANCIERO.ADMI_BANCO AB,
    DB_FINANCIERO.ADMI_TIPO_CUENTA ATC
  WHERE ABTC.BANCO_ID        = AB.ID_BANCO
  AND ABTC.TIPO_CUENTA_ID    = ATC.ID_TIPO_CUENTA
  AND ATC.DESCRIPCION_CUENTA = 'AHORRO'
  AND ATC.ESTADO             = 'Activo'
  AND AB.DESCRIPCION_BANCO   = 'BANCO GUAYAQUIL'
  AND AB.ESTADO              = 'Activo'
  )  
AND POSICION     = 6 
AND TIPO_FORMATO = 'DESGLOSE_RENTA_B' 
AND EMPRESA_COD  = 18 
AND ESTADO       = 'Activo'
),

(
SELECT ID_FORMATO_DEBITO FROM DB_FINANCIERO.ADMI_FORMATO_DEBITO 
WHERE DESCRIPCION        = 'Valorneto' 
AND BANCO_TIPO_CUENTA_ID = 
  (
  SELECT ABTC.ID_BANCO_TIPO_CUENTA
  FROM DB_FINANCIERO.ADMI_BANCO_TIPO_CUENTA ABTC,
    DB_FINANCIERO.ADMI_BANCO AB,
    DB_FINANCIERO.ADMI_TIPO_CUENTA ATC
  WHERE ABTC.BANCO_ID        = AB.ID_BANCO
  AND ABTC.TIPO_CUENTA_ID    = ATC.ID_TIPO_CUENTA
  AND ATC.DESCRIPCION_CUENTA = 'AHORRO'
  AND ATC.ESTADO             = 'Activo'
  AND AB.DESCRIPCION_BANCO   = 'BANCO GUAYAQUIL'
  AND AB.ESTADO              = 'Activo'
  )  
AND POSICION     = 7 
AND TIPO_FORMATO = 'DESGLOSE_RENTA_B' 
AND EMPRESA_COD  = 18 
AND ESTADO       = 'Activo'
),

(
SELECT ID_FORMATO_DEBITO FROM DB_FINANCIERO.ADMI_FORMATO_DEBITO 
WHERE DESCRIPCION        = 'TipoProceso' 
AND BANCO_TIPO_CUENTA_ID = 
  (
  SELECT ABTC.ID_BANCO_TIPO_CUENTA
  FROM DB_FINANCIERO.ADMI_BANCO_TIPO_CUENTA ABTC,
    DB_FINANCIERO.ADMI_BANCO AB,
    DB_FINANCIERO.ADMI_TIPO_CUENTA ATC
  WHERE ABTC.BANCO_ID        = AB.ID_BANCO
  AND ABTC.TIPO_CUENTA_ID    = ATC.ID_TIPO_CUENTA
  AND ATC.DESCRIPCION_CUENTA = 'AHORRO'
  AND ATC.ESTADO             = 'Activo'
  AND AB.DESCRIPCION_BANCO   = 'BANCO GUAYAQUIL'
  AND AB.ESTADO              = 'Activo'
  )  
AND POSICION     = 1 
AND TIPO_FORMATO = 'DESGLOSE_IVA_SERV' 
AND EMPRESA_COD  = 18 
AND ESTADO       = 'Activo'
),

(
SELECT ID_FORMATO_DEBITO FROM DB_FINANCIERO.ADMI_FORMATO_DEBITO 
WHERE DESCRIPCION        = 'Secuencial' 
AND BANCO_TIPO_CUENTA_ID = 
  (
  SELECT ABTC.ID_BANCO_TIPO_CUENTA
  FROM DB_FINANCIERO.ADMI_BANCO_TIPO_CUENTA ABTC,
    DB_FINANCIERO.ADMI_BANCO AB,
    DB_FINANCIERO.ADMI_TIPO_CUENTA ATC
  WHERE ABTC.BANCO_ID        = AB.ID_BANCO
  AND ABTC.TIPO_CUENTA_ID    = ATC.ID_TIPO_CUENTA
  AND ATC.DESCRIPCION_CUENTA = 'AHORRO'
  AND ATC.ESTADO             = 'Activo'
  AND AB.DESCRIPCION_BANCO   = 'BANCO GUAYAQUIL'
  AND AB.ESTADO              = 'Activo'
  )  
AND POSICION     = 2 
AND TIPO_FORMATO = 'DESGLOSE_IVA_SERV' 
AND EMPRESA_COD  = 18 
AND ESTADO       = 'Activo'
),

(
SELECT ID_FORMATO_DEBITO FROM DB_FINANCIERO.ADMI_FORMATO_DEBITO 
WHERE DESCRIPCION        = 'Tiporubro' 
AND BANCO_TIPO_CUENTA_ID = 
  (
  SELECT ABTC.ID_BANCO_TIPO_CUENTA
  FROM DB_FINANCIERO.ADMI_BANCO_TIPO_CUENTA ABTC,
    DB_FINANCIERO.ADMI_BANCO AB,
    DB_FINANCIERO.ADMI_TIPO_CUENTA ATC
  WHERE ABTC.BANCO_ID        = AB.ID_BANCO
  AND ABTC.TIPO_CUENTA_ID    = ATC.ID_TIPO_CUENTA
  AND ATC.DESCRIPCION_CUENTA = 'AHORRO'
  AND ATC.ESTADO             = 'Activo'
  AND AB.DESCRIPCION_BANCO   = 'BANCO GUAYAQUIL'
  AND AB.ESTADO              = 'Activo'
  )  
AND POSICION     = 3 
AND TIPO_FORMATO = 'DESGLOSE_IVA_SERV' 
AND EMPRESA_COD  = 18 
AND ESTADO       = 'Activo'
),

(
SELECT ID_FORMATO_DEBITO FROM DB_FINANCIERO.ADMI_FORMATO_DEBITO 
WHERE DESCRIPCION        = 'Concepto' 
AND BANCO_TIPO_CUENTA_ID = 
  (
  SELECT ABTC.ID_BANCO_TIPO_CUENTA
  FROM DB_FINANCIERO.ADMI_BANCO_TIPO_CUENTA ABTC,
    DB_FINANCIERO.ADMI_BANCO AB,
    DB_FINANCIERO.ADMI_TIPO_CUENTA ATC
  WHERE ABTC.BANCO_ID        = AB.ID_BANCO
  AND ABTC.TIPO_CUENTA_ID    = ATC.ID_TIPO_CUENTA
  AND ATC.DESCRIPCION_CUENTA = 'AHORRO'
  AND ATC.ESTADO             = 'Activo'
  AND AB.DESCRIPCION_BANCO   = 'BANCO GUAYAQUIL'
  AND AB.ESTADO              = 'Activo'
  )  
AND POSICION     = 4 
AND TIPO_FORMATO = 'DESGLOSE_IVA_SERV' 
AND EMPRESA_COD  = 18 
AND ESTADO       = 'Activo'
),

(
SELECT ID_FORMATO_DEBITO FROM DB_FINANCIERO.ADMI_FORMATO_DEBITO 
WHERE DESCRIPCION        = 'Valorbase' 
AND BANCO_TIPO_CUENTA_ID = 
  (
  SELECT ABTC.ID_BANCO_TIPO_CUENTA
  FROM DB_FINANCIERO.ADMI_BANCO_TIPO_CUENTA ABTC,
    DB_FINANCIERO.ADMI_BANCO AB,
    DB_FINANCIERO.ADMI_TIPO_CUENTA ATC
  WHERE ABTC.BANCO_ID        = AB.ID_BANCO
  AND ABTC.TIPO_CUENTA_ID    = ATC.ID_TIPO_CUENTA
  AND ATC.DESCRIPCION_CUENTA = 'AHORRO'
  AND ATC.ESTADO             = 'Activo'
  AND AB.DESCRIPCION_BANCO   = 'BANCO GUAYAQUIL'
  AND AB.ESTADO              = 'Activo'
  )  
AND POSICION     = 5 
AND TIPO_FORMATO = 'DESGLOSE_IVA_SERV' 
AND EMPRESA_COD  = 18 
AND ESTADO       = 'Activo'
),

(
SELECT ID_FORMATO_DEBITO FROM DB_FINANCIERO.ADMI_FORMATO_DEBITO 
WHERE DESCRIPCION        = 'Porcentaje' 
AND BANCO_TIPO_CUENTA_ID = 
  (
  SELECT ABTC.ID_BANCO_TIPO_CUENTA
  FROM DB_FINANCIERO.ADMI_BANCO_TIPO_CUENTA ABTC,
    DB_FINANCIERO.ADMI_BANCO AB,
    DB_FINANCIERO.ADMI_TIPO_CUENTA ATC
  WHERE ABTC.BANCO_ID        = AB.ID_BANCO
  AND ABTC.TIPO_CUENTA_ID    = ATC.ID_TIPO_CUENTA
  AND ATC.DESCRIPCION_CUENTA = 'AHORRO'
  AND ATC.ESTADO             = 'Activo'
  AND AB.DESCRIPCION_BANCO   = 'BANCO GUAYAQUIL'
  AND AB.ESTADO              = 'Activo'
  )  
AND POSICION     = 6 
AND TIPO_FORMATO = 'DESGLOSE_IVA_SERV' 
AND EMPRESA_COD  = 18 
AND ESTADO       = 'Activo'
),

(
SELECT ID_FORMATO_DEBITO FROM DB_FINANCIERO.ADMI_FORMATO_DEBITO 
WHERE DESCRIPCION        = 'Valorneto' 
AND BANCO_TIPO_CUENTA_ID = 
  (
  SELECT ABTC.ID_BANCO_TIPO_CUENTA
  FROM DB_FINANCIERO.ADMI_BANCO_TIPO_CUENTA ABTC,
    DB_FINANCIERO.ADMI_BANCO AB,
    DB_FINANCIERO.ADMI_TIPO_CUENTA ATC
  WHERE ABTC.BANCO_ID        = AB.ID_BANCO
  AND ABTC.TIPO_CUENTA_ID    = ATC.ID_TIPO_CUENTA
  AND ATC.DESCRIPCION_CUENTA = 'AHORRO'
  AND ATC.ESTADO             = 'Activo'
  AND AB.DESCRIPCION_BANCO   = 'BANCO GUAYAQUIL'
  AND AB.ESTADO              = 'Activo'
  )  
AND POSICION     = 7 
AND TIPO_FORMATO = 'DESGLOSE_IVA_SERV' 
AND EMPRESA_COD  = 18 
AND ESTADO       = 'Activo'
),

(
SELECT ID_FORMATO_DEBITO FROM DB_FINANCIERO.ADMI_FORMATO_DEBITO 
WHERE DESCRIPCION        = 'TipoProceso' 
AND BANCO_TIPO_CUENTA_ID = 
  (
  SELECT ABTC.ID_BANCO_TIPO_CUENTA
  FROM DB_FINANCIERO.ADMI_BANCO_TIPO_CUENTA ABTC,
    DB_FINANCIERO.ADMI_BANCO AB,
    DB_FINANCIERO.ADMI_TIPO_CUENTA ATC
  WHERE ABTC.BANCO_ID        = AB.ID_BANCO
  AND ABTC.TIPO_CUENTA_ID    = ATC.ID_TIPO_CUENTA
  AND ATC.DESCRIPCION_CUENTA = 'AHORRO'
  AND ATC.ESTADO             = 'Activo'
  AND AB.DESCRIPCION_BANCO   = 'BANCO GUAYAQUIL'
  AND AB.ESTADO              = 'Activo'
  )  
AND POSICION     = 1 
AND TIPO_FORMATO = 'DESGLOSE_RENTA_S' 
AND EMPRESA_COD  = 18 
AND ESTADO       = 'Activo'
),

(
SELECT ID_FORMATO_DEBITO FROM DB_FINANCIERO.ADMI_FORMATO_DEBITO 
WHERE DESCRIPCION        = 'Secuencial' 
AND BANCO_TIPO_CUENTA_ID = 
  (
  SELECT ABTC.ID_BANCO_TIPO_CUENTA
  FROM DB_FINANCIERO.ADMI_BANCO_TIPO_CUENTA ABTC,
    DB_FINANCIERO.ADMI_BANCO AB,
    DB_FINANCIERO.ADMI_TIPO_CUENTA ATC
  WHERE ABTC.BANCO_ID        = AB.ID_BANCO
  AND ABTC.TIPO_CUENTA_ID    = ATC.ID_TIPO_CUENTA
  AND ATC.DESCRIPCION_CUENTA = 'AHORRO'
  AND ATC.ESTADO             = 'Activo'
  AND AB.DESCRIPCION_BANCO   = 'BANCO GUAYAQUIL'
  AND AB.ESTADO              = 'Activo'
  )  
AND POSICION     = 2 
AND TIPO_FORMATO = 'DESGLOSE_RENTA_S' 
AND EMPRESA_COD  = 18 
AND ESTADO       = 'Activo'
),

(
SELECT ID_FORMATO_DEBITO FROM DB_FINANCIERO.ADMI_FORMATO_DEBITO 
WHERE DESCRIPCION        = 'Tiporubro' 
AND BANCO_TIPO_CUENTA_ID = 
  (
  SELECT ABTC.ID_BANCO_TIPO_CUENTA
  FROM DB_FINANCIERO.ADMI_BANCO_TIPO_CUENTA ABTC,
    DB_FINANCIERO.ADMI_BANCO AB,
    DB_FINANCIERO.ADMI_TIPO_CUENTA ATC
  WHERE ABTC.BANCO_ID        = AB.ID_BANCO
  AND ABTC.TIPO_CUENTA_ID    = ATC.ID_TIPO_CUENTA
  AND ATC.DESCRIPCION_CUENTA = 'AHORRO'
  AND ATC.ESTADO             = 'Activo'
  AND AB.DESCRIPCION_BANCO   = 'BANCO GUAYAQUIL'
  AND AB.ESTADO              = 'Activo'
  )  
AND POSICION     = 3 
AND TIPO_FORMATO = 'DESGLOSE_RENTA_S' 
AND EMPRESA_COD  = 18 
AND ESTADO       = 'Activo'
),

(
SELECT ID_FORMATO_DEBITO FROM DB_FINANCIERO.ADMI_FORMATO_DEBITO 
WHERE DESCRIPCION        = 'Concepto' 
AND BANCO_TIPO_CUENTA_ID = 
  (
  SELECT ABTC.ID_BANCO_TIPO_CUENTA
  FROM DB_FINANCIERO.ADMI_BANCO_TIPO_CUENTA ABTC,
    DB_FINANCIERO.ADMI_BANCO AB,
    DB_FINANCIERO.ADMI_TIPO_CUENTA ATC
  WHERE ABTC.BANCO_ID        = AB.ID_BANCO
  AND ABTC.TIPO_CUENTA_ID    = ATC.ID_TIPO_CUENTA
  AND ATC.DESCRIPCION_CUENTA = 'AHORRO'
  AND ATC.ESTADO             = 'Activo'
  AND AB.DESCRIPCION_BANCO   = 'BANCO GUAYAQUIL'
  AND AB.ESTADO              = 'Activo'
  )  
AND POSICION     = 4 
AND TIPO_FORMATO = 'DESGLOSE_RENTA_S' 
AND EMPRESA_COD  = 18 
AND ESTADO       = 'Activo'
),

(
SELECT ID_FORMATO_DEBITO FROM DB_FINANCIERO.ADMI_FORMATO_DEBITO 
WHERE DESCRIPCION        = 'Valorbase' 
AND BANCO_TIPO_CUENTA_ID = 
  (
  SELECT ABTC.ID_BANCO_TIPO_CUENTA
  FROM DB_FINANCIERO.ADMI_BANCO_TIPO_CUENTA ABTC,
    DB_FINANCIERO.ADMI_BANCO AB,
    DB_FINANCIERO.ADMI_TIPO_CUENTA ATC
  WHERE ABTC.BANCO_ID        = AB.ID_BANCO
  AND ABTC.TIPO_CUENTA_ID    = ATC.ID_TIPO_CUENTA
  AND ATC.DESCRIPCION_CUENTA = 'AHORRO'
  AND ATC.ESTADO             = 'Activo'
  AND AB.DESCRIPCION_BANCO   = 'BANCO GUAYAQUIL'
  AND AB.ESTADO              = 'Activo'
  )  
AND POSICION 	   = 5 
AND TIPO_FORMATO = 'DESGLOSE_RENTA_S' 
AND EMPRESA_COD	 = 18 
AND ESTADO       = 'Activo'
),

(
SELECT ID_FORMATO_DEBITO FROM DB_FINANCIERO.ADMI_FORMATO_DEBITO 
WHERE DESCRIPCION        = 'Porcentaje' 
AND BANCO_TIPO_CUENTA_ID = 
  (
  SELECT ABTC.ID_BANCO_TIPO_CUENTA
  FROM DB_FINANCIERO.ADMI_BANCO_TIPO_CUENTA ABTC,
    DB_FINANCIERO.ADMI_BANCO AB,
    DB_FINANCIERO.ADMI_TIPO_CUENTA ATC
  WHERE ABTC.BANCO_ID        = AB.ID_BANCO
  AND ABTC.TIPO_CUENTA_ID    = ATC.ID_TIPO_CUENTA
  AND ATC.DESCRIPCION_CUENTA = 'AHORRO'
  AND ATC.ESTADO             = 'Activo'
  AND AB.DESCRIPCION_BANCO   = 'BANCO GUAYAQUIL'
  AND AB.ESTADO              = 'Activo'
  )  
AND POSICION     = 6 
AND TIPO_FORMATO = 'DESGLOSE_RENTA_S' 
AND EMPRESA_COD  = 18 
AND ESTADO 		   = 'Activo'
),

(
SELECT ID_FORMATO_DEBITO FROM DB_FINANCIERO.ADMI_FORMATO_DEBITO 
WHERE DESCRIPCION        = 'Valorneto' 
AND BANCO_TIPO_CUENTA_ID = 
  (
  SELECT ABTC.ID_BANCO_TIPO_CUENTA
  FROM DB_FINANCIERO.ADMI_BANCO_TIPO_CUENTA ABTC,
    DB_FINANCIERO.ADMI_BANCO AB,
    DB_FINANCIERO.ADMI_TIPO_CUENTA ATC
  WHERE ABTC.BANCO_ID        = AB.ID_BANCO
  AND ABTC.TIPO_CUENTA_ID    = ATC.ID_TIPO_CUENTA
  AND ATC.DESCRIPCION_CUENTA = 'AHORRO'
  AND ATC.ESTADO             = 'Activo'
  AND AB.DESCRIPCION_BANCO   = 'BANCO GUAYAQUIL'
  AND AB.ESTADO              = 'Activo'
  )  
AND POSICION     = 7 
AND TIPO_FORMATO = 'DESGLOSE_RENTA_S' 
AND EMPRESA_COD  = 18 
AND ESTADO       = 'Activo'
)
);


UPDATE DB_FINANCIERO.ADMI_NOMBRE_ARCHIVO_EMPRESA 
SET NOMBRE_ARCHIVO_FORMATO = 'NDE',
SEPARADOR_COLUMNA 	  	   = 'vacio',
FORMATO_NOMBRE					   = 'nombre_archivo|Ymd|E0|_|secuencial|.|extension',
USR_ULT_MOD                = 'atarreaga',
FE_ULT_MOD                 = SYSDATE
WHERE BANCO_TIPO_CUENTA_ID = 
	(
	SELECT ABTC.ID_BANCO_TIPO_CUENTA
	FROM DB_FINANCIERO.ADMI_BANCO_TIPO_CUENTA ABTC,
		DB_FINANCIERO.ADMI_BANCO AB,
		DB_FINANCIERO.ADMI_TIPO_CUENTA ATC
	WHERE ABTC.BANCO_ID        = AB.ID_BANCO
	AND ABTC.TIPO_CUENTA_ID    = ATC.ID_TIPO_CUENTA
	AND ATC.DESCRIPCION_CUENTA = 'AHORRO'
	AND ATC.ESTADO             = 'Activo'
	AND AB.DESCRIPCION_BANCO   = 'BANCO GUAYAQUIL'
	AND AB.ESTADO              = 'Activo'
	)
AND EMPRESA_COD = 18 ;


COMMIT;
/
