INSERT INTO DB_COMPROBANTES.ADMI_ESTADO_DOCUMENTO
 (ID_EST_DOC,
 NOMBRE,
 DESCRIPCION, 
FE_CREACION,
 USR_CREACION,
 IP_CREACION) 
VALUES ('10',
'Creado', 
'Documento fue migrado desde INFO_COMPROBANTE_ELECTRONICO', 
SYSDATE, 
'admin', 
'127.0.0.1')
;
COMMIT;