/**
 * DEBE EJECUTARSE EN DB_GENERAL
 * Script para agregar parametros detalles de DEBITOS_PLANIFICADOS
 * @author Ivan Romero <icromero@telconet.ec>
 * @version 1.0 06-05-2021 - Version Inicial.
 */
--Mensajes TN 
Insert into db_general.admi_parametro_det (ID_PARAMETRO_DET,PARAMETRO_ID,DESCRIPCION,VALOR1,VALOR2,VALOR3,VALOR4,ESTADO,USR_CREACION,FE_CREACION,IP_CREACION,USR_ULT_MOD,FE_ULT_MOD,IP_ULT_MOD,VALOR5,EMPRESA_COD,VALOR6,VALOR7,OBSERVACION) 
values (db_general.seq_admi_parametro_det.nextval,(select ID_PARAMETRO from db_general.admi_parametro_Cab where nombre_parametro='DEBITOS_PLANIFICADOS'),'MensajePlanificado','Se generaran los archivos de los bancos en la Fecha: %FECHA% y los mismos serán notificados vi&#769;a Correo electro&#769;nico. Desea continuar?','Mensaje',null,null,'Activo','icromero',sysdate,'127.0.0.1',null,null,null,null,'10',null,null,null);
Insert into db_general.admi_parametro_det (ID_PARAMETRO_DET,PARAMETRO_ID,DESCRIPCION,VALOR1,VALOR2,VALOR3,VALOR4,ESTADO,USR_CREACION,FE_CREACION,IP_CREACION,USR_ULT_MOD,FE_ULT_MOD,IP_ULT_MOD,VALOR5,EMPRESA_COD,VALOR6,VALOR7,OBSERVACION) 
values (db_general.seq_admi_parametro_det.nextval,(select ID_PARAMETRO from db_general.admi_parametro_Cab where nombre_parametro='DEBITOS_PLANIFICADOS'),'MensajeNoPlanificado','Se generaran los archivos de los bancos a partir de este momento y los mismos serán notificados vi&#769;a correo electro&#769;nico. Desea continuar?','Mensaje',null,null,'Activo','icromero',sysdate,'127.0.0.1',null,null,null,null,'10',null,null,null);
Insert into db_general.admi_parametro_det (ID_PARAMETRO_DET,PARAMETRO_ID,DESCRIPCION,VALOR1,VALOR2,VALOR3,VALOR4,ESTADO,USR_CREACION,FE_CREACION,IP_CREACION,USR_ULT_MOD,FE_ULT_MOD,IP_ULT_MOD,VALOR5,EMPRESA_COD,VALOR6,VALOR7,OBSERVACION) 
values (db_general.seq_admi_parametro_det.nextval,(select ID_PARAMETRO from db_general.admi_parametro_Cab where nombre_parametro='DEBITOS_PLANIFICADOS'),'MensajeFechaVacia','Debe seleccionar una fecha para la Generacio&#769;n Planificada','Mensaje',null,null,'Activo','icromero',sysdate,'127.0.0.1',null,null,null,null,'10',null,null,null);
Insert into db_general.admi_parametro_det (ID_PARAMETRO_DET,PARAMETRO_ID,DESCRIPCION,VALOR1,VALOR2,VALOR3,VALOR4,ESTADO,USR_CREACION,FE_CREACION,IP_CREACION,USR_ULT_MOD,FE_ULT_MOD,IP_ULT_MOD,VALOR5,EMPRESA_COD,VALOR6,VALOR7,OBSERVACION) 
values (db_general.seq_admi_parametro_det.nextval,(select ID_PARAMETRO from db_general.admi_parametro_Cab where nombre_parametro='DEBITOS_PLANIFICADOS'),'MensajeFechaMenor','Debe seleccionar una fecha mayor a la actual para la Generacio&#769;n Planificada','Mensaje',null,null,'Activo','icromero',sysdate,'127.0.0.1',null,null,null,null,'10',null,null,null);
--Parametros TN
Insert into db_general.admi_parametro_det (ID_PARAMETRO_DET,PARAMETRO_ID,DESCRIPCION,VALOR1,VALOR2,VALOR3,VALOR4,ESTADO,USR_CREACION,FE_CREACION,IP_CREACION,USR_ULT_MOD,FE_ULT_MOD,IP_ULT_MOD,VALOR5,EMPRESA_COD,VALOR6,VALOR7,OBSERVACION) 
values (db_general.seq_admi_parametro_det.nextval,(select ID_PARAMETRO from db_general.admi_parametro_Cab where nombre_parametro='DEBITOS_PLANIFICADOS'),'RutaJarScriptGeneracion','/home/scripts-telcos/md/financiero/sources/generacion-archivos-debitos/dist/generacionArchivosDebitos.jar','Parametro',null,null,'Activo','icromero',sysdate,'127.0.0.1',null,null,null,null,'10',null,null,null);
Insert into db_general.admi_parametro_det (ID_PARAMETRO_DET,PARAMETRO_ID,DESCRIPCION,VALOR1,VALOR2,VALOR3,VALOR4,ESTADO,USR_CREACION,FE_CREACION,IP_CREACION,USR_ULT_MOD,FE_ULT_MOD,IP_ULT_MOD,VALOR5,EMPRESA_COD,VALOR6,VALOR7,OBSERVACION) 
values (db_general.seq_admi_parametro_det.nextval,(select ID_PARAMETRO from db_general.admi_parametro_Cab where nombre_parametro='DEBITOS_PLANIFICADOS'),'FlujoDebitoPlanificado','NO','Parametro',null,null,'Activo','icromero',sysdate,'127.0.0.1',null,null,null,null,'10',null,null,null);
Insert into db_general.admi_parametro_det (ID_PARAMETRO_DET,PARAMETRO_ID,DESCRIPCION,VALOR1,VALOR2,VALOR3,VALOR4,ESTADO,USR_CREACION,FE_CREACION,IP_CREACION,USR_ULT_MOD,FE_ULT_MOD,IP_ULT_MOD,VALOR5,EMPRESA_COD,VALOR6,VALOR7,OBSERVACION) 
values (db_general.seq_admi_parametro_det.nextval,(select ID_PARAMETRO from db_general.admi_parametro_Cab where nombre_parametro='DEBITOS_PLANIFICADOS'),'UsuarioFacturaRecurrente','telcos','Parametro',null,null,'Activo','icromero',sysdate,'127.0.0.1',null,null,null,null,'10',null,null,null);
Insert into db_general.admi_parametro_det (ID_PARAMETRO_DET,PARAMETRO_ID,DESCRIPCION,VALOR1,VALOR2,VALOR3,VALOR4,ESTADO,USR_CREACION,FE_CREACION,IP_CREACION,USR_ULT_MOD,FE_ULT_MOD,IP_ULT_MOD,VALOR5,EMPRESA_COD,VALOR6,VALOR7,OBSERVACION) 
values (db_general.seq_admi_parametro_det.nextval,(select ID_PARAMETRO from db_general.admi_parametro_Cab where nombre_parametro='DEBITOS_PLANIFICADOS'),'UsuarioFacturaNoRecurrente','telcos_proporcional|telcos_reactivacion|telcos_cambioPrecio','Parametro',null,null,'Activo','icromero',sysdate,'127.0.0.1',null,null,null,null,'10',null,null,null);
Insert into db_general.admi_parametro_det (ID_PARAMETRO_DET,PARAMETRO_ID,DESCRIPCION,VALOR1,VALOR2,VALOR3,VALOR4,ESTADO,USR_CREACION,FE_CREACION,IP_CREACION,USR_ULT_MOD,FE_ULT_MOD,IP_ULT_MOD,VALOR5,EMPRESA_COD,VALOR6,VALOR7,OBSERVACION) 
values (db_general.seq_admi_parametro_det.nextval,(select ID_PARAMETRO from db_general.admi_parametro_Cab where nombre_parametro='DEBITOS_PLANIFICADOS'),'FacturaEsRecurrente','S','Parametro',null,null,'Activo','icromero',sysdate,'127.0.0.1',null,null,null,null,'10',null,null,null);
Insert into db_general.admi_parametro_det (ID_PARAMETRO_DET,PARAMETRO_ID,DESCRIPCION,VALOR1,VALOR2,VALOR3,VALOR4,ESTADO,USR_CREACION,FE_CREACION,IP_CREACION,USR_ULT_MOD,FE_ULT_MOD,IP_ULT_MOD,VALOR5,EMPRESA_COD,VALOR6,VALOR7,OBSERVACION) 
values (db_general.seq_admi_parametro_det.nextval,(select ID_PARAMETRO from db_general.admi_parametro_Cab where nombre_parametro='DEBITOS_PLANIFICADOS'),'TipoDocumentoRecurrente','1','Parametro',null,null,'Activo','icromero',sysdate,'127.0.0.1',null,null,null,null,'10',null,null,null);
Insert into db_general.admi_parametro_det (ID_PARAMETRO_DET,PARAMETRO_ID,DESCRIPCION,VALOR1,VALOR2,VALOR3,VALOR4,ESTADO,USR_CREACION,FE_CREACION,IP_CREACION,USR_ULT_MOD,FE_ULT_MOD,IP_ULT_MOD,VALOR5,EMPRESA_COD,VALOR6,VALOR7,OBSERVACION) 
values (db_general.seq_admi_parametro_det.nextval,(select ID_PARAMETRO from db_general.admi_parametro_Cab where nombre_parametro='DEBITOS_PLANIFICADOS'),'TipoDocumentoNoRecurrente','5','Parametro',null,null,'Activo','icromero',sysdate,'127.0.0.1',null,null,null,null,'10',null,null,null);
Insert into db_general.admi_parametro_det (ID_PARAMETRO_DET,PARAMETRO_ID,DESCRIPCION,VALOR1,VALOR2,VALOR3,VALOR4,ESTADO,USR_CREACION,FE_CREACION,IP_CREACION,USR_ULT_MOD,FE_ULT_MOD,IP_ULT_MOD,VALOR5,EMPRESA_COD,VALOR6,VALOR7,OBSERVACION) 
values (db_general.seq_admi_parametro_det.nextval,(select ID_PARAMETRO from db_general.admi_parametro_Cab where nombre_parametro='DEBITOS_PLANIFICADOS'),'FacturaEsAutomatica','S','Parametro',null,null,'Activo','icromero',sysdate,'127.0.0.1',null,null,null,null,'10',null,null,null);
Insert into db_general.admi_parametro_det (ID_PARAMETRO_DET,PARAMETRO_ID,DESCRIPCION,VALOR1,VALOR2,VALOR3,VALOR4,ESTADO,USR_CREACION,FE_CREACION,IP_CREACION,USR_ULT_MOD,FE_ULT_MOD,IP_ULT_MOD,VALOR5,EMPRESA_COD,VALOR6,VALOR7,OBSERVACION) 
values (db_general.seq_admi_parametro_det.nextval,(select ID_PARAMETRO from db_general.admi_parametro_Cab where nombre_parametro='DEBITOS_PLANIFICADOS'),'EjecutandoDebitosAutomaticos','N','Parametro',null,null,'Activo','icromero',sysdate,'127.0.0.1',null,null,null,null,'10',null,null,null);
Insert into db_general.admi_parametro_det (ID_PARAMETRO_DET,PARAMETRO_ID,DESCRIPCION,VALOR1,VALOR2,VALOR3,VALOR4,ESTADO,USR_CREACION,FE_CREACION,IP_CREACION,USR_ULT_MOD,FE_ULT_MOD,IP_ULT_MOD,VALOR5,EMPRESA_COD,VALOR6,VALOR7,OBSERVACION) 
values (db_general.seq_admi_parametro_det.nextval,(select ID_PARAMETRO from db_general.admi_parametro_Cab where nombre_parametro='DEBITOS_PLANIFICADOS'),'DelayDebitosPlanificados','25000','Parametro',null,null,'Activo','icromero',sysdate,'127.0.0.1',null,null,null,null,'10',null,null,null);
Insert into db_general.admi_parametro_det (ID_PARAMETRO_DET,PARAMETRO_ID,DESCRIPCION,VALOR1,VALOR2,VALOR3,VALOR4,ESTADO,USR_CREACION,FE_CREACION,IP_CREACION,USR_ULT_MOD,FE_ULT_MOD,IP_ULT_MOD,VALOR5,EMPRESA_COD,VALOR6,VALOR7,OBSERVACION) 
values (db_general.seq_admi_parametro_det.nextval,(select ID_PARAMETRO from db_general.admi_parametro_Cab where nombre_parametro='DEBITOS_PLANIFICADOS'),'DivideDelayxDebitos','2.5','Parametro',null,null,'Activo','icromero',sysdate,'127.0.0.1',null,null,null,null,'10',null,null,null);

-- Parametros ms nfs TN
Insert into db_general.admi_parametro_det (ID_PARAMETRO_DET,PARAMETRO_ID,DESCRIPCION,VALOR1,VALOR2,VALOR3,VALOR4,ESTADO,USR_CREACION,FE_CREACION,IP_CREACION,USR_ULT_MOD,FE_ULT_MOD,IP_ULT_MOD,VALOR5,EMPRESA_COD,VALOR6,VALOR7,OBSERVACION) 
values (db_general.seq_admi_parametro_det.nextval,(select ID_PARAMETRO from db_general.admi_parametro_Cab where nombre_parametro='DEBITOS_PLANIFICADOS'),'ms.nfs.modulo',null,'Financiero',null,null,'Activo','icromero',sysdate,'127.0.0.1',null,null,null,null,'10',null,null,null);
Insert into db_general.admi_parametro_det (ID_PARAMETRO_DET,PARAMETRO_ID,DESCRIPCION,VALOR1,VALOR2,VALOR3,VALOR4,ESTADO,USR_CREACION,FE_CREACION,IP_CREACION,USR_ULT_MOD,FE_ULT_MOD,IP_ULT_MOD,VALOR5,EMPRESA_COD,VALOR6,VALOR7,OBSERVACION) 
values (db_general.seq_admi_parametro_det.nextval,(select ID_PARAMETRO from db_general.admi_parametro_Cab where nombre_parametro='DEBITOS_PLANIFICADOS'),'ms.nfs.submodulo',null,'Debitos',null,null,'Activo','icromero',sysdate,'127.0.0.1',null,null,null,null,'10',null,null,null);
Insert into db_general.admi_parametro_det (ID_PARAMETRO_DET,PARAMETRO_ID,DESCRIPCION,VALOR1,VALOR2,VALOR3,VALOR4,ESTADO,USR_CREACION,FE_CREACION,IP_CREACION,USR_ULT_MOD,FE_ULT_MOD,IP_ULT_MOD,VALOR5,EMPRESA_COD,VALOR6,VALOR7,OBSERVACION) 
values (db_general.seq_admi_parametro_det.nextval,(select ID_PARAMETRO from db_general.admi_parametro_Cab where nombre_parametro='DEBITOS_PLANIFICADOS'),'ms.nfs.url',null,'http://172.24.14.107:1618/nfs/procesar',null,null,'Activo','icromero',sysdate,'127.0.0.1',null,null,null,null,'10',null,null,null);



--Mensajes MD
Insert into db_general.admi_parametro_det (ID_PARAMETRO_DET,PARAMETRO_ID,DESCRIPCION,VALOR1,VALOR2,VALOR3,VALOR4,ESTADO,USR_CREACION,FE_CREACION,IP_CREACION,USR_ULT_MOD,FE_ULT_MOD,IP_ULT_MOD,VALOR5,EMPRESA_COD,VALOR6,VALOR7,OBSERVACION) 
values (db_general.seq_admi_parametro_det.nextval,(select ID_PARAMETRO from db_general.admi_parametro_Cab where nombre_parametro='DEBITOS_PLANIFICADOS'),'MensajePlanificado','Se generaran los archivos de los bancos en la Fecha: %FECHA% y los mismos serán notificados vi&#769;a Correo electro&#769;nico. Desea continuar?','Mensaje',null,null,'Activo','icromero',sysdate,'127.0.0.1',null,null,null,null,'18',null,null,null);
Insert into db_general.admi_parametro_det (ID_PARAMETRO_DET,PARAMETRO_ID,DESCRIPCION,VALOR1,VALOR2,VALOR3,VALOR4,ESTADO,USR_CREACION,FE_CREACION,IP_CREACION,USR_ULT_MOD,FE_ULT_MOD,IP_ULT_MOD,VALOR5,EMPRESA_COD,VALOR6,VALOR7,OBSERVACION) 
values (db_general.seq_admi_parametro_det.nextval,(select ID_PARAMETRO from db_general.admi_parametro_Cab where nombre_parametro='DEBITOS_PLANIFICADOS'),'MensajeNoPlanificado','Se generaran los archivos de los bancos a partir de este momento y los mismos serán notificados vi&#769;a correo electro&#769;nico. Desea continuar?','Mensaje',null,null,'Activo','icromero',sysdate,'127.0.0.1',null,null,null,null,'18',null,null,null);
Insert into db_general.admi_parametro_det (ID_PARAMETRO_DET,PARAMETRO_ID,DESCRIPCION,VALOR1,VALOR2,VALOR3,VALOR4,ESTADO,USR_CREACION,FE_CREACION,IP_CREACION,USR_ULT_MOD,FE_ULT_MOD,IP_ULT_MOD,VALOR5,EMPRESA_COD,VALOR6,VALOR7,OBSERVACION) 
values (db_general.seq_admi_parametro_det.nextval,(select ID_PARAMETRO from db_general.admi_parametro_Cab where nombre_parametro='DEBITOS_PLANIFICADOS'),'MensajeFechaVacia','Debe seleccionar una fecha para la Generacio&#769;n Planificada','Mensaje',null,null,'Activo','icromero',sysdate,'127.0.0.1',null,null,null,null,'18',null,null,null);
Insert into db_general.admi_parametro_det (ID_PARAMETRO_DET,PARAMETRO_ID,DESCRIPCION,VALOR1,VALOR2,VALOR3,VALOR4,ESTADO,USR_CREACION,FE_CREACION,IP_CREACION,USR_ULT_MOD,FE_ULT_MOD,IP_ULT_MOD,VALOR5,EMPRESA_COD,VALOR6,VALOR7,OBSERVACION) 
values (db_general.seq_admi_parametro_det.nextval,(select ID_PARAMETRO from db_general.admi_parametro_Cab where nombre_parametro='DEBITOS_PLANIFICADOS'),'MensajeFechaMenor','Debe seleccionar una fecha mayor a la actual para la Generacio&#769;n Planificada','Mensaje',null,null,'Activo','icromero',sysdate,'127.0.0.1',null,null,null,null,'18',null,null,null);
--Parametros MD
Insert into db_general.admi_parametro_det (ID_PARAMETRO_DET,PARAMETRO_ID,DESCRIPCION,VALOR1,VALOR2,VALOR3,VALOR4,ESTADO,USR_CREACION,FE_CREACION,IP_CREACION,USR_ULT_MOD,FE_ULT_MOD,IP_ULT_MOD,VALOR5,EMPRESA_COD,VALOR6,VALOR7,OBSERVACION) 
values (db_general.seq_admi_parametro_det.nextval,(select ID_PARAMETRO from db_general.admi_parametro_Cab where nombre_parametro='DEBITOS_PLANIFICADOS'),'RutaJarScriptGeneracion','/home/scripts-telcos/md/financiero/sources/generacion-archivos-debitos/dist/generacionArchivosDebitos.jar','Parametro',null,null,'Activo','icromero',sysdate,'127.0.0.1',null,null,null,null,'18',null,null,null);
Insert into db_general.admi_parametro_det (ID_PARAMETRO_DET,PARAMETRO_ID,DESCRIPCION,VALOR1,VALOR2,VALOR3,VALOR4,ESTADO,USR_CREACION,FE_CREACION,IP_CREACION,USR_ULT_MOD,FE_ULT_MOD,IP_ULT_MOD,VALOR5,EMPRESA_COD,VALOR6,VALOR7,OBSERVACION) 
values (db_general.seq_admi_parametro_det.nextval,(select ID_PARAMETRO from db_general.admi_parametro_Cab where nombre_parametro='DEBITOS_PLANIFICADOS'),'FlujoDebitoPlanificado','SI','Parametro',null,null,'Activo','icromero',sysdate,'127.0.0.1',null,null,null,null,'18',null,null,null);
Insert into db_general.admi_parametro_det (ID_PARAMETRO_DET,PARAMETRO_ID,DESCRIPCION,VALOR1,VALOR2,VALOR3,VALOR4,ESTADO,USR_CREACION,FE_CREACION,IP_CREACION,USR_ULT_MOD,FE_ULT_MOD,IP_ULT_MOD,VALOR5,EMPRESA_COD,VALOR6,VALOR7,OBSERVACION) 
values (db_general.seq_admi_parametro_det.nextval,(select ID_PARAMETRO from db_general.admi_parametro_Cab where nombre_parametro='DEBITOS_PLANIFICADOS'),'UsuarioFacturaRecurrente','telcos','Parametro',null,null,'Activo','icromero',sysdate,'127.0.0.1',null,null,null,null,'18',null,null,null);
Insert into db_general.admi_parametro_det (ID_PARAMETRO_DET,PARAMETRO_ID,DESCRIPCION,VALOR1,VALOR2,VALOR3,VALOR4,ESTADO,USR_CREACION,FE_CREACION,IP_CREACION,USR_ULT_MOD,FE_ULT_MOD,IP_ULT_MOD,VALOR5,EMPRESA_COD,VALOR6,VALOR7,OBSERVACION) 
values (db_general.seq_admi_parametro_det.nextval,(select ID_PARAMETRO from db_general.admi_parametro_Cab where nombre_parametro='DEBITOS_PLANIFICADOS'),'UsuarioFacturaNoRecurrente','telcos_proporcional|telcos_reactivacion|telcos_cambioPrecio','Parametro',null,null,'Activo','icromero',sysdate,'127.0.0.1',null,null,null,null,'18',null,null,null);
Insert into db_general.admi_parametro_det (ID_PARAMETRO_DET,PARAMETRO_ID,DESCRIPCION,VALOR1,VALOR2,VALOR3,VALOR4,ESTADO,USR_CREACION,FE_CREACION,IP_CREACION,USR_ULT_MOD,FE_ULT_MOD,IP_ULT_MOD,VALOR5,EMPRESA_COD,VALOR6,VALOR7,OBSERVACION) 
values (db_general.seq_admi_parametro_det.nextval,(select ID_PARAMETRO from db_general.admi_parametro_Cab where nombre_parametro='DEBITOS_PLANIFICADOS'),'FacturaEsRecurrente','S','Parametro',null,null,'Activo','icromero',sysdate,'127.0.0.1',null,null,null,null,'18',null,null,null);
Insert into db_general.admi_parametro_det (ID_PARAMETRO_DET,PARAMETRO_ID,DESCRIPCION,VALOR1,VALOR2,VALOR3,VALOR4,ESTADO,USR_CREACION,FE_CREACION,IP_CREACION,USR_ULT_MOD,FE_ULT_MOD,IP_ULT_MOD,VALOR5,EMPRESA_COD,VALOR6,VALOR7,OBSERVACION) 
values (db_general.seq_admi_parametro_det.nextval,(select ID_PARAMETRO from db_general.admi_parametro_Cab where nombre_parametro='DEBITOS_PLANIFICADOS'),'TipoDocumentoRecurrente','1','Parametro',null,null,'Activo','icromero',sysdate,'127.0.0.1',null,null,null,null,'18',null,null,null);
Insert into db_general.admi_parametro_det (ID_PARAMETRO_DET,PARAMETRO_ID,DESCRIPCION,VALOR1,VALOR2,VALOR3,VALOR4,ESTADO,USR_CREACION,FE_CREACION,IP_CREACION,USR_ULT_MOD,FE_ULT_MOD,IP_ULT_MOD,VALOR5,EMPRESA_COD,VALOR6,VALOR7,OBSERVACION) 
values (db_general.seq_admi_parametro_det.nextval,(select ID_PARAMETRO from db_general.admi_parametro_Cab where nombre_parametro='DEBITOS_PLANIFICADOS'),'TipoDocumentoNoRecurrente','5','Parametro',null,null,'Activo','icromero',sysdate,'127.0.0.1',null,null,null,null,'18',null,null,null);
Insert into db_general.admi_parametro_det (ID_PARAMETRO_DET,PARAMETRO_ID,DESCRIPCION,VALOR1,VALOR2,VALOR3,VALOR4,ESTADO,USR_CREACION,FE_CREACION,IP_CREACION,USR_ULT_MOD,FE_ULT_MOD,IP_ULT_MOD,VALOR5,EMPRESA_COD,VALOR6,VALOR7,OBSERVACION) 
values (db_general.seq_admi_parametro_det.nextval,(select ID_PARAMETRO from db_general.admi_parametro_Cab where nombre_parametro='DEBITOS_PLANIFICADOS'),'FacturaEsAutomatica','S','Parametro',null,null,'Activo','icromero',sysdate,'127.0.0.1',null,null,null,null,'18',null,null,null);
Insert into db_general.admi_parametro_det (ID_PARAMETRO_DET,PARAMETRO_ID,DESCRIPCION,VALOR1,VALOR2,VALOR3,VALOR4,ESTADO,USR_CREACION,FE_CREACION,IP_CREACION,USR_ULT_MOD,FE_ULT_MOD,IP_ULT_MOD,VALOR5,EMPRESA_COD,VALOR6,VALOR7,OBSERVACION) 
values (db_general.seq_admi_parametro_det.nextval,(select ID_PARAMETRO from db_general.admi_parametro_Cab where nombre_parametro='DEBITOS_PLANIFICADOS'),'EjecutandoDebitosAutomaticos','N','Parametro',null,null,'Activo','icromero',sysdate,'127.0.0.1',null,null,null,null,'18',null,null,null);
Insert into db_general.admi_parametro_det (ID_PARAMETRO_DET,PARAMETRO_ID,DESCRIPCION,VALOR1,VALOR2,VALOR3,VALOR4,ESTADO,USR_CREACION,FE_CREACION,IP_CREACION,USR_ULT_MOD,FE_ULT_MOD,IP_ULT_MOD,VALOR5,EMPRESA_COD,VALOR6,VALOR7,OBSERVACION) 
values (db_general.seq_admi_parametro_det.nextval,(select ID_PARAMETRO from db_general.admi_parametro_Cab where nombre_parametro='DEBITOS_PLANIFICADOS'),'DelayDebitosPlanificados','25000','Parametro',null,null,'Activo','icromero',sysdate,'127.0.0.1',null,null,null,null,'18',null,null,null);
Insert into db_general.admi_parametro_det (ID_PARAMETRO_DET,PARAMETRO_ID,DESCRIPCION,VALOR1,VALOR2,VALOR3,VALOR4,ESTADO,USR_CREACION,FE_CREACION,IP_CREACION,USR_ULT_MOD,FE_ULT_MOD,IP_ULT_MOD,VALOR5,EMPRESA_COD,VALOR6,VALOR7,OBSERVACION) 
values (db_general.seq_admi_parametro_det.nextval,(select ID_PARAMETRO from db_general.admi_parametro_Cab where nombre_parametro='DEBITOS_PLANIFICADOS'),'DivideDelayxDebitos','2.5','Parametro',null,null,'Activo','icromero',sysdate,'127.0.0.1',null,null,null,null,'18',null,null,null);

-- Parametros ms nfs MD
Insert into db_general.admi_parametro_det (ID_PARAMETRO_DET,PARAMETRO_ID,DESCRIPCION,VALOR1,VALOR2,VALOR3,VALOR4,ESTADO,USR_CREACION,FE_CREACION,IP_CREACION,USR_ULT_MOD,FE_ULT_MOD,IP_ULT_MOD,VALOR5,EMPRESA_COD,VALOR6,VALOR7,OBSERVACION) 
values (db_general.seq_admi_parametro_det.nextval,(select ID_PARAMETRO from db_general.admi_parametro_Cab where nombre_parametro='DEBITOS_PLANIFICADOS'),'ms.nfs.modulo',null,'Financiero',null,null,'Activo','icromero',sysdate,'127.0.0.1',null,null,null,null,'18',null,null,null);
Insert into db_general.admi_parametro_det (ID_PARAMETRO_DET,PARAMETRO_ID,DESCRIPCION,VALOR1,VALOR2,VALOR3,VALOR4,ESTADO,USR_CREACION,FE_CREACION,IP_CREACION,USR_ULT_MOD,FE_ULT_MOD,IP_ULT_MOD,VALOR5,EMPRESA_COD,VALOR6,VALOR7,OBSERVACION) 
values (db_general.seq_admi_parametro_det.nextval,(select ID_PARAMETRO from db_general.admi_parametro_Cab where nombre_parametro='DEBITOS_PLANIFICADOS'),'ms.nfs.submodulo',null,'Debitos',null,null,'Activo','icromero',sysdate,'127.0.0.1',null,null,null,null,'18',null,null,null);
Insert into db_general.admi_parametro_det (ID_PARAMETRO_DET,PARAMETRO_ID,DESCRIPCION,VALOR1,VALOR2,VALOR3,VALOR4,ESTADO,USR_CREACION,FE_CREACION,IP_CREACION,USR_ULT_MOD,FE_ULT_MOD,IP_ULT_MOD,VALOR5,EMPRESA_COD,VALOR6,VALOR7,OBSERVACION) 
values (db_general.seq_admi_parametro_det.nextval,(select ID_PARAMETRO from db_general.admi_parametro_Cab where nombre_parametro='DEBITOS_PLANIFICADOS'),'ms.nfs.url',null,'http://172.24.14.107:1618/nfs/procesar',null,null,'Activo','icromero',sysdate,'127.0.0.1',null,null,null,null,'18',null,null,null);


  COMMIT;

