# RESTful Web Services: anidados en /rs/soporte
rs_soporte_webServices:
    resource: restfulws/soporte.yml
    defaults: { _format: json }
    requirements: { _method: post, _format: json }
    prefix: /ws/rest
