--SE INSERTAN LOS ID_TAREA QUE REQUIEREN EQUIPOS
SET serveroutput ON

BEGIN
  FOR SOMEONE IN 
  (
    SELECT COLUMN_VALUE AS ID_TAREA FROM TABLE
    (
      SYS.ODCIVARCHAR2LIST
      (
        6519,
        2619,
		2627,
		2671,
		6525,
		2602,
		2076
      )
    )
  )
  LOOP
    INSERT INTO DB_SOPORTE.INFO_TAREA_CARACTERISTICA
    (
      ID_TAREA_CARACTERISTICA,
      TAREA_ID,
      DETALLE_ID,
      CARACTERISTICA_ID,
      VALOR,
      FE_CREACION,
      USR_CREACION,
      IP_CREACION,
      FE_MODIFICACION,
      USR_MODIFICACION,
      IP_MODIFICACION,
      ESTADO
    ) 
    VALUES 
    (
      DB_SOPORTE.SEQ_INFO_TAREA_CARACTERISTICA.NEXTVAL,
      SOMEONE.ID_TAREA,
      null,
      (SELECT ID_CARACTERISTICA FROM DB_COMERCIAL.ADMI_CARACTERISTICA WHERE DESCRIPCION_CARACTERISTICA = 'REQUIERE_EQUIPO'),
      'S',
      SYSDATE,
      'rmoranc',
      '127.0.0.1',
      null,
      null,
      null,
      'Activo'
    );
    DBMS_OUTPUT.PUT_LINE('INSERT EXITOSO REQUIERE_EQUIPO ' || SOMEONE.ID_TAREA);
  END LOOP;

END;
/

--ACTUALIZANDO FIN DE TAREA PARA QUE NO REQUIERE REGISTRO DE MATERIAL 
UPDATE 
DB_SOPORTE.INFO_TAREA_CARACTERISTICA 
SET VALOR = 'N'
WHERE 
TAREA_ID = 6519
AND CARACTERISTICA_ID = 
(SELECT ID_CARACTERISTICA 
FROM
DB_COMERCIAL.ADMI_CARACTERISTICA 
WHERE 
DESCRIPCION_CARACTERISTICA = 'REQUIERE_MATERIAL');

COMMIT;

/
