--Insert de la característica EXPORTAR_REPORTE_CASOS.
INSERT INTO DB_COMERCIAL.ADMI_CARACTERISTICA (
    ID_CARACTERISTICA,
    DESCRIPCION_CARACTERISTICA,
    TIPO_INGRESO,
    ESTADO,
    FE_CREACION,
    USR_CREACION,
    TIPO
) VALUES (
     DB_COMERCIAL.SEQ_ADMI_CARACTERISTICA.NEXTVAL,
    'EXPORTAR_REPORTE_CASOS',
    'T',
    'Activo',
     SYSDATE,
    'gvalenzuela',
    'SOPORTE'
);
COMMIT;
/
