UPDATE DB_SOPORTE.INFO_PROGRESO_PORCENTAJE IPP SET IPP.PORCENTAJE = 20 
WHERE IPP.ID_PROGRESO_PORCENTAJE = 49;
UPDATE DB_SOPORTE.INFO_PROGRESO_PORCENTAJE IPP SET IPP.PORCENTAJE = 30
WHERE IPP.ID_PROGRESO_PORCENTAJE = 55;

COMMIT;