--Eliminación del parámetro para el cierre de la tarea
DELETE FROM DB_GENERAL.ADMI_PARAMETRO_DET WHERE DESCRIPCION = 'PARAMETROS_CIERRE_TAREA';
DELETE FROM DB_GENERAL.ADMI_PARAMETRO_DET WHERE DESCRIPCION = 'URL ECUCERT 2';
DELETE FROM DB_GENERAL.ADMI_PARAMETRO_DET WHERE DESCRIPCION = 'PARAMETROS PARA CREAR TAREA MEGADATOS';
DELETE FROM DB_GENERAL.ADMI_PARAMETRO_DET WHERE DESCRIPCION = 'CORREOS ALIAS ECUCERT';
DELETE FROM DB_COMERCIAL.INFO_PERSONA_EMPRESA_ROL WHERE PERSONA_ID = 187;
DELETE FROM DB_GENERAL.ADMI_PARAMETRO_DET WHERE DESCRIPCION='CODIGO DE PLANTILLA ECUCERT' AND EMPRESA_COD=18;

COMMIT;
/