--SE CREA NUEVO PROGRESO PARA LA CONFIRMACION DE LA IP DEL SERVICIO 
INSERT INTO
"DB_SOPORTE"."ADMI_TIPO_PROGRESO"
(
ID_TIPO_PROGRESO,
CODIGO,
NOMBRE_TIPO_PROGRESO,
DESCRIPCION,
ESTADO,
USR_CREACION,
FE_CREACION,
IP_CREACION,
USR_ULT_MOD,
FE_ULT_MOD
)
VALUES 
(
DB_SOPORTE.SEQ_ADMI_TIPO_PROGRESO.NEXTVAL, 
'CONFIRMA_IP_SERVICIO', 
'Confirmacion de la ip del servicio', 
null,
'Activo', 
'admin', 
SYSDATE, 
'127.0.0.1',
null,
null
);

--INGRESANDO NUEVO PROGRESO PARA TAREAS DE CASO_ACTA TN 
INSERT INTO "DB_SOPORTE"."INFO_PROGRESO_PORCENTAJE" 
(
ID_PROGRESO_PORCENTAJE, 
PORCENTAJE, 
TIPO_PROGRESO_ID, 
TAREA_ID, 
ESTADO, 
USR_CREACION, 
FE_CREACION, 
IP_CREACION,
USR_ULT_MOD, 
FE_ULT_MOD, 
ORDEN, 
EMPRESA_ID
)
VALUES 
(
DB_SOPORTE.SEQ_INFO_PROGRESO_PORCENTAJE.NEXTVAL, 
'10', 
(select ID_TIPO_PROGRESO from DB_SOPORTE.ADMI_TIPO_PROGRESO where CODIGO = 'CONFIRMA_IP_SERVICIO'),
'0', 
'Activo', 
'admin', 
SYSDATE, 
'127.0.0.1',
NULL,
SYSDATE, 
'10', 
'10'
);


--SE ACTUALIZA PROGRESO PARA QUE LA SUMA DE 100 EMPRESA TN TAREA 0 CASO_ACTA
UPDATE "DB_SOPORTE"."INFO_PROGRESO_PORCENTAJE" 
SET 
PORCENTAJE = '30' 
WHERE 
EMPRESA_ID = 10
AND TAREA_ID = 0
AND TIPO_PROGRESO_ID = 9;



--IDs de progresos de CONFIRMA_IP_SERVICIO para tareas de soporte TN
Insert into DB_GENERAL.ADMI_PARAMETRO_DET
values         
(
                DB_GENERAL.SEQ_ADMI_PARAMETRO_DET.NEXTVAL,
                (SELECT ID_PARAMETRO FROM DB_GENERAL.ADMI_PARAMETRO_CAB WHERE NOMBRE_PARAMETRO='IDS_PROGRESOS_TAREAS'),
                'IDs de progreso de Confirmacion de ip para tareas de soporte TN',
                'PROG_SOPORTE_TN_CONFIRMAIP',
				'89',
				NULL,
				NULL,
				'Activo',
				'rmoranc',
				SYSDATE,
				'127.0.0.1',
				NULL,
				NULL,
				NULL,
				NULL,
				NULL,
				NULL,
				NULL,
				NULL
);



--CABECERA DE UMBRALES PARA FIBRA EN TAREA DE SOPORTE TN
INSERT
	INTO
	DB_GENERAL.ADMI_PARAMETRO_CAB (
		ID_PARAMETRO, 
		NOMBRE_PARAMETRO, 
		DESCRIPCION,
		MODULO, 
		PROCESO, 
		ESTADO, 
		USR_CREACION, 
		FE_CREACION, 
		IP_CREACION, 
		USR_ULT_MOD, 
		FE_ULT_MOD, 
		IP_ULT_MOD)
VALUES(
	DB_GENERAL.SEQ_ADMI_PARAMETRO_CAB.NEXTVAL , 
	'UMBRALES_VALIDACION_ENLACES_FIBRA', 
	'UMBRALES PARA VALIDAR LA  POTENCIA DE ENLACES ', 
	'TECNICO', 
	NULL, 
	'Activo', 
	'wvera', 
	SYSDATE , 
	'127.0.0.1', 
	NULL, 
	NULL, 
	NULL);

--PARAMETRIZANDO VALOR DE PORCENTAJE DE PAQUETES PARA CONFIRMACION DE ENLACE 
INSERT
	INTO
	DB_GENERAL.ADMI_PARAMETRO_DET (ID_PARAMETRO_DET,
     PARAMETRO_ID,
     DESCRIPCION,
     VALOR1,
     VALOR2,
     VALOR3,
     VALOR4,
     ESTADO,
     USR_CREACION,
     FE_CREACION,
     IP_CREACION,
     USR_ULT_MOD,
     FE_ULT_MOD,
     IP_ULT_MOD,
     VALOR5,
     EMPRESA_COD,
     VALOR6,
     VALOR7,
     OBSERVACION)
VALUES(DB_GENERAL.SEQ_ADMI_PARAMETRO_DET.NEXTVAL ,
 (
SELECT
	ID_PARAMETRO
FROM
	DB_GENERAL.ADMI_PARAMETRO_CAB
WHERE
	NOMBRE_PARAMETRO = 'UMBRALES_VALIDACION_ENLACES_FIBRA'),
     'MIN_PORCENTAJE_PAQUETES_RECIBIDO',
     '100',
     NULL,
     NULL,
     NULL,
     'Activo',
     'wvera',
     SYSDATE ,
     '172.17.0.1',
     NULL,
     NULL,
     NULL,
     NULL,
     NULL,
     NULL,
     NULL,
     NULL);

--PARAMETRIZANDO VALOR DE LATENCIA MEDIA PARA CONFIRMACION DE ENLACE
INSERT
	INTO
	DB_GENERAL.ADMI_PARAMETRO_DET (ID_PARAMETRO_DET,
     PARAMETRO_ID,
     DESCRIPCION,
     VALOR1,
     VALOR2,
     VALOR3,
     VALOR4,
     ESTADO,
     USR_CREACION,
     FE_CREACION,
     IP_CREACION,
     USR_ULT_MOD,
     FE_ULT_MOD,
     IP_ULT_MOD,
     VALOR5,
     EMPRESA_COD,
     VALOR6,
     VALOR7,
     OBSERVACION)
VALUES(DB_GENERAL.SEQ_ADMI_PARAMETRO_DET.NEXTVAL ,
 (
SELECT
	ID_PARAMETRO
FROM
	DB_GENERAL.ADMI_PARAMETRO_CAB
WHERE
	NOMBRE_PARAMETRO = 'UMBRALES_VALIDACION_ENLACES_FIBRA'),
     'MAX_LATENCIA_MEDIA',
     '15',
     NULL,
     NULL,
     NULL,
     'Activo',
     'wvera',
     SYSDATE ,
     '172.17.0.1',
     NULL,
     NULL,
     NULL,
     NULL,
     NULL,
     NULL,
     NULL,
     NULL);

	 
--PARAMETRIZANDO VALOR DE LATENCIA MÁXIMA PARA CONFIRMACIÓN DE ENLACE
INSERT
	INTO
	DB_GENERAL.ADMI_PARAMETRO_DET (ID_PARAMETRO_DET,
     PARAMETRO_ID,
     DESCRIPCION,
     VALOR1,
     VALOR2,
     VALOR3,
     VALOR4,
     ESTADO,
     USR_CREACION,
     FE_CREACION,
     IP_CREACION,
     USR_ULT_MOD,
     FE_ULT_MOD,
     IP_ULT_MOD,
     VALOR5,
     EMPRESA_COD,
     VALOR6,
     VALOR7,
     OBSERVACION)
VALUES(DB_GENERAL.SEQ_ADMI_PARAMETRO_DET.NEXTVAL ,
 (
SELECT
	ID_PARAMETRO
FROM
	DB_GENERAL.ADMI_PARAMETRO_CAB
WHERE
	NOMBRE_PARAMETRO = 'UMBRALES_VALIDACION_ENLACES_FIBRA'),
     'MAX_LATENCIA_MAXIMA',
     '12',
     NULL,
     NULL,
     NULL,
     'Activo',
     'wvera',
     SYSDATE ,
     '172.17.0.1',
     NULL,
     NULL,
     NULL,
     NULL,
     NULL,
     NULL,
     NULL,
     NULL);


--OTORGANDO PERMISO PARA MOSTRAR CONTENIDO DE TABLA DESDE ESQUEMA DB_GENERAL
GRANT SELECT ON DB_SOPORTE.INFO_PROGRESO_PORCENTAJE TO DB_GENERAL;
--OTORGANDO PERMISO PARA MOSTRAR CONTENIDO DE TABLA DESDE ESQUEMA DB_GENERAL
GRANT SELECT ON DB_SOPORTE.INFO_PROGRESO_TAREA TO DB_GENERAL;

COMMIT;






