-- Borrar valor para el nuevo proceso y tarea de CERT. Valor 3 proceso  valor 4 tarea
DELETE FROM DB_SOPORTE.ADMI_TAREA WHERE NOMBRE_TAREA='GESTION DE INCIDENTES DE SEGURIDAD DE INFRAESTRUCTURA';
DELETE FROM DB_SOPORTE.ADMI_PROCESO WHERE NOMBRE_PROCESO='TAREAS DE CERT - GESTION DE INCIDENTES DE SEGURIDAD DE INFRAESTRUCTURA';
UPDATE DB_GENERAL.ADMI_PARAMETRO_DET SET VALOR3=null, VALOR4=null WHERE DESCRIPCION = 'PARAMETROS PARA CREAR TAREA 3';
COMMIT;
 /
 