/**
 * Rollback de actualizacion de arbol de tareas para SYSCLOUD
 * @author José Bedón Sánchez <jobedon@telconet.ec>
 * @version 1.0 29-04-2021 - Versión Inicial.
 */

DELETE
FROM DB_GENERAL.ADMI_PARAMETRO_DET APD
WHERE APD.USR_CREACION = 'jobedon'
AND EXISTS
  (SELECT 1
  FROM DB_GENERAL.ADMI_PARAMETRO_CAB APC
  WHERE APC.NOMBRE_PARAMETRO= 'CATEGORIA_TAREA'
  AND APC.ID_PARAMETRO      = APD.PARAMETRO_ID
  )
AND APD.FE_CREACION >= '18-MAY-21' ;

DELETE FROM DB_SOPORTE.ADMI_PROCESO 
WHERE FE_CREACION >= '18-MAY-21'
AND USR_CREACION = 'jobedon';


DELETE FROM DB_SOPORTE.ADMI_TAREA
WHERE FE_CREACION >= '18-MAY-21'
AND USR_CREACION = 'jobedon';


UPDATE DB_SOPORTE.ADMI_PROCESO AP
SET AP.NOMBRE_PROCESO = 'GESTION DE PROBLEMAS CLOUD',
  AP.DESCRIPCION_PROCESO = 'Gestion de Problemas para servicios Cloud'
WHERE AP.NOMBRE_PROCESO IN ('TI - GESTION DE PROBLEMAS CLOUD');

UPDATE DB_SOPORTE.ADMI_PROCESO AP
SET AP.NOMBRE_PROCESO = 'EJECUCIÓN DE CAMBIOS DC (CLOUD)',
  AP.DESCRIPCION_PROCESO = 'EJECUCIÓN DE CAMBIOS DC (CLOUD)'
WHERE AP.NOMBRE_PROCESO IN ('TI - EJECUCIÓN DE CAMBIOS DC (CLOUD)');

UPDATE DB_SOPORTE.ADMI_PROCESO AP
SET AP.NOMBRE_PROCESO = 'PLANIFICACIÓN DE CAMBIOS DC (CLOUD)',
  AP.DESCRIPCION_PROCESO = 'PLANIFICACIÓN DE CAMBIOS DC (CLOUD)'
WHERE AP.NOMBRE_PROCESO IN ('TI - PLANIFICACIÓN DE CAMBIOS DC (CLOUD)');

UPDATE DB_SOPORTE.ADMI_PROCESO AP
SET AP.NOMBRE_PROCESO = 'PLANIFICACIÓN DE CAPACIDAD DC (CLOUD)',
  AP.DESCRIPCION_PROCESO = 'Planificacion de capacidad de los recursos TI'
WHERE AP.NOMBRE_PROCESO IN ('TI - PLANIFICACIÓN DE CAPACIDAD DC (CLOUD)');


-- SE ARREGLA FACTIBILIDAD
UPDATE DB_GENERAL.ADMI_PARAMETRO_DET APD
SET APD.VALOR2    = 'BOC FACTIBILIDAD'
WHERE APD.VALOR3 IN
  (SELECT ATA.ID_TAREA
  FROM DB_SOPORTE.ADMI_TAREA ATA
  WHERE ATA.NOMBRE_TAREA = 'BOC FACTIBILIDAD ESPACIO'
  )
AND EXISTS
  (SELECT 1
  FROM DB_GENERAL.ADMI_PARAMETRO_CAB APC
  WHERE APC.NOMBRE_PARAMETRO= 'CATEGORIA_TAREA'
  AND APC.ID_PARAMETRO      = APD.PARAMETRO_ID
  ) ;

-- SE ACTUALIZA PROCESO DE 2 TAREAS
UPDATE DB_GENERAL.ADMI_PARAMETRO_DET APD
SET APD.VALOR2    = 'BOC - DOCUMENTACION'
WHERE APD.VALOR3 IN
  (SELECT ATA.ID_TAREA
  FROM DB_SOPORTE.ADMI_TAREA ATA
  WHERE ATA.NOMBRE_TAREA IN ('SERVICIO DE MANOS REMOTAS - REVISION DE PANELES PARA RELLENO DE RACK', 'SERVICIO DE MANOS REMOTAS - REVISION DE RACKS/JAULAS ABIERTAS')
  )
AND EXISTS
  (SELECT 1
  FROM DB_GENERAL.ADMI_PARAMETRO_CAB APC
  WHERE APC.NOMBRE_PARAMETRO= 'CATEGORIA_TAREA'
  AND APC.ID_PARAMETRO      = APD.PARAMETRO_ID
  ) ; 


DELETE
FROM DB_GENERAL.ADMI_PARAMETRO_DET A
WHERE A.PARAMETRO_ID =
  (SELECT B.ID_PARAMETRO
  FROM DB_GENERAL.ADMI_PARAMETRO_CAB B
  WHERE B.NOMBRE_PARAMETRO = 'ACTUALIZA_TAREA_REASIGNACION'
  );
  
DELETE FROM DB_GENERAL.ADMI_PARAMETRO_CAB B
  WHERE B.NOMBRE_PARAMETRO = 'ACTUALIZA_TAREA_REASIGNACION';


COMMIT;

/