--BORRAR DETALLES DE PARAMETRO: Consultar hipotesis por arbol

DELETE FROM DB_GENERAL.ADMI_PARAMETRO_DET WHERE PARAMETRO_ID = 
(SELECT ID_PARAMETRO FROM DB_GENERAL.ADMI_PARAMETRO_CAB WHERE NOMBRE_PARAMETRO = 'EMPRESA_APLICA_PROCESO') 
AND DESCRIPCION = 'Consultar hipotesis por arbol'
AND USR_CREACION = 'amontero';

/