DELETE FROM DB_GENERAL.ADMI_PARAMETRO_DET 
WHERE PARAMETRO_ID = 
(SELECT ID_PARAMETRO FROM DB_GENERAL.ADMI_PARAMETRO_CAB WHERE NOMBRE_PARAMETRO = 'CANTONES PARA MODULO ASIGNACIONES TN')
AND USR_CREACION = 'amontero';

DELETE FROM DB_GENERAL.ADMI_PARAMETRO_CAB 
WHERE 
NOMBRE_PARAMETRO = 'CANTONES PARA MODULO ASIGNACIONES TN'
AND MODULO = 'SOPORTE'
AND USR_CREACION = 'amontero';

COMMIT;

/
