DELETE FROM DB_GENERAL.ADMI_PARAMETRO_DET WHERE DESCRIPCION = 'USAR NUEVA FUNCION EN GRID PRINCIPAL DE TAREAS. VALOR1=S =>NUEVA FUNCION VALOR1=N ANTIGUA FUNCION' AND USR_CREACION='amontero';

DELETE FROM DB_GENERAL.ADMI_PARAMETRO_CAB WHERE NOMBRE_PARAMETRO = 'VALIDACION PARA USAR NUEVA FUNCION GRID TAREAS' AND MODULO='SOPORTE' AND USR_CREACION='amontero';

COMMIT;

/
