procesomasivo_cargaDataGis:
    pattern:  /
    defaults: { _controller: "tecnicoBundle:CargaInfoGis:index" }

procesomasivo_upLoadFile:
    pattern:  /upLoadFile
    defaults: { _controller: "tecnicoBundle:CargaInfoGis:upLoadFile" }