--SE AGREGA LA COLUMNA ZONA_PRESTADA_ID EN LA TABLA INFO_CUADRILLA_PLANIF_CAB
--DEL AMBIENTE DB_SOPORTE
ALTER TABLE DB_SOPORTE.INFO_CUADRILLA_PLANIF_CAB ADD ZONA_PRESTADA_ID NUMBER;
COMMENT ON COLUMN DB_SOPORTE.INFO_CUADRILLA_PLANIF_CAB.ZONA_PRESTADA_ID	IS 'id de la zona prestada';
/
