# RESTful Web Services: anidados en /rs/seguridad/ws/rest/procesar

rs_seguridad_procesar:
  pattern:  /procesar
  defaults: { _controller: telconet\seguridadBundle\WebService\SeguridadWSController::procesarAction }