--SE OTORGA PRIVILEGIOS DE GRANT AL ESQUEMA DB_COMERCIAL PARA EL PAQUETE DB_SOPORTE.SPKG_ASIGNACION_SOLICITUD
--PARA USAR FUNCIONES NECESARIAS QUE ESTAN LIGADAS A LAS TAREAS
GRANT execute ON DB_SOPORTE.SPKG_ASIGNACION_SOLICITUD to DB_COMERCIAL;
/
