GRANT SELECT ON DB_INFRAESTRUCTURA.INFO_PROCESO_MASIVO_CAB TO DB_COMERCIAL WITH GRANT OPTION;
GRANT SELECT ON DB_GENERAL.ADMI_PARAMETRO_DET TO DB_COMERCIAL WITH GRANT OPTION;
GRANT SELECT ON DB_GENERAL.ADMI_PARAMETRO_CAB TO DB_COMERCIAL WITH GRANT OPTION;
/