/*
  SCRIPT PARA REMOVER LOS PRIVILEGIOS OTORGADOS
*/
REVOKE EXECUTE ON DB_COMERCIAL.CMKG_PROMOCIONES FROM DB_EXTERNO;
REVOKE EXECUTE ON DB_GENERAL.GNRLPCK_UTIL       FROM DB_EXTERNO;
REVOKE SELECT  ON DB_GENERAL.INFO_ERROR         FROM DB_EXTERNO,DB_SOPORTE;
REVOKE EXECUTE ON DB_SOPORTE.SPKG_REPORTES      FROM DB_COMERCIAL;
/