-- Grant otorgados por proyecto de segmenacion de VLAN reservadas para Nedetel

GRANT SELECT ON DB_COMERCIAL.INFO_PERSONA_EMPRESA_ROL_CARAC TO DB_INFRAESTRUCTURA;
GRANT SELECT ON DB_COMERCIAL.SEQ_INFO_PERSONA_EMP_ROL_CARAC TO DB_INFRAESTRUCTURA;
GRANT INSERT ON DB_COMERCIAL.INFO_PERSONA_EMPRESA_ROL_CARAC TO DB_INFRAESTRUCTURA;

/
