--=======================================================================
-- Reverso la api para generar las tareas internas
-- Reverso el tipo de solicitud RPA cancelación licencia
-- Reverso los detalles de parámetros de los id de las marcas de los elementos de los productos para la cancelación del servicio con licencias Fortigate
--=======================================================================

-- REVERSO LA API PARA LA GENERACION DE LA TAREA INTERNA
DELETE DB_TOKENSECURITY.WEB_SERVICE WHERE ID_APPLICATION = (SELECT ID_APPLICATION FROM DB_TOKENSECURITY.APPLICATION WHERE NAME = 'TELCOS_RPA');
DELETE DB_TOKENSECURITY.USER_TOKEN WHERE APPLICATION_ID = (SELECT ID_APPLICATION FROM DB_TOKENSECURITY.APPLICATION WHERE NAME = 'TELCOS_RPA');
DELETE DB_TOKENSECURITY.APPLICATION WHERE NAME = 'TELCOS_RPA';

-- REVERSO EL TIPO DE SOLICITUD DE 'SOLICITUD RPA CANCELACION LICENCIA'
DELETE DB_COMERCIAL.ADMI_TIPO_SOLICITUD
WHERE
    DESCRIPCION_SOLICITUD = 'SOLICITUD RPA CANCELACION LICENCIA';

-- REVERSO DE LA CABECERA DE PARAMETROS DE 'RPA_MARCA_ELEMENTOS_CANCELACION_LICENCIA'
DELETE DB_GENERAL.ADMI_PARAMETRO_DET
WHERE
    PARAMETRO_ID = (
        SELECT
            ID_PARAMETRO
        FROM
            DB_GENERAL.ADMI_PARAMETRO_CAB
        WHERE
            NOMBRE_PARAMETRO = 'RPA_MARCA_ELEMENTOS_CANCELACION_LICENCIA'
    );
DELETE DB_GENERAL.ADMI_PARAMETRO_CAB
WHERE
    NOMBRE_PARAMETRO = 'RPA_MARCA_ELEMENTOS_CANCELACION_LICENCIA';

COMMIT;
/
