
DELETE FROM DB_GENERAL.ADMI_PARAMETRO_DET 
WHERE PARAMETRO_ID = (SELECT ID_PARAMETRO FROM DB_GENERAL.ADMI_PARAMETRO_CAB 
                       WHERE NOMBRE_PARAMETRO='ESTADOS_PRODUCTOS_ADICIONALES_CONTRATOS_WEB');

DELETE FROM DB_GENERAL.ADMI_PARAMETRO_CAB 
WHERE NOMBRE_PARAMETRO='ESTADOS_PRODUCTOS_ADICIONALES_CONTRATOS_WEB';

commit;
/
