--CREACIÓN DE LA CARACTERÍSTICA *MONITOREO_BAJO_DEMANDA*
INSERT INTO DB_COMERCIAL.ADMI_CARACTERISTICA (
    ID_CARACTERISTICA,
    DESCRIPCION_CARACTERISTICA,
    TIPO_INGRESO,
    FE_CREACION,
    USR_CREACION,
    TIPO,
    ESTADO
) VALUES (
    DB_COMERCIAL.SEQ_ADMI_CARACTERISTICA.NEXTVAL,
   'MONITOREO_BAJO_DEMANDA',
   'T',
    SYSDATE,
   'gvalenzuela',
   'TECNICA',
   'Activo'
);

COMMIT;

/