/**
 * Se realiza asignación de lista de perfiles para acción IMPRIMIR en módulos CONTRATO y DOCUMENTOS_AGREGADOS.
 *
 * @author Brando Tomala <btomala@telconet.ec>
 * @version 1.0 08-06-2021
 */

DECLARE

CURSOR GET_ID_PERFIL IS 
SELECT SP.* FROM DB_SEGURIDAD.SIST_PERFIL SP 
WHERE UPPER(SP.NOMBRE_PERFIL) IN (
'MD_ABOGADO',
'MD_ABOGADO_COBRANZAS',
'MD_ASISTENTE_ADMINISTRACION_CONTRATOS',
'MD_ASISTENTE_ADMINISTRATIVA_GERENCIAL',
'MD_ASISTENTE_COBRANZAS_SR',
'MD_ASISTENTE_SERVICIO_CLIENTE',
'MD_COORDINADOR_COBRANZAS',
'MD_COORDINADOR_FACTURACION',
'MD_COORDINADOR_IPCC',
'MD_COORDINADOR_SERVICIO_CLIENTE',
'MD_COORDINADOR_VENTAS',
'MD_JEFE_COBRANZAS',
'MD_JEFE_VENTAS'
);

CURSOR GET_DATA(ID_PERFIL NUMBER, ID_RELACION_SIST NUMBER) IS
SELECT SA.* FROM DB_SEGURIDAD.SEGU_ASIGNACION SA 
WHERE SA.PERFIL_ID = ID_PERFIL
AND SA.RELACION_SISTEMA_ID = ID_RELACION_SIST;

CURSOR GET_ID_RELACION IS
SELECT RS.* FROM DB_SEGURIDAD.SEGU_RELACION_SISTEMA RS 
WHERE RS.MODULO_ID IN (60, 302)
AND RS.ACCION_ID =8058;

bol_existe_info boolean;
c_datos GET_DATA%rowtype;


BEGIN

  FOR i IN GET_ID_PERFIL LOOP
    FOR j IN GET_ID_RELACION LOOP
    
      OPEN GET_DATA (i.ID_PERFIL, j.ID_RELACION_SISTEMA);
      bol_existe_info:= GET_DATA%FOUND;
      CLOSE GET_DATA;
    
      IF(NOT bol_existe_info) 
      THEN
      
        INSERT INTO DB_SEGURIDAD.SEGU_ASIGNACION (PERFIL_ID, RELACION_SISTEMA_ID, USR_CREACION, FE_CREACION, IP_CREACION)
        VALUES (i.ID_PERFIL, j.ID_RELACION_SISTEMA, 'btomala', systimestamp, '127.0.0.1');
        COMMIT;
      
      END IF;
    END LOOP;  

  END LOOP;
END;