--SE INSERTA NUEVA CARACTERISTICA PARA REQUIERE_EQUIPO
--
INSERT INTO DB_COMERCIAL.ADMI_CARACTERISTICA 
(
    ID_CARACTERISTICA,
    DESCRIPCION_CARACTERISTICA,
    TIPO_INGRESO,
    ESTADO,
    FE_CREACION,
    USR_CREACION,
    FE_ULT_MOD,
    USR_ULT_MOD,
    TIPO,
	DETALLE_CARACTERISTICA
) 
VALUES 
(
    DB_COMERCIAL.SEQ_ADMI_CARACTERISTICA.NEXTVAL,
    'REQUIERE_EQUIPO',
    'C',
    'Activo',
    SYSDATE,
    'rmoranc',
    NULL,
    NULL,
    'SOPORTE',
	NULL 
);
 

COMMIT;
/