DELETE
FROM DB_GENERAL.ADMI_PARAMETRO_DET
WHERE ID_PARAMETRO_DET IN
  ( SELECT DET.ID_PARAMETRO_DET
    FROM DB_GENERAL.ADMI_PARAMETRO_CAB CAB
    INNER JOIN DB_GENERAL.ADMI_PARAMETRO_DET DET
    ON DET.PARAMETRO_ID = CAB.ID_PARAMETRO
    WHERE CAB.NOMBRE_PARAMETRO = 'PARAMETROS_ASOCIADOS_A_SERVICIOS_EN'
    AND CAB.ESTADO = 'Activo'
    AND DET.VALOR1 = 'CORTE_MASIVO'
    AND DET.VALOR2 = 'TIPOS_DE_DOCUMENTOS'
    AND DET.ESTADO = 'Activo'
  );
DELETE
FROM DB_GENERAL.ADMI_PARAMETRO_DET
WHERE ID_PARAMETRO_DET IN
  ( SELECT DET.ID_PARAMETRO_DET
    FROM DB_GENERAL.ADMI_PARAMETRO_CAB CAB
    INNER JOIN DB_GENERAL.ADMI_PARAMETRO_DET DET
    ON DET.PARAMETRO_ID = CAB.ID_PARAMETRO
    WHERE CAB.NOMBRE_PARAMETRO = 'PARAMETROS_ASOCIADOS_A_SERVICIOS_EN'
    AND CAB.ESTADO = 'Activo'
    AND DET.VALOR1 = 'CORTE_MASIVO'
    AND DET.VALOR2 = 'NUM_LOGINES_POR_LOTE'
    AND DET.ESTADO = 'Activo'
  );
DELETE
FROM DB_GENERAL.ADMI_PARAMETRO_DET
WHERE ID_PARAMETRO_DET IN
  ( SELECT DET.ID_PARAMETRO_DET
    FROM DB_GENERAL.ADMI_PARAMETRO_CAB CAB
    INNER JOIN DB_GENERAL.ADMI_PARAMETRO_DET DET
    ON DET.PARAMETRO_ID = CAB.ID_PARAMETRO
    WHERE CAB.NOMBRE_PARAMETRO = 'PARAMETROS_ASOCIADOS_A_SERVICIOS_EN'
    AND CAB.ESTADO = 'Activo'
    AND DET.VALOR1 = 'CORTE_MASIVO'
    AND DET.VALOR2 = 'IDS_FORMAS_PAGO_CUENTA_TARJETA_BANCOS'
    AND DET.ESTADO = 'Activo'
  );
DELETE
FROM DB_GENERAL.ADMI_PARAMETRO_DET
WHERE ID_PARAMETRO_DET IN
  ( SELECT DET.ID_PARAMETRO_DET
    FROM DB_GENERAL.ADMI_PARAMETRO_CAB CAB
    INNER JOIN DB_GENERAL.ADMI_PARAMETRO_DET DET
    ON DET.PARAMETRO_ID = CAB.ID_PARAMETRO
    WHERE CAB.NOMBRE_PARAMETRO = 'PARAMETROS_ASOCIADOS_A_SERVICIOS_EN'
    AND CAB.ESTADO = 'Activo'
    AND DET.VALOR1 = 'CORTE_MASIVO'
    AND DET.VALOR2 = 'BANCOS_NO_PERMITIDOS'
    AND DET.ESTADO = 'Activo'
  );
  DELETE
FROM DB_GENERAL.ADMI_PARAMETRO_DET
WHERE ID_PARAMETRO_DET IN
  ( SELECT DET.ID_PARAMETRO_DET
    FROM DB_GENERAL.ADMI_PARAMETRO_CAB CAB
    INNER JOIN DB_GENERAL.ADMI_PARAMETRO_DET DET
    ON DET.PARAMETRO_ID = CAB.ID_PARAMETRO
    WHERE CAB.NOMBRE_PARAMETRO = 'EMPRESAS_CORTE_REAC_MASIVO'
    AND CAB.ESTADO = 'Activo'
    AND DET.VALOR1 = 'CortarCliente'
    AND DET.VALOR2 = 'CortarCliente'
    AND DET.VALOR3 = 'EN'
    AND DET.ESTADO = 'Activo'
  );
  DELETE 
  FROM DB_GENERAL.ADMI_GESTION_DIRECTORIOS
  WHERE EMPRESA = 'EN'
  AND MODULO = 'Tecnico'
  AND SUBMODULO = 'CorteMasivo'
  AND USR_CREACION = 'jpiloso';
  COMMIT;
/
