/**
 * Documentación para reversar creación de parámetros
 * Eliminación en DB_GENERAL.ADMI_PARAMETRO_CAB 
 * y DB_GENERAL.ADMI_PARAMATRO_DET.
 *
 * @author Luis Farro <lfarro@telconet.ec>
 * @version 1.0 30-12-2022
 */

SET SERVEROUTPUT ON

--ELIMINAR EN ADMI_PARAMETRO_DET
DELETE FROM DB_GENERAL.ADMI_PARAMETRO_DET
WHERE PARAMETRO_ID = (SELECT ID_PARAMETRO FROM DB_GENERAL.ADMI_PARAMETRO_CAB WHERE NOMBRE_PARAMETRO = 'PE_DATACENTER');

--ELIMINAR EN ADMI_PARAMETRO_CAB
DELETE FROM DB_GENERAL.ADMI_PARAMETRO_CAB
WHERE NOMBRE_PARAMETRO = 'PE_DATACENTER';

COMMIT;
/
