
--------------------------------------
--DB_COMERCIAL
--------------------------------------
-- CREACION DE INFO EMPRESA GRUPO GUATEMALA---


INSERT INTO DB_COMERCIAL.INFO_EMPRESA_GRUPO (COD_EMPRESA,NOMBRE_EMPRESA,RAZON_SOCIAL,RUC,ESTADO,USR_CREACION,FE_CREACION,IP_CREACION,LDAP_DN,PREFIJO,FACTURA_ELECTRONICO) values ('27','TELCONET GUATEMALA','TELCONET GUATEMALA','97949000','Activo','eholguin',SYSDATE,'0.0.0.0',null,'TNG','N');

-- CREACION DE INFO_OFICINA_GRUPO GUATEMALA---

INSERT INTO DB_COMERCIAL.INFO_OFICINA_GRUPO (ID_OFICINA,EMPRESA_ID,CANTON_ID,NOMBRE_OFICINA,DIRECCION_OFICINA,TELEFONO_FIJO_OFICINA,EXTENSION_OFICINA,FAX_OFICINA,CODIGO_POSTAL_OFI,ES_MATRIZ,ES_OFICINA_FACTURACION,ESTADO,USR_CREACION,FE_CREACION,IP_CREACION,ES_VIRTUAL,TERRITORIO,CTA_CONTABLE_CLIENTES,CTA_CONTABLE_ANTICIPOS,CTA_CONTABLE_PAGOS,NO_CTA,NUM_ESTAB_SRI,CTA_CONTABLE_CARGO,REF_OFICINA_ID) values (DB_COMERCIAL.SEQ_INFO_OFICINA_GRUPO.NEXTVAL,(SELECT COD_EMPRESA FROM DB_COMERCIAL.INFO_EMPRESA_GRUPO WHERE NOMBRE_EMPRESA = 'TELCONET GUATEMALA'),(SELECT ID_CANTON FROM DB_GENERAL.ADMI_CANTON WHERE NOMBRE_CANTON = 'GUATEMALA'),'TELCONET - GUATEMALA','Via 4 1-00 Zona 4 Edificio TEC2 Of. 910','23161800','0',null,'0','S','S','Activo','eholguin',SYSDATE,'127.0.0.1','N',null,null,null,null,null,null,null,null);

--TIPOS DE NEGOCIO
INSERT INTO DB_COMERCIAL.ADMI_TIPO_NEGOCIO (ID_TIPO_NEGOCIO, CODIGO_TIPO_NEGOCIO, NOMBRE_TIPO_NEGOCIO, FE_CREACION, USR_CREACION, ESTADO, EMPRESA_COD) VALUES (DB_COMERCIAL.SEQ_ADMI_TIPO_NEGOCIO.NEXTVAL, 'CGTM', 'CORPORATIVO', SYSDATE, 'eholguin', 'Activo', (SELECT COD_EMPRESA FROM DB_COMERCIAL.INFO_EMPRESA_GRUPO WHERE NOMBRE_EMPRESA = 'TELCONET GUATEMALA'));

INSERT INTO DB_COMERCIAL.ADMI_TIPO_NEGOCIO (ID_TIPO_NEGOCIO, CODIGO_TIPO_NEGOCIO, NOMBRE_TIPO_NEGOCIO, FE_CREACION, USR_CREACION, ESTADO, EMPRESA_COD) VALUES (DB_COMERCIAL.SEQ_ADMI_TIPO_NEGOCIO.NEXTVAL, 'PGTM', 'PYME', SYSDATE, 'eholguin', 'Activo', (SELECT COD_EMPRESA FROM DB_COMERCIAL.INFO_EMPRESA_GRUPO WHERE NOMBRE_EMPRESA = 'TELCONET GUATEMALA'));

-- TIPO UBICACION --
INSERT INTO DB_COMERCIAL.ADMI_TIPO_UBICACION (ID_TIPO_UBICACION,CODIGO_TIPO_UBICACION,DESCRIPCION_TIPO_UBICACION,FE_CREACION,USR_CREACION,ESTADO) values (DB_COMERCIAL.SEQ_ADMI_NUMERACION.NEXTVAL,'EDIF','Edificio',SYSDATE,'eholguin','Activo');

--TIPO DE CONTRATO
INSERT INTO DB_COMERCIAL.ADMI_TIPO_CONTRATO (ID_TIPO_CONTRATO,EMPRESA_COD,DESCRIPCION_TIPO_CONTRATO,FE_CREACION,USR_CREACION,ESTADO,TIEMPO_FINALIZACION,TIEMPO_ALERTA_FINALIZACION)VALUES(DB_COMERCIAL.SEQ_ADMI_TIPO_CONTRATO.NEXTVAL,(SELECT COD_EMPRESA FROM DB_COMERCIAL.INFO_EMPRESA_GRUPO WHERE NOMBRE_EMPRESA = 'TELCONET GUATEMALA'),'CORPORATIVO',SYSDATE,'eholguin','Activo',0,0);

--NUMERACION DE CONTRATO
INSERT INTO "DB_COMERCIAL"."ADMI_NUMERACION" (ID_NUMERACION, EMPRESA_ID, OFICINA_ID, DESCRIPCION, CODIGO, NUMERACION_UNO, NUMERACION_DOS, SECUENCIA, FE_CREACION, USR_CREACION, TABLA, ESTADO, PROCESOS_AUTOMATICOS) VALUES (DB_COMERCIAL.SEQ_ADMI_NUMERACION.NEXTVAL, (SELECT COD_EMPRESA FROM DB_COMERCIAL.INFO_EMPRESA_GRUPO WHERE NOMBRE_EMPRESA = 'TELCONET GUATEMALA'), (SELECT ID_OFICINA FROM DB_COMERCIAL.INFO_OFICINA_GRUPO WHERE NOMBRE_OFICINA='TELCONET - GUATEMALA'), 'Numeracion Contrato Guatemala', 'CON', '001', '001', '1', SYSDATE, 'eholguin', 'info_contrato', 'Activo', 'N');

--NUMERACION ORDEN DE TRABAJO
INSERT INTO "DB_COMERCIAL"."ADMI_NUMERACION" (ID_NUMERACION, EMPRESA_ID, OFICINA_ID, DESCRIPCION, CODIGO, NUMERACION_UNO, NUMERACION_DOS, SECUENCIA, FE_CREACION, USR_CREACION, TABLA, ESTADO, PROCESOS_AUTOMATICOS) VALUES (DB_COMERCIAL.SEQ_ADMI_NUMERACION.NEXTVAL, (SELECT COD_EMPRESA FROM DB_COMERCIAL.INFO_EMPRESA_GRUPO WHERE NOMBRE_EMPRESA = 'TELCONET GUATEMALA'), (SELECT ID_OFICINA FROM DB_COMERCIAL.INFO_OFICINA_GRUPO WHERE NOMBRE_OFICINA='TELCONET - GUATEMALA'), 'Numeracion Contrato Guatemala', 'ORD', '001', '001', '1', SYSDATE, 'eholguin', 'info_contrato', 'Activo', 'N');

--NUMERACION GENERACION LOGIN
INSERT INTO "DB_COMERCIAL"."ADMI_NUMERACION" (ID_NUMERACION, EMPRESA_ID, OFICINA_ID, DESCRIPCION, CODIGO, NUMERACION_UNO, NUMERACION_DOS, SECUENCIA, FE_CREACION, USR_CREACION, TABLA, ESTADO, PROCESOS_AUTOMATICOS) VALUES (DB_COMERCIAL.SEQ_ADMI_NUMERACION.NEXTVAL, (SELECT COD_EMPRESA FROM DB_COMERCIAL.INFO_EMPRESA_GRUPO WHERE NOMBRE_EMPRESA = 'TELCONET GUATEMALA'), (SELECT ID_OFICINA FROM DB_COMERCIAL.INFO_OFICINA_GRUPO WHERE NOMBRE_OFICINA='TELCONET - GUATEMALA'), 'Numeracion Secuencia Login Guatemala', 'TG', '000', '000', '1', SYSDATE, 'eholguin', 'info_punto', 'Activo', 'N');

--ROL CLIENTE
INSERT INTO "DB_COMERCIAL"."INFO_EMPRESA_ROL" (ID_EMPRESA_ROL, EMPRESA_COD, ROL_ID, ESTADO, USR_CREACION, FE_CREACION, IP_CREACION) VALUES (DB_COMERCIAL.SEQ_INFO_EMPRESA_ROL.nextval, (SELECT COD_EMPRESA FROM DB_COMERCIAL.INFO_EMPRESA_GRUPO WHERE NOMBRE_EMPRESA = 'TELCONET GUATEMALA'), '1', 'Activo', 'eholguin',SYSDATE, '127.0.0.1');
--ROL PRE-CLIENTE
INSERT INTO "DB_COMERCIAL"."INFO_EMPRESA_ROL" (ID_EMPRESA_ROL, EMPRESA_COD, ROL_ID, ESTADO, USR_CREACION, FE_CREACION, IP_CREACION) VALUES (DB_COMERCIAL.SEQ_INFO_EMPRESA_ROL.nextval, (SELECT COD_EMPRESA FROM DB_COMERCIAL.INFO_EMPRESA_GRUPO WHERE NOMBRE_EMPRESA = 'TELCONET GUATEMALA'), '4', 'Activo', 'eholguin',SYSDATE, '127.0.0.1');
--ROL CONTACTO COMERCIAL
INSERT INTO "DB_COMERCIAL"."INFO_EMPRESA_ROL" (ID_EMPRESA_ROL, EMPRESA_COD, ROL_ID, ESTADO, USR_CREACION, FE_CREACION, IP_CREACION) VALUES (DB_COMERCIAL.SEQ_INFO_EMPRESA_ROL.nextval, (SELECT COD_EMPRESA FROM DB_COMERCIAL.INFO_EMPRESA_GRUPO WHERE NOMBRE_EMPRESA = 'TELCONET GUATEMALA'), '6', 'Activo', 'eholguin',SYSDATE, '127.0.0.1');
--ROL CONTACTO TECNICO
INSERT INTO "DB_COMERCIAL"."INFO_EMPRESA_ROL" (ID_EMPRESA_ROL, EMPRESA_COD, ROL_ID, ESTADO, USR_CREACION, FE_CREACION, IP_CREACION) VALUES (DB_COMERCIAL.SEQ_INFO_EMPRESA_ROL.nextval, (SELECT COD_EMPRESA FROM DB_COMERCIAL.INFO_EMPRESA_GRUPO WHERE NOMBRE_EMPRESA = 'TELCONET GUATEMALA'), '586', 'Activo', 'eholguin',SYSDATE, '127.0.0.1');
--ROL CONTACTO FACTURACION
INSERT INTO "DB_COMERCIAL"."INFO_EMPRESA_ROL" (ID_EMPRESA_ROL, EMPRESA_COD, ROL_ID, ESTADO, USR_CREACION, FE_CREACION, IP_CREACION) VALUES (DB_COMERCIAL.SEQ_INFO_EMPRESA_ROL.nextval, (SELECT COD_EMPRESA FROM DB_COMERCIAL.INFO_EMPRESA_GRUPO WHERE NOMBRE_EMPRESA = 'TELCONET GUATEMALA'), '648', 'Activo', 'eholguin',SYSDATE, '127.0.0.1');
--ROL CONTACTO COBRANZA
INSERT INTO "DB_COMERCIAL"."INFO_EMPRESA_ROL" (ID_EMPRESA_ROL, EMPRESA_COD, ROL_ID, ESTADO, USR_CREACION, FE_CREACION, IP_CREACION) VALUES (DB_COMERCIAL.SEQ_INFO_EMPRESA_ROL.nextval, (SELECT COD_EMPRESA FROM DB_COMERCIAL.INFO_EMPRESA_GRUPO WHERE NOMBRE_EMPRESA = 'TELCONET GUATEMALA'), '649', 'Activo', 'eholguin',SYSDATE, '127.0.0.1');
--SECUENCIA NUMERACION LOGINES TNG--
INSERT INTO DB_COMERCIAL.ADMI_NUMERACION (ID_NUMERACION,EMPRESA_ID,OFICINA_ID,DESCRIPCION,CODIGO,NUMERACION_UNO,NUMERACION_DOS,SECUENCIA,FE_CREACION,USR_CREACION,TABLA,ESTADO,NUMERO_AUTORIZACION,PROCESOS_AUTOMATICOS,TIPO_ID) values (DB_COMERCIAL.SEQ_ADMI_NUMERACION.nextval,(SELECT COD_EMPRESA FROM DB_COMERCIAL.INFO_EMPRESA_GRUPO WHERE NOMBRE_EMPRESA = 'TELCONET GUATEMALA'),(SELECT ID_OFICINA FROM DB_COMERCIAL.INFO_OFICINA_GRUPO WHERE NOMBRE_OFICINA = 'TELCONET - GUATEMALA'),'Numeracion Logines Telconet Guatemala','TG','000','000',1,SYSDATE,'eholguin','info_punto','Activo',null,'N',null);

-- CONFIGURACION PARA INGRESO DE PROSPECTO TNG ---

--- DB_FINANCIERO ---

INSERT INTO DB_FINANCIERO.ADMI_CICLO (ID_CICLO,NOMBRE_CICLO,FE_INICIO,FE_FIN,OBSERVACION,FE_CREACION,USR_CREACION,IP_CREACION,EMPRESA_COD,ESTADO,CODIGO) VALUES (DB_FINANCIERO.SEQ_ADMI_CICLO.nextval,'Ciclo (I) - 1 al 30',to_date('01-JAN-19','DD-MON-RR'),to_date('31-JAN-19','DD-MON-RR'),'Ciclo inicial configurado',SYSDATE,'eholguin','127.0.0.1',(SELECT COD_EMPRESA FROM DB_COMERCIAL.INFO_EMPRESA_GRUPO WHERE NOMBRE_EMPRESA = 'TELCONET GUATEMALA'),'Activo','CICLO1');

-- DB_COMERCIAL ---

ALTER TABLE DB_COMERCIAL.INFO_PERSONA 
DROP CONSTRAINT INFO_PERSONA_CHK3;

ALTER TABLE DB_COMERCIAL.INFO_PERSONA
ADD CONSTRAINT INFO_PERSONA_CHK3 CHECK 
(TIPO_IDENTIFICACION IN ('CED', 'RUC', 'PAS','NIT','DPI'))
ENABLE;


COMMIT;