DECLARE
  --
  CURSOR C_GetPersonal
  IS
    --
    SELECT
      OFICINA_ID, TBL_PERSONAL.USR_VENDEDOR
    FROM (
      SELECT
          MAX(IPER.ID_PERSONA_ROL) AS ID_PERSONA_ROL, IDS.USR_VENDEDOR
        FROM
          DB_COMERCIAL.INFO_PERSONA_EMPRESA_ROL IPER
          JOIN DB_COMERCIAL.INFO_PERSONA IPE ON IPE.ID_PERSONA = IPER.PERSONA_ID
          JOIN DB_COMERCIAL.INFO_EMPRESA_ROL IER ON IER.ID_EMPRESA_ROL = IPER.EMPRESA_ROL_ID
          JOIN DB_COMERCIAL.INFO_EMPRESA_GRUPO IEG ON IEG.COD_EMPRESA = IER.EMPRESA_COD
          JOIN DB_GENERAL.ADMI_ROL AR ON AR.ID_ROL = IER.ROL_ID
          JOIN DB_GENERAL.ADMI_TIPO_ROL ATR ON AR.TIPO_ROL_ID = ATR.ID_TIPO_ROL
          JOIN DB_COMERCIAL.INFO_DASHBOARD_SERVICIO IDS ON IDS.USR_VENDEDOR = IPE.LOGIN
        WHERE
          IEG.PREFIJO = 'TN'
          AND   ATR.DESCRIPCION_TIPO_ROL = 'Empleado'
        GROUP BY IDS.USR_VENDEDOR
        ) TBL_PERSONAL
    JOIN 
      DB_COMERCIAL.INFO_PERSONA_EMPRESA_ROL IPERS
      ON IPERS.ID_PERSONA_ROL = TBL_PERSONAL.ID_PERSONA_ROL;
  --
	Lr_GetPersonal C_GetPersonal%ROWTYPE;
	--
BEGIN
  --
  IF C_GetPersonal%ISOPEN THEN
    CLOSE C_GetPersonal;
  END IF;
  --
  OPEN C_GetPersonal;
  LOOP
    --
    FETCH C_GetPersonal INTO Lr_GetPersonal;
    --
    EXIT
    WHEN C_GetPersonal%NOTFOUND;
		--
		--
		IF Lr_GetPersonal.OFICINA_ID > 0 THEN
		  --
			UPDATE DB_COMERCIAL.INFO_DASHBOARD_SERVICIO
			SET OFICINA_VENDEDOR_ID = Lr_GetPersonal.OFICINA_ID
			WHERE USR_VENDEDOR = Lr_GetPersonal.USR_VENDEDOR;
			--
		END IF;
		--
	END LOOP;
  --
	COMMIT;
	--
END;






