DELETE DB_GENERAL.ADMI_PARAMETRO_DET
WHERE
    PARAMETRO_ID = (
        SELECT
            ID_PARAMETRO
        FROM
            DB_GENERAL.ADMI_PARAMETRO_CAB
        WHERE
            NOMBRE_PARAMETRO = 'CAMBIO_FACTURA_COMISION'
            AND MODULO = 'COMERCIAL'
    )
    AND DESCRIPCION='LISTA_USUARIO_APROBACION';

COMMIT;

/