INSERT
INTO DB_COMERCIAL.ADMI_CARACTERISTICA
  (
    ID_CARACTERISTICA,
    DESCRIPCION_CARACTERISTICA,
    TIPO_INGRESO,
    ESTADO,
    FE_CREACION,
    USR_CREACION,
    FE_ULT_MOD,
    USR_ULT_MOD,
    TIPO
  )
  VALUES
  (
    DB_COMERCIAL.SEQ_ADMI_CARACTERISTICA.NEXTVAL,
    'REQUIERE_SERIE',
    'T',
    'Activo',
    SYSDATE,
    'apenaherrera',
    NULL,
    NULL,
    'COMERCIAL'
  );

INSERT
INTO DB_COMERCIAL.ADMI_CARACTERISTICA
  (
    ID_CARACTERISTICA,
    DESCRIPCION_CARACTERISTICA,
    TIPO_INGRESO,
    ESTADO,
    FE_CREACION,
    USR_CREACION,
    FE_ULT_MOD,
    USR_ULT_MOD,
    TIPO
  )
  VALUES
  (
    DB_COMERCIAL.SEQ_ADMI_CARACTERISTICA.NEXTVAL,
    'CANTIDAD_NETHOME',
    'N',
    'Activo',
    SYSDATE,
    'apenaherrera',
    NULL,
    NULL,
    'COMERCIAL'
  );

INSERT
INTO DB_COMERCIAL.ADMI_CARACTERISTICA
  (
    ID_CARACTERISTICA,
    DESCRIPCION_CARACTERISTICA,
    TIPO_INGRESO,
    ESTADO,
    FE_CREACION,
    USR_CREACION,
    FE_ULT_MOD,
    USR_ULT_MOD,
    TIPO
  )
  VALUES
  (
    DB_COMERCIAL.SEQ_ADMI_CARACTERISTICA.NEXTVAL,
    'PRECIO_NETHOME',
    'N',
    'Activo',
    SYSDATE,
    'apenaherrera',
    NULL,
    NULL,
    'COMERCIAL'
  );

INSERT
INTO DB_COMERCIAL.ADMI_CARACTERISTICA
  (
    ID_CARACTERISTICA,
    DESCRIPCION_CARACTERISTICA,
    TIPO_INGRESO,
    ESTADO,
    FE_CREACION,
    USR_CREACION,
    FE_ULT_MOD,
    USR_ULT_MOD,
    TIPO
  )
  VALUES
  (
    DB_COMERCIAL.SEQ_ADMI_CARACTERISTICA.NEXTVAL,
    'VENDEDOR_NETHOME',
    'N',
    'Activo',
    SYSDATE,
    'apenaherrera',
    NULL,
    NULL,
    'COMERCIAL'
  );

INSERT
INTO DB_COMERCIAL.ADMI_CARACTERISTICA
  (
    ID_CARACTERISTICA,
    DESCRIPCION_CARACTERISTICA,
    TIPO_INGRESO,
    ESTADO,
    FE_CREACION,
    USR_CREACION,
    FE_ULT_MOD,
    USR_ULT_MOD,
    TIPO
  )
  VALUES
  (
    DB_COMERCIAL.SEQ_ADMI_CARACTERISTICA.NEXTVAL,
    'NETHOME',
    'T',
    'Activo',
    SYSDATE,
    'apenaherrera',
    NULL,
    NULL,
    'COMERCIAL'
  );

INSERT
INTO DB_COMERCIAL.ADMI_PRODUCTO
  (
    ID_PRODUCTO,
    EMPRESA_COD,
    CODIGO_PRODUCTO,
    DESCRIPCION_PRODUCTO,
    FUNCION_COSTO,
    FUNCION_PRECIO,
    INSTALACION,
    ESTADO,
    FE_CREACION,
    USR_CREACION,
    IP_CREACION,
    CTA_CONTABLE_PROD,
    CTA_CONTABLE_PROD_NC,
    ES_PREFERENCIA,
    ES_ENLACE,
    REQUIERE_PLANIFICACION,
    REQUIERE_INFO_TECNICA,
    NOMBRE_TECNICO,
    CTA_CONTABLE_DESC,
    TIPO,
    ES_CONCENTRADOR,
    SOPORTE_MASIVO,
    ESTADO_INICIAL,
    GRUPO,
    COMISION_VENTA,
    COMISION_MANTENIMIENTO,
    USR_GERENTE,
    CLASIFICACION,
    REQUIERE_COMISIONAR,
    SUBGRUPO,
    LINEA_NEGOCIO
  )
  VALUES
  (
   DB_COMERCIAL.SEQ_ADMI_PRODUCTO.NEXTVAL,
    '18',
    'NHOME',
    'NETHOME',
    NULL,
    'PRECIO=0',
    0,
    'Inactivo',
    SYSDATE,
    'apenaherrera',
    '127.0.0.1',
    NULL,
    NULL,
    'NO',
    'NO',
    'SI',
    'NO',
    'NETHOME',
    NULL,
    'S',
    'NO',
    NULL,
    NULL,
    'NETHOME',
    NULL,
    NULL,
    NULL,
    NULL,
    'NO',
    NULL,
    NULL
  );

INSERT
INTO DB_COMERCIAL.ADMI_PRODUCTO_CARACTERISTICA
  (
    ID_PRODUCTO_CARACTERISITICA,
    PRODUCTO_ID,
    CARACTERISTICA_ID,
    FE_CREACION,
    FE_ULT_MOD,
    USR_CREACION,
    USR_ULT_MOD,
    ESTADO,
    VISIBLE_COMERCIAL
  )
  VALUES
  (
    DB_COMERCIAL.SEQ_ADMI_PRODUCTO_CARAC.NEXTVAL,
    (
     SELECT ID_PRODUCTO
     FROM DB_COMERCIAL.ADMI_PRODUCTO 
     WHERE CODIGO_PRODUCTO='NHOME'
    ),
    (
     SELECT ID_CARACTERISTICA 
     FROM DB_COMERCIAL.ADMI_CARACTERISTICA 
     WHERE DESCRIPCION_CARACTERISTICA='FACTURACION_UNICA' 
     AND ESTADO='Activo'
    ),
    SYSDATE,
    NULL,
    'apenaherrera',
    NULL,
    'Activo',
    NULL
  );

INSERT
INTO DB_COMERCIAL.ADMI_PRODUCTO_CARACTERISTICA
  (
    ID_PRODUCTO_CARACTERISITICA,
    PRODUCTO_ID,
    CARACTERISTICA_ID,
    FE_CREACION,
    FE_ULT_MOD,
    USR_CREACION,
    USR_ULT_MOD,
    ESTADO,
    VISIBLE_COMERCIAL
  )
  VALUES
  (
    DB_COMERCIAL.SEQ_ADMI_PRODUCTO_CARAC.NEXTVAL,
    (
     SELECT ID_PRODUCTO
     FROM DB_COMERCIAL.ADMI_PRODUCTO 
     WHERE CODIGO_PRODUCTO='NHOME'
    ),
    (
     SELECT ID_CARACTERISTICA 
     FROM DB_COMERCIAL.ADMI_CARACTERISTICA 
     WHERE DESCRIPCION_CARACTERISTICA='NETHOME' 
     AND ESTADO='Activo'
    ),
    SYSDATE,
    NULL,
    'apenaherrera',
    NULL,
    'Activo',
    NULL
  );

INSERT
INTO DB_COMERCIAL.INFO_PRODUCTO_IMPUESTO
  (
    ID_PRODUCTO_IMPUESTO,
    PRODUCTO_ID,
    IMPUESTO_ID,
    PORCENTAJE_IMPUESTO,
    FE_CREACION,
    USR_CREACION,
    FE_ULT_MOD,
    USR_ULT_MOD,
    ESTADO
  )
  VALUES
  (
    DB_COMERCIAL.SEQ_INFO_PRODUCTO_IMPUESTO.NEXTVAL,
    (
     SELECT ID_PRODUCTO
     FROM DB_COMERCIAL.ADMI_PRODUCTO 
     WHERE CODIGO_PRODUCTO='NHOME'
    ),
    1,
    12,
    SYSDATE,
    'apenaherrera',
    NULL,
    NULL,
    'Activo'
  );

INSERT
INTO DB_COMERCIAL.ADMI_PRODUCTO
  (
    ID_PRODUCTO,
    EMPRESA_COD,
    CODIGO_PRODUCTO,
    DESCRIPCION_PRODUCTO,
    FUNCION_COSTO,
    FUNCION_PRECIO,
    INSTALACION,
    ESTADO,
    FE_CREACION,
    USR_CREACION,
    IP_CREACION,
    CTA_CONTABLE_PROD,
    CTA_CONTABLE_PROD_NC,
    ES_PREFERENCIA,
    ES_ENLACE,
    REQUIERE_PLANIFICACION,
    REQUIERE_INFO_TECNICA,
    NOMBRE_TECNICO,
    CTA_CONTABLE_DESC,
    TIPO,
    ES_CONCENTRADOR,
    SOPORTE_MASIVO,
    ESTADO_INICIAL,
    GRUPO,
    COMISION_VENTA,
    COMISION_MANTENIMIENTO,
    USR_GERENTE,
    CLASIFICACION,
    REQUIERE_COMISIONAR,
    SUBGRUPO,
    LINEA_NEGOCIO
  )
  VALUES
  (
   DB_COMERCIAL.SEQ_ADMI_PRODUCTO.NEXTVAL,
    '18',
    'CONTR_UI',
    'Controlador de área Ultra Inteligente. WiFi, Zwave, Zigbee',
    NULL,
    'PRECIO=159.99',
    0,
    'Activo',
    SYSDATE,
    'apenaherrera',
    '127.0.0.1',
    NULL,
    NULL,
    'NO',
    'NO',
    'SI',
    'NO',
    'NETHOME',
    NULL,
    'S',
    'NO',
    NULL,
    NULL,
    'NETHOME',
    NULL,
    NULL,
    NULL,
    NULL,
    'NO',
    NULL,
    NULL
  );

INSERT
INTO DB_COMERCIAL.ADMI_PRODUCTO_CARACTERISTICA
  (
    ID_PRODUCTO_CARACTERISITICA,
    PRODUCTO_ID,
    CARACTERISTICA_ID,
    FE_CREACION,
    FE_ULT_MOD,
    USR_CREACION,
    USR_ULT_MOD,
    ESTADO,
    VISIBLE_COMERCIAL
  )
  VALUES
  (
    DB_COMERCIAL.SEQ_ADMI_PRODUCTO_CARAC.NEXTVAL,
    (
     SELECT ID_PRODUCTO
     FROM DB_COMERCIAL.ADMI_PRODUCTO 
     WHERE CODIGO_PRODUCTO='CONTR_UI'
     AND ESTADO='Activo'
    ),
    (
     SELECT ID_CARACTERISTICA 
     FROM DB_COMERCIAL.ADMI_CARACTERISTICA 
     WHERE DESCRIPCION_CARACTERISTICA='FACTURACION_UNICA' 
     AND ESTADO='Activo'
    ),
    SYSDATE,
    NULL,
    'apenaherrera',
    NULL,
    'Activo',
    NULL
  );

INSERT
INTO DB_COMERCIAL.ADMI_PRODUCTO_CARACTERISTICA
  (
    ID_PRODUCTO_CARACTERISITICA,
    PRODUCTO_ID,
    CARACTERISTICA_ID,
    FE_CREACION,
    FE_ULT_MOD,
    USR_CREACION,
    USR_ULT_MOD,
    ESTADO,
    VISIBLE_COMERCIAL
  )
  VALUES
  (
    DB_COMERCIAL.SEQ_ADMI_PRODUCTO_CARAC.NEXTVAL,
    (
     SELECT ID_PRODUCTO
     FROM DB_COMERCIAL.ADMI_PRODUCTO 
     WHERE CODIGO_PRODUCTO='CONTR_UI'
     AND ESTADO='Activo'
    ),
    (
     SELECT ID_CARACTERISTICA 
     FROM DB_COMERCIAL.ADMI_CARACTERISTICA 
     WHERE DESCRIPCION_CARACTERISTICA='NETHOME' 
     AND ESTADO='Activo'
    ),
    SYSDATE,
    NULL,
    'apenaherrera',
    NULL,
    'Activo',
    NULL
  );

INSERT
INTO DB_COMERCIAL.ADMI_PRODUCTO_CARACTERISTICA
  (
    ID_PRODUCTO_CARACTERISITICA,
    PRODUCTO_ID,
    CARACTERISTICA_ID,
    FE_CREACION,
    FE_ULT_MOD,
    USR_CREACION,
    USR_ULT_MOD,
    ESTADO,
    VISIBLE_COMERCIAL
  )
  VALUES
  (
    DB_COMERCIAL.SEQ_ADMI_PRODUCTO_CARAC.NEXTVAL,
    (
     SELECT ID_PRODUCTO
     FROM DB_COMERCIAL.ADMI_PRODUCTO 
     WHERE CODIGO_PRODUCTO='CONTR_UI'
     AND ESTADO='Activo'
    ),
    (
     SELECT ID_CARACTERISTICA 
     FROM DB_COMERCIAL.ADMI_CARACTERISTICA 
     WHERE DESCRIPCION_CARACTERISTICA='CANTIDAD_NETHOME' 
     AND ESTADO='Activo'
    ),
    SYSDATE,
    NULL,
    'apenaherrera',
    NULL,
    'Activo',
    NULL
  );

INSERT
INTO DB_COMERCIAL.ADMI_PRODUCTO_CARACTERISTICA
  (
    ID_PRODUCTO_CARACTERISITICA,
    PRODUCTO_ID,
    CARACTERISTICA_ID,
    FE_CREACION,
    FE_ULT_MOD,
    USR_CREACION,
    USR_ULT_MOD,
    ESTADO,
    VISIBLE_COMERCIAL
  )
  VALUES
  (
    DB_COMERCIAL.SEQ_ADMI_PRODUCTO_CARAC.NEXTVAL,
    (
     SELECT ID_PRODUCTO
     FROM DB_COMERCIAL.ADMI_PRODUCTO 
     WHERE CODIGO_PRODUCTO='CONTR_UI'
     AND ESTADO='Activo'
    ),
    (
     SELECT ID_CARACTERISTICA 
     FROM DB_COMERCIAL.ADMI_CARACTERISTICA 
     WHERE DESCRIPCION_CARACTERISTICA='PRECIO_NETHOME' 
     AND ESTADO='Activo'
    ),
    SYSDATE,
    NULL,
    'apenaherrera',
    NULL,
    'Activo',
    NULL
  );

INSERT
INTO DB_COMERCIAL.ADMI_PRODUCTO_CARACTERISTICA
  (
    ID_PRODUCTO_CARACTERISITICA,
    PRODUCTO_ID,
    CARACTERISTICA_ID,
    FE_CREACION,
    FE_ULT_MOD,
    USR_CREACION,
    USR_ULT_MOD,
    ESTADO,
    VISIBLE_COMERCIAL
  )
  VALUES
  (
    DB_COMERCIAL.SEQ_ADMI_PRODUCTO_CARAC.NEXTVAL,
    (
     SELECT ID_PRODUCTO
     FROM DB_COMERCIAL.ADMI_PRODUCTO 
     WHERE CODIGO_PRODUCTO='CONTR_UI'
     AND ESTADO='Activo'
    ),
    (
     SELECT ID_CARACTERISTICA 
     FROM DB_COMERCIAL.ADMI_CARACTERISTICA 
     WHERE DESCRIPCION_CARACTERISTICA='VENDEDOR_NETHOME' 
     AND ESTADO='Activo'
    ),
    SYSDATE,
    NULL,
    'apenaherrera',
    NULL,
    'Activo',
    NULL
  );

INSERT
INTO DB_COMERCIAL.ADMI_PRODUCTO_CARACTERISTICA
  (
    ID_PRODUCTO_CARACTERISITICA,
    PRODUCTO_ID,
    CARACTERISTICA_ID,
    FE_CREACION,
    FE_ULT_MOD,
    USR_CREACION,
    USR_ULT_MOD,
    ESTADO,
    VISIBLE_COMERCIAL
  )
  VALUES
  (
    DB_COMERCIAL.SEQ_ADMI_PRODUCTO_CARAC.NEXTVAL,
    (
     SELECT ID_PRODUCTO
     FROM DB_COMERCIAL.ADMI_PRODUCTO 
     WHERE CODIGO_PRODUCTO='CONTR_UI'
     AND ESTADO='Activo'
    ),
    (
     SELECT ID_CARACTERISTICA 
     FROM DB_COMERCIAL.ADMI_CARACTERISTICA 
     WHERE DESCRIPCION_CARACTERISTICA='REQUIERE_SERIE' 
     AND ESTADO='Activo'
    ),
    SYSDATE,
    NULL,
    'apenaherrera',
    NULL,
    'Activo',
    NULL
  );

INSERT
INTO DB_COMERCIAL.INFO_PRODUCTO_IMPUESTO
  (
    ID_PRODUCTO_IMPUESTO,
    PRODUCTO_ID,
    IMPUESTO_ID,
    PORCENTAJE_IMPUESTO,
    FE_CREACION,
    USR_CREACION,
    FE_ULT_MOD,
    USR_ULT_MOD,
    ESTADO
  )
  VALUES
  (
    DB_COMERCIAL.SEQ_INFO_PRODUCTO_IMPUESTO.NEXTVAL,
    (
     SELECT ID_PRODUCTO
     FROM DB_COMERCIAL.ADMI_PRODUCTO 
     WHERE CODIGO_PRODUCTO='CONTR_UI'
     AND ESTADO='Activo'
    ),
    1,
    12,
    SYSDATE,
    'apenaherrera',
    NULL,
    NULL,
    'Activo'
  );

INSERT
INTO DB_COMERCIAL.ADMI_PRODUCTO
  (
    ID_PRODUCTO,
    EMPRESA_COD,
    CODIGO_PRODUCTO,
    DESCRIPCION_PRODUCTO,
    FUNCION_COSTO,
    FUNCION_PRECIO,
    INSTALACION,
    ESTADO,
    FE_CREACION,
    USR_CREACION,
    IP_CREACION,
    CTA_CONTABLE_PROD,
    CTA_CONTABLE_PROD_NC,
    ES_PREFERENCIA,
    ES_ENLACE,
    REQUIERE_PLANIFICACION,
    REQUIERE_INFO_TECNICA,
    NOMBRE_TECNICO,
    CTA_CONTABLE_DESC,
    TIPO,
    ES_CONCENTRADOR,
    SOPORTE_MASIVO,
    ESTADO_INICIAL,
    GRUPO,
    COMISION_VENTA,
    COMISION_MANTENIMIENTO,
    USR_GERENTE,
    CLASIFICACION,
    REQUIERE_COMISIONAR,
    SUBGRUPO,
    LINEA_NEGOCIO
  )
  VALUES
  (
   DB_COMERCIAL.SEQ_ADMI_PRODUCTO.NEXTVAL,
    '18',
    'SENS_PV',
    'Sensor de Puerta/Ventana con 2 baterias AAA',
    NULL,
    'PRECIO=39.99',
    0,
    'Activo',
    SYSDATE,
    'apenaherrera',
    '127.0.0.1',
    NULL,
    NULL,
    'NO',
    'NO',
    'SI',
    'NO',
    'NETHOME',
    NULL,
    'S',
    'NO',
    NULL,
    NULL,
    'NETHOME',
    NULL,
    NULL,
    NULL,
    NULL,
    'NO',
    NULL,
    NULL
  );

INSERT
INTO DB_COMERCIAL.ADMI_PRODUCTO_CARACTERISTICA
  (
    ID_PRODUCTO_CARACTERISITICA,
    PRODUCTO_ID,
    CARACTERISTICA_ID,
    FE_CREACION,
    FE_ULT_MOD,
    USR_CREACION,
    USR_ULT_MOD,
    ESTADO,
    VISIBLE_COMERCIAL
  )
  VALUES
  (
    DB_COMERCIAL.SEQ_ADMI_PRODUCTO_CARAC.NEXTVAL,
    (
     SELECT ID_PRODUCTO
     FROM DB_COMERCIAL.ADMI_PRODUCTO 
     WHERE CODIGO_PRODUCTO='SENS_PV'
     AND ESTADO='Activo'
    ),
    (
     SELECT ID_CARACTERISTICA 
     FROM DB_COMERCIAL.ADMI_CARACTERISTICA 
     WHERE DESCRIPCION_CARACTERISTICA='FACTURACION_UNICA' 
     AND ESTADO='Activo'
    ),
    SYSDATE,
    NULL,
    'apenaherrera',
    NULL,
    'Activo',
    NULL
  );

INSERT
INTO DB_COMERCIAL.ADMI_PRODUCTO_CARACTERISTICA
  (
    ID_PRODUCTO_CARACTERISITICA,
    PRODUCTO_ID,
    CARACTERISTICA_ID,
    FE_CREACION,
    FE_ULT_MOD,
    USR_CREACION,
    USR_ULT_MOD,
    ESTADO,
    VISIBLE_COMERCIAL
  )
  VALUES
  (
    DB_COMERCIAL.SEQ_ADMI_PRODUCTO_CARAC.NEXTVAL,
    (
     SELECT ID_PRODUCTO
     FROM DB_COMERCIAL.ADMI_PRODUCTO 
     WHERE CODIGO_PRODUCTO='SENS_PV'
     AND ESTADO='Activo'
    ),
    (
     SELECT ID_CARACTERISTICA 
     FROM DB_COMERCIAL.ADMI_CARACTERISTICA 
     WHERE DESCRIPCION_CARACTERISTICA='NETHOME' 
     AND ESTADO='Activo'
    ),
    SYSDATE,
    NULL,
    'apenaherrera',
    NULL,
    'Activo',
    NULL
  );

INSERT
INTO DB_COMERCIAL.ADMI_PRODUCTO_CARACTERISTICA
  (
    ID_PRODUCTO_CARACTERISITICA,
    PRODUCTO_ID,
    CARACTERISTICA_ID,
    FE_CREACION,
    FE_ULT_MOD,
    USR_CREACION,
    USR_ULT_MOD,
    ESTADO,
    VISIBLE_COMERCIAL
  )
  VALUES
  (
    DB_COMERCIAL.SEQ_ADMI_PRODUCTO_CARAC.NEXTVAL,
    (
     SELECT ID_PRODUCTO
     FROM DB_COMERCIAL.ADMI_PRODUCTO 
     WHERE CODIGO_PRODUCTO='SENS_PV'
     AND ESTADO='Activo'
    ),
    (
     SELECT ID_CARACTERISTICA 
     FROM DB_COMERCIAL.ADMI_CARACTERISTICA 
     WHERE DESCRIPCION_CARACTERISTICA='CANTIDAD_NETHOME' 
     AND ESTADO='Activo'
    ),
    SYSDATE,
    NULL,
    'apenaherrera',
    NULL,
    'Activo',
    NULL
  );

INSERT
INTO DB_COMERCIAL.ADMI_PRODUCTO_CARACTERISTICA
  (
    ID_PRODUCTO_CARACTERISITICA,
    PRODUCTO_ID,
    CARACTERISTICA_ID,
    FE_CREACION,
    FE_ULT_MOD,
    USR_CREACION,
    USR_ULT_MOD,
    ESTADO,
    VISIBLE_COMERCIAL
  )
  VALUES
  (
    DB_COMERCIAL.SEQ_ADMI_PRODUCTO_CARAC.NEXTVAL,
    (
     SELECT ID_PRODUCTO
     FROM DB_COMERCIAL.ADMI_PRODUCTO 
     WHERE CODIGO_PRODUCTO='SENS_PV'
     AND ESTADO='Activo'
    ),
    (
     SELECT ID_CARACTERISTICA 
     FROM DB_COMERCIAL.ADMI_CARACTERISTICA 
     WHERE DESCRIPCION_CARACTERISTICA='PRECIO_NETHOME' 
     AND ESTADO='Activo'
    ),
    SYSDATE,
    NULL,
    'apenaherrera',
    NULL,
    'Activo',
    NULL
  );

INSERT
INTO DB_COMERCIAL.ADMI_PRODUCTO_CARACTERISTICA
  (
    ID_PRODUCTO_CARACTERISITICA,
    PRODUCTO_ID,
    CARACTERISTICA_ID,
    FE_CREACION,
    FE_ULT_MOD,
    USR_CREACION,
    USR_ULT_MOD,
    ESTADO,
    VISIBLE_COMERCIAL
  )
  VALUES
  (
    DB_COMERCIAL.SEQ_ADMI_PRODUCTO_CARAC.NEXTVAL,
    (
     SELECT ID_PRODUCTO
     FROM DB_COMERCIAL.ADMI_PRODUCTO 
     WHERE CODIGO_PRODUCTO='SENS_PV'
     AND ESTADO='Activo'
    ),
    (
     SELECT ID_CARACTERISTICA 
     FROM DB_COMERCIAL.ADMI_CARACTERISTICA 
     WHERE DESCRIPCION_CARACTERISTICA='VENDEDOR_NETHOME' 
     AND ESTADO='Activo'
    ),
    SYSDATE,
    NULL,
    'apenaherrera',
    NULL,
    'Activo',
    NULL
  );

INSERT
INTO DB_COMERCIAL.ADMI_PRODUCTO_CARACTERISTICA
  (
    ID_PRODUCTO_CARACTERISITICA,
    PRODUCTO_ID,
    CARACTERISTICA_ID,
    FE_CREACION,
    FE_ULT_MOD,
    USR_CREACION,
    USR_ULT_MOD,
    ESTADO,
    VISIBLE_COMERCIAL
  )
  VALUES
  (
    DB_COMERCIAL.SEQ_ADMI_PRODUCTO_CARAC.NEXTVAL,
    (
     SELECT ID_PRODUCTO
     FROM DB_COMERCIAL.ADMI_PRODUCTO 
     WHERE CODIGO_PRODUCTO='SENS_PV'
     AND ESTADO='Activo'
    ),
    (
     SELECT ID_CARACTERISTICA 
     FROM DB_COMERCIAL.ADMI_CARACTERISTICA 
     WHERE DESCRIPCION_CARACTERISTICA='REQUIERE_SERIE' 
     AND ESTADO='Activo'
    ),
    SYSDATE,
    NULL,
    'apenaherrera',
    NULL,
    'Activo',
    NULL
  );

INSERT
INTO DB_COMERCIAL.INFO_PRODUCTO_IMPUESTO
  (
    ID_PRODUCTO_IMPUESTO,
    PRODUCTO_ID,
    IMPUESTO_ID,
    PORCENTAJE_IMPUESTO,
    FE_CREACION,
    USR_CREACION,
    FE_ULT_MOD,
    USR_ULT_MOD,
    ESTADO
  )
  VALUES
  (
    DB_COMERCIAL.SEQ_INFO_PRODUCTO_IMPUESTO.NEXTVAL,
    (
     SELECT ID_PRODUCTO
     FROM DB_COMERCIAL.ADMI_PRODUCTO 
     WHERE CODIGO_PRODUCTO='SENS_PV'
     AND ESTADO='Activo'
    ),
    1,
    12,
    SYSDATE,
    'apenaherrera',
    NULL,
    NULL,
    'Activo'
  );

INSERT
INTO DB_COMERCIAL.ADMI_PRODUCTO
  (
    ID_PRODUCTO,
    EMPRESA_COD,
    CODIGO_PRODUCTO,
    DESCRIPCION_PRODUCTO,
    FUNCION_COSTO,
    FUNCION_PRECIO,
    INSTALACION,
    ESTADO,
    FE_CREACION,
    USR_CREACION,
    IP_CREACION,
    CTA_CONTABLE_PROD,
    CTA_CONTABLE_PROD_NC,
    ES_PREFERENCIA,
    ES_ENLACE,
    REQUIERE_PLANIFICACION,
    REQUIERE_INFO_TECNICA,
    NOMBRE_TECNICO,
    CTA_CONTABLE_DESC,
    TIPO,
    ES_CONCENTRADOR,
    SOPORTE_MASIVO,
    ESTADO_INICIAL,
    GRUPO,
    COMISION_VENTA,
    COMISION_MANTENIMIENTO,
    USR_GERENTE,
    CLASIFICACION,
    REQUIERE_COMISIONAR,
    SUBGRUPO,
    LINEA_NEGOCIO
  )
  VALUES
  (
   DB_COMERCIAL.SEQ_ADMI_PRODUCTO.NEXTVAL,
    '18',
    'SENS_PVR',
    'Sensor de Puerta/Ventana con baterías recargables',
    NULL,
    'PRECIO=39.99',
    0,
    'Activo',
    SYSDATE,
    'apenaherrera',
    '127.0.0.1',
    NULL,
    NULL,
    'NO',
    'NO',
    'SI',
    'NO',
    'NETHOME',
    NULL,
    'S',
    'NO',
    NULL,
    NULL,
    'NETHOME',
    NULL,
    NULL,
    NULL,
    NULL,
    'NO',
    NULL,
    NULL
  );

INSERT
INTO DB_COMERCIAL.ADMI_PRODUCTO_CARACTERISTICA
  (
    ID_PRODUCTO_CARACTERISITICA,
    PRODUCTO_ID,
    CARACTERISTICA_ID,
    FE_CREACION,
    FE_ULT_MOD,
    USR_CREACION,
    USR_ULT_MOD,
    ESTADO,
    VISIBLE_COMERCIAL
  )
  VALUES
  (
    DB_COMERCIAL.SEQ_ADMI_PRODUCTO_CARAC.NEXTVAL,
    (
     SELECT ID_PRODUCTO
     FROM DB_COMERCIAL.ADMI_PRODUCTO 
     WHERE CODIGO_PRODUCTO='SENS_PVR'
     AND ESTADO='Activo'
    ),
    (
     SELECT ID_CARACTERISTICA 
     FROM DB_COMERCIAL.ADMI_CARACTERISTICA 
     WHERE DESCRIPCION_CARACTERISTICA='FACTURACION_UNICA' 
     AND ESTADO='Activo'
    ),
    SYSDATE,
    NULL,
    'apenaherrera',
    NULL,
    'Activo',
    NULL
  );

INSERT
INTO DB_COMERCIAL.ADMI_PRODUCTO_CARACTERISTICA
  (
    ID_PRODUCTO_CARACTERISITICA,
    PRODUCTO_ID,
    CARACTERISTICA_ID,
    FE_CREACION,
    FE_ULT_MOD,
    USR_CREACION,
    USR_ULT_MOD,
    ESTADO,
    VISIBLE_COMERCIAL
  )
  VALUES
  (
    DB_COMERCIAL.SEQ_ADMI_PRODUCTO_CARAC.NEXTVAL,
    (
     SELECT ID_PRODUCTO
     FROM DB_COMERCIAL.ADMI_PRODUCTO 
     WHERE CODIGO_PRODUCTO='SENS_PVR'
     AND ESTADO='Activo'
    ),
    (
     SELECT ID_CARACTERISTICA 
     FROM DB_COMERCIAL.ADMI_CARACTERISTICA 
     WHERE DESCRIPCION_CARACTERISTICA='NETHOME' 
     AND ESTADO='Activo'
    ),
    SYSDATE,
    NULL,
    'apenaherrera',
    NULL,
    'Activo',
    NULL
  );

INSERT
INTO DB_COMERCIAL.ADMI_PRODUCTO_CARACTERISTICA
  (
    ID_PRODUCTO_CARACTERISITICA,
    PRODUCTO_ID,
    CARACTERISTICA_ID,
    FE_CREACION,
    FE_ULT_MOD,
    USR_CREACION,
    USR_ULT_MOD,
    ESTADO,
    VISIBLE_COMERCIAL
  )
  VALUES
  (
    DB_COMERCIAL.SEQ_ADMI_PRODUCTO_CARAC.NEXTVAL,
    (
     SELECT ID_PRODUCTO
     FROM DB_COMERCIAL.ADMI_PRODUCTO 
     WHERE CODIGO_PRODUCTO='SENS_PVR'
     AND ESTADO='Activo'
    ),
    (
     SELECT ID_CARACTERISTICA 
     FROM DB_COMERCIAL.ADMI_CARACTERISTICA 
     WHERE DESCRIPCION_CARACTERISTICA='CANTIDAD_NETHOME' 
     AND ESTADO='Activo'
    ),
    SYSDATE,
    NULL,
    'apenaherrera',
    NULL,
    'Activo',
    NULL
  );

INSERT
INTO DB_COMERCIAL.ADMI_PRODUCTO_CARACTERISTICA
  (
    ID_PRODUCTO_CARACTERISITICA,
    PRODUCTO_ID,
    CARACTERISTICA_ID,
    FE_CREACION,
    FE_ULT_MOD,
    USR_CREACION,
    USR_ULT_MOD,
    ESTADO,
    VISIBLE_COMERCIAL
  )
  VALUES
  (
    DB_COMERCIAL.SEQ_ADMI_PRODUCTO_CARAC.NEXTVAL,
    (
     SELECT ID_PRODUCTO
     FROM DB_COMERCIAL.ADMI_PRODUCTO 
     WHERE CODIGO_PRODUCTO='SENS_PVR'
     AND ESTADO='Activo'
    ),
    (
     SELECT ID_CARACTERISTICA 
     FROM DB_COMERCIAL.ADMI_CARACTERISTICA 
     WHERE DESCRIPCION_CARACTERISTICA='PRECIO_NETHOME' 
     AND ESTADO='Activo'
    ),
    SYSDATE,
    NULL,
    'apenaherrera',
    NULL,
    'Activo',
    NULL
  );

INSERT
INTO DB_COMERCIAL.ADMI_PRODUCTO_CARACTERISTICA
  (
    ID_PRODUCTO_CARACTERISITICA,
    PRODUCTO_ID,
    CARACTERISTICA_ID,
    FE_CREACION,
    FE_ULT_MOD,
    USR_CREACION,
    USR_ULT_MOD,
    ESTADO,
    VISIBLE_COMERCIAL
  )
  VALUES
  (
    DB_COMERCIAL.SEQ_ADMI_PRODUCTO_CARAC.NEXTVAL,
    (
     SELECT ID_PRODUCTO
     FROM DB_COMERCIAL.ADMI_PRODUCTO 
     WHERE CODIGO_PRODUCTO='SENS_PVR'
     AND ESTADO='Activo'
    ),
    (
     SELECT ID_CARACTERISTICA 
     FROM DB_COMERCIAL.ADMI_CARACTERISTICA 
     WHERE DESCRIPCION_CARACTERISTICA='VENDEDOR_NETHOME' 
     AND ESTADO='Activo'
    ),
    SYSDATE,
    NULL,
    'apenaherrera',
    NULL,
    'Activo',
    NULL
  );

INSERT
INTO DB_COMERCIAL.ADMI_PRODUCTO_CARACTERISTICA
  (
    ID_PRODUCTO_CARACTERISITICA,
    PRODUCTO_ID,
    CARACTERISTICA_ID,
    FE_CREACION,
    FE_ULT_MOD,
    USR_CREACION,
    USR_ULT_MOD,
    ESTADO,
    VISIBLE_COMERCIAL
  )
  VALUES
  (
    DB_COMERCIAL.SEQ_ADMI_PRODUCTO_CARAC.NEXTVAL,
    (
     SELECT ID_PRODUCTO
     FROM DB_COMERCIAL.ADMI_PRODUCTO 
     WHERE CODIGO_PRODUCTO='SENS_PVR'
     AND ESTADO='Activo'
    ),
    (
     SELECT ID_CARACTERISTICA 
     FROM DB_COMERCIAL.ADMI_CARACTERISTICA 
     WHERE DESCRIPCION_CARACTERISTICA='REQUIERE_SERIE' 
     AND ESTADO='Activo'
    ),
    SYSDATE,
    NULL,
    'apenaherrera',
    NULL,
    'Activo',
    NULL
  );

INSERT
INTO DB_COMERCIAL.INFO_PRODUCTO_IMPUESTO
  (
    ID_PRODUCTO_IMPUESTO,
    PRODUCTO_ID,
    IMPUESTO_ID,
    PORCENTAJE_IMPUESTO,
    FE_CREACION,
    USR_CREACION,
    FE_ULT_MOD,
    USR_ULT_MOD,
    ESTADO
  )
  VALUES
  (
    DB_COMERCIAL.SEQ_INFO_PRODUCTO_IMPUESTO.NEXTVAL,
    (
     SELECT ID_PRODUCTO
     FROM DB_COMERCIAL.ADMI_PRODUCTO 
     WHERE CODIGO_PRODUCTO='SENS_PVR'
     AND ESTADO='Activo'
    ),
    1,
    12,
    SYSDATE,
    'apenaherrera',
    NULL,
    NULL,
    'Activo'
  );

INSERT
INTO DB_COMERCIAL.ADMI_PRODUCTO
  (
    ID_PRODUCTO,
    EMPRESA_COD,
    CODIGO_PRODUCTO,
    DESCRIPCION_PRODUCTO,
    FUNCION_COSTO,
    FUNCION_PRECIO,
    INSTALACION,
    ESTADO,
    FE_CREACION,
    USR_CREACION,
    IP_CREACION,
    CTA_CONTABLE_PROD,
    CTA_CONTABLE_PROD_NC,
    ES_PREFERENCIA,
    ES_ENLACE,
    REQUIERE_PLANIFICACION,
    REQUIERE_INFO_TECNICA,
    NOMBRE_TECNICO,
    CTA_CONTABLE_DESC,
    TIPO,
    ES_CONCENTRADOR,
    SOPORTE_MASIVO,
    ESTADO_INICIAL,
    GRUPO,
    COMISION_VENTA,
    COMISION_MANTENIMIENTO,
    USR_GERENTE,
    CLASIFICACION,
    REQUIERE_COMISIONAR,
    SUBGRUPO,
    LINEA_NEGOCIO
  )
  VALUES
  (
   DB_COMERCIAL.SEQ_ADMI_PRODUCTO.NEXTVAL,
    '18',
    'SENS_M1',
    'Sensor de Movimiento con baterías de duración estimada 1 año',
    NULL,
    'PRECIO=44.99',
    0,
    'Activo',
    SYSDATE,
    'apenaherrera',
    '127.0.0.1',
    NULL,
    NULL,
    'NO',
    'NO',
    'SI',
    'NO',
    'NETHOME',
    NULL,
    'S',
    'NO',
    NULL,
    NULL,
    'NETHOME',
    NULL,
    NULL,
    NULL,
    NULL,
    'NO',
    NULL,
    NULL
  );

INSERT
INTO DB_COMERCIAL.ADMI_PRODUCTO_CARACTERISTICA
  (
    ID_PRODUCTO_CARACTERISITICA,
    PRODUCTO_ID,
    CARACTERISTICA_ID,
    FE_CREACION,
    FE_ULT_MOD,
    USR_CREACION,
    USR_ULT_MOD,
    ESTADO,
    VISIBLE_COMERCIAL
  )
  VALUES
  (
    DB_COMERCIAL.SEQ_ADMI_PRODUCTO_CARAC.NEXTVAL,
    (
     SELECT ID_PRODUCTO
     FROM DB_COMERCIAL.ADMI_PRODUCTO 
     WHERE CODIGO_PRODUCTO='SENS_M1'
     AND ESTADO='Activo'
    ),
    (
     SELECT ID_CARACTERISTICA 
     FROM DB_COMERCIAL.ADMI_CARACTERISTICA 
     WHERE DESCRIPCION_CARACTERISTICA='FACTURACION_UNICA' 
     AND ESTADO='Activo'
    ),
    SYSDATE,
    NULL,
    'apenaherrera',
    NULL,
    'Activo',
    NULL
  );

INSERT
INTO DB_COMERCIAL.ADMI_PRODUCTO_CARACTERISTICA
  (
    ID_PRODUCTO_CARACTERISITICA,
    PRODUCTO_ID,
    CARACTERISTICA_ID,
    FE_CREACION,
    FE_ULT_MOD,
    USR_CREACION,
    USR_ULT_MOD,
    ESTADO,
    VISIBLE_COMERCIAL
  )
  VALUES
  (
    DB_COMERCIAL.SEQ_ADMI_PRODUCTO_CARAC.NEXTVAL,
    (
     SELECT ID_PRODUCTO
     FROM DB_COMERCIAL.ADMI_PRODUCTO 
     WHERE CODIGO_PRODUCTO='SENS_M1'
     AND ESTADO='Activo'
    ),
    (
     SELECT ID_CARACTERISTICA 
     FROM DB_COMERCIAL.ADMI_CARACTERISTICA 
     WHERE DESCRIPCION_CARACTERISTICA='NETHOME' 
     AND ESTADO='Activo'
    ),
    SYSDATE,
    NULL,
    'apenaherrera',
    NULL,
    'Activo',
    NULL
  );

INSERT
INTO DB_COMERCIAL.ADMI_PRODUCTO_CARACTERISTICA
  (
    ID_PRODUCTO_CARACTERISITICA,
    PRODUCTO_ID,
    CARACTERISTICA_ID,
    FE_CREACION,
    FE_ULT_MOD,
    USR_CREACION,
    USR_ULT_MOD,
    ESTADO,
    VISIBLE_COMERCIAL
  )
  VALUES
  (
    DB_COMERCIAL.SEQ_ADMI_PRODUCTO_CARAC.NEXTVAL,
    (
     SELECT ID_PRODUCTO
     FROM DB_COMERCIAL.ADMI_PRODUCTO 
     WHERE CODIGO_PRODUCTO='SENS_M1'
     AND ESTADO='Activo'
    ),
    (
     SELECT ID_CARACTERISTICA 
     FROM DB_COMERCIAL.ADMI_CARACTERISTICA 
     WHERE DESCRIPCION_CARACTERISTICA='CANTIDAD_NETHOME' 
     AND ESTADO='Activo'
    ),
    SYSDATE,
    NULL,
    'apenaherrera',
    NULL,
    'Activo',
    NULL
  );

INSERT
INTO DB_COMERCIAL.ADMI_PRODUCTO_CARACTERISTICA
  (
    ID_PRODUCTO_CARACTERISITICA,
    PRODUCTO_ID,
    CARACTERISTICA_ID,
    FE_CREACION,
    FE_ULT_MOD,
    USR_CREACION,
    USR_ULT_MOD,
    ESTADO,
    VISIBLE_COMERCIAL
  )
  VALUES
  (
    DB_COMERCIAL.SEQ_ADMI_PRODUCTO_CARAC.NEXTVAL,
    (
     SELECT ID_PRODUCTO
     FROM DB_COMERCIAL.ADMI_PRODUCTO 
     WHERE CODIGO_PRODUCTO='SENS_M1'
     AND ESTADO='Activo'
    ),
    (
     SELECT ID_CARACTERISTICA 
     FROM DB_COMERCIAL.ADMI_CARACTERISTICA 
     WHERE DESCRIPCION_CARACTERISTICA='PRECIO_NETHOME' 
     AND ESTADO='Activo'
    ),
    SYSDATE,
    NULL,
    'apenaherrera',
    NULL,
    'Activo',
    NULL
  );

INSERT
INTO DB_COMERCIAL.ADMI_PRODUCTO_CARACTERISTICA
  (
    ID_PRODUCTO_CARACTERISITICA,
    PRODUCTO_ID,
    CARACTERISTICA_ID,
    FE_CREACION,
    FE_ULT_MOD,
    USR_CREACION,
    USR_ULT_MOD,
    ESTADO,
    VISIBLE_COMERCIAL
  )
  VALUES
  (
    DB_COMERCIAL.SEQ_ADMI_PRODUCTO_CARAC.NEXTVAL,
    (
     SELECT ID_PRODUCTO
     FROM DB_COMERCIAL.ADMI_PRODUCTO 
     WHERE CODIGO_PRODUCTO='SENS_M1'
     AND ESTADO='Activo'
    ),
    (
     SELECT ID_CARACTERISTICA 
     FROM DB_COMERCIAL.ADMI_CARACTERISTICA 
     WHERE DESCRIPCION_CARACTERISTICA='VENDEDOR_NETHOME' 
     AND ESTADO='Activo'
    ),
    SYSDATE,
    NULL,
    'apenaherrera',
    NULL,
    'Activo',
    NULL
  );

INSERT
INTO DB_COMERCIAL.ADMI_PRODUCTO_CARACTERISTICA
  (
    ID_PRODUCTO_CARACTERISITICA,
    PRODUCTO_ID,
    CARACTERISTICA_ID,
    FE_CREACION,
    FE_ULT_MOD,
    USR_CREACION,
    USR_ULT_MOD,
    ESTADO,
    VISIBLE_COMERCIAL
  )
  VALUES
  (
    DB_COMERCIAL.SEQ_ADMI_PRODUCTO_CARAC.NEXTVAL,
    (
     SELECT ID_PRODUCTO
     FROM DB_COMERCIAL.ADMI_PRODUCTO 
     WHERE CODIGO_PRODUCTO='SENS_M1'
     AND ESTADO='Activo'
    ),
    (
     SELECT ID_CARACTERISTICA 
     FROM DB_COMERCIAL.ADMI_CARACTERISTICA 
     WHERE DESCRIPCION_CARACTERISTICA='REQUIERE_SERIE' 
     AND ESTADO='Activo'
    ),
    SYSDATE,
    NULL,
    'apenaherrera',
    NULL,
    'Activo',
    NULL
  );

INSERT
INTO DB_COMERCIAL.INFO_PRODUCTO_IMPUESTO
  (
    ID_PRODUCTO_IMPUESTO,
    PRODUCTO_ID,
    IMPUESTO_ID,
    PORCENTAJE_IMPUESTO,
    FE_CREACION,
    USR_CREACION,
    FE_ULT_MOD,
    USR_ULT_MOD,
    ESTADO
  )
  VALUES
  (
    DB_COMERCIAL.SEQ_INFO_PRODUCTO_IMPUESTO.NEXTVAL,
    (
     SELECT ID_PRODUCTO
     FROM DB_COMERCIAL.ADMI_PRODUCTO 
     WHERE CODIGO_PRODUCTO='SENS_M1'
     AND ESTADO='Activo'
    ),
    1,
    12,
    SYSDATE,
    'apenaherrera',
    NULL,
    NULL,
    'Activo'
  );

INSERT
INTO DB_COMERCIAL.ADMI_PRODUCTO
  (
    ID_PRODUCTO,
    EMPRESA_COD,
    CODIGO_PRODUCTO,
    DESCRIPCION_PRODUCTO,
    FUNCION_COSTO,
    FUNCION_PRECIO,
    INSTALACION,
    ESTADO,
    FE_CREACION,
    USR_CREACION,
    IP_CREACION,
    CTA_CONTABLE_PROD,
    CTA_CONTABLE_PROD_NC,
    ES_PREFERENCIA,
    ES_ENLACE,
    REQUIERE_PLANIFICACION,
    REQUIERE_INFO_TECNICA,
    NOMBRE_TECNICO,
    CTA_CONTABLE_DESC,
    TIPO,
    ES_CONCENTRADOR,
    SOPORTE_MASIVO,
    ESTADO_INICIAL,
    GRUPO,
    COMISION_VENTA,
    COMISION_MANTENIMIENTO,
    USR_GERENTE,
    CLASIFICACION,
    REQUIERE_COMISIONAR,
    SUBGRUPO,
    LINEA_NEGOCIO
  )
  VALUES
  (
   DB_COMERCIAL.SEQ_ADMI_PRODUCTO.NEXTVAL,
    '18',
    'SENS_M2',
    'Sensor de Movimiento con baterías de duración estimada 2 años',
    NULL,
    'PRECIO=59.98',
    0,
    'Activo',
    SYSDATE,
    'apenaherrera',
    '127.0.0.1',
    NULL,
    NULL,
    'NO',
    'NO',
    'SI',
    'NO',
    'NETHOME',
    NULL,
    'S',
    'NO',
    NULL,
    NULL,
    'NETHOME',
    NULL,
    NULL,
    NULL,
    NULL,
    'NO',
    NULL,
    NULL
  );

INSERT
INTO DB_COMERCIAL.ADMI_PRODUCTO_CARACTERISTICA
  (
    ID_PRODUCTO_CARACTERISITICA,
    PRODUCTO_ID,
    CARACTERISTICA_ID,
    FE_CREACION,
    FE_ULT_MOD,
    USR_CREACION,
    USR_ULT_MOD,
    ESTADO,
    VISIBLE_COMERCIAL
  )
  VALUES
  (
    DB_COMERCIAL.SEQ_ADMI_PRODUCTO_CARAC.NEXTVAL,
    (
     SELECT ID_PRODUCTO
     FROM DB_COMERCIAL.ADMI_PRODUCTO 
     WHERE CODIGO_PRODUCTO='SENS_M2'
     AND ESTADO='Activo'
    ),
    (
     SELECT ID_CARACTERISTICA 
     FROM DB_COMERCIAL.ADMI_CARACTERISTICA 
     WHERE DESCRIPCION_CARACTERISTICA='FACTURACION_UNICA' 
     AND ESTADO='Activo'
    ),
    SYSDATE,
    NULL,
    'apenaherrera',
    NULL,
    'Activo',
    NULL
  );

INSERT
INTO DB_COMERCIAL.ADMI_PRODUCTO_CARACTERISTICA
  (
    ID_PRODUCTO_CARACTERISITICA,
    PRODUCTO_ID,
    CARACTERISTICA_ID,
    FE_CREACION,
    FE_ULT_MOD,
    USR_CREACION,
    USR_ULT_MOD,
    ESTADO,
    VISIBLE_COMERCIAL
  )
  VALUES
  (
    DB_COMERCIAL.SEQ_ADMI_PRODUCTO_CARAC.NEXTVAL,
    (
     SELECT ID_PRODUCTO
     FROM DB_COMERCIAL.ADMI_PRODUCTO 
     WHERE CODIGO_PRODUCTO='SENS_M2'
     AND ESTADO='Activo'
    ),
    (
     SELECT ID_CARACTERISTICA 
     FROM DB_COMERCIAL.ADMI_CARACTERISTICA 
     WHERE DESCRIPCION_CARACTERISTICA='NETHOME' 
     AND ESTADO='Activo'
    ),
    SYSDATE,
    NULL,
    'apenaherrera',
    NULL,
    'Activo',
    NULL
  );

INSERT
INTO DB_COMERCIAL.ADMI_PRODUCTO_CARACTERISTICA
  (
    ID_PRODUCTO_CARACTERISITICA,
    PRODUCTO_ID,
    CARACTERISTICA_ID,
    FE_CREACION,
    FE_ULT_MOD,
    USR_CREACION,
    USR_ULT_MOD,
    ESTADO,
    VISIBLE_COMERCIAL
  )
  VALUES
  (
    DB_COMERCIAL.SEQ_ADMI_PRODUCTO_CARAC.NEXTVAL,
    (
     SELECT ID_PRODUCTO
     FROM DB_COMERCIAL.ADMI_PRODUCTO 
     WHERE CODIGO_PRODUCTO='SENS_M2'
     AND ESTADO='Activo'
    ),
    (
     SELECT ID_CARACTERISTICA 
     FROM DB_COMERCIAL.ADMI_CARACTERISTICA 
     WHERE DESCRIPCION_CARACTERISTICA='CANTIDAD_NETHOME' 
     AND ESTADO='Activo'
    ),
    SYSDATE,
    NULL,
    'apenaherrera',
    NULL,
    'Activo',
    NULL
  );

INSERT
INTO DB_COMERCIAL.ADMI_PRODUCTO_CARACTERISTICA
  (
    ID_PRODUCTO_CARACTERISITICA,
    PRODUCTO_ID,
    CARACTERISTICA_ID,
    FE_CREACION,
    FE_ULT_MOD,
    USR_CREACION,
    USR_ULT_MOD,
    ESTADO,
    VISIBLE_COMERCIAL
  )
  VALUES
  (
    DB_COMERCIAL.SEQ_ADMI_PRODUCTO_CARAC.NEXTVAL,
    (
     SELECT ID_PRODUCTO
     FROM DB_COMERCIAL.ADMI_PRODUCTO 
     WHERE CODIGO_PRODUCTO='SENS_M2'
     AND ESTADO='Activo'
    ),
    (
     SELECT ID_CARACTERISTICA 
     FROM DB_COMERCIAL.ADMI_CARACTERISTICA 
     WHERE DESCRIPCION_CARACTERISTICA='PRECIO_NETHOME' 
     AND ESTADO='Activo'
    ),
    SYSDATE,
    NULL,
    'apenaherrera',
    NULL,
    'Activo',
    NULL
  );

INSERT
INTO DB_COMERCIAL.ADMI_PRODUCTO_CARACTERISTICA
  (
    ID_PRODUCTO_CARACTERISITICA,
    PRODUCTO_ID,
    CARACTERISTICA_ID,
    FE_CREACION,
    FE_ULT_MOD,
    USR_CREACION,
    USR_ULT_MOD,
    ESTADO,
    VISIBLE_COMERCIAL
  )
  VALUES
  (
    DB_COMERCIAL.SEQ_ADMI_PRODUCTO_CARAC.NEXTVAL,
    (
     SELECT ID_PRODUCTO
     FROM DB_COMERCIAL.ADMI_PRODUCTO 
     WHERE CODIGO_PRODUCTO='SENS_M2'
     AND ESTADO='Activo'
    ),
    (
     SELECT ID_CARACTERISTICA 
     FROM DB_COMERCIAL.ADMI_CARACTERISTICA 
     WHERE DESCRIPCION_CARACTERISTICA='VENDEDOR_NETHOME' 
     AND ESTADO='Activo'
    ),
    SYSDATE,
    NULL,
    'apenaherrera',
    NULL,
    'Activo',
    NULL
  );

INSERT
INTO DB_COMERCIAL.ADMI_PRODUCTO_CARACTERISTICA
  (
    ID_PRODUCTO_CARACTERISITICA,
    PRODUCTO_ID,
    CARACTERISTICA_ID,
    FE_CREACION,
    FE_ULT_MOD,
    USR_CREACION,
    USR_ULT_MOD,
    ESTADO,
    VISIBLE_COMERCIAL
  )
  VALUES
  (
    DB_COMERCIAL.SEQ_ADMI_PRODUCTO_CARAC.NEXTVAL,
    (
     SELECT ID_PRODUCTO
     FROM DB_COMERCIAL.ADMI_PRODUCTO 
     WHERE CODIGO_PRODUCTO='SENS_M2'
     AND ESTADO='Activo'
    ),
    (
     SELECT ID_CARACTERISTICA 
     FROM DB_COMERCIAL.ADMI_CARACTERISTICA 
     WHERE DESCRIPCION_CARACTERISTICA='REQUIERE_SERIE' 
     AND ESTADO='Activo'
    ),
    SYSDATE,
    NULL,
    'apenaherrera',
    NULL,
    'Activo',
    NULL
  );

INSERT
INTO DB_COMERCIAL.INFO_PRODUCTO_IMPUESTO
  (
    ID_PRODUCTO_IMPUESTO,
    PRODUCTO_ID,
    IMPUESTO_ID,
    PORCENTAJE_IMPUESTO,
    FE_CREACION,
    USR_CREACION,
    FE_ULT_MOD,
    USR_ULT_MOD,
    ESTADO
  )
  VALUES
  (
    DB_COMERCIAL.SEQ_INFO_PRODUCTO_IMPUESTO.NEXTVAL,
    (
     SELECT ID_PRODUCTO
     FROM DB_COMERCIAL.ADMI_PRODUCTO 
     WHERE CODIGO_PRODUCTO='SENS_M2'
     AND ESTADO='Activo'
    ),
    1,
    12,
    SYSDATE,
    'apenaherrera',
    NULL,
    NULL,
    'Activo'
  );

INSERT
INTO DB_COMERCIAL.ADMI_PRODUCTO
  (
    ID_PRODUCTO,
    EMPRESA_COD,
    CODIGO_PRODUCTO,
    DESCRIPCION_PRODUCTO,
    FUNCION_COSTO,
    FUNCION_PRECIO,
    INSTALACION,
    ESTADO,
    FE_CREACION,
    USR_CREACION,
    IP_CREACION,
    CTA_CONTABLE_PROD,
    CTA_CONTABLE_PROD_NC,
    ES_PREFERENCIA,
    ES_ENLACE,
    REQUIERE_PLANIFICACION,
    REQUIERE_INFO_TECNICA,
    NOMBRE_TECNICO,
    CTA_CONTABLE_DESC,
    TIPO,
    ES_CONCENTRADOR,
    SOPORTE_MASIVO,
    ESTADO_INICIAL,
    GRUPO,
    COMISION_VENTA,
    COMISION_MANTENIMIENTO,
    USR_GERENTE,
    CLASIFICACION,
    REQUIERE_COMISIONAR,
    SUBGRUPO,
    LINEA_NEGOCIO
  )
  VALUES
  (
   DB_COMERCIAL.SEQ_ADMI_PRODUCTO.NEXTVAL,
    '18',
    'TOMA_SUP',
    'Tomacorriente controlado (Superpuesto)',
    NULL,
    'PRECIO=44.99',
    0,
    'Activo',
    SYSDATE,
    'apenaherrera',
    '127.0.0.1',
    NULL,
    NULL,
    'NO',
    'NO',
    'SI',
    'NO',
    'NETHOME',
    NULL,
    'S',
    'NO',
    NULL,
    NULL,
    'NETHOME',
    NULL,
    NULL,
    NULL,
    NULL,
    'NO',
    NULL,
    NULL
  );

INSERT
INTO DB_COMERCIAL.ADMI_PRODUCTO_CARACTERISTICA
  (
    ID_PRODUCTO_CARACTERISITICA,
    PRODUCTO_ID,
    CARACTERISTICA_ID,
    FE_CREACION,
    FE_ULT_MOD,
    USR_CREACION,
    USR_ULT_MOD,
    ESTADO,
    VISIBLE_COMERCIAL
  )
  VALUES
  (
    DB_COMERCIAL.SEQ_ADMI_PRODUCTO_CARAC.NEXTVAL,
    (
     SELECT ID_PRODUCTO
     FROM DB_COMERCIAL.ADMI_PRODUCTO 
     WHERE CODIGO_PRODUCTO='TOMA_SUP'
     AND ESTADO='Activo'
    ),
    (
     SELECT ID_CARACTERISTICA 
     FROM DB_COMERCIAL.ADMI_CARACTERISTICA 
     WHERE DESCRIPCION_CARACTERISTICA='FACTURACION_UNICA' 
     AND ESTADO='Activo'
    ),
    SYSDATE,
    NULL,
    'apenaherrera',
    NULL,
    'Activo',
    NULL
  );

INSERT
INTO DB_COMERCIAL.ADMI_PRODUCTO_CARACTERISTICA
  (
    ID_PRODUCTO_CARACTERISITICA,
    PRODUCTO_ID,
    CARACTERISTICA_ID,
    FE_CREACION,
    FE_ULT_MOD,
    USR_CREACION,
    USR_ULT_MOD,
    ESTADO,
    VISIBLE_COMERCIAL
  )
  VALUES
  (
    DB_COMERCIAL.SEQ_ADMI_PRODUCTO_CARAC.NEXTVAL,
    (
     SELECT ID_PRODUCTO
     FROM DB_COMERCIAL.ADMI_PRODUCTO 
     WHERE CODIGO_PRODUCTO='TOMA_SUP'
     AND ESTADO='Activo'
    ),
    (
     SELECT ID_CARACTERISTICA 
     FROM DB_COMERCIAL.ADMI_CARACTERISTICA 
     WHERE DESCRIPCION_CARACTERISTICA='NETHOME' 
     AND ESTADO='Activo'
    ),
    SYSDATE,
    NULL,
    'apenaherrera',
    NULL,
    'Activo',
    NULL
  );

INSERT
INTO DB_COMERCIAL.ADMI_PRODUCTO_CARACTERISTICA
  (
    ID_PRODUCTO_CARACTERISITICA,
    PRODUCTO_ID,
    CARACTERISTICA_ID,
    FE_CREACION,
    FE_ULT_MOD,
    USR_CREACION,
    USR_ULT_MOD,
    ESTADO,
    VISIBLE_COMERCIAL
  )
  VALUES
  (
    DB_COMERCIAL.SEQ_ADMI_PRODUCTO_CARAC.NEXTVAL,
    (
     SELECT ID_PRODUCTO
     FROM DB_COMERCIAL.ADMI_PRODUCTO 
     WHERE CODIGO_PRODUCTO='TOMA_SUP'
     AND ESTADO='Activo'
    ),
    (
     SELECT ID_CARACTERISTICA 
     FROM DB_COMERCIAL.ADMI_CARACTERISTICA 
     WHERE DESCRIPCION_CARACTERISTICA='CANTIDAD_NETHOME' 
     AND ESTADO='Activo'
    ),
    SYSDATE,
    NULL,
    'apenaherrera',
    NULL,
    'Activo',
    NULL
  );

INSERT
INTO DB_COMERCIAL.ADMI_PRODUCTO_CARACTERISTICA
  (
    ID_PRODUCTO_CARACTERISITICA,
    PRODUCTO_ID,
    CARACTERISTICA_ID,
    FE_CREACION,
    FE_ULT_MOD,
    USR_CREACION,
    USR_ULT_MOD,
    ESTADO,
    VISIBLE_COMERCIAL
  )
  VALUES
  (
    DB_COMERCIAL.SEQ_ADMI_PRODUCTO_CARAC.NEXTVAL,
    (
     SELECT ID_PRODUCTO
     FROM DB_COMERCIAL.ADMI_PRODUCTO 
     WHERE CODIGO_PRODUCTO='TOMA_SUP'
     AND ESTADO='Activo'
    ),
    (
     SELECT ID_CARACTERISTICA 
     FROM DB_COMERCIAL.ADMI_CARACTERISTICA 
     WHERE DESCRIPCION_CARACTERISTICA='PRECIO_NETHOME' 
     AND ESTADO='Activo'
    ),
    SYSDATE,
    NULL,
    'apenaherrera',
    NULL,
    'Activo',
    NULL
  );

INSERT
INTO DB_COMERCIAL.ADMI_PRODUCTO_CARACTERISTICA
  (
    ID_PRODUCTO_CARACTERISITICA,
    PRODUCTO_ID,
    CARACTERISTICA_ID,
    FE_CREACION,
    FE_ULT_MOD,
    USR_CREACION,
    USR_ULT_MOD,
    ESTADO,
    VISIBLE_COMERCIAL
  )
  VALUES
  (
    DB_COMERCIAL.SEQ_ADMI_PRODUCTO_CARAC.NEXTVAL,
    (
     SELECT ID_PRODUCTO
     FROM DB_COMERCIAL.ADMI_PRODUCTO 
     WHERE CODIGO_PRODUCTO='TOMA_SUP'
     AND ESTADO='Activo'
    ),
    (
     SELECT ID_CARACTERISTICA 
     FROM DB_COMERCIAL.ADMI_CARACTERISTICA 
     WHERE DESCRIPCION_CARACTERISTICA='VENDEDOR_NETHOME' 
     AND ESTADO='Activo'
    ),
    SYSDATE,
    NULL,
    'apenaherrera',
    NULL,
    'Activo',
    NULL
  );

INSERT
INTO DB_COMERCIAL.ADMI_PRODUCTO_CARACTERISTICA
  (
    ID_PRODUCTO_CARACTERISITICA,
    PRODUCTO_ID,
    CARACTERISTICA_ID,
    FE_CREACION,
    FE_ULT_MOD,
    USR_CREACION,
    USR_ULT_MOD,
    ESTADO,
    VISIBLE_COMERCIAL
  )
  VALUES
  (
    DB_COMERCIAL.SEQ_ADMI_PRODUCTO_CARAC.NEXTVAL,
    (
     SELECT ID_PRODUCTO
     FROM DB_COMERCIAL.ADMI_PRODUCTO 
     WHERE CODIGO_PRODUCTO='TOMA_SUP'
     AND ESTADO='Activo'
    ),
    (
     SELECT ID_CARACTERISTICA 
     FROM DB_COMERCIAL.ADMI_CARACTERISTICA 
     WHERE DESCRIPCION_CARACTERISTICA='REQUIERE_SERIE' 
     AND ESTADO='Activo'
    ),
    SYSDATE,
    NULL,
    'apenaherrera',
    NULL,
    'Activo',
    NULL
  );

INSERT
INTO DB_COMERCIAL.INFO_PRODUCTO_IMPUESTO
  (
    ID_PRODUCTO_IMPUESTO,
    PRODUCTO_ID,
    IMPUESTO_ID,
    PORCENTAJE_IMPUESTO,
    FE_CREACION,
    USR_CREACION,
    FE_ULT_MOD,
    USR_ULT_MOD,
    ESTADO
  )
  VALUES
  (
    DB_COMERCIAL.SEQ_INFO_PRODUCTO_IMPUESTO.NEXTVAL,
    (
     SELECT ID_PRODUCTO
     FROM DB_COMERCIAL.ADMI_PRODUCTO 
     WHERE CODIGO_PRODUCTO='TOMA_SUP'
     AND ESTADO='Activo'
    ),
    1,
    12,
    SYSDATE,
    'apenaherrera',
    NULL,
    NULL,
    'Activo'
  );

INSERT
INTO DB_COMERCIAL.ADMI_PRODUCTO
  (
    ID_PRODUCTO,
    EMPRESA_COD,
    CODIGO_PRODUCTO,
    DESCRIPCION_PRODUCTO,
    FUNCION_COSTO,
    FUNCION_PRECIO,
    INSTALACION,
    ESTADO,
    FE_CREACION,
    USR_CREACION,
    IP_CREACION,
    CTA_CONTABLE_PROD,
    CTA_CONTABLE_PROD_NC,
    ES_PREFERENCIA,
    ES_ENLACE,
    REQUIERE_PLANIFICACION,
    REQUIERE_INFO_TECNICA,
    NOMBRE_TECNICO,
    CTA_CONTABLE_DESC,
    TIPO,
    ES_CONCENTRADOR,
    SOPORTE_MASIVO,
    ESTADO_INICIAL,
    GRUPO,
    COMISION_VENTA,
    COMISION_MANTENIMIENTO,
    USR_GERENTE,
    CLASIFICACION,
    REQUIERE_COMISIONAR,
    SUBGRUPO,
    LINEA_NEGOCIO
  )
  VALUES
  (
   DB_COMERCIAL.SEQ_ADMI_PRODUCTO.NEXTVAL,
    '18',
    'TOMA_EMP',
    'Tomacorriente controlado (Empotrable)',
    NULL,
    'PRECIO=49.99',
    0,
    'Activo',
    SYSDATE,
    'apenaherrera',
    '127.0.0.1',
    NULL,
    NULL,
    'NO',
    'NO',
    'SI',
    'NO',
    'NETHOME',
    NULL,
    'S',
    'NO',
    NULL,
    NULL,
    'NETHOME',
    NULL,
    NULL,
    NULL,
    NULL,
    'NO',
    NULL,
    NULL
  );

INSERT
INTO DB_COMERCIAL.ADMI_PRODUCTO_CARACTERISTICA
  (
    ID_PRODUCTO_CARACTERISITICA,
    PRODUCTO_ID,
    CARACTERISTICA_ID,
    FE_CREACION,
    FE_ULT_MOD,
    USR_CREACION,
    USR_ULT_MOD,
    ESTADO,
    VISIBLE_COMERCIAL
  )
  VALUES
  (
    DB_COMERCIAL.SEQ_ADMI_PRODUCTO_CARAC.NEXTVAL,
    (
     SELECT ID_PRODUCTO
     FROM DB_COMERCIAL.ADMI_PRODUCTO 
     WHERE CODIGO_PRODUCTO='TOMA_EMP'
     AND ESTADO='Activo'
    ),
    (
     SELECT ID_CARACTERISTICA 
     FROM DB_COMERCIAL.ADMI_CARACTERISTICA 
     WHERE DESCRIPCION_CARACTERISTICA='FACTURACION_UNICA' 
     AND ESTADO='Activo'
    ),
    SYSDATE,
    NULL,
    'apenaherrera',
    NULL,
    'Activo',
    NULL
  );

INSERT
INTO DB_COMERCIAL.ADMI_PRODUCTO_CARACTERISTICA
  (
    ID_PRODUCTO_CARACTERISITICA,
    PRODUCTO_ID,
    CARACTERISTICA_ID,
    FE_CREACION,
    FE_ULT_MOD,
    USR_CREACION,
    USR_ULT_MOD,
    ESTADO,
    VISIBLE_COMERCIAL
  )
  VALUES
  (
    DB_COMERCIAL.SEQ_ADMI_PRODUCTO_CARAC.NEXTVAL,
    (
     SELECT ID_PRODUCTO
     FROM DB_COMERCIAL.ADMI_PRODUCTO 
     WHERE CODIGO_PRODUCTO='TOMA_EMP'
     AND ESTADO='Activo'
    ),
    (
     SELECT ID_CARACTERISTICA 
     FROM DB_COMERCIAL.ADMI_CARACTERISTICA 
     WHERE DESCRIPCION_CARACTERISTICA='NETHOME' 
     AND ESTADO='Activo'
    ),
    SYSDATE,
    NULL,
    'apenaherrera',
    NULL,
    'Activo',
    NULL
  );

INSERT
INTO DB_COMERCIAL.ADMI_PRODUCTO_CARACTERISTICA
  (
    ID_PRODUCTO_CARACTERISITICA,
    PRODUCTO_ID,
    CARACTERISTICA_ID,
    FE_CREACION,
    FE_ULT_MOD,
    USR_CREACION,
    USR_ULT_MOD,
    ESTADO,
    VISIBLE_COMERCIAL
  )
  VALUES
  (
    DB_COMERCIAL.SEQ_ADMI_PRODUCTO_CARAC.NEXTVAL,
    (
     SELECT ID_PRODUCTO
     FROM DB_COMERCIAL.ADMI_PRODUCTO 
     WHERE CODIGO_PRODUCTO='TOMA_EMP'
     AND ESTADO='Activo'
    ),
    (
     SELECT ID_CARACTERISTICA 
     FROM DB_COMERCIAL.ADMI_CARACTERISTICA 
     WHERE DESCRIPCION_CARACTERISTICA='CANTIDAD_NETHOME' 
     AND ESTADO='Activo'
    ),
    SYSDATE,
    NULL,
    'apenaherrera',
    NULL,
    'Activo',
    NULL
  );

INSERT
INTO DB_COMERCIAL.ADMI_PRODUCTO_CARACTERISTICA
  (
    ID_PRODUCTO_CARACTERISITICA,
    PRODUCTO_ID,
    CARACTERISTICA_ID,
    FE_CREACION,
    FE_ULT_MOD,
    USR_CREACION,
    USR_ULT_MOD,
    ESTADO,
    VISIBLE_COMERCIAL
  )
  VALUES
  (
    DB_COMERCIAL.SEQ_ADMI_PRODUCTO_CARAC.NEXTVAL,
    (
     SELECT ID_PRODUCTO
     FROM DB_COMERCIAL.ADMI_PRODUCTO 
     WHERE CODIGO_PRODUCTO='TOMA_EMP'
     AND ESTADO='Activo'
    ),
    (
     SELECT ID_CARACTERISTICA 
     FROM DB_COMERCIAL.ADMI_CARACTERISTICA 
     WHERE DESCRIPCION_CARACTERISTICA='PRECIO_NETHOME' 
     AND ESTADO='Activo'
    ),
    SYSDATE,
    NULL,
    'apenaherrera',
    NULL,
    'Activo',
    NULL
  );

INSERT
INTO DB_COMERCIAL.ADMI_PRODUCTO_CARACTERISTICA
  (
    ID_PRODUCTO_CARACTERISITICA,
    PRODUCTO_ID,
    CARACTERISTICA_ID,
    FE_CREACION,
    FE_ULT_MOD,
    USR_CREACION,
    USR_ULT_MOD,
    ESTADO,
    VISIBLE_COMERCIAL
  )
  VALUES
  (
    DB_COMERCIAL.SEQ_ADMI_PRODUCTO_CARAC.NEXTVAL,
    (
     SELECT ID_PRODUCTO
     FROM DB_COMERCIAL.ADMI_PRODUCTO 
     WHERE CODIGO_PRODUCTO='TOMA_EMP'
     AND ESTADO='Activo'
    ),
    (
     SELECT ID_CARACTERISTICA 
     FROM DB_COMERCIAL.ADMI_CARACTERISTICA 
     WHERE DESCRIPCION_CARACTERISTICA='VENDEDOR_NETHOME' 
     AND ESTADO='Activo'
    ),
    SYSDATE,
    NULL,
    'apenaherrera',
    NULL,
    'Activo',
    NULL
  );

INSERT
INTO DB_COMERCIAL.ADMI_PRODUCTO_CARACTERISTICA
  (
    ID_PRODUCTO_CARACTERISITICA,
    PRODUCTO_ID,
    CARACTERISTICA_ID,
    FE_CREACION,
    FE_ULT_MOD,
    USR_CREACION,
    USR_ULT_MOD,
    ESTADO,
    VISIBLE_COMERCIAL
  )
  VALUES
  (
    DB_COMERCIAL.SEQ_ADMI_PRODUCTO_CARAC.NEXTVAL,
    (
     SELECT ID_PRODUCTO
     FROM DB_COMERCIAL.ADMI_PRODUCTO 
     WHERE CODIGO_PRODUCTO='TOMA_EMP'
     AND ESTADO='Activo'
    ),
    (
     SELECT ID_CARACTERISTICA 
     FROM DB_COMERCIAL.ADMI_CARACTERISTICA 
     WHERE DESCRIPCION_CARACTERISTICA='REQUIERE_SERIE' 
     AND ESTADO='Activo'
    ),
    SYSDATE,
    NULL,
    'apenaherrera',
    NULL,
    'Activo',
    NULL
  );

INSERT
INTO DB_COMERCIAL.INFO_PRODUCTO_IMPUESTO
  (
    ID_PRODUCTO_IMPUESTO,
    PRODUCTO_ID,
    IMPUESTO_ID,
    PORCENTAJE_IMPUESTO,
    FE_CREACION,
    USR_CREACION,
    FE_ULT_MOD,
    USR_ULT_MOD,
    ESTADO
  )
  VALUES
  (
    DB_COMERCIAL.SEQ_INFO_PRODUCTO_IMPUESTO.NEXTVAL,
    (
     SELECT ID_PRODUCTO
     FROM DB_COMERCIAL.ADMI_PRODUCTO 
     WHERE CODIGO_PRODUCTO='TOMA_EMP'
     AND ESTADO='Activo'
    ),
    1,
    12,
    SYSDATE,
    'apenaherrera',
    NULL,
    NULL,
    'Activo'
  );

INSERT
INTO DB_COMERCIAL.ADMI_PRODUCTO
  (
    ID_PRODUCTO,
    EMPRESA_COD,
    CODIGO_PRODUCTO,
    DESCRIPCION_PRODUCTO,
    FUNCION_COSTO,
    FUNCION_PRECIO,
    INSTALACION,
    ESTADO,
    FE_CREACION,
    USR_CREACION,
    IP_CREACION,
    CTA_CONTABLE_PROD,
    CTA_CONTABLE_PROD_NC,
    ES_PREFERENCIA,
    ES_ENLACE,
    REQUIERE_PLANIFICACION,
    REQUIERE_INFO_TECNICA,
    NOMBRE_TECNICO,
    CTA_CONTABLE_DESC,
    TIPO,
    ES_CONCENTRADOR,
    SOPORTE_MASIVO,
    ESTADO_INICIAL,
    GRUPO,
    COMISION_VENTA,
    COMISION_MANTENIMIENTO,
    USR_GERENTE,
    CLASIFICACION,
    REQUIERE_COMISIONAR,
    SUBGRUPO,
    LINEA_NEGOCIO
  )
  VALUES
  (
   DB_COMERCIAL.SEQ_ADMI_PRODUCTO.NEXTVAL,
    '18',
    'K_LUCES',
    'Kit de 4 Luces LED con colores',
    NULL,
    'PRECIO=149.99',
    0,
    'Activo',
    SYSDATE,
    'apenaherrera',
    '127.0.0.1',
    NULL,
    NULL,
    'NO',
    'NO',
    'SI',
    'NO',
    'NETHOME',
    NULL,
    'S',
    'NO',
    NULL,
    NULL,
    'NETHOME',
    NULL,
    NULL,
    NULL,
    NULL,
    'NO',
    NULL,
    NULL
  );

INSERT
INTO DB_COMERCIAL.ADMI_PRODUCTO_CARACTERISTICA
  (
    ID_PRODUCTO_CARACTERISITICA,
    PRODUCTO_ID,
    CARACTERISTICA_ID,
    FE_CREACION,
    FE_ULT_MOD,
    USR_CREACION,
    USR_ULT_MOD,
    ESTADO,
    VISIBLE_COMERCIAL
  )
  VALUES
  (
    DB_COMERCIAL.SEQ_ADMI_PRODUCTO_CARAC.NEXTVAL,
    (
     SELECT ID_PRODUCTO
     FROM DB_COMERCIAL.ADMI_PRODUCTO 
     WHERE CODIGO_PRODUCTO='K_LUCES'
     AND ESTADO='Activo'
    ),
    (
     SELECT ID_CARACTERISTICA 
     FROM DB_COMERCIAL.ADMI_CARACTERISTICA 
     WHERE DESCRIPCION_CARACTERISTICA='FACTURACION_UNICA' 
     AND ESTADO='Activo'
    ),
    SYSDATE,
    NULL,
    'apenaherrera',
    NULL,
    'Activo',
    NULL
  );

INSERT
INTO DB_COMERCIAL.ADMI_PRODUCTO_CARACTERISTICA
  (
    ID_PRODUCTO_CARACTERISITICA,
    PRODUCTO_ID,
    CARACTERISTICA_ID,
    FE_CREACION,
    FE_ULT_MOD,
    USR_CREACION,
    USR_ULT_MOD,
    ESTADO,
    VISIBLE_COMERCIAL
  )
  VALUES
  (
    DB_COMERCIAL.SEQ_ADMI_PRODUCTO_CARAC.NEXTVAL,
    (
     SELECT ID_PRODUCTO
     FROM DB_COMERCIAL.ADMI_PRODUCTO 
     WHERE CODIGO_PRODUCTO='K_LUCES'
     AND ESTADO='Activo'
    ),
    (
     SELECT ID_CARACTERISTICA 
     FROM DB_COMERCIAL.ADMI_CARACTERISTICA 
     WHERE DESCRIPCION_CARACTERISTICA='NETHOME' 
     AND ESTADO='Activo'
    ),
    SYSDATE,
    NULL,
    'apenaherrera',
    NULL,
    'Activo',
    NULL
  );

INSERT
INTO DB_COMERCIAL.ADMI_PRODUCTO_CARACTERISTICA
  (
    ID_PRODUCTO_CARACTERISITICA,
    PRODUCTO_ID,
    CARACTERISTICA_ID,
    FE_CREACION,
    FE_ULT_MOD,
    USR_CREACION,
    USR_ULT_MOD,
    ESTADO,
    VISIBLE_COMERCIAL
  )
  VALUES
  (
    DB_COMERCIAL.SEQ_ADMI_PRODUCTO_CARAC.NEXTVAL,
    (
     SELECT ID_PRODUCTO
     FROM DB_COMERCIAL.ADMI_PRODUCTO 
     WHERE CODIGO_PRODUCTO='K_LUCES'
     AND ESTADO='Activo'
    ),
    (
     SELECT ID_CARACTERISTICA 
     FROM DB_COMERCIAL.ADMI_CARACTERISTICA 
     WHERE DESCRIPCION_CARACTERISTICA='CANTIDAD_NETHOME' 
     AND ESTADO='Activo'
    ),
    SYSDATE,
    NULL,
    'apenaherrera',
    NULL,
    'Activo',
    NULL
  );

INSERT
INTO DB_COMERCIAL.ADMI_PRODUCTO_CARACTERISTICA
  (
    ID_PRODUCTO_CARACTERISITICA,
    PRODUCTO_ID,
    CARACTERISTICA_ID,
    FE_CREACION,
    FE_ULT_MOD,
    USR_CREACION,
    USR_ULT_MOD,
    ESTADO,
    VISIBLE_COMERCIAL
  )
  VALUES
  (
    DB_COMERCIAL.SEQ_ADMI_PRODUCTO_CARAC.NEXTVAL,
    (
     SELECT ID_PRODUCTO
     FROM DB_COMERCIAL.ADMI_PRODUCTO 
     WHERE CODIGO_PRODUCTO='K_LUCES'
     AND ESTADO='Activo'
    ),
    (
     SELECT ID_CARACTERISTICA 
     FROM DB_COMERCIAL.ADMI_CARACTERISTICA 
     WHERE DESCRIPCION_CARACTERISTICA='PRECIO_NETHOME' 
     AND ESTADO='Activo'
    ),
    SYSDATE,
    NULL,
    'apenaherrera',
    NULL,
    'Activo',
    NULL
  );

INSERT
INTO DB_COMERCIAL.ADMI_PRODUCTO_CARACTERISTICA
  (
    ID_PRODUCTO_CARACTERISITICA,
    PRODUCTO_ID,
    CARACTERISTICA_ID,
    FE_CREACION,
    FE_ULT_MOD,
    USR_CREACION,
    USR_ULT_MOD,
    ESTADO,
    VISIBLE_COMERCIAL
  )
  VALUES
  (
    DB_COMERCIAL.SEQ_ADMI_PRODUCTO_CARAC.NEXTVAL,
    (
     SELECT ID_PRODUCTO
     FROM DB_COMERCIAL.ADMI_PRODUCTO 
     WHERE CODIGO_PRODUCTO='K_LUCES'
     AND ESTADO='Activo'
    ),
    (
     SELECT ID_CARACTERISTICA 
     FROM DB_COMERCIAL.ADMI_CARACTERISTICA 
     WHERE DESCRIPCION_CARACTERISTICA='VENDEDOR_NETHOME' 
     AND ESTADO='Activo'
    ),
    SYSDATE,
    NULL,
    'apenaherrera',
    NULL,
    'Activo',
    NULL
  );

INSERT
INTO DB_COMERCIAL.ADMI_PRODUCTO_CARACTERISTICA
  (
    ID_PRODUCTO_CARACTERISITICA,
    PRODUCTO_ID,
    CARACTERISTICA_ID,
    FE_CREACION,
    FE_ULT_MOD,
    USR_CREACION,
    USR_ULT_MOD,
    ESTADO,
    VISIBLE_COMERCIAL
  )
  VALUES
  (
    DB_COMERCIAL.SEQ_ADMI_PRODUCTO_CARAC.NEXTVAL,
    (
     SELECT ID_PRODUCTO
     FROM DB_COMERCIAL.ADMI_PRODUCTO 
     WHERE CODIGO_PRODUCTO='K_LUCES'
     AND ESTADO='Activo'
    ),
    (
     SELECT ID_CARACTERISTICA 
     FROM DB_COMERCIAL.ADMI_CARACTERISTICA 
     WHERE DESCRIPCION_CARACTERISTICA='REQUIERE_SERIE' 
     AND ESTADO='Activo'
    ),
    SYSDATE,
    NULL,
    'apenaherrera',
    NULL,
    'Activo',
    NULL
  );

INSERT
INTO DB_COMERCIAL.INFO_PRODUCTO_IMPUESTO
  (
    ID_PRODUCTO_IMPUESTO,
    PRODUCTO_ID,
    IMPUESTO_ID,
    PORCENTAJE_IMPUESTO,
    FE_CREACION,
    USR_CREACION,
    FE_ULT_MOD,
    USR_ULT_MOD,
    ESTADO
  )
  VALUES
  (
    DB_COMERCIAL.SEQ_INFO_PRODUCTO_IMPUESTO.NEXTVAL,
    (
     SELECT ID_PRODUCTO
     FROM DB_COMERCIAL.ADMI_PRODUCTO 
     WHERE CODIGO_PRODUCTO='K_LUCES'
     AND ESTADO='Activo'
    ),
    1,
    12,
    SYSDATE,
    'apenaherrera',
    NULL,
    NULL,
    'Activo'
  );

INSERT
INTO DB_COMERCIAL.ADMI_PRODUCTO
  (
    ID_PRODUCTO,
    EMPRESA_COD,
    CODIGO_PRODUCTO,
    DESCRIPCION_PRODUCTO,
    FUNCION_COSTO,
    FUNCION_PRECIO,
    INSTALACION,
    ESTADO,
    FE_CREACION,
    USR_CREACION,
    IP_CREACION,
    CTA_CONTABLE_PROD,
    CTA_CONTABLE_PROD_NC,
    ES_PREFERENCIA,
    ES_ENLACE,
    REQUIERE_PLANIFICACION,
    REQUIERE_INFO_TECNICA,
    NOMBRE_TECNICO,
    CTA_CONTABLE_DESC,
    TIPO,
    ES_CONCENTRADOR,
    SOPORTE_MASIVO,
    ESTADO_INICIAL,
    GRUPO,
    COMISION_VENTA,
    COMISION_MANTENIMIENTO,
    USR_GERENTE,
    CLASIFICACION,
    REQUIERE_COMISIONAR,
    SUBGRUPO,
    LINEA_NEGOCIO
  )
  VALUES
  (
   DB_COMERCIAL.SEQ_ADMI_PRODUCTO.NEXTVAL,
    '18',
    'FOCO_LED',
    'Foco de colores LED de 800 lumen',
    NULL,
    'PRECIO=44.99',
    0,
    'Activo',
    SYSDATE,
    'apenaherrera',
    '127.0.0.1',
    NULL,
    NULL,
    'NO',
    'NO',
    'SI',
    'NO',
    'NETHOME',
    NULL,
    'S',
    'NO',
    NULL,
    NULL,
    'NETHOME',
    NULL,
    NULL,
    NULL,
    NULL,
    'NO',
    NULL,
    NULL
  );

INSERT
INTO DB_COMERCIAL.ADMI_PRODUCTO_CARACTERISTICA
  (
    ID_PRODUCTO_CARACTERISITICA,
    PRODUCTO_ID,
    CARACTERISTICA_ID,
    FE_CREACION,
    FE_ULT_MOD,
    USR_CREACION,
    USR_ULT_MOD,
    ESTADO,
    VISIBLE_COMERCIAL
  )
  VALUES
  (
    DB_COMERCIAL.SEQ_ADMI_PRODUCTO_CARAC.NEXTVAL,
    (
     SELECT ID_PRODUCTO
     FROM DB_COMERCIAL.ADMI_PRODUCTO 
     WHERE CODIGO_PRODUCTO='FOCO_LED'
     AND ESTADO='Activo'
    ),
    (
     SELECT ID_CARACTERISTICA 
     FROM DB_COMERCIAL.ADMI_CARACTERISTICA 
     WHERE DESCRIPCION_CARACTERISTICA='FACTURACION_UNICA' 
     AND ESTADO='Activo'
    ),
    SYSDATE,
    NULL,
    'apenaherrera',
    NULL,
    'Activo',
    NULL
  );

INSERT
INTO DB_COMERCIAL.ADMI_PRODUCTO_CARACTERISTICA
  (
    ID_PRODUCTO_CARACTERISITICA,
    PRODUCTO_ID,
    CARACTERISTICA_ID,
    FE_CREACION,
    FE_ULT_MOD,
    USR_CREACION,
    USR_ULT_MOD,
    ESTADO,
    VISIBLE_COMERCIAL
  )
  VALUES
  (
    DB_COMERCIAL.SEQ_ADMI_PRODUCTO_CARAC.NEXTVAL,
    (
     SELECT ID_PRODUCTO
     FROM DB_COMERCIAL.ADMI_PRODUCTO 
     WHERE CODIGO_PRODUCTO='FOCO_LED'
     AND ESTADO='Activo'
    ),
    (
     SELECT ID_CARACTERISTICA 
     FROM DB_COMERCIAL.ADMI_CARACTERISTICA 
     WHERE DESCRIPCION_CARACTERISTICA='NETHOME' 
     AND ESTADO='Activo'
    ),
    SYSDATE,
    NULL,
    'apenaherrera',
    NULL,
    'Activo',
    NULL
  );

INSERT
INTO DB_COMERCIAL.ADMI_PRODUCTO_CARACTERISTICA
  (
    ID_PRODUCTO_CARACTERISITICA,
    PRODUCTO_ID,
    CARACTERISTICA_ID,
    FE_CREACION,
    FE_ULT_MOD,
    USR_CREACION,
    USR_ULT_MOD,
    ESTADO,
    VISIBLE_COMERCIAL
  )
  VALUES
  (
    DB_COMERCIAL.SEQ_ADMI_PRODUCTO_CARAC.NEXTVAL,
    (
     SELECT ID_PRODUCTO
     FROM DB_COMERCIAL.ADMI_PRODUCTO 
     WHERE CODIGO_PRODUCTO='FOCO_LED'
     AND ESTADO='Activo'
    ),
    (
     SELECT ID_CARACTERISTICA 
     FROM DB_COMERCIAL.ADMI_CARACTERISTICA 
     WHERE DESCRIPCION_CARACTERISTICA='CANTIDAD_NETHOME' 
     AND ESTADO='Activo'
    ),
    SYSDATE,
    NULL,
    'apenaherrera',
    NULL,
    'Activo',
    NULL
  );

INSERT
INTO DB_COMERCIAL.ADMI_PRODUCTO_CARACTERISTICA
  (
    ID_PRODUCTO_CARACTERISITICA,
    PRODUCTO_ID,
    CARACTERISTICA_ID,
    FE_CREACION,
    FE_ULT_MOD,
    USR_CREACION,
    USR_ULT_MOD,
    ESTADO,
    VISIBLE_COMERCIAL
  )
  VALUES
  (
    DB_COMERCIAL.SEQ_ADMI_PRODUCTO_CARAC.NEXTVAL,
    (
     SELECT ID_PRODUCTO
     FROM DB_COMERCIAL.ADMI_PRODUCTO 
     WHERE CODIGO_PRODUCTO='FOCO_LED'
     AND ESTADO='Activo'
    ),
    (
     SELECT ID_CARACTERISTICA 
     FROM DB_COMERCIAL.ADMI_CARACTERISTICA 
     WHERE DESCRIPCION_CARACTERISTICA='PRECIO_NETHOME' 
     AND ESTADO='Activo'
    ),
    SYSDATE,
    NULL,
    'apenaherrera',
    NULL,
    'Activo',
    NULL
  );

INSERT
INTO DB_COMERCIAL.ADMI_PRODUCTO_CARACTERISTICA
  (
    ID_PRODUCTO_CARACTERISITICA,
    PRODUCTO_ID,
    CARACTERISTICA_ID,
    FE_CREACION,
    FE_ULT_MOD,
    USR_CREACION,
    USR_ULT_MOD,
    ESTADO,
    VISIBLE_COMERCIAL
  )
  VALUES
  (
    DB_COMERCIAL.SEQ_ADMI_PRODUCTO_CARAC.NEXTVAL,
    (
     SELECT ID_PRODUCTO
     FROM DB_COMERCIAL.ADMI_PRODUCTO 
     WHERE CODIGO_PRODUCTO='FOCO_LED'
     AND ESTADO='Activo'
    ),
    (
     SELECT ID_CARACTERISTICA 
     FROM DB_COMERCIAL.ADMI_CARACTERISTICA 
     WHERE DESCRIPCION_CARACTERISTICA='VENDEDOR_NETHOME' 
     AND ESTADO='Activo'
    ),
    SYSDATE,
    NULL,
    'apenaherrera',
    NULL,
    'Activo',
    NULL
  );

INSERT
INTO DB_COMERCIAL.ADMI_PRODUCTO_CARACTERISTICA
  (
    ID_PRODUCTO_CARACTERISITICA,
    PRODUCTO_ID,
    CARACTERISTICA_ID,
    FE_CREACION,
    FE_ULT_MOD,
    USR_CREACION,
    USR_ULT_MOD,
    ESTADO,
    VISIBLE_COMERCIAL
  )
  VALUES
  (
    DB_COMERCIAL.SEQ_ADMI_PRODUCTO_CARAC.NEXTVAL,
    (
     SELECT ID_PRODUCTO
     FROM DB_COMERCIAL.ADMI_PRODUCTO 
     WHERE CODIGO_PRODUCTO='FOCO_LED'
     AND ESTADO='Activo'
    ),
    (
     SELECT ID_CARACTERISTICA 
     FROM DB_COMERCIAL.ADMI_CARACTERISTICA 
     WHERE DESCRIPCION_CARACTERISTICA='REQUIERE_SERIE' 
     AND ESTADO='Activo'
    ),
    SYSDATE,
    NULL,
    'apenaherrera',
    NULL,
    'Activo',
    NULL
  );

INSERT
INTO DB_COMERCIAL.INFO_PRODUCTO_IMPUESTO
  (
    ID_PRODUCTO_IMPUESTO,
    PRODUCTO_ID,
    IMPUESTO_ID,
    PORCENTAJE_IMPUESTO,
    FE_CREACION,
    USR_CREACION,
    FE_ULT_MOD,
    USR_ULT_MOD,
    ESTADO
  )
  VALUES
  (
    DB_COMERCIAL.SEQ_INFO_PRODUCTO_IMPUESTO.NEXTVAL,
    (
     SELECT ID_PRODUCTO
     FROM DB_COMERCIAL.ADMI_PRODUCTO 
     WHERE CODIGO_PRODUCTO='FOCO_LED'
     AND ESTADO='Activo'
    ),
    1,
    12,
    SYSDATE,
    'apenaherrera',
    NULL,
    NULL,
    'Activo'
  );
INSERT
INTO DB_COMERCIAL.ADMI_PRODUCTO
  (
    ID_PRODUCTO,
    EMPRESA_COD,
    CODIGO_PRODUCTO,
    DESCRIPCION_PRODUCTO,
    FUNCION_COSTO,
    FUNCION_PRECIO,
    INSTALACION,
    ESTADO,
    FE_CREACION,
    USR_CREACION,
    IP_CREACION,
    CTA_CONTABLE_PROD,
    CTA_CONTABLE_PROD_NC,
    ES_PREFERENCIA,
    ES_ENLACE,
    REQUIERE_PLANIFICACION,
    REQUIERE_INFO_TECNICA,
    NOMBRE_TECNICO,
    CTA_CONTABLE_DESC,
    TIPO,
    ES_CONCENTRADOR,
    SOPORTE_MASIVO,
    ESTADO_INICIAL,
    GRUPO,
    COMISION_VENTA,
    COMISION_MANTENIMIENTO,
    USR_GERENTE,
    CLASIFICACION,
    REQUIERE_COMISIONAR,
    SUBGRUPO,
    LINEA_NEGOCIO
  )
  VALUES
  (
   DB_COMERCIAL.SEQ_ADMI_PRODUCTO.NEXTVAL,
    '18',
    'CERR_ULT',
    'Cerradura de cerrojo Ultra-Inteligente',
    NULL,
    'PRECIO=259.99',
    0,
    'Activo',
    SYSDATE,
    'apenaherrera',
    '127.0.0.1',
    NULL,
    NULL,
    'NO',
    'NO',
    'SI',
    'NO',
    'NETHOME',
    NULL,
    'S',
    'NO',
    NULL,
    NULL,
    'NETHOME',
    NULL,
    NULL,
    NULL,
    NULL,
    'NO',
    NULL,
    NULL
  );

INSERT
INTO DB_COMERCIAL.ADMI_PRODUCTO_CARACTERISTICA
  (
    ID_PRODUCTO_CARACTERISITICA,
    PRODUCTO_ID,
    CARACTERISTICA_ID,
    FE_CREACION,
    FE_ULT_MOD,
    USR_CREACION,
    USR_ULT_MOD,
    ESTADO,
    VISIBLE_COMERCIAL
  )
  VALUES
  (
    DB_COMERCIAL.SEQ_ADMI_PRODUCTO_CARAC.NEXTVAL,
    (
     SELECT ID_PRODUCTO
     FROM DB_COMERCIAL.ADMI_PRODUCTO 
     WHERE CODIGO_PRODUCTO='CERR_ULT'
     AND ESTADO='Activo'
    ),
    (
     SELECT ID_CARACTERISTICA 
     FROM DB_COMERCIAL.ADMI_CARACTERISTICA 
     WHERE DESCRIPCION_CARACTERISTICA='FACTURACION_UNICA' 
     AND ESTADO='Activo'
    ),
    SYSDATE,
    NULL,
    'apenaherrera',
    NULL,
    'Activo',
    NULL
  );

INSERT
INTO DB_COMERCIAL.ADMI_PRODUCTO_CARACTERISTICA
  (
    ID_PRODUCTO_CARACTERISITICA,
    PRODUCTO_ID,
    CARACTERISTICA_ID,
    FE_CREACION,
    FE_ULT_MOD,
    USR_CREACION,
    USR_ULT_MOD,
    ESTADO,
    VISIBLE_COMERCIAL
  )
  VALUES
  (
    DB_COMERCIAL.SEQ_ADMI_PRODUCTO_CARAC.NEXTVAL,
    (
     SELECT ID_PRODUCTO
     FROM DB_COMERCIAL.ADMI_PRODUCTO 
     WHERE CODIGO_PRODUCTO='CERR_ULT'
     AND ESTADO='Activo'
    ),
    (
     SELECT ID_CARACTERISTICA 
     FROM DB_COMERCIAL.ADMI_CARACTERISTICA 
     WHERE DESCRIPCION_CARACTERISTICA='NETHOME' 
     AND ESTADO='Activo'
    ),
    SYSDATE,
    NULL,
    'apenaherrera',
    NULL,
    'Activo',
    NULL
  );

INSERT
INTO DB_COMERCIAL.ADMI_PRODUCTO_CARACTERISTICA
  (
    ID_PRODUCTO_CARACTERISITICA,
    PRODUCTO_ID,
    CARACTERISTICA_ID,
    FE_CREACION,
    FE_ULT_MOD,
    USR_CREACION,
    USR_ULT_MOD,
    ESTADO,
    VISIBLE_COMERCIAL
  )
  VALUES
  (
    DB_COMERCIAL.SEQ_ADMI_PRODUCTO_CARAC.NEXTVAL,
    (
     SELECT ID_PRODUCTO
     FROM DB_COMERCIAL.ADMI_PRODUCTO 
     WHERE CODIGO_PRODUCTO='CERR_ULT'
     AND ESTADO='Activo'
    ),
    (
     SELECT ID_CARACTERISTICA 
     FROM DB_COMERCIAL.ADMI_CARACTERISTICA 
     WHERE DESCRIPCION_CARACTERISTICA='CANTIDAD_NETHOME' 
     AND ESTADO='Activo'
    ),
    SYSDATE,
    NULL,
    'apenaherrera',
    NULL,
    'Activo',
    NULL
  );

INSERT
INTO DB_COMERCIAL.ADMI_PRODUCTO_CARACTERISTICA
  (
    ID_PRODUCTO_CARACTERISITICA,
    PRODUCTO_ID,
    CARACTERISTICA_ID,
    FE_CREACION,
    FE_ULT_MOD,
    USR_CREACION,
    USR_ULT_MOD,
    ESTADO,
    VISIBLE_COMERCIAL
  )
  VALUES
  (
    DB_COMERCIAL.SEQ_ADMI_PRODUCTO_CARAC.NEXTVAL,
    (
     SELECT ID_PRODUCTO
     FROM DB_COMERCIAL.ADMI_PRODUCTO 
     WHERE CODIGO_PRODUCTO='CERR_ULT'
     AND ESTADO='Activo'
    ),
    (
     SELECT ID_CARACTERISTICA 
     FROM DB_COMERCIAL.ADMI_CARACTERISTICA 
     WHERE DESCRIPCION_CARACTERISTICA='PRECIO_NETHOME' 
     AND ESTADO='Activo'
    ),
    SYSDATE,
    NULL,
    'apenaherrera',
    NULL,
    'Activo',
    NULL
  );

INSERT
INTO DB_COMERCIAL.ADMI_PRODUCTO_CARACTERISTICA
  (
    ID_PRODUCTO_CARACTERISITICA,
    PRODUCTO_ID,
    CARACTERISTICA_ID,
    FE_CREACION,
    FE_ULT_MOD,
    USR_CREACION,
    USR_ULT_MOD,
    ESTADO,
    VISIBLE_COMERCIAL
  )
  VALUES
  (
    DB_COMERCIAL.SEQ_ADMI_PRODUCTO_CARAC.NEXTVAL,
    (
     SELECT ID_PRODUCTO
     FROM DB_COMERCIAL.ADMI_PRODUCTO 
     WHERE CODIGO_PRODUCTO='CERR_ULT'
     AND ESTADO='Activo'
    ),
    (
     SELECT ID_CARACTERISTICA 
     FROM DB_COMERCIAL.ADMI_CARACTERISTICA 
     WHERE DESCRIPCION_CARACTERISTICA='VENDEDOR_NETHOME' 
     AND ESTADO='Activo'
    ),
    SYSDATE,
    NULL,
    'apenaherrera',
    NULL,
    'Activo',
    NULL
  );

INSERT
INTO DB_COMERCIAL.ADMI_PRODUCTO_CARACTERISTICA
  (
    ID_PRODUCTO_CARACTERISITICA,
    PRODUCTO_ID,
    CARACTERISTICA_ID,
    FE_CREACION,
    FE_ULT_MOD,
    USR_CREACION,
    USR_ULT_MOD,
    ESTADO,
    VISIBLE_COMERCIAL
  )
  VALUES
  (
    DB_COMERCIAL.SEQ_ADMI_PRODUCTO_CARAC.NEXTVAL,
    (
     SELECT ID_PRODUCTO
     FROM DB_COMERCIAL.ADMI_PRODUCTO 
     WHERE CODIGO_PRODUCTO='CERR_ULT'
     AND ESTADO='Activo'
    ),
    (
     SELECT ID_CARACTERISTICA 
     FROM DB_COMERCIAL.ADMI_CARACTERISTICA 
     WHERE DESCRIPCION_CARACTERISTICA='REQUIERE_SERIE' 
     AND ESTADO='Activo'
    ),
    SYSDATE,
    NULL,
    'apenaherrera',
    NULL,
    'Activo',
    NULL
  );

INSERT
INTO DB_COMERCIAL.INFO_PRODUCTO_IMPUESTO
  (
    ID_PRODUCTO_IMPUESTO,
    PRODUCTO_ID,
    IMPUESTO_ID,
    PORCENTAJE_IMPUESTO,
    FE_CREACION,
    USR_CREACION,
    FE_ULT_MOD,
    USR_ULT_MOD,
    ESTADO
  )
  VALUES
  (
    DB_COMERCIAL.SEQ_INFO_PRODUCTO_IMPUESTO.NEXTVAL,
    (
     SELECT ID_PRODUCTO
     FROM DB_COMERCIAL.ADMI_PRODUCTO 
     WHERE CODIGO_PRODUCTO='CERR_ULT'
     AND ESTADO='Activo'
    ),
    1,
    12,
    SYSDATE,
    'apenaherrera',
    NULL,
    NULL,
    'Activo'
  );

INSERT
INTO DB_COMERCIAL.ADMI_PRODUCTO
  (
    ID_PRODUCTO,
    EMPRESA_COD,
    CODIGO_PRODUCTO,
    DESCRIPCION_PRODUCTO,
    FUNCION_COSTO,
    FUNCION_PRECIO,
    INSTALACION,
    ESTADO,
    FE_CREACION,
    USR_CREACION,
    IP_CREACION,
    CTA_CONTABLE_PROD,
    CTA_CONTABLE_PROD_NC,
    ES_PREFERENCIA,
    ES_ENLACE,
    REQUIERE_PLANIFICACION,
    REQUIERE_INFO_TECNICA,
    NOMBRE_TECNICO,
    CTA_CONTABLE_DESC,
    TIPO,
    ES_CONCENTRADOR,
    SOPORTE_MASIVO,
    ESTADO_INICIAL,
    GRUPO,
    COMISION_VENTA,
    COMISION_MANTENIMIENTO,
    USR_GERENTE,
    CLASIFICACION,
    REQUIERE_COMISIONAR,
    SUBGRUPO,
    LINEA_NEGOCIO
  )
  VALUES
  (
   DB_COMERCIAL.SEQ_ADMI_PRODUCTO.NEXTVAL,
    '18',
    'REPET',
    'Repetidor',
    NULL,
    'PRECIO=29.99',
    0,
    'Activo',
    SYSDATE,
    'apenaherrera',
    '127.0.0.1',
    NULL,
    NULL,
    'NO',
    'NO',
    'SI',
    'NO',
    'NETHOME',
    NULL,
    'S',
    'NO',
    NULL,
    NULL,
    'NETHOME',
    NULL,
    NULL,
    NULL,
    NULL,
    'NO',
    NULL,
    NULL
  );

INSERT
INTO DB_COMERCIAL.ADMI_PRODUCTO_CARACTERISTICA
  (
    ID_PRODUCTO_CARACTERISITICA,
    PRODUCTO_ID,
    CARACTERISTICA_ID,
    FE_CREACION,
    FE_ULT_MOD,
    USR_CREACION,
    USR_ULT_MOD,
    ESTADO,
    VISIBLE_COMERCIAL
  )
  VALUES
  (
    DB_COMERCIAL.SEQ_ADMI_PRODUCTO_CARAC.NEXTVAL,
    (
     SELECT ID_PRODUCTO
     FROM DB_COMERCIAL.ADMI_PRODUCTO 
     WHERE CODIGO_PRODUCTO='REPET'
     AND ESTADO='Activo'
    ),
    (
     SELECT ID_CARACTERISTICA 
     FROM DB_COMERCIAL.ADMI_CARACTERISTICA 
     WHERE DESCRIPCION_CARACTERISTICA='FACTURACION_UNICA' 
     AND ESTADO='Activo'
    ),
    SYSDATE,
    NULL,
    'apenaherrera',
    NULL,
    'Activo',
    NULL
  );

INSERT
INTO DB_COMERCIAL.ADMI_PRODUCTO_CARACTERISTICA
  (
    ID_PRODUCTO_CARACTERISITICA,
    PRODUCTO_ID,
    CARACTERISTICA_ID,
    FE_CREACION,
    FE_ULT_MOD,
    USR_CREACION,
    USR_ULT_MOD,
    ESTADO,
    VISIBLE_COMERCIAL
  )
  VALUES
  (
    DB_COMERCIAL.SEQ_ADMI_PRODUCTO_CARAC.NEXTVAL,
    (
     SELECT ID_PRODUCTO
     FROM DB_COMERCIAL.ADMI_PRODUCTO 
     WHERE CODIGO_PRODUCTO='REPET'
     AND ESTADO='Activo'
    ),
    (
     SELECT ID_CARACTERISTICA 
     FROM DB_COMERCIAL.ADMI_CARACTERISTICA 
     WHERE DESCRIPCION_CARACTERISTICA='NETHOME' 
     AND ESTADO='Activo'
    ),
    SYSDATE,
    NULL,
    'apenaherrera',
    NULL,
    'Activo',
    NULL
  );

INSERT
INTO DB_COMERCIAL.ADMI_PRODUCTO_CARACTERISTICA
  (
    ID_PRODUCTO_CARACTERISITICA,
    PRODUCTO_ID,
    CARACTERISTICA_ID,
    FE_CREACION,
    FE_ULT_MOD,
    USR_CREACION,
    USR_ULT_MOD,
    ESTADO,
    VISIBLE_COMERCIAL
  )
  VALUES
  (
    DB_COMERCIAL.SEQ_ADMI_PRODUCTO_CARAC.NEXTVAL,
    (
     SELECT ID_PRODUCTO
     FROM DB_COMERCIAL.ADMI_PRODUCTO 
     WHERE CODIGO_PRODUCTO='REPET'
     AND ESTADO='Activo'
    ),
    (
     SELECT ID_CARACTERISTICA 
     FROM DB_COMERCIAL.ADMI_CARACTERISTICA 
     WHERE DESCRIPCION_CARACTERISTICA='CANTIDAD_NETHOME' 
     AND ESTADO='Activo'
    ),
    SYSDATE,
    NULL,
    'apenaherrera',
    NULL,
    'Activo',
    NULL
  );

INSERT
INTO DB_COMERCIAL.ADMI_PRODUCTO_CARACTERISTICA
  (
    ID_PRODUCTO_CARACTERISITICA,
    PRODUCTO_ID,
    CARACTERISTICA_ID,
    FE_CREACION,
    FE_ULT_MOD,
    USR_CREACION,
    USR_ULT_MOD,
    ESTADO,
    VISIBLE_COMERCIAL
  )
  VALUES
  (
    DB_COMERCIAL.SEQ_ADMI_PRODUCTO_CARAC.NEXTVAL,
    (
     SELECT ID_PRODUCTO
     FROM DB_COMERCIAL.ADMI_PRODUCTO 
     WHERE CODIGO_PRODUCTO='REPET'
     AND ESTADO='Activo'
    ),
    (
     SELECT ID_CARACTERISTICA 
     FROM DB_COMERCIAL.ADMI_CARACTERISTICA 
     WHERE DESCRIPCION_CARACTERISTICA='PRECIO_NETHOME' 
     AND ESTADO='Activo'
    ),
    SYSDATE,
    NULL,
    'apenaherrera',
    NULL,
    'Activo',
    NULL
  );

INSERT
INTO DB_COMERCIAL.ADMI_PRODUCTO_CARACTERISTICA
  (
    ID_PRODUCTO_CARACTERISITICA,
    PRODUCTO_ID,
    CARACTERISTICA_ID,
    FE_CREACION,
    FE_ULT_MOD,
    USR_CREACION,
    USR_ULT_MOD,
    ESTADO,
    VISIBLE_COMERCIAL
  )
  VALUES
  (
    DB_COMERCIAL.SEQ_ADMI_PRODUCTO_CARAC.NEXTVAL,
    (
     SELECT ID_PRODUCTO
     FROM DB_COMERCIAL.ADMI_PRODUCTO 
     WHERE CODIGO_PRODUCTO='REPET'
     AND ESTADO='Activo'
    ),
    (
     SELECT ID_CARACTERISTICA 
     FROM DB_COMERCIAL.ADMI_CARACTERISTICA 
     WHERE DESCRIPCION_CARACTERISTICA='VENDEDOR_NETHOME' 
     AND ESTADO='Activo'
    ),
    SYSDATE,
    NULL,
    'apenaherrera',
    NULL,
    'Activo',
    NULL
  );

INSERT
INTO DB_COMERCIAL.ADMI_PRODUCTO_CARACTERISTICA
  (
    ID_PRODUCTO_CARACTERISITICA,
    PRODUCTO_ID,
    CARACTERISTICA_ID,
    FE_CREACION,
    FE_ULT_MOD,
    USR_CREACION,
    USR_ULT_MOD,
    ESTADO,
    VISIBLE_COMERCIAL
  )
  VALUES
  (
    DB_COMERCIAL.SEQ_ADMI_PRODUCTO_CARAC.NEXTVAL,
    (
     SELECT ID_PRODUCTO
     FROM DB_COMERCIAL.ADMI_PRODUCTO 
     WHERE CODIGO_PRODUCTO='REPET'
     AND ESTADO='Activo'
    ),
    (
     SELECT ID_CARACTERISTICA 
     FROM DB_COMERCIAL.ADMI_CARACTERISTICA 
     WHERE DESCRIPCION_CARACTERISTICA='REQUIERE_SERIE' 
     AND ESTADO='Activo'
    ),
    SYSDATE,
    NULL,
    'apenaherrera',
    NULL,
    'Activo',
    NULL
  );

INSERT
INTO DB_COMERCIAL.INFO_PRODUCTO_IMPUESTO
  (
    ID_PRODUCTO_IMPUESTO,
    PRODUCTO_ID,
    IMPUESTO_ID,
    PORCENTAJE_IMPUESTO,
    FE_CREACION,
    USR_CREACION,
    FE_ULT_MOD,
    USR_ULT_MOD,
    ESTADO
  )
  VALUES
  (
    DB_COMERCIAL.SEQ_INFO_PRODUCTO_IMPUESTO.NEXTVAL,
    (
     SELECT ID_PRODUCTO
     FROM DB_COMERCIAL.ADMI_PRODUCTO 
     WHERE CODIGO_PRODUCTO='REPET'
     AND ESTADO='Activo'
    ),
    1,
    12,
    SYSDATE,
    'apenaherrera',
    NULL,
    NULL,
    'Activo'
  );

INSERT
INTO DB_COMERCIAL.ADMI_PRODUCTO
  (
    ID_PRODUCTO,
    EMPRESA_COD,
    CODIGO_PRODUCTO,
    DESCRIPCION_PRODUCTO,
    FUNCION_COSTO,
    FUNCION_PRECIO,
    INSTALACION,
    ESTADO,
    FE_CREACION,
    USR_CREACION,
    IP_CREACION,
    CTA_CONTABLE_PROD,
    CTA_CONTABLE_PROD_NC,
    ES_PREFERENCIA,
    ES_ENLACE,
    REQUIERE_PLANIFICACION,
    REQUIERE_INFO_TECNICA,
    NOMBRE_TECNICO,
    CTA_CONTABLE_DESC,
    TIPO,
    ES_CONCENTRADOR,
    SOPORTE_MASIVO,
    ESTADO_INICIAL,
    GRUPO,
    COMISION_VENTA,
    COMISION_MANTENIMIENTO,
    USR_GERENTE,
    CLASIFICACION,
    REQUIERE_COMISIONAR,
    SUBGRUPO,
    LINEA_NEGOCIO
  )
  VALUES
  (
   DB_COMERCIAL.SEQ_ADMI_PRODUCTO.NEXTVAL,
    '18',
    'CO_CORTI',
    'Controlador de cortinas/motores',
    NULL,
    'PRECIO=49.99',
    0,
    'Activo',
    SYSDATE,
    'apenaherrera',
    '127.0.0.1',
    NULL,
    NULL,
    'NO',
    'NO',
    'SI',
    'NO',
    'NETHOME',
    NULL,
    'S',
    'NO',
    NULL,
    NULL,
    'NETHOME',
    NULL,
    NULL,
    NULL,
    NULL,
    'NO',
    NULL,
    NULL
  );

INSERT
INTO DB_COMERCIAL.ADMI_PRODUCTO_CARACTERISTICA
  (
    ID_PRODUCTO_CARACTERISITICA,
    PRODUCTO_ID,
    CARACTERISTICA_ID,
    FE_CREACION,
    FE_ULT_MOD,
    USR_CREACION,
    USR_ULT_MOD,
    ESTADO,
    VISIBLE_COMERCIAL
  )
  VALUES
  (
    DB_COMERCIAL.SEQ_ADMI_PRODUCTO_CARAC.NEXTVAL,
    (
     SELECT ID_PRODUCTO
     FROM DB_COMERCIAL.ADMI_PRODUCTO 
     WHERE CODIGO_PRODUCTO='CO_CORTI'
     AND ESTADO='Activo'
    ),
    (
     SELECT ID_CARACTERISTICA 
     FROM DB_COMERCIAL.ADMI_CARACTERISTICA 
     WHERE DESCRIPCION_CARACTERISTICA='FACTURACION_UNICA' 
     AND ESTADO='Activo'
    ),
    SYSDATE,
    NULL,
    'apenaherrera',
    NULL,
    'Activo',
    NULL
  );

INSERT
INTO DB_COMERCIAL.ADMI_PRODUCTO_CARACTERISTICA
  (
    ID_PRODUCTO_CARACTERISITICA,
    PRODUCTO_ID,
    CARACTERISTICA_ID,
    FE_CREACION,
    FE_ULT_MOD,
    USR_CREACION,
    USR_ULT_MOD,
    ESTADO,
    VISIBLE_COMERCIAL
  )
  VALUES
  (
    DB_COMERCIAL.SEQ_ADMI_PRODUCTO_CARAC.NEXTVAL,
    (
     SELECT ID_PRODUCTO
     FROM DB_COMERCIAL.ADMI_PRODUCTO 
     WHERE CODIGO_PRODUCTO='CO_CORTI'
     AND ESTADO='Activo'
    ),
    (
     SELECT ID_CARACTERISTICA 
     FROM DB_COMERCIAL.ADMI_CARACTERISTICA 
     WHERE DESCRIPCION_CARACTERISTICA='NETHOME' 
     AND ESTADO='Activo'
    ),
    SYSDATE,
    NULL,
    'apenaherrera',
    NULL,
    'Activo',
    NULL
  );

INSERT
INTO DB_COMERCIAL.ADMI_PRODUCTO_CARACTERISTICA
  (
    ID_PRODUCTO_CARACTERISITICA,
    PRODUCTO_ID,
    CARACTERISTICA_ID,
    FE_CREACION,
    FE_ULT_MOD,
    USR_CREACION,
    USR_ULT_MOD,
    ESTADO,
    VISIBLE_COMERCIAL
  )
  VALUES
  (
    DB_COMERCIAL.SEQ_ADMI_PRODUCTO_CARAC.NEXTVAL,
    (
     SELECT ID_PRODUCTO
     FROM DB_COMERCIAL.ADMI_PRODUCTO 
     WHERE CODIGO_PRODUCTO='CO_CORTI'
     AND ESTADO='Activo'
    ),
    (
     SELECT ID_CARACTERISTICA 
     FROM DB_COMERCIAL.ADMI_CARACTERISTICA 
     WHERE DESCRIPCION_CARACTERISTICA='CANTIDAD_NETHOME' 
     AND ESTADO='Activo'
    ),
    SYSDATE,
    NULL,
    'apenaherrera',
    NULL,
    'Activo',
    NULL
  );

INSERT
INTO DB_COMERCIAL.ADMI_PRODUCTO_CARACTERISTICA
  (
    ID_PRODUCTO_CARACTERISITICA,
    PRODUCTO_ID,
    CARACTERISTICA_ID,
    FE_CREACION,
    FE_ULT_MOD,
    USR_CREACION,
    USR_ULT_MOD,
    ESTADO,
    VISIBLE_COMERCIAL
  )
  VALUES
  (
    DB_COMERCIAL.SEQ_ADMI_PRODUCTO_CARAC.NEXTVAL,
    (
     SELECT ID_PRODUCTO
     FROM DB_COMERCIAL.ADMI_PRODUCTO 
     WHERE CODIGO_PRODUCTO='CO_CORTI'
     AND ESTADO='Activo'
    ),
    (
     SELECT ID_CARACTERISTICA 
     FROM DB_COMERCIAL.ADMI_CARACTERISTICA 
     WHERE DESCRIPCION_CARACTERISTICA='PRECIO_NETHOME' 
     AND ESTADO='Activo'
    ),
    SYSDATE,
    NULL,
    'apenaherrera',
    NULL,
    'Activo',
    NULL
  );

INSERT
INTO DB_COMERCIAL.ADMI_PRODUCTO_CARACTERISTICA
  (
    ID_PRODUCTO_CARACTERISITICA,
    PRODUCTO_ID,
    CARACTERISTICA_ID,
    FE_CREACION,
    FE_ULT_MOD,
    USR_CREACION,
    USR_ULT_MOD,
    ESTADO,
    VISIBLE_COMERCIAL
  )
  VALUES
  (
    DB_COMERCIAL.SEQ_ADMI_PRODUCTO_CARAC.NEXTVAL,
    (
     SELECT ID_PRODUCTO
     FROM DB_COMERCIAL.ADMI_PRODUCTO 
     WHERE CODIGO_PRODUCTO='CO_CORTI'
     AND ESTADO='Activo'
    ),
    (
     SELECT ID_CARACTERISTICA 
     FROM DB_COMERCIAL.ADMI_CARACTERISTICA 
     WHERE DESCRIPCION_CARACTERISTICA='VENDEDOR_NETHOME' 
     AND ESTADO='Activo'
    ),
    SYSDATE,
    NULL,
    'apenaherrera',
    NULL,
    'Activo',
    NULL
  );

INSERT
INTO DB_COMERCIAL.ADMI_PRODUCTO_CARACTERISTICA
  (
    ID_PRODUCTO_CARACTERISITICA,
    PRODUCTO_ID,
    CARACTERISTICA_ID,
    FE_CREACION,
    FE_ULT_MOD,
    USR_CREACION,
    USR_ULT_MOD,
    ESTADO,
    VISIBLE_COMERCIAL
  )
  VALUES
  (
    DB_COMERCIAL.SEQ_ADMI_PRODUCTO_CARAC.NEXTVAL,
    (
     SELECT ID_PRODUCTO
     FROM DB_COMERCIAL.ADMI_PRODUCTO 
     WHERE CODIGO_PRODUCTO='CO_CORTI'
     AND ESTADO='Activo'
    ),
    (
     SELECT ID_CARACTERISTICA 
     FROM DB_COMERCIAL.ADMI_CARACTERISTICA 
     WHERE DESCRIPCION_CARACTERISTICA='REQUIERE_SERIE' 
     AND ESTADO='Activo'
    ),
    SYSDATE,
    NULL,
    'apenaherrera',
    NULL,
    'Activo',
    NULL
  );

INSERT
INTO DB_COMERCIAL.INFO_PRODUCTO_IMPUESTO
  (
    ID_PRODUCTO_IMPUESTO,
    PRODUCTO_ID,
    IMPUESTO_ID,
    PORCENTAJE_IMPUESTO,
    FE_CREACION,
    USR_CREACION,
    FE_ULT_MOD,
    USR_ULT_MOD,
    ESTADO
  )
  VALUES
  (
    DB_COMERCIAL.SEQ_INFO_PRODUCTO_IMPUESTO.NEXTVAL,
    (
     SELECT ID_PRODUCTO
     FROM DB_COMERCIAL.ADMI_PRODUCTO 
     WHERE CODIGO_PRODUCTO='CO_CORTI'
     AND ESTADO='Activo'
    ),
    1,
    12,
    SYSDATE,
    'apenaherrera',
    NULL,
    NULL,
    'Activo'
  );

INSERT
INTO DB_COMERCIAL.ADMI_PRODUCTO
  (
    ID_PRODUCTO,
    EMPRESA_COD,
    CODIGO_PRODUCTO,
    DESCRIPCION_PRODUCTO,
    FUNCION_COSTO,
    FUNCION_PRECIO,
    INSTALACION,
    ESTADO,
    FE_CREACION,
    USR_CREACION,
    IP_CREACION,
    CTA_CONTABLE_PROD,
    CTA_CONTABLE_PROD_NC,
    ES_PREFERENCIA,
    ES_ENLACE,
    REQUIERE_PLANIFICACION,
    REQUIERE_INFO_TECNICA,
    NOMBRE_TECNICO,
    CTA_CONTABLE_DESC,
    TIPO,
    ES_CONCENTRADOR,
    SOPORTE_MASIVO,
    ESTADO_INICIAL,
    GRUPO,
    COMISION_VENTA,
    COMISION_MANTENIMIENTO,
    USR_GERENTE,
    CLASIFICACION,
    REQUIERE_COMISIONAR,
    SUBGRUPO,
    LINEA_NEGOCIO
  )
  VALUES
  (
   DB_COMERCIAL.SEQ_ADMI_PRODUCTO.NEXTVAL,
    '18',
    'CO_AC',
    'Controlador Aire Acondicionado central',
    NULL,
    'PRECIO=219.99',
    0,
    'Activo',
    SYSDATE,
    'apenaherrera',
    '127.0.0.1',
    NULL,
    NULL,
    'NO',
    'NO',
    'SI',
    'NO',
    'NETHOME',
    NULL,
    'S',
    'NO',
    NULL,
    NULL,
    'NETHOME',
    NULL,
    NULL,
    NULL,
    NULL,
    'NO',
    NULL,
    NULL
  );

INSERT
INTO DB_COMERCIAL.ADMI_PRODUCTO_CARACTERISTICA
  (
    ID_PRODUCTO_CARACTERISITICA,
    PRODUCTO_ID,
    CARACTERISTICA_ID,
    FE_CREACION,
    FE_ULT_MOD,
    USR_CREACION,
    USR_ULT_MOD,
    ESTADO,
    VISIBLE_COMERCIAL
  )
  VALUES
  (
    DB_COMERCIAL.SEQ_ADMI_PRODUCTO_CARAC.NEXTVAL,
    (
     SELECT ID_PRODUCTO
     FROM DB_COMERCIAL.ADMI_PRODUCTO 
     WHERE CODIGO_PRODUCTO='CO_AC'
     AND ESTADO='Activo'
    ),
    (
     SELECT ID_CARACTERISTICA 
     FROM DB_COMERCIAL.ADMI_CARACTERISTICA 
     WHERE DESCRIPCION_CARACTERISTICA='FACTURACION_UNICA' 
     AND ESTADO='Activo'
    ),
    SYSDATE,
    NULL,
    'apenaherrera',
    NULL,
    'Activo',
    NULL
  );

INSERT
INTO DB_COMERCIAL.ADMI_PRODUCTO_CARACTERISTICA
  (
    ID_PRODUCTO_CARACTERISITICA,
    PRODUCTO_ID,
    CARACTERISTICA_ID,
    FE_CREACION,
    FE_ULT_MOD,
    USR_CREACION,
    USR_ULT_MOD,
    ESTADO,
    VISIBLE_COMERCIAL
  )
  VALUES
  (
    DB_COMERCIAL.SEQ_ADMI_PRODUCTO_CARAC.NEXTVAL,
    (
     SELECT ID_PRODUCTO
     FROM DB_COMERCIAL.ADMI_PRODUCTO 
     WHERE CODIGO_PRODUCTO='CO_AC'
     AND ESTADO='Activo'
    ),
    (
     SELECT ID_CARACTERISTICA 
     FROM DB_COMERCIAL.ADMI_CARACTERISTICA 
     WHERE DESCRIPCION_CARACTERISTICA='NETHOME' 
     AND ESTADO='Activo'
    ),
    SYSDATE,
    NULL,
    'apenaherrera',
    NULL,
    'Activo',
    NULL
  );

INSERT
INTO DB_COMERCIAL.ADMI_PRODUCTO_CARACTERISTICA
  (
    ID_PRODUCTO_CARACTERISITICA,
    PRODUCTO_ID,
    CARACTERISTICA_ID,
    FE_CREACION,
    FE_ULT_MOD,
    USR_CREACION,
    USR_ULT_MOD,
    ESTADO,
    VISIBLE_COMERCIAL
  )
  VALUES
  (
    DB_COMERCIAL.SEQ_ADMI_PRODUCTO_CARAC.NEXTVAL,
    (
     SELECT ID_PRODUCTO
     FROM DB_COMERCIAL.ADMI_PRODUCTO 
     WHERE CODIGO_PRODUCTO='CO_AC'
     AND ESTADO='Activo'
    ),
    (
     SELECT ID_CARACTERISTICA 
     FROM DB_COMERCIAL.ADMI_CARACTERISTICA 
     WHERE DESCRIPCION_CARACTERISTICA='CANTIDAD_NETHOME' 
     AND ESTADO='Activo'
    ),
    SYSDATE,
    NULL,
    'apenaherrera',
    NULL,
    'Activo',
    NULL
  );

INSERT
INTO DB_COMERCIAL.ADMI_PRODUCTO_CARACTERISTICA
  (
    ID_PRODUCTO_CARACTERISITICA,
    PRODUCTO_ID,
    CARACTERISTICA_ID,
    FE_CREACION,
    FE_ULT_MOD,
    USR_CREACION,
    USR_ULT_MOD,
    ESTADO,
    VISIBLE_COMERCIAL
  )
  VALUES
  (
    DB_COMERCIAL.SEQ_ADMI_PRODUCTO_CARAC.NEXTVAL,
    (
     SELECT ID_PRODUCTO
     FROM DB_COMERCIAL.ADMI_PRODUCTO 
     WHERE CODIGO_PRODUCTO='CO_AC'
     AND ESTADO='Activo'
    ),
    (
     SELECT ID_CARACTERISTICA 
     FROM DB_COMERCIAL.ADMI_CARACTERISTICA 
     WHERE DESCRIPCION_CARACTERISTICA='PRECIO_NETHOME' 
     AND ESTADO='Activo'
    ),
    SYSDATE,
    NULL,
    'apenaherrera',
    NULL,
    'Activo',
    NULL
  );

INSERT
INTO DB_COMERCIAL.ADMI_PRODUCTO_CARACTERISTICA
  (
    ID_PRODUCTO_CARACTERISITICA,
    PRODUCTO_ID,
    CARACTERISTICA_ID,
    FE_CREACION,
    FE_ULT_MOD,
    USR_CREACION,
    USR_ULT_MOD,
    ESTADO,
    VISIBLE_COMERCIAL
  )
  VALUES
  (
    DB_COMERCIAL.SEQ_ADMI_PRODUCTO_CARAC.NEXTVAL,
    (
     SELECT ID_PRODUCTO
     FROM DB_COMERCIAL.ADMI_PRODUCTO 
     WHERE CODIGO_PRODUCTO='CO_AC'
     AND ESTADO='Activo'
    ),
    (
     SELECT ID_CARACTERISTICA 
     FROM DB_COMERCIAL.ADMI_CARACTERISTICA 
     WHERE DESCRIPCION_CARACTERISTICA='VENDEDOR_NETHOME' 
     AND ESTADO='Activo'
    ),
    SYSDATE,
    NULL,
    'apenaherrera',
    NULL,
    'Activo',
    NULL
  );

INSERT
INTO DB_COMERCIAL.ADMI_PRODUCTO_CARACTERISTICA
  (
    ID_PRODUCTO_CARACTERISITICA,
    PRODUCTO_ID,
    CARACTERISTICA_ID,
    FE_CREACION,
    FE_ULT_MOD,
    USR_CREACION,
    USR_ULT_MOD,
    ESTADO,
    VISIBLE_COMERCIAL
  )
  VALUES
  (
    DB_COMERCIAL.SEQ_ADMI_PRODUCTO_CARAC.NEXTVAL,
    (
     SELECT ID_PRODUCTO
     FROM DB_COMERCIAL.ADMI_PRODUCTO 
     WHERE CODIGO_PRODUCTO='CO_AC'
     AND ESTADO='Activo'
    ),
    (
     SELECT ID_CARACTERISTICA 
     FROM DB_COMERCIAL.ADMI_CARACTERISTICA 
     WHERE DESCRIPCION_CARACTERISTICA='REQUIERE_SERIE' 
     AND ESTADO='Activo'
    ),
    SYSDATE,
    NULL,
    'apenaherrera',
    NULL,
    'Activo',
    NULL
  );

INSERT
INTO DB_COMERCIAL.INFO_PRODUCTO_IMPUESTO
  (
    ID_PRODUCTO_IMPUESTO,
    PRODUCTO_ID,
    IMPUESTO_ID,
    PORCENTAJE_IMPUESTO,
    FE_CREACION,
    USR_CREACION,
    FE_ULT_MOD,
    USR_ULT_MOD,
    ESTADO
  )
  VALUES
  (
    DB_COMERCIAL.SEQ_INFO_PRODUCTO_IMPUESTO.NEXTVAL,
    (
     SELECT ID_PRODUCTO
     FROM DB_COMERCIAL.ADMI_PRODUCTO 
     WHERE CODIGO_PRODUCTO='CO_AC'
     AND ESTADO='Activo'
    ),
    1,
    12,
    SYSDATE,
    'apenaherrera',
    NULL,
    NULL,
    'Activo'
  );

INSERT
INTO DB_COMERCIAL.ADMI_PRODUCTO
  (
    ID_PRODUCTO,
    EMPRESA_COD,
    CODIGO_PRODUCTO,
    DESCRIPCION_PRODUCTO,
    FUNCION_COSTO,
    FUNCION_PRECIO,
    INSTALACION,
    ESTADO,
    FE_CREACION,
    USR_CREACION,
    IP_CREACION,
    CTA_CONTABLE_PROD,
    CTA_CONTABLE_PROD_NC,
    ES_PREFERENCIA,
    ES_ENLACE,
    REQUIERE_PLANIFICACION,
    REQUIERE_INFO_TECNICA,
    NOMBRE_TECNICO,
    CTA_CONTABLE_DESC,
    TIPO,
    ES_CONCENTRADOR,
    SOPORTE_MASIVO,
    ESTADO_INICIAL,
    GRUPO,
    COMISION_VENTA,
    COMISION_MANTENIMIENTO,
    USR_GERENTE,
    CLASIFICACION,
    REQUIERE_COMISIONAR,
    SUBGRUPO,
    LINEA_NEGOCIO
  )
  VALUES
  (
   DB_COMERCIAL.SEQ_ADMI_PRODUCTO.NEXTVAL,
    '18',
    'CO_DISP',
    'Controlador de dispositivos de alto consumo hasta 40A',
    NULL,
    'PRECIO=99.99',
    0,
    'Activo',
    SYSDATE,
    'apenaherrera',
    '127.0.0.1',
    NULL,
    NULL,
    'NO',
    'NO',
    'SI',
    'NO',
    'NETHOME',
    NULL,
    'S',
    'NO',
    NULL,
    NULL,
    'NETHOME',
    NULL,
    NULL,
    NULL,
    NULL,
    'NO',
    NULL,
    NULL
  );

INSERT
INTO DB_COMERCIAL.ADMI_PRODUCTO_CARACTERISTICA
  (
    ID_PRODUCTO_CARACTERISITICA,
    PRODUCTO_ID,
    CARACTERISTICA_ID,
    FE_CREACION,
    FE_ULT_MOD,
    USR_CREACION,
    USR_ULT_MOD,
    ESTADO,
    VISIBLE_COMERCIAL
  )
  VALUES
  (
    DB_COMERCIAL.SEQ_ADMI_PRODUCTO_CARAC.NEXTVAL,
    (
     SELECT ID_PRODUCTO
     FROM DB_COMERCIAL.ADMI_PRODUCTO 
     WHERE CODIGO_PRODUCTO='CO_DISP'
     AND ESTADO='Activo'
    ),
    (
     SELECT ID_CARACTERISTICA 
     FROM DB_COMERCIAL.ADMI_CARACTERISTICA 
     WHERE DESCRIPCION_CARACTERISTICA='FACTURACION_UNICA' 
     AND ESTADO='Activo'
    ),
    SYSDATE,
    NULL,
    'apenaherrera',
    NULL,
    'Activo',
    NULL
  );

INSERT
INTO DB_COMERCIAL.ADMI_PRODUCTO_CARACTERISTICA
  (
    ID_PRODUCTO_CARACTERISITICA,
    PRODUCTO_ID,
    CARACTERISTICA_ID,
    FE_CREACION,
    FE_ULT_MOD,
    USR_CREACION,
    USR_ULT_MOD,
    ESTADO,
    VISIBLE_COMERCIAL
  )
  VALUES
  (
    DB_COMERCIAL.SEQ_ADMI_PRODUCTO_CARAC.NEXTVAL,
    (
     SELECT ID_PRODUCTO
     FROM DB_COMERCIAL.ADMI_PRODUCTO 
     WHERE CODIGO_PRODUCTO='CO_DISP'
     AND ESTADO='Activo'
    ),
    (
     SELECT ID_CARACTERISTICA 
     FROM DB_COMERCIAL.ADMI_CARACTERISTICA 
     WHERE DESCRIPCION_CARACTERISTICA='NETHOME' 
     AND ESTADO='Activo'
    ),
    SYSDATE,
    NULL,
    'apenaherrera',
    NULL,
    'Activo',
    NULL
  );

INSERT
INTO DB_COMERCIAL.ADMI_PRODUCTO_CARACTERISTICA
  (
    ID_PRODUCTO_CARACTERISITICA,
    PRODUCTO_ID,
    CARACTERISTICA_ID,
    FE_CREACION,
    FE_ULT_MOD,
    USR_CREACION,
    USR_ULT_MOD,
    ESTADO,
    VISIBLE_COMERCIAL
  )
  VALUES
  (
    DB_COMERCIAL.SEQ_ADMI_PRODUCTO_CARAC.NEXTVAL,
    (
     SELECT ID_PRODUCTO
     FROM DB_COMERCIAL.ADMI_PRODUCTO 
     WHERE CODIGO_PRODUCTO='CO_DISP'
     AND ESTADO='Activo'
    ),
    (
     SELECT ID_CARACTERISTICA 
     FROM DB_COMERCIAL.ADMI_CARACTERISTICA 
     WHERE DESCRIPCION_CARACTERISTICA='CANTIDAD_NETHOME' 
     AND ESTADO='Activo'
    ),
    SYSDATE,
    NULL,
    'apenaherrera',
    NULL,
    'Activo',
    NULL
  );

INSERT
INTO DB_COMERCIAL.ADMI_PRODUCTO_CARACTERISTICA
  (
    ID_PRODUCTO_CARACTERISITICA,
    PRODUCTO_ID,
    CARACTERISTICA_ID,
    FE_CREACION,
    FE_ULT_MOD,
    USR_CREACION,
    USR_ULT_MOD,
    ESTADO,
    VISIBLE_COMERCIAL
  )
  VALUES
  (
    DB_COMERCIAL.SEQ_ADMI_PRODUCTO_CARAC.NEXTVAL,
    (
     SELECT ID_PRODUCTO
     FROM DB_COMERCIAL.ADMI_PRODUCTO 
     WHERE CODIGO_PRODUCTO='CO_DISP'
     AND ESTADO='Activo'
    ),
    (
     SELECT ID_CARACTERISTICA 
     FROM DB_COMERCIAL.ADMI_CARACTERISTICA 
     WHERE DESCRIPCION_CARACTERISTICA='PRECIO_NETHOME' 
     AND ESTADO='Activo'
    ),
    SYSDATE,
    NULL,
    'apenaherrera',
    NULL,
    'Activo',
    NULL
  );

INSERT
INTO DB_COMERCIAL.ADMI_PRODUCTO_CARACTERISTICA
  (
    ID_PRODUCTO_CARACTERISITICA,
    PRODUCTO_ID,
    CARACTERISTICA_ID,
    FE_CREACION,
    FE_ULT_MOD,
    USR_CREACION,
    USR_ULT_MOD,
    ESTADO,
    VISIBLE_COMERCIAL
  )
  VALUES
  (
    DB_COMERCIAL.SEQ_ADMI_PRODUCTO_CARAC.NEXTVAL,
    (
     SELECT ID_PRODUCTO
     FROM DB_COMERCIAL.ADMI_PRODUCTO 
     WHERE CODIGO_PRODUCTO='CO_DISP'
     AND ESTADO='Activo'
    ),
    (
     SELECT ID_CARACTERISTICA 
     FROM DB_COMERCIAL.ADMI_CARACTERISTICA 
     WHERE DESCRIPCION_CARACTERISTICA='VENDEDOR_NETHOME' 
     AND ESTADO='Activo'
    ),
    SYSDATE,
    NULL,
    'apenaherrera',
    NULL,
    'Activo',
    NULL
  );

INSERT
INTO DB_COMERCIAL.ADMI_PRODUCTO_CARACTERISTICA
  (
    ID_PRODUCTO_CARACTERISITICA,
    PRODUCTO_ID,
    CARACTERISTICA_ID,
    FE_CREACION,
    FE_ULT_MOD,
    USR_CREACION,
    USR_ULT_MOD,
    ESTADO,
    VISIBLE_COMERCIAL
  )
  VALUES
  (
    DB_COMERCIAL.SEQ_ADMI_PRODUCTO_CARAC.NEXTVAL,
    (
     SELECT ID_PRODUCTO
     FROM DB_COMERCIAL.ADMI_PRODUCTO 
     WHERE CODIGO_PRODUCTO='CO_DISP'
     AND ESTADO='Activo'
    ),
    (
     SELECT ID_CARACTERISTICA 
     FROM DB_COMERCIAL.ADMI_CARACTERISTICA 
     WHERE DESCRIPCION_CARACTERISTICA='REQUIERE_SERIE' 
     AND ESTADO='Activo'
    ),
    SYSDATE,
    NULL,
    'apenaherrera',
    NULL,
    'Activo',
    NULL
  );

INSERT
INTO DB_COMERCIAL.INFO_PRODUCTO_IMPUESTO
  (
    ID_PRODUCTO_IMPUESTO,
    PRODUCTO_ID,
    IMPUESTO_ID,
    PORCENTAJE_IMPUESTO,
    FE_CREACION,
    USR_CREACION,
    FE_ULT_MOD,
    USR_ULT_MOD,
    ESTADO
  )
  VALUES
  (
    DB_COMERCIAL.SEQ_INFO_PRODUCTO_IMPUESTO.NEXTVAL,
    (
     SELECT ID_PRODUCTO
     FROM DB_COMERCIAL.ADMI_PRODUCTO 
     WHERE CODIGO_PRODUCTO='CO_DISP'
     AND ESTADO='Activo'
    ),
    1,
    12,
    SYSDATE,
    'apenaherrera',
    NULL,
    NULL,
    'Activo'
  );

INSERT
INTO DB_COMERCIAL.ADMI_PRODUCTO
  (
    ID_PRODUCTO,
    EMPRESA_COD,
    CODIGO_PRODUCTO,
    DESCRIPCION_PRODUCTO,
    FUNCION_COSTO,
    FUNCION_PRECIO,
    INSTALACION,
    ESTADO,
    FE_CREACION,
    USR_CREACION,
    IP_CREACION,
    CTA_CONTABLE_PROD,
    CTA_CONTABLE_PROD_NC,
    ES_PREFERENCIA,
    ES_ENLACE,
    REQUIERE_PLANIFICACION,
    REQUIERE_INFO_TECNICA,
    NOMBRE_TECNICO,
    CTA_CONTABLE_DESC,
    TIPO,
    ES_CONCENTRADOR,
    SOPORTE_MASIVO,
    ESTADO_INICIAL,
    GRUPO,
    COMISION_VENTA,
    COMISION_MANTENIMIENTO,
    USR_GERENTE,
    CLASIFICACION,
    REQUIERE_COMISIONAR,
    SUBGRUPO,
    LINEA_NEGOCIO
  )
  VALUES
  (
   DB_COMERCIAL.SEQ_ADMI_PRODUCTO.NEXTVAL,
    '18',
    'SIR_CONF',
    'Sirena de hasta 105dB Configurable',
    NULL,
    'PRECIO=44.99',
    0,
    'Activo',
    SYSDATE,
    'apenaherrera',
    '127.0.0.1',
    NULL,
    NULL,
    'NO',
    'NO',
    'SI',
    'NO',
    'NETHOME',
    NULL,
    'S',
    'NO',
    NULL,
    NULL,
    'NETHOME',
    NULL,
    NULL,
    NULL,
    NULL,
    'NO',
    NULL,
    NULL
  );

INSERT
INTO DB_COMERCIAL.ADMI_PRODUCTO_CARACTERISTICA
  (
    ID_PRODUCTO_CARACTERISITICA,
    PRODUCTO_ID,
    CARACTERISTICA_ID,
    FE_CREACION,
    FE_ULT_MOD,
    USR_CREACION,
    USR_ULT_MOD,
    ESTADO,
    VISIBLE_COMERCIAL
  )
  VALUES
  (
    DB_COMERCIAL.SEQ_ADMI_PRODUCTO_CARAC.NEXTVAL,
    (
     SELECT ID_PRODUCTO
     FROM DB_COMERCIAL.ADMI_PRODUCTO 
     WHERE CODIGO_PRODUCTO='SIR_CONF'
     AND ESTADO='Activo'
    ),
    (
     SELECT ID_CARACTERISTICA 
     FROM DB_COMERCIAL.ADMI_CARACTERISTICA 
     WHERE DESCRIPCION_CARACTERISTICA='FACTURACION_UNICA' 
     AND ESTADO='Activo'
    ),
    SYSDATE,
    NULL,
    'apenaherrera',
    NULL,
    'Activo',
    NULL
  );

INSERT
INTO DB_COMERCIAL.ADMI_PRODUCTO_CARACTERISTICA
  (
    ID_PRODUCTO_CARACTERISITICA,
    PRODUCTO_ID,
    CARACTERISTICA_ID,
    FE_CREACION,
    FE_ULT_MOD,
    USR_CREACION,
    USR_ULT_MOD,
    ESTADO,
    VISIBLE_COMERCIAL
  )
  VALUES
  (
    DB_COMERCIAL.SEQ_ADMI_PRODUCTO_CARAC.NEXTVAL,
    (
     SELECT ID_PRODUCTO
     FROM DB_COMERCIAL.ADMI_PRODUCTO 
     WHERE CODIGO_PRODUCTO='SIR_CONF'
     AND ESTADO='Activo'
    ),
    (
     SELECT ID_CARACTERISTICA 
     FROM DB_COMERCIAL.ADMI_CARACTERISTICA 
     WHERE DESCRIPCION_CARACTERISTICA='NETHOME' 
     AND ESTADO='Activo'
    ),
    SYSDATE,
    NULL,
    'apenaherrera',
    NULL,
    'Activo',
    NULL
  );

INSERT
INTO DB_COMERCIAL.ADMI_PRODUCTO_CARACTERISTICA
  (
    ID_PRODUCTO_CARACTERISITICA,
    PRODUCTO_ID,
    CARACTERISTICA_ID,
    FE_CREACION,
    FE_ULT_MOD,
    USR_CREACION,
    USR_ULT_MOD,
    ESTADO,
    VISIBLE_COMERCIAL
  )
  VALUES
  (
    DB_COMERCIAL.SEQ_ADMI_PRODUCTO_CARAC.NEXTVAL,
    (
     SELECT ID_PRODUCTO
     FROM DB_COMERCIAL.ADMI_PRODUCTO 
     WHERE CODIGO_PRODUCTO='SIR_CONF'
     AND ESTADO='Activo'
    ),
    (
     SELECT ID_CARACTERISTICA 
     FROM DB_COMERCIAL.ADMI_CARACTERISTICA 
     WHERE DESCRIPCION_CARACTERISTICA='CANTIDAD_NETHOME' 
     AND ESTADO='Activo'
    ),
    SYSDATE,
    NULL,
    'apenaherrera',
    NULL,
    'Activo',
    NULL
  );

INSERT
INTO DB_COMERCIAL.ADMI_PRODUCTO_CARACTERISTICA
  (
    ID_PRODUCTO_CARACTERISITICA,
    PRODUCTO_ID,
    CARACTERISTICA_ID,
    FE_CREACION,
    FE_ULT_MOD,
    USR_CREACION,
    USR_ULT_MOD,
    ESTADO,
    VISIBLE_COMERCIAL
  )
  VALUES
  (
    DB_COMERCIAL.SEQ_ADMI_PRODUCTO_CARAC.NEXTVAL,
    (
     SELECT ID_PRODUCTO
     FROM DB_COMERCIAL.ADMI_PRODUCTO 
     WHERE CODIGO_PRODUCTO='SIR_CONF'
     AND ESTADO='Activo'
    ),
    (
     SELECT ID_CARACTERISTICA 
     FROM DB_COMERCIAL.ADMI_CARACTERISTICA 
     WHERE DESCRIPCION_CARACTERISTICA='PRECIO_NETHOME' 
     AND ESTADO='Activo'
    ),
    SYSDATE,
    NULL,
    'apenaherrera',
    NULL,
    'Activo',
    NULL
  );

INSERT
INTO DB_COMERCIAL.ADMI_PRODUCTO_CARACTERISTICA
  (
    ID_PRODUCTO_CARACTERISITICA,
    PRODUCTO_ID,
    CARACTERISTICA_ID,
    FE_CREACION,
    FE_ULT_MOD,
    USR_CREACION,
    USR_ULT_MOD,
    ESTADO,
    VISIBLE_COMERCIAL
  )
  VALUES
  (
    DB_COMERCIAL.SEQ_ADMI_PRODUCTO_CARAC.NEXTVAL,
    (
     SELECT ID_PRODUCTO
     FROM DB_COMERCIAL.ADMI_PRODUCTO 
     WHERE CODIGO_PRODUCTO='SIR_CONF'
     AND ESTADO='Activo'
    ),
    (
     SELECT ID_CARACTERISTICA 
     FROM DB_COMERCIAL.ADMI_CARACTERISTICA 
     WHERE DESCRIPCION_CARACTERISTICA='VENDEDOR_NETHOME' 
     AND ESTADO='Activo'
    ),
    SYSDATE,
    NULL,
    'apenaherrera',
    NULL,
    'Activo',
    NULL
  );

INSERT
INTO DB_COMERCIAL.ADMI_PRODUCTO_CARACTERISTICA
  (
    ID_PRODUCTO_CARACTERISITICA,
    PRODUCTO_ID,
    CARACTERISTICA_ID,
    FE_CREACION,
    FE_ULT_MOD,
    USR_CREACION,
    USR_ULT_MOD,
    ESTADO,
    VISIBLE_COMERCIAL
  )
  VALUES
  (
    DB_COMERCIAL.SEQ_ADMI_PRODUCTO_CARAC.NEXTVAL,
    (
     SELECT ID_PRODUCTO
     FROM DB_COMERCIAL.ADMI_PRODUCTO 
     WHERE CODIGO_PRODUCTO='SIR_CONF'
     AND ESTADO='Activo'
    ),
    (
     SELECT ID_CARACTERISTICA 
     FROM DB_COMERCIAL.ADMI_CARACTERISTICA 
     WHERE DESCRIPCION_CARACTERISTICA='REQUIERE_SERIE' 
     AND ESTADO='Activo'
    ),
    SYSDATE,
    NULL,
    'apenaherrera',
    NULL,
    'Activo',
    NULL
  );

INSERT
INTO DB_COMERCIAL.INFO_PRODUCTO_IMPUESTO
  (
    ID_PRODUCTO_IMPUESTO,
    PRODUCTO_ID,
    IMPUESTO_ID,
    PORCENTAJE_IMPUESTO,
    FE_CREACION,
    USR_CREACION,
    FE_ULT_MOD,
    USR_ULT_MOD,
    ESTADO
  )
  VALUES
  (
    DB_COMERCIAL.SEQ_INFO_PRODUCTO_IMPUESTO.NEXTVAL,
    (
     SELECT ID_PRODUCTO
     FROM DB_COMERCIAL.ADMI_PRODUCTO 
     WHERE CODIGO_PRODUCTO='SIR_CONF'
     AND ESTADO='Activo'
    ),
    1,
    12,
    SYSDATE,
    'apenaherrera',
    NULL,
    NULL,
    'Activo'
  );

INSERT
INTO DB_GENERAL.ADMI_PARAMETRO_DET
  (
    ID_PARAMETRO_DET,
    PARAMETRO_ID,
    DESCRIPCION,
    VALOR1,
    VALOR2,
    VALOR3,
    VALOR4,
    ESTADO,
    USR_CREACION,
    FE_CREACION,
    IP_CREACION,
    USR_ULT_MOD,
    FE_ULT_MOD,
    IP_ULT_MOD,
    VALOR5,
    EMPRESA_COD,
    OBSERVACION
  )
  VALUES
  (
    DB_GENERAL.SEQ_ADMI_PARAMETRO_DET.NEXTVAL,
    (
      SELECT ID_PARAMETRO
      FROM DB_GENERAL.ADMI_PARAMETRO_CAB
      WHERE NOMBRE_PARAMETRO = 'INFO_SERVICIO'
      AND PROCESO            = 'ACTIVACION_SERVICIO'
      AND ESTADO             = 'Activo'
    ),
    'ESTADOS PERMITIDOS DEL SERVICIO DE INTERNET PARA EL FLUJO DE NETHOME',
    'ESTADOS_INTERNET_NETHOME',
    'Activo',
    'NULL',
    'NULL',
    'Activo',
    'apenaherrera',
    SYSDATE,
    '127.0.0.1',
    NULL,
    NULL,
    NULL,
    NULL,
    '18',
    'CONTIENE VALOR1: ESTADOS_INTERNET_NETHOME (DEFINE QUE ESTADOS SERAN CONSIDERADOS 
     PARA VALIDAR EL SERVICIO DE INTERNET EXISTENTE PARA LA CONTRATACION DEL PRODUCTO NETHOME)
     VALOR2: CONTIENE EL ESTADO PERMITIDO PARA EL SERVICIO DE INTERNET (INFO_SERVICIO)'
  );

INSERT
INTO DB_GENERAL.ADMI_PARAMETRO_DET
  (
    ID_PARAMETRO_DET,
    PARAMETRO_ID,
    DESCRIPCION,
    VALOR1,
    VALOR2,
    VALOR3,
    VALOR4,
    ESTADO,
    USR_CREACION,
    FE_CREACION,
    IP_CREACION,
    USR_ULT_MOD,
    FE_ULT_MOD,
    IP_ULT_MOD,
    VALOR5,
    EMPRESA_COD,
    OBSERVACION
  )
  VALUES
  (
    DB_GENERAL.SEQ_ADMI_PARAMETRO_DET.NEXTVAL,
    (
      SELECT ID_PARAMETRO
      FROM DB_GENERAL.ADMI_PARAMETRO_CAB
      WHERE NOMBRE_PARAMETRO = 'INFO_SERVICIO'
      AND PROCESO            = 'ACTIVACION_SERVICIO'
      AND ESTADO             = 'Activo'
    ),
    'ULTIMAS MILLAS PERMITIDAS DEL SERVICIO DE INTERNET PARA EL FLUJO DE NETHOME',
    'ULTIMAS_MILLAS_INTERNET_NETHOME',
    '1',
    'Fibra Optica',
    'NULL',
    'Activo',
    'apenaherrera',
    SYSDATE,
    '127.0.0.1',
    NULL,
    NULL,
    NULL,
    'NULL',
    '18',
    'CONTIENE VALOR1: ULTIMAS_MILLAS_INTERNET_NETHOME(DEFINE LAS ULTIMAS MILLAS PERMITIDAS PARA EL SERVICIO DE INTERNET PARA 
    EL FLUJO DE CONTRATACION DEL PRODUCTO NETHOME)
    VALOR2: ID_TIPO_MEDIO (ADMI_TIPO_MEDIO) FIBRA OPTICA
    VALOR3: NOMBRE_TIPO_MEDIO (ADMI_TIPO_MEDIO) FIBRA OPTICA'
  );

INSERT
INTO DB_GENERAL.ADMI_PARAMETRO_DET
  (
    ID_PARAMETRO_DET,
    PARAMETRO_ID,
    DESCRIPCION,
    VALOR1,
    VALOR2,
    VALOR3,
    VALOR4,
    ESTADO,
    USR_CREACION,
    FE_CREACION,
    IP_CREACION,
    USR_ULT_MOD,
    FE_ULT_MOD,
    IP_ULT_MOD,
    VALOR5,
    EMPRESA_COD
  )
  VALUES
  (
    DB_GENERAL.SEQ_ADMI_PARAMETRO_DET.NEXTVAL,
    (
      SELECT ID_PARAMETRO
      FROM DB_GENERAL.ADMI_PARAMETRO_CAB
      WHERE NOMBRE_PARAMETRO = 'NOMBRE_TECNICO_PRODUCTO'
      AND PROCESO            = 'NOMBRE_TECNICO_PRODUCTO'
      AND ESTADO             = 'Activo'
    ),
    'NETHOME',
    'NETHOME',
    NULL,
    NULL,
    NULL,
    'Activo',
    'apenaherrera',
    SYSDATE,
    '127.0.0.1',
    NULL,
    NULL,
    NULL,
    NULL,
    '18'
  );

INSERT
INTO DB_GENERAL.ADMI_PARAMETRO_CAB
  (
    ID_PARAMETRO,
    NOMBRE_PARAMETRO,
    DESCRIPCION,
    MODULO,
    PROCESO,
    ESTADO,
    USR_CREACION,
    FE_CREACION,
    IP_CREACION,
    USR_ULT_MOD,
    FE_ULT_MOD,
    IP_ULT_MOD
  )
  VALUES
  (
    DB_GENERAL.SEQ_ADMI_PARAMETRO_CAB.NEXTVAL,
    'PRODUCTO_NETHOME_GENERICO',
    'Permite definir el producto NETHOME GENERICO que agrupara el totalizado de los servicios NETHOME a nivel de CARACTERISTICAS asignados a un Login, se define el Producto, la cantidad y la ultima milla',
    'COMERCIAL',
    'AGREGAR_SERVICIO_NETHOME',
    'Activo',
    'apenaherrera',
    SYSDATE,
    '172.17.0.1',
    'apenaherrera',
    SYSDATE,
    '172.17.0.1'
  );

INSERT
INTO DB_GENERAL.ADMI_PARAMETRO_DET
  (
    ID_PARAMETRO_DET,
    PARAMETRO_ID,
    DESCRIPCION,
    VALOR1,
    VALOR2,
    VALOR3,
    VALOR4,
    ESTADO,
    USR_CREACION,
    FE_CREACION,
    IP_CREACION,
    USR_ULT_MOD,
    FE_ULT_MOD,
    IP_ULT_MOD,
    VALOR5,
    EMPRESA_COD, 
    OBSERVACION
  )
  VALUES
  (
    DB_GENERAL.SEQ_ADMI_PARAMETRO_DET.NEXTVAL,
    (
      SELECT ID_PARAMETRO
      FROM DB_GENERAL.ADMI_PARAMETRO_CAB
      WHERE NOMBRE_PARAMETRO = 'PRODUCTO_NETHOME_GENERICO'
      AND ESTADO             = 'Activo'
    ),
    'DEFINE EL PRODUCTO NETHOME GENERICO QUE AGRUPARA EL TOTALIZADO DE LOS SERVICIOS NETHOME',
    'NHOME',
    'NETHOME',
    '1',
    'FO',
    'Activo',
    'apenaherrera',
    SYSDATE,
    '172.17.0.1',
    'apenaherrera',
    SYSDATE,
    '172.17.0.1',
    'FACTURACION_UNICA',
    '18',
    'CONTIENE VALOR1: CODIGO DEL PRODUCTO NETHOME GENERICO DE ADMI_PRODUCTO
     VALOR2: DESCRIPCION DEL PRODUCTO NETHOME GENERICO DE ADMI_PRODUCTO
     VALOR3: CANTIDAD A INGRESARSE POR DETALLE DEL PRODUCTO
     VALOR4: DEFINE LA ULTIMA MILLA A REGISTRARSE DEL PRODUCTO NETHOME GENERICO ADMI_TIPO_MEDIO
     VALOR5: DEFINE SI EL PRODUCTO ES DE FACTURACION UNICA O DE RENTA MENSUAL, SIEMPRE QUE EL PRODUCTO
     NETHOME POSEA LA CARACTERISTICA FACTURACION_UNICA'
  );

INSERT INTO DB_GENERAL.ADMI_MOTIVO
 (
   ID_MOTIVO,
   RELACION_SISTEMA_ID,
   NOMBRE_MOTIVO,ESTADO,
   USR_CREACION,
   FE_CREACION,
   USR_ULT_MOD,
   FE_ULT_MOD,
   CTA_CONTABLE,
   REF_MOTIVO_ID
 ) 
  VALUES 
 (
   DB_GENERAL.SEQ_ADMI_MOTIVO.NEXTVAL,
   NULL,
   'Facturacion Unica por Detalle',
   'Activo',
   'apenaherrera',
   SYSDATE,
   'apenaherrera',
   SYSDATE,
   NULL,
   NULL
 );

COMMIT;


