DELETE FROM DB_GENERAL.ADMI_PARAMETRO_DET
WHERE PARAMETRO_ID IN ( SELECT ID_PARAMETRO
                        FROM DB_GENERAL.ADMI_PARAMETRO_CAB
                        WHERE NOMBRE_PARAMETRO = 'PROMOCIONES_PARAMETROS_EJECUCION_DE_ALCANCE'
                        AND ESTADO             = 'Activo');

DELETE FROM DB_GENERAL.ADMI_PARAMETRO_CAB
WHERE NOMBRE_PARAMETRO = 'PROMOCIONES_PARAMETROS_EJECUCION_DE_ALCANCE'
  AND ESTADO           = 'Activo';

COMMIT;
/
