/**
* DELETE DE PARAMETROS PARA CLIENTES SOPORTE LOGICO CAMARA
* 
* @author Jorge Gomez <jigomez@telconet.ec>
* @version 1.0 13-03-2023
* 
*/


DELETE FROM DB_GENERAL.ADMI_PARAMETRO_DET WHERE DESCRIPCION = 'VALORES DE CLIENTES CON SOPORTE LOGICO';
     

DELETE FROM DB_GENERAL.ADMI_PARAMETRO_CAB WHERE NOMBRE_PARAMETRO = 'CLIENTES SOPORTE LOGICO CAMARA';

	  
COMMIT;

/