
DELETE FROM DB_GENERAL.ADMI_PARAMETRO_DET
WHERE PARAMETRO_ID IN ( SELECT ID_PARAMETRO
                        FROM DB_GENERAL.ADMI_PARAMETRO_CAB
                        WHERE NOMBRE_PARAMETRO = 'PROM_PARAMETROS'
                        AND ESTADO             = 'Activo')
AND DESCRIPCION IN ('PROM_DESC_CAMBIO_PLAN','PROM_CICLOS_FACTURACION');

COMMIT;
/