/** 
 * @author Alex Arreaga <atarreaga@telconet.ec>
 * @version 1.0 
 * @since 31-03-2022  
 * Se crea DML de reverso de configuraciones de leyendas promociones.
 */

--SE ELIMINA DESCRIPCION DE PARAMETRO ADMI_PARAMETRO_HIST
DELETE FROM DB_GENERAL.ADMI_PARAMETRO_HIST 
 WHERE PARAMETRO_ID IN (SELECT ID_PARAMETRO FROM DB_GENERAL.ADMI_PARAMETRO_CAB WHERE NOMBRE_PARAMETRO = 'RESTRICCION_PLANES_X_INSTALACION')
AND VALOR2 = 'c' AND EMPRESA_COD = '18'
AND DESCRIPCION = 'Planes que no pagan instalación (Planes finalizados en "FARMA","EMTN","EMPL","EMNL"): 100% de descuento';  


--SE ELIMINA DETALLES DE PARAMETROS
DELETE FROM DB_GENERAL.ADMI_PARAMETRO_DET
	WHERE PARAMETRO_ID IN ( SELECT ID_PARAMETRO
	                        FROM DB_GENERAL.ADMI_PARAMETRO_CAB
	                        WHERE NOMBRE_PARAMETRO = 'PARAM_EVALUA_TENTATIVA'
	                        AND ESTADO             = 'Activo');

DELETE FROM DB_GENERAL.ADMI_PARAMETRO_CAB WHERE NOMBRE_PARAMETRO = 'PARAM_EVALUA_TENTATIVA';


--Reverso actualizar descripción Restricción de planes
UPDATE DB_GENERAL.ADMI_PARAMETRO_DET 
SET DESCRIPCION = 'Planes que no pagan instalación (Planes finalizados en "FARMA","EMTN","EMPL"): 100% de descuento'
WHERE PARAMETRO_ID IN (SELECT ID_PARAMETRO FROM DB_GENERAL.ADMI_PARAMETRO_CAB WHERE NOMBRE_PARAMETRO = 'RESTRICCION_PLANES_X_INSTALACION')
AND VALOR2 = 'c' AND EMPRESA_COD = '18';  

COMMIT;
/
