/**
* INSERT PARA RELACIONAR MAC CON PRODUCTO SEGURIDAD ELECTRONICA VIDEO VIGILANCIA
* 
* @author Jorge Gomez <jigomez@telconet.ec>
* @version 1.0 13-03-2023
* 
*/


INSERT INTO  DB_COMERCIAL.ADMI_PRODUCTO_CARACTERISTICA (ID_PRODUCTO_CARACTERISITICA, PRODUCTO_ID, CARACTERISTICA_ID, FE_CREACION, FE_ULT_MOD, USR_CREACION, USR_ULT_MOD, ESTADO, VISIBLE_COMERCIAL)
VALUES (DB_COMERCIAL.SEQ_ADMI_PRODUCTO_CARAC.NEXTVAL, 1099, 6, SYSDATE, SYSDATE, 'jigomez', 'jigomez','Activo', 'NO');


	  
COMMIT;

/