/**
 * PKS para ingresar nueva caracteristica y asociarla a un producto
 *
 * @author Jean Pierre Nazareno Martinez <jnazareno@telconet.ec>
 * @version 1.0 11-10-2021
 */


--SE INSERTA NUEVA CARACTERISTICA (Migración de Tecnología SDWAN)
--
INSERT INTO DB_COMERCIAL.ADMI_CARACTERISTICA 
(
    ID_CARACTERISTICA,
    DESCRIPCION_CARACTERISTICA,
    TIPO_INGRESO,
    ESTADO,
    FE_CREACION,
    USR_CREACION,
    FE_ULT_MOD,
    USR_ULT_MOD,
    TIPO,
	DETALLE_CARACTERISTICA
) 
VALUES 
(
    DB_COMERCIAL.SEQ_ADMI_CARACTERISTICA.NEXTVAL,
    'Migración de Tecnología SDWAN',
    'S',
    'Activo',
    SYSDATE,
    'jnazareno',
    NULL,
    NULL,
    'COMERCIAL',
	NULL 
);
 
--SE ASOCIA LA CARACTERISTICA CON EL PRODUCTO
--
INSERT
INTO DB_COMERCIAL.ADMI_PRODUCTO_CARACTERISTICA
  (
    ID_PRODUCTO_CARACTERISITICA,
    PRODUCTO_ID,
    CARACTERISTICA_ID,
    FE_CREACION,
    USR_CREACION,
    ESTADO,
    VISIBLE_COMERCIAL
  )
  VALUES
  (
    DB_COMERCIAL.SEQ_ADMI_PRODUCTO_CARAC.NEXTVAL,
    (SELECT ID_PRODUCTO
    FROM DB_COMERCIAL.ADMI_PRODUCTO
    WHERE DESCRIPCION_PRODUCTO = 'Internet SDWAN'
    ),
    (SELECT ID_CARACTERISTICA 
    FROM DB_COMERCIAL.ADMI_CARACTERISTICA 
    WHERE DESCRIPCION_CARACTERISTICA = 'Migración de Tecnología SDWAN'),
    SYSDATE,
    'jnazareno',
    'Activo',
    'SI'
  );

INSERT
INTO DB_COMERCIAL.ADMI_PRODUCTO_CARACTERISTICA
  (
    ID_PRODUCTO_CARACTERISITICA,
    PRODUCTO_ID,
    CARACTERISTICA_ID,
    FE_CREACION,
    USR_CREACION,
    ESTADO,
    VISIBLE_COMERCIAL
  )
  VALUES
  (
    DB_COMERCIAL.SEQ_ADMI_PRODUCTO_CARAC.NEXTVAL,
    (SELECT ID_PRODUCTO
    FROM DB_COMERCIAL.ADMI_PRODUCTO
    WHERE DESCRIPCION_PRODUCTO = 'L3MPLS SDWAN'
    ),
    (SELECT ID_CARACTERISTICA 
    FROM DB_COMERCIAL.ADMI_CARACTERISTICA 
    WHERE DESCRIPCION_CARACTERISTICA = 'Migración de Tecnología SDWAN'),
    SYSDATE,
    'jnazareno',
    'Activo',
    'SI'
  );

COMMIT;
/