--ELIMINAMOS DETALLE DE FILTRO PARA DEPARTAMENTOS
DELETE FROM DB_GENERAL.ADMI_PARAMETRO_DET DETALLE
WHERE
    PARAMETRO_ID = (
        SELECT
            ID_PARAMETRO
        FROM
            DB_GENERAL.ADMI_PARAMETRO_CAB
        WHERE
            NOMBRE_PARAMETRO = 'PARAMETROS_GENERALES_MOVIL'
    );
    
--ELIMINAMOS CABECERA
DELETE FROM DB_GENERAL.ADMI_PARAMETRO_CAB CABECERA
WHERE
    CABECERA.NOMBRE_PARAMETRO = 'PARAMETROS_GENERALES_MOVIL';


COMMIT;
/