-- Eliminamos los nuevos parametros del proyecto
DELETE FROM DB_GENERAL.ADMI_PARAMETRO_DET
WHERE PARAMETRO_ID = (SELECT ID_PARAMETRO FROM DB_GENERAL.ADMI_PARAMETRO_CAB
                      WHERE NOMBRE_PARAMETRO = 'PRODUCTOS ADICIONALES MANUALES')
AND DESCRIPCION = 'Productos para planificacion con HAL'
AND USR_CREACION = 'djreyes';

COMMIT;
/