DELETE FROM DB_GENERAL.ADMI_PARAMETRO_DET
WHERE PARAMETRO_ID = (
        SELECT ID_PARAMETRO
        FROM DB_GENERAL.ADMI_PARAMETRO_CAB
        WHERE NOMBRE_PARAMETRO = 'PROMOCION ANCHO BANDA'
    )
AND DESCRIPCION = 'Bandera para ejecutar proceso de configuracion'
AND VALOR1 = 'PROM_BW'
AND USR_CREACION = 'djreyes';

COMMIT;
/
