SET DEFINE OFF;

-- Eliminar en la tabla ADMI_PARAMETRO_DET
DELETE FROM DB_GENERAL.ADMI_PARAMETRO_DET
WHERE PARAMETRO_ID = (SELECT ID_PARAMETRO FROM DB_GENERAL.ADMI_PARAMETRO_CAB WHERE NOMBRE_PARAMETRO = 'GENERAR_LOGIN_AUXILIAR_GPON_TN');

-- Eliminar en la tabla ADMI_PARAMETRO_CAB
DELETE FROM DB_GENERAL.ADMI_PARAMETRO_CAB
WHERE NOMBRE_PARAMETRO = 'GENERAR_LOGIN_AUXILIAR_GPON_TN';

COMMIT;

/
