/*
 * Script de reverso de los parámetros.
 */
DELETE FROM DB_GENERAL.ADMI_PARAMETRO_DET WHERE PARAMETRO_ID IN (
  SELECT ID_PARAMETRO
    FROM DB_GENERAL.ADMI_PARAMETRO_CAB
  WHERE NOMBRE_PARAMETRO = 'DIAS_CONSULTA_GESTION_DOCUMENTOS'
    AND ESTADO           = 'Activo'
);
DELETE FROM DB_GENERAL.ADMI_PARAMETRO_CAB WHERE NOMBRE_PARAMETRO = 'DIAS_CONSULTA_GESTION_DOCUMENTOS';
COMMIT;
/
