parameters:
#    inicio.example.class: telconet\inicioBundle\Example

services:
#    inicio.example:
#        class: %inicio.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
